### ISSUE TITLE
18c/36t task startup lag with latest code

### ISSUE THREAD

**Issue by fstrugar** [taskflow/taskflow#108]
I don't quite understand cpp-taskflow worker thread system but I've noticed that, with the latest code as of now, on the 18c/36t machine there is a significant (ranging from 0.1-1ms, measured using observer & chrome://tracing) lag when running parallel_for before all workers join execution, resulting in fewer workers handling multiple tasks and thus few odd tasks running very late.

I've changed the "_notifier.notify(false)" to "_notifier.notify(true)" in Executor::_schedule(PassiveVector<Node*>& nodes) and completely disabled the yield loop in _explore_task (by just doing "if(f++ > F) { break; }") and this seems to largely remedy the issue for me: the lag is now relatively stable, from 0.05 to 0.15ms, and almost all threads pick up tasks reducing overall execution time of this specific workload by half.

I don't know if these changes make any sense or are correct so I'd love to hear thoughts / ideas on reducing the task startup lag?

**Comment by clin99** [comment]
Hi @fstrugar , thanks for bringing up this issue. The two changes make sense. `_notifier.notify(false)` notifies one thread while `_notifier.notify(true)` notifies all threads. Because in the beginning all threads are sleeping, waking them up at once can reduce the startup lag. The yield loop lets a thread release its CPU to others so disabling it might possibly (depending on the OS scheduler) reduce the latency. Those changes do not affect the functionalities of Cpp-Taskflow so feel free to keep those changes if they can improve your program's performance.

I am curious about which change is more critical to the performance improvement. Could you please let me know if you have the results?

Also from my perspective the lag is quite small (0.75 ms). Could you please give me some information about this parallel-for workload?  like how many iterations are in the for-loop and the workload of each iteration.


Thanks!

**Comment by tsung-wei-huang** [comment]
@fstrugar , it will be better if you can provide us your benchmark so we can try reproducing it. Thanks for bringing this up.

**Comment by fstrugar** [comment]
Hi @tsung-wei-huang & @clin99, thanks for the quick answers.

I've extracted the relevant code into standalone commandline project (I hope windows / VS2017 is ok) that only contains the relevant code and cpp-taskflow integration. The repo is here:
https://github.com/fstrugar/cpp-taskflow-particles-test (you should have received invitations). 

This is a very quick and dirty port where not everything is multithreaded but it was enough for my immediate need (removing the CPU bottleneck for the tests I'm doing). On the long run I'm looking to find a suitable thread scheduler for use across the whole project which will be opensourced. I didn't instrument it so it's very rudimentary, just showing the number of loops per second it does. The code that uses taskflow is in vaSimpleParticles.cpp file (can be enabled/disabled with a define: https://github.com/fstrugar/cpp-taskflow-particles-test/blob/master/vaSimpleParticles.cpp#L22)

> I am curious about which change is more critical to the performance improvement. Could you please let me know if you have the results?

On the 18c/36t system on Windows10 the first change (https://github.com/fstrugar/cpp-taskflow-particles-test/blob/master/taskflow/core/executor.hpp#L615) provides most gain. The numbers are as follows:

default: _notifier.notify(false)
```
avg tick = 1.25ms
avg sort = 1.37ms
avg draw = 0.58ms
```

changed: _notifier.notify(true)
```
avg tick = 1.03ms
avg sort = 1.12ms
avg draw = 0.36ms
```

delta:
```
avg tick = 0.82x (18% faster)
avg sort = 0.82x (18% faster)
avg draw = 0.62x (38% faster)
```

The second change (https://github.com/fstrugar/cpp-taskflow-particles-test/blob/master/taskflow/core/executor.hpp#L366) provides about third of the gain of the first change (they stack up).

Interestingly, on the 6c/12t system with the first change I notice almost no difference at all, while the second  one provides similar improvement as on the 18c/36t system!

> Also from my perspective the lag is quite small (0.75 ms). Could you please provide some information about this parallel-for workload? like how many iterations are in the for-loop and the workload of each iteration.

There are about 60000 elements being processed in one of the for-loops, which takes about 0.36ms to execute on the 18c/36t system and about 0.75ms on the 6c/12t system (with the changes I made) or about 5ms done in a single thread (roughly the same on both systems).

This is a game-like workload for testing GPU performance scaling so my requirement is that it is not CPU bound at any point between 30 and 300Hz (or even higher), which is where the low lag requirement comes from :)

**Comment by tsung-wei-huang** [comment]
@fstrugar , is it possible to provide a cmake so we can compile it on non-windows platform? We are right now short of windows machines.

**Comment by fstrugar** [comment]
Yes, I've just added CMakeLists.txt to the repo! Had to do some changes to code to make sure it compiles with gcc (tested with gcc 7.4.0 on ubuntu). Interestingly, the CHANGE_2 doesn't make any difference there, while the CHANGE_1 still makes a big difference (tested on Ubuntu sideloaded on Windows 10).
Please let me know if there are any issues.

**Comment by clin99** [comment]
Hi @fstrugar , thanks for providing the CMake file! I have tried it on my Ubuntu machine and it works!   
I will look into the code to figure out how to solve this.
