### ISSUE TITLE
Can it be applied to Android Platform?

### ISSUE THREAD

**Issue by lxz1104** [taskflow/taskflow#113]
I want to use it in Android applications via the JNI interface.But I'm not sure if he can work properly.

**Comment by tsung-wei-huang** [comment]
We havn't tried running on Android platform yet. I guess if you are able to support C++17 build with threading support like pthread, it can work.

**Comment by clin99** [comment]
Hi @lxz1104 , the Android NDK has [C++17 library support](https://developer.android.com/ndk/guides/cpp-support) and [CMake](https://developer.android.com/ndk/guides/cmake). You can follow the [guide](https://developer.android.com/studio/projects/add-native-code) to try building a project with Cpp-Taskflow.

Thanks.

**Comment by devhandle** [comment]
I've tried to build on Android but it seems std::invocable_v is missing. I'm building with clang which supports C++17. [Running the code here also fails setting compiler to clang c++17](https://en.cppreference.com/w/cpp/types/is_invocable)

```
cpp-taskflow/taskflow/core/flow_builder.hpp:372:21: error: no member named 'is_invocable_v' in namespace 'std'
  if constexpr(std::is_invocable_v<C, Subflow&>) {
```

**Comment by tsung-wei-huang** [comment]
@devhandle , would you please sync up with the master branch and see if you still see the problem? I have removed the `invocable_v` and use a custom function traits.

**Comment by milinddeore** [comment]
@devhandle Did you get any results? Thanks!

**Comment by hxxfff** [comment]
> @devhandle Did you get any results? Thanks!

yes,  it works on android OS. I have test it. you need not to build library,  just include the  taskflow header in your own code,  then it work.
