### ISSUE TITLE
Make Taskflow movable

### ISSUE THREAD

**Issue by robinchrist** [taskflow/taskflow#118]
It would be very useful if `tf::Taskflow` was movable.

Due to the special structure of this particular part of our application (taskflow coupled with nodes ` AsyncProgressQueueWorker`), there is a designated launcher threads which owns the Taskflow after it was created. Currently I'm wrapping the Taskflow into a `unique_ptr`, but I think it would be nicer if `tf::Taskflow` was movable.

**Comment by tsung-wei-huang** [comment]
@robinchrist , each taskflow has a `std::mutex` that prevents the object from being movable or copyable. Using `unique_ptr` is a good option in my opinion otherwise it will be time-consuming to move a taskflow object. Taskflow is not light.

**Comment by tsung-wei-huang** [comment]
@robinchrist this has been done in the master branch - it did take a long time because of internal parallelism - :) Please read the [doc here](https://taskflow.github.io/taskflow/StaticTasking.html#MoveATaskflow)
