### ISSUE TITLE
Real time task scheduling support across multi cores

### ISSUE THREAD

**Issue by saumi22** [taskflow/taskflow#119]
Hi,
I was just curious that is there any support of real time scheduling if tasks across multi cores?
like preemptive scheduling if last 2 nodes of task graph cant be scheduled because of timing requirement etc.

**Comment by tsung-wei-huang** [comment]
We don't do real-time scheduling but try to make the entire graph finish as soon as possible. Thanks.

**Comment by saumi22** [comment]
Thanks for quick response , Does this frameworks supports individual Task Priorities and Executor thread affinity set to particular CPU?

**Comment by tsung-wei-huang** [comment]
Currently, we do not plan to do this but leave it as a future work.
