### ISSUE TITLE
Include FastFlow in benchmarks

### ISSUE THREAD

**Issue by jmakov** [taskflow/taskflow#120]
Reading the research paper I noticed https://github.com/fastflow/fastflow wasn't mentioned. Since both approaches are similar, it would be interesting to see a comparison.

**Comment by tsung-wei-huang** [comment]
@jmakov thanks for bringing this up. I will be interested in seeing the difference between cpp-taskflow and fastflow in the future. Currently, we only provided benchmarks against openmp and tbb (see [benchmarks](https://github.com/cpp-taskflow/cpp-taskflow/blob/master/benchmarks/benchmarks.md)). Feel free to contribute though :)
