### ISSUE TITLE
Uniting Taskflows within Function Scopes

### ISSUE THREAD

**Issue by michaelhayashi** [taskflow/taskflow#123]
**Please describe your feature request.**
I am unsure how to unite taskflow graphs into a main taskflow graph easily when calling functions that themselves have their own taskflow graphs.

My issue likely comes from a shallow understanding of the nature of task-based parallelism and lambda functions. I am writing a program with a taskflow graph. Within that program, I would like to call functions from a separate header which themselves have taskflow graphs within their scopes. What is the easiest way to include taskflow graphs from within functions into a main taskflow graph?  To maintain compatibility, I would like tasks within called functions to work only with variables in the function scope.

Here is an example with main() calling foo() and bar():
[function_scope.zip](https://github.com/cpp-taskflow/cpp-taskflow/files/3849423/function_scope.zip)

**Comment by michaelhayashi** [comment]
I recently updated my C++ compiler to GNU g++ 8.3.0. I compiled the given example using `$CXX function_scope.cpp -std=c++17 -I $CPP_TASKFLOW_DIR -O2 -lpthread -o function_scope` with the two environment variables set. I switched the language standards flag to `-std=c++17` because the compiler documentation said `-std=c++1z` was deprecated.

Here is an example with main() calling foo() and bar():
[function_scope.zip](https://github.com/cpp-taskflow/cpp-taskflow/files/3852882/function_scope.zip)

**Comment by tsung-wei-huang** [comment]
I assume this has been solved. If not, please feel free to reopen.
