### ISSUE TITLE
Support asynchronous task

### ISSUE THREAD

**Issue by xuchen-plus** [taskflow/taskflow#126]
**Please describe your feature request.**
Is there any way to support asynchronous task?
Use case could be a workflow with several tasks which issue requests over network, and each task is asynchronously executed.

**Comment by mratsim** [comment]
Network requests are IO while Cpp-taskflow is a framework for compute. You should use a dedicated event library to handle IO like libuv.

Putting IO on top of cpp-taskflow will completely block the thread unless the internals also support kqueue/epoll/IOCP. This is a completely different beast than the current scheduling for compute-bound tasks.

**Comment by fsaintjacques** [comment]
Ignoring the asynchronous-ness, would it be hard to add an extra domain, e.g. `HOST_IO` with its own worker pool, probably with higher count than the HOST worker pool?

**Comment by tsung-wei-huang** [comment]
I believe the conservation has two aspects, IO-driven (multitasking) and compute-driven (multithreaded). cpp-taskflow is for the letter, and yes, for io tasks you may consider libuv or libevent for the event loop. However, it's possible to have cpp-taskflow live together with the event loop simply by using taskflow as an independent execution engine.

**Comment by fsaintjacques** [comment]
The reason I ask is because my problem share both workload. I have an compute DAG of relational algebra operators, essentially Memory/CPU bound tasks. The input leaves of the DAG may or not come from IO, e.g. in-memory table, local disks or high latency IO like Amazon S3 or Google GCP.

**Comment by tsung-wei-huang** [comment]
I believe this has been solved in [Asynchronous Tasking](https://taskflow.github.io/taskflow/AsyncTasking.html).
