### ISSUE TITLE
Very strange performance for the Black and Scholes benchmark

### ISSUE THREAD

**Issue by mratsim** [taskflow/taskflow#127]
All implementations TBB, OpenMP and CppTaskflow exhibits very strange performance profile on the Black & Scholes benchmark.

## Problem 1

10000 rounds take about 30s for TBB and OpenMP and 1min30 for CPP-Taskflow.
I've triple-checked if maybe I was not using release mode or if there was something else and I'm at a loss.

This is the VTune Amplifier summary of all implementations, note that all implementation are spending most of their time waiting at a barrier or busy spinning.

### TBB

![image](https://user-images.githubusercontent.com/22738317/70354766-bfb5fc00-1870-11ea-9386-174eb9a4bccd.png)

### OpenMP

![image](https://user-images.githubusercontent.com/22738317/70354839-ed02aa00-1870-11ea-8b15-a3e669228878.png)

### CppTaskflow

![image](https://user-images.githubusercontent.com/22738317/70354885-0efc2c80-1871-11ea-8511-c9b1b09be698.png)

### System

i9-9980XE 18 physical cores, 36 logical. Overclocked at 4.1GHz (all-cores turbo)

## Problem 2

While TBB uses 99.8% of my CPU on this benchmark, Cpp-Taskflow only uses about 30% of each core.

## Alternative implementation

I've done an alternative implementation in the Nim language + OpenMP in [my own runtime repo](https://github.com/mratsim/weave/blob/master/benchmarks/black_scholes/openmp_black_scholes.nim).
Sequential execution is 3.5s-4s and parallel execution around 300-350ms and the output are the same.

So the current benchmark are about 100x slower than expected.

I was thinking that maybe there was some false sharing but it seems like the arrays are padded by 4x times the cache line size:

https://github.com/cpp-taskflow/cpp-taskflow/blob/5d1b0e3dd84a64343184ead413aed17335995eb2/benchmark/black_scholes/common.hpp#L264-L276

**Comment by clin99** [comment]
Hi @mratsim , thanks for reporting the issue. The dev branch is for our internal test only and those benchmarks are under development. We test different settings of the libraries on those benchmarks so current results might be strange. We are investigating these details and will make public benchmarks soon.

**Comment by tsung-wei-huang** [comment]
@mratsim I believe this has been solved with the current parallel algorithm implementation.
