### ISSUE TITLE
Testcase ParallelForOnIndex fails on Solaris

### ISSUE THREAD

**Issue by vedranmiletic** [taskflow/taskflow#129]
**Describe the bug**
Testcase ParallelForOnIndex fails on Solaris:

```
[doctest] doctest version is "2.3.1"
[doctest] run with "--help" for options
===============================================================================
../unittest/taskflow.cpp:581:
TEST CASE:  ParallelForOnIndex
  PositiveFloatingStep

../unittest/taskflow.cpp:679: FATAL ERROR: REQUIRE( n == counter ) is NOT correct!
  values: REQUIRE( 3 == 2 )

===============================================================================
[doctest] test cases:      1 |      0 passed |      1 failed |     14 skipped
[doctest] assertions:  12424 |  12423 passed |      1 failed |
[doctest] Status: FAILURE!
```

**To Reproduce**
1. Compile.
2. Test.
3. See error

**Desktop (please complete the following information):**
 - OS: SunOS solaris-asus 5.11 omnios-r151032-702376803e i86pc i386 i86pc
 - Compiler: gcc (OmniOS 151032/8.3.0-il-0) 8.3.0

**Comment by tsung-wei-huang** [comment]
Hi @vedranmiletic  thanks for pointing this out. We are looking into this problem and will get back to you soon.

**Comment by tsung-wei-huang** [comment]
@vedranmiletic  I have updated a new version on the master branch. It turned out to be the difference of floating point calculations in either positive or negative direction. Would you please try it again?

**Comment by vedranmiletic** [comment]
Unfortunately still fails with:

```
[doctest] doctest version is "2.3.1"
[doctest] run with "--help" for options
===============================================================================
../unittest/taskflow.cpp:581:
TEST CASE:  ParallelForOnIndex
  PositiveFloatingStep

../unittest/taskflow.cpp:679: FATAL ERROR: REQUIRE( n == counter ) is NOT correct!
  values: REQUIRE( 3 == 2 )

===============================================================================
[doctest] test cases:      1 |      0 passed |      1 failed |     14 skipped
[doctest] assertions:  12424 |  12423 passed |      1 failed |
[doctest] Status: FAILURE!
```

**Comment by tsung-wei-huang** [comment]
Hi @vedranmiletic , will you be able to check again on the dev branch? It seems to be a floating calculation issue. We are working on several new features and fixes in dev branch and will merge it to the master soon.

**Comment by vedranmiletic** [comment]
> Hi @vedranmiletic , will you be able to check again on the dev branch? It seems to be a floating calculation issue. We are working on several new features and fixes in dev branch and will merge it to the master soon.

I tested the code at commit 8c5a60aa87e845e5d1ccca3c8258cb18400b7b56 and I still see the same issue.

**Comment by tsung-wei-huang** [comment]
@vedranmiletic Mm...anyway I can access your platform to test?

**Comment by vedranmiletic** [comment]
> @vedranmiletic Mm...anyway I can access your platform to test?

Sure, I'll send you an e-mail with the details.

**Comment by vedranmiletic** [comment]
@tsung-wei-huang Did anything change or are you just closing old issues?

**Comment by tsung-wei-huang** [comment]
@vedranmiletic This has been solved - there is another issue newer about this and I have removed the floating indices problems.

**Comment by vedranmiletic** [comment]
Excellent! I just tested and indeed it's fixed. I'll submit a small patch for another unrelated issue soon.

**Comment by tsung-wei-huang** [comment]
perfect !
