### ISSUE TITLE
Running Taskflow multiple times with varying subflow graph

### ISSUE THREAD

**Issue by Mortano** [taskflow/taskflow#138]
**Describe the bug**
I am trying to execute a Taskflow using dynamic tasking multiple times, but the number of dynamic tasks created varies between executions. Essentially I am traversing a tree starting from the root, each node is visited as a single task and creates sub-tasks for all children using `tf::Subflow`. The tree is traversed multiple times but it changes after each traversal. My code does what it should, i.e. the traversal works, however upon using `tf::ExecutorObserver` to inspect the execution, I get broken data. It shows that child nodes are sometimes processed before parent nodes, which should be impossible because the parent node creates the task for the child node during its execution. Also, the names of the tasks are sometimes corrupted. 

I created a small test project illustrating the problem here: https://github.com/Mortano/taskflow_test 

Is running the same `tf::Taskflow` object with a subflow graph that changes between executions not supported? 

**To Reproduce**
Run the example project here: https://github.com/Mortano/taskflow_test 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04, compiling with gcc 7.4.0, using v2.2.0 of cpp-taskflow

**Comment by clin99** [comment]
Hi @Mortano , when executing the task graph, the subflow (and its tasks) created in previous run will be removed before the new subflow starts. Therefore, the task view objects stored in your observer will be corrupted. Instead, you can store the names of the tasks like the comments in your program.

**Comment by Mortano** [comment]
Thanks for clarifying this. Would it perhaps make sense to change `tf::ExecutorObserver` so that it can deal with these situations? From looking at the implementation of `tf::ExecutorObserver`, the `tf::TaskView` object is only used to get the name of the task during the call to `dump`, this could be changed to just store the name of the task instead.

**Comment by tsung-wei-huang** [comment]
I believe this can be done on the application side.
