### ISSUE TITLE
Parallel STL built on top of Taskflow

### ISSUE THREAD

**Issue by vedranmiletic** [taskflow/taskflow#140]
GCC's libstdc++ implements parallel STL built on top of TBB:

- https://gcc.gnu.org/gcc-9/changes.html
- https://gcc.gnu.org/ml/libstdc++/2017-11/msg00112.html
- https://github.com/intel/parallelstl

It would be great to have parallel STL built on top of Cpp-Taskflow.

**Comment by isidorostsa** [comment]
This sounds like an amazing effort. How would this be orchestrated? I am interested in contributing to this idea.

**Comment by isidorostsa** [comment]
That's great to hear! What algorithms would you consider to be of highest priority to implement?

**Comment by isidorostsa** [comment]
@vedranmiletic would love to hear your opinion on that as well! I am interested in doing this as a google summer of code project.

**Comment by vedranmiletic** [comment]
> @vedranmiletic would love to hear your opinion on that as well! I am interested in doing this as a google summer of code project.

Sounds like a great effort. I can help with testing. Have you thought about implementing this in GCC or Clang?

**Comment by isidorostsa** [comment]
Why does the compiler choice matter?

**Comment by vedranmiletic** [comment]
> Why does the compiler choice matter?

I would expect that the LLVM community would welcome such a feature since there is no existing implementation of parallel STL you would have to beat in terms of performance or ease of code reuse. Regarding GCC, there is an existing implementation via TBB so I would expect that you would have to prove that you implementation is at least as good to be considered for upstreaming.

To clarify, this is just how I would expect things to happen. I have nothing against licensing or technological aspects of either GCC or LLVM, both have their strengths and I use both daily. I teach the internals of LLVM and have previously contributed non-trivial patches to LLVM, but only very minor fixes to GCC so my knowledge of GCC's community is very limited compared to LLVM's.

In your situation, I would definitely approach both communities and find out what do they think about upstreaming your code before choosing how and where to do it.

**Comment by tsung-wei-huang** [comment]
Please refer to [Taskflow Algorithms](https://taskflow.github.io/taskflow/Algorithms.html). Thanks!
