### ISSUE TITLE
A way to get the value of the work item of a task

### ISSUE THREAD

**Issue by aaalexandrov** [taskflow/taskflow#147]
As of release 2.3.0 there doesn't seem to be a way to get the value of the work item given to a task. An algorithm that processes the task dependency graph has no way to inspect the work objects that a task corresponds to.
Please provide a way to get their value, or alternatively add a mechanism to associate user data with a task.

**Comment by aaalexandrov** [comment]
Tangentially related to that, tasks don't seem to be hashable right now. Please expose a way to get a hash code.

**Comment by tsung-wei-huang** [comment]
@aaalexandrov what do u mean by getting the value of the work item? Please provide an example. Regarding hash, do u mean std::hash<tf::Task>?

**Comment by aaalexandrov** [comment]
WorkItem work; // callable, but not necessarily a function
tf::Task workTask = taskflow.emplace(work);
// ... someplace else
WorkItem &work = workTask.get_work<WorkItem>();
// ... do stuff with work

As for hashing - yes, std::hash<tf::Task> would be perfect.

**Comment by tsung-wei-huang** [comment]
@aaalexandrov  I think you can simply use `task.work` to change the work you had assigned?

**Comment by aaalexandrov** [comment]
It is not about changing the work, but rather about getting the information you put inside back out.
If I have a bunch of tasks that I want to reason about at a later time, I need to either be able to get some specifics about what kind of work I assigned to the task, or make a lookup structure to map between tasks, and the work items, which is redundant. Or, I should somehow be able to associate some non-opaque data with the task so I can figure out what it does.

```
	struct Incrementer {
		int _a;
		Incrementer(int a) : _a(a) {}
		void operator()() { ++_a; }
	};

	std::vector<tf::Task> tasks;
	tasks.emplace_back().work(Incrementer(5));
	tasks.emplace_back().work(Incrementer(8));

	tf::Task t = tasks[rand() % tasks.size()];
	// how can i tell what number this task will increment?

```

**Comment by tsung-wei-huang** [comment]
I believe this can be achieved using the newest feature of [Attaching User Data to a Task](https://taskflow.github.io/taskflow/StaticTasking.html#AttachUserDataToATask).
