### ISSUE TITLE
Possibility to run "Fire-and-forget" Taskflows

### ISSUE THREAD

**Issue by robinchrist** [taskflow/taskflow#165]
**Please describe your feature request.**
I'd like to enqueue Taskflows to an executor in a Fire-and-forget fashion, i.e. not having to care about their lifetime manually, but rather have the library delete them once they have finished execution.

Is it possible to implement that? Or am I thinking way too complicated? 

At what **exact** point in time can the Taskflow be destroyed without risking nullptr dereference by the lib or something similar?

**Comment by robinchrist** [comment]
I basically need a callback with a strong "All cleanup tasks are done, nothing refers to the taskflow anymore" guarantee.
As far as I can tell from the source code, it's not safe to delete the Taskflow in the callback function you can pass to the executor:
https://github.com/cpp-taskflow/cpp-taskflow/blob/75500eccbca3049c06a63ad5aa57e27db348e2d5/taskflow/core/executor.hpp#L1112

To me it seems that the callback is called but after the call has completed, references to the Taskflow are still made. Right?

**Comment by tsung-wei-huang** [comment]
Hi @robinchrist , I believe this is doable with some hacks. Topology is a data structure created by the executor at runtime when you run a taskflow. It does store the callback and that callback lives together with the topology. You can store your taskflow in the callback capture, something like the following:

```cpp
auto taskflow = std::make_shared<Taskflow>();
executor.run(*taskflow, [taskflow] () { std::cout << "end of the execution and taskflow is still safe\n";  }).wait();
```

**Comment by robinchrist** [comment]
Thanks for the info!
Just to be sure and sum things up: Once the callback has been called and exited, you can safely delete the Taskflow without risking access to already freed memory, right?

**Comment by tsung-wei-huang** [comment]
Yes. You can take a look at the [code](https://github.com/cpp-taskflow/cpp-taskflow/blob/7cc2f3872df939f3f9abbdf237474f2b2c6d208d/taskflow/core/executor.hpp#L1185). When the callback is called, executor check if it is the last topology (due to `run_n`) and then erase the topology from the list [here](https://github.com/cpp-taskflow/cpp-taskflow/blob/7cc2f3872df939f3f9abbdf237474f2b2c6d208d/taskflow/core/executor.hpp#L1224). 

Hope this help clarify your question :)

**Comment by fstrugar** [comment]
Hi! I believe in this scenario the mutex unlock [here](https://github.com/taskflow/taskflow/blob/7cc2f3872df939f3f9abbdf237474f2b2c6d208d/taskflow/core/executor.hpp#L1226) gets called after the topology object gets destroyed here [f._topologies.pop_front()](https://github.com/cpp-taskflow/cpp-taskflow/blob/7cc2f3872df939f3f9abbdf237474f2b2c6d208d/taskflow/core/executor.hpp#L1224) - I get a debug runtime error. 
I've temporarily backed-up the lambda capture above like this:
`auto bc { std::move((*tpg)->_call) };`
and that delays the destruction to after leaving the scope. Does this sound sensible?

**Comment by tsung-wei-huang** [comment]
@fstrugar , I didn't notice this issue :( Sorry for this. Yes, your modification can solve this particular problem. I think a better way is to extract the topology node from the linked list and keep it alive until the taskflow is not being accessed anymore. But, STL doesn't have this capability in `std::list`. I will see what I can do to fix it. 

At the same time, feel free to submit a pull request for your modification or any unittest you think can be added to test suite (`unittest/basics.cpp`) for this problem.

**Comment by fstrugar** [comment]
I've added the pull request! Couldn't really think of a good unit test for it - for some reason a simple version of what I did doesn't trigger the same runtime error in basics.cpp.
(I'm not 100% understanding the promise setting part and why it's set outside of the mutex lock but my change doesn't affect the way that works.)

**Comment by mgood7123** [comment]
> Hi @robinchrist , I believe this is doable with some hacks. Topology is a data structure created by the executor at runtime when you run a taskflow. It does store the callback and that callback lives together with the topology. You can store your taskflow in the callback capture, something like the following:
> 
> ```c++
> auto taskflow = std::make_shared<Taskflow>();
> executor.run(*taskflow, [taskflow] () { std::cout << "end of the execution and taskflow is still safe\n";  }).wait();
> ```

this can be wrapped up into

```C++
#include "taskflow/taskflow/taskflow.hpp"
#include <iostream>

struct fireAndForget {
    tf::Executor executor;
    tf::Taskflow taskflow;
    tf::Task task = taskflow.placeholder();
    std::future<void> future;
    
    template <typename C>
    fireAndForget(C && callable) {
        task.work(callable);
        future = executor.run(taskflow);
    }
    
    ~fireAndForget() {
        future.wait();
    }
};

int main() {
    fireAndForget([] () { std::cout << "test\n"; });
    return 0;
}
```

**Comment by tsung-wei-huang** [comment]
Hello @robinchrist @fstrugar @mgood7123 , the newest master branch has implemented a movable taskflow and submission to let the executor automatically manage the lifetime of a moved taskflow. Please read the [doc here](https://taskflow.github.io/taskflow/ExecuteTaskflow.html#ExecuteATaskflowWithTransferredOwnership). 

Please reopen the issue if there is still anything to improve
