### ISSUE TITLE
Incorrect task partitioning in parallel_for

### ISSUE THREAD

**Issue by mrduda** [taskflow/taskflow#169]
There's a problem in tf::FlowBuilder::parallel_for (one without a 'step' argument): if calling code leaves default argument value (chunk=1), the method splits entire range (begin..end) into N=(end-begin) count of small tasks. 

As a result, there will be many small tasks (as many as item count in the range) instead of having groups or subranges spread across N threads. This is bad because the time overhead of separate task execution in tf::Executor may be comparable to the whole time of the task itself.

Before this commit to master:
```
Revision: a09863da9039e59d808eaeec9edadad31f9126ac
Date: 03.01.2020 21:59:09
Message: updated dev/core
```
it did partition the begin..end range into subranges of (count / thread_count) items in each, so default value of the "p" argument did what is expected: splits the begin..end range into subranges and spawn only small amount of tasks.

.
**Desktop (please complete the following information):**
 - OS: any
 - Version: HEAD

**Comment by tsung-wei-huang** [comment]
Hi @mrduda , Yes, we are aware of that. For now, we leave the partition choice to users. Previously, we tried to do a static partition but in many workloads it still suffers from unbalanced partition and the runtime is not good.  Flowbuilder has no information about the executor and the executor may configure a different number of threads. The best strategy is to do some in-loop stealing but we are still working on an efficient algorithm to do this.

**Comment by WalterDehnen** [comment]
I think this is best implemented using dynamic tasks. Obviously, a task needs to have some information in order to decide whether to execute a sub-range loop serially or whether to split it dynamically into sub-tasks. One possible hint would be the size of the stack of tasks at the executing thread: if that is large, execute serially.

**Comment by tsung-wei-huang** [comment]
@WalterDehnen  I have redesigned the `tf::Taskflow::parallel_for` algorithms based on OpenMP's three partition algorithms, static, dynamic, and guided to largely improve the performance of parallel-for (very close to OpenMP and sometimes even better). You may check the master branch and [here](https://taskflow.github.io/taskflow/A0ParallelFor.html).
