### ISSUE TITLE
Make data export format configurable

### ISSUE THREAD

**Issue by elfring** [taskflow/taskflow#17]
[The data format “DOT”](https://en.wikipedia.org/wiki/DOT_(graph_description_language) "Usage for a graph description language") is supported by [the dump() function](https://github.com/cpp-taskflow/cpp-taskflow/blob/9cf75aeec0fefa98e597b53169a615acec9e921e/taskflow.hpp#L940 "Data export") so far.
* How do you think about to [support further file formats](http://www.gupro.de/GXL/ "Description for the graph exchange language") there by passing a corresponding data export object?
* Would you like to select any related parameters?

**Comment by twhuang-uiuc** [comment]
This is a good suggestion and we definitely can include it to the TODO list. At the same time, would you please share us with your thoughts about the API spec you would like to use?

**Comment by elfring** [comment]
The API specification can vary together with the involved classes also for this application domain, can't it?

**Comment by robinchrist** [comment]
@tsung-wei-huang Could you include the TODO list in the GitHub repo?
I really like this project and would like to improve it if there's any work to do and if I can find some spare time!

**Comment by tsung-wei-huang** [comment]
Hi @robinchrist , in fact, we have something similar in our [documentation page])https://cpp-taskflow.github.io/cpp-taskflow/master-branch.html). All the newest features are in the master branch. But it's good to have a TODO item list in that page. Thanks for the suggestion.
