### ISSUE TITLE
Schedule an individual task with an executor

### ISSUE THREAD

**Issue by bangerth** [taskflow/taskflow#172]
We're working to convert the deal.II project (see https://github/dealii/dealii) to use cpp-taskflow (#170 was a result of this attempt) and in https://github.com/dealii/dealii/issues/10388 I was wondering whether there is a way to schedule individual tasks with an executor without actually creating a `TaskFlow` object?

Right now, we are creating individual tasks using `std::async` (see https://github.com/dealii/dealii/pull/10389). In essence, this just puts the object into the background. But if cpp-taskflow uses a different thread pool to schedule task flows than the C++ runtime environment, then these two thread pools will get in each others' ways. As a consequence, I'm looking for a way to run individual tasks through cpp-taskflow executors instead of `std::async`. It seems unnecessary to create a whole task graph for a single task, but I can't quite find the right interface to avoid this.

**Comment by tsung-wei-huang** [comment]
Hi @bangerth, thanks for bringing this up. I am aware of this issue and I am adding this capability to `tf::executor`. Ideally, the API will look like `executor.async([] (){ ...})`, completely thread-safe. It takes some time to add this capability because the scheduler needs a bit redesign (details can be found [here](https://arxiv.org/abs/2004.10908v2)) for the best performance. However, if you can tolerate the performance, I may create this API on top of a heavy taskflow object managed transparently by the executor.

**Comment by bangerth** [comment]
@tsung-wei-huang Putting this on my reading list :-)

I have a feeling that at least for our own purposes, performance is of secondary concern for these individual tasks -- the tasks we schedule this way are pretty heavy. So we'd take whatever you already have! The syntax you show makes perfect sense to me!

**Comment by tsung-wei-huang** [comment]
@bangerth Thanks. I will keep you posted for this new capability :)

**Comment by tsung-wei-huang** [comment]
@bangerth I have added an method, `tf::Executor::async`, in the master branch that allows you to launch a STL-styled asynchronous task. You may find details [here](https://taskflow.github.io/taskflow/master-branch.html). It is thread-safe and can be called from an external thread or a task inside a taskflow. The scheduler autonomously detects the thread that submitted the task and integrates its execution into the work-stealing loop.

**Comment by bangerth** [comment]
Ah, most excellent! Do you have a timeline for a release that includes this? We can of course just work with the development sources, but generally prefer releases.

Looking forward to using this new feature -- thanks for implementing it! Extra kudos for already returning the proper `std::future` object :-)

**Comment by tsung-wei-huang** [comment]
@bangerth this will be included in the next release 2.7.0. For now, it is in the master branch because I would like to have it tested for another while but certainly will be in v2.7.0

**Comment by bangerth** [comment]
Thanks. Do you have a timeline for the 2.7 release?

**Comment by tsung-wei-huang** [comment]
@bangerth I plan to have it ready by the end of Sep.

**Comment by bangerth** [comment]
OK, great, thanks! We'll update our internal version then and convert our current task creation to TaskFlow!

**Comment by fstrugar** [comment]
Hi - just wondering whether the new tf::Executor::async is safe to call from different threads? I'm assuming not but just wanted to make sure.

**Comment by tsung-wei-huang** [comment]
Yes, it is thread-safe and can be called from any other threads. There are two cases: (1) if you call it from a non-worker thread, scheduling goes through a centralized queue which normally falls back to a simple thread-pool use; (2) if you call it from a task (worker inside the executor), scheduling goes through efficient work-stealing together with tasks.

**Comment by mfornace** [comment]
Hi, just wanted some advance clarification of `tf::Executor::async`. Will the returned future have a blocking destructor like the one from `std::async`?

**Comment by tsung-wei-huang** [comment]
@mfornace No - the future doesn't have a blocking destructor.

**Comment by tsung-wei-huang** [comment]
@bangerth I have made a new release today [v2.7.0](https://github.com/taskflow/taskflow/releases/tag/v2.7.0) that includes this feature.

**Comment by bangerth** [comment]
I saw, and already created an issue relating to importing it into deal.II :-)
https://github.com/dealii/dealii/issues/10989

**Comment by mfornace** [comment]
Hi @tsung-wei-huang thanks for the addition and response 👍. 

I'm glad I know the answer now, but I would suggest noting the non-blocking destructor in the docs. `std::async` has caused me and other people so much confusion due to its special case nature (which people will think of for any method called `async` I'd guess).

**Comment by tsung-wei-huang** [comment]
@mfornace sure I will modify the docs to add this info :)

**Comment by tsung-wei-huang** [comment]
I believe this has been solved in [Asynchronous Tasking](https://taskflow.github.io/taskflow/AsyncTasking.html).
