### ISSUE TITLE
add a header file with version information

### ISSUE THREAD

**Issue by tamiko** [taskflow/taskflow#175]
**Please describe your feature request.**

Currently, the only possibility to get a version information for (externally installed) cpp-taskflow headers is by querying the cmake configuration. This is what I currently do for deal.II for finding an external cpp-taskflow "library" (https://github.com/dealii/dealii/blob/master/cmake/modules/FindCPP_TASKFLOW.cmake).

However, it would be highly desirable to have a programmatic way of retrieving the version number from the header files alone. Having the version number available is necessary for us because we try to maintain compatibility with a number of upstream versions of a library and need to be able to adapt to more efficient interfaces and changes in upstream libraries.

**Comment by tsung-wei-huang** [comment]
Will include it in the next release. Thanks!

**Comment by tsung-wei-huang** [comment]
@tamiko I have added [version.hpp](https://github.com/taskflow/taskflow/blob/master/taskflow/version.hpp) to reflect the version programmatically. It is currently available in the master branch and will be formally included in the next release.

**Comment by tamiko** [comment]
@tsung-wei-huang This looks very good, thank you!
