### ISSUE TITLE
Parallel sort feature

### ISSUE THREAD

**Issue by bsviglo** [taskflow/taskflow#180]
Hi guys, thanks a lot for such a great library.
Do you plan to add some "parallel sort" implementation into the library via example or extension to the library (like TBB)?
It'll be very helpful because often we need some parallel sort implementation right in the library instead of each user add custom implemention for internal use only.

**Comment by bsviglo** [comment]
I'd say vector of size about 1000s of elements and bottleneck in sorting is complexity of comporator

**Comment by bsviglo** [comment]
Hi guys, any chance that this feature will be included into the core of taskflow?

**Comment by tsung-wei-huang** [comment]
Hi @bsviglo , this will be included soon. Currently, we are extending the [algorithm collection](https://taskflow.github.io/taskflow/Algorithms.html) to have more items.

**Comment by tsung-wei-huang** [comment]
@bsviglo this has been pushed to the master branch and will be included in the next major release 3.0.0. Please visit the [page](https://taskflow.github.io/taskflow/ParallelSort.html).
