### ISSUE TITLE
confict with boost 1.63

### ISSUE THREAD

**Issue by yulei666** [taskflow/taskflow#184]
**Describe the bug**
In file taskflow/utility/traits.hpp
MACRO **"has_member"** is defined but isn't used any where. And it is conflict with boost 1.63, make it complie error

**Suggestion**
Chang Name to tf_has_member Or Remove it?

**Comment by Liam0205** [comment]
Met this issue too. 

Naming macros with project prefix and using UPPER_CASE_WITH_UNDERSCORE is always good practice. `: )`
