### ISSUE TITLE
Nested parallel_for

### ISSUE THREAD

**Issue by DenisIshmukhametov** [taskflow/taskflow#185]
Hi! I wanted to ask if nested **parallel_for** is supported. I'm trying to use parallel_for inside parallel_for and I get a constant crash inside here: 
`inline Node* Graph::emplace_back()` in graph.hpp

If nested parallel_for is not currently supported are you guys planning to add that feature?

**Comment by tsung-wei-huang** [comment]
Do you have any code example?

**Comment by DenisIshmukhametov** [comment]
So my code on a high level was something like this:

```
void myFunction(tf::Subflow& subflow)
{
    subflow.parallel_for(outerArray.begin(), outerArray.end(), [&](auto elem1)
    {
        //...
        subflow.parallel_for(innerArray.begin(), innerArray.end(), [&](auto elem2)
        {
            //...
        }, 0, "Update inner array"); 
    }, 0, "Update outer array");
}
```

I could fix it by adding a custom copy of parallel for with changed signature:
```
void myFunction(tf::Subflow& subflow)
{
    my_parallel_for(outerArray.begin(), outerArray.end(), [&](tf::Subflow& innerSubflow, auto elem1)
    {
        //...
        innerSubflow.parallel_for(innerArray.begin(), innerArray.end(), [&](auto elem2)
        {
            //...
        }, 0, "Update inner array"); 
    }, 0, "Update outer array");
}
```

**Comment by tsung-wei-huang** [comment]
Yes, you need nested subflow in this case. Each lambda corresponds to an execution context of a task.
