### ISSUE TITLE
Is taskflow suitable for this scenario ?

### ISSUE THREAD

**Issue by boxerab** [taskflow/taskflow#186]
This looks like a wonderful project.

Here is my problem:

I would like to run an incremental filter on a compressed 2D image i.e. decompress the image in small windows and then filter each window once it is fully decompressed. The uncompressed image is broken down into 64x64 code blocks (each code block has a matching compressed code stream), and the blocks are grouped into overlapping 128x128 windows, where each window covers 4 blocks. All blocks in a window must be decompressed before that window gets filtered. 

Say I have a 192x192 image; then there are 4 overlapping windows. 

Let's say I have four threads, and each thread processes one window. Each thread tries to decompress its blocks, and when they are all decompressed, it applies the filter, But, if a block is already being decompressed by another thread, then we must wait until the other thread is done (but while waiting we can steal decompress jobs from some other thread).

So....... could this problem be modelled efficiently with taskflow ?

One more issue: I would like to set the thread affinity of the threads in the pool, and reserve one core and it's hyperthreaded sibling for each window.

Thanks very much!
Aaron

**Comment by tsung-wei-huang** [comment]
Hi, I think the best way to do this is twofold. First, you may reduce the filter size to create more tasks. You don't need to implement any stealing mechanism as long as you are able to decompose your workload into a task graph. Our library will handle the scheduling using work-stealing. Second, if you have GPU, I suggest using our cudaFlow to model these tasks. It will be much faster than CPU in your case I think.

It is always better if you can draw a task graph from your workload. Once the graph is there, it is fairly easy to convert it to taskflow :)

**Comment by hxxfff** [comment]
filtering a 64*64, maybe cost less than 1us,  is too Fine-Grained to create&schedule a task .

**Comment by boxerab** [comment]
Thanks for the quick reply. The filter is a wavelet filter, so it is time consuming and will act on all 4 blocks in the window. In fact, I forgot to mention that it will act on 4 windows at a time. All blocks
in all 4 windows must be decompressed before I perform the wavelet step. 64x64 block size is partly determined by the way the image is compressed, usually in 64x64 blocks.

As for GPU, I have implemented this algorithm on the GPU, but because of the GPU architecture and how SIMT works there, the algorithm there must be completely different than on the CPU in order to get a speed up. CPU cores seem more suitable to complex flows.

I will draw a task graph, thanks for the suggestion.

**Comment by boxerab** [comment]
> filtering a 64*64, maybe cost less than 1us, is too Fine-Grained to create&schedule a task .

Yes, filter 64x64 will be quick. In fact, the task is to filter 4 128x128 windows after all 64x64 blocks are decompressed. And I can change the size of the windows. From profiling on simple thread pool, 128x128 gives the best performance for the filtering.

**Comment by boxerab** [comment]
Can you recommend a good program to create task graphs ?

**Comment by hxxfff** [comment]
I am not familiar with task-flow,  but i find that it need to create task function for thread to run.
if the task is too small, the create action is not to be neglected.
CPU also can deal with Fine-Grained task, using thread pool and share the global atomic task id, without mutex.

**Comment by hxxfff** [comment]
for example, if there are 1000000 tasks for 8 threads to run. every task need about 0.1us ,  its a huge cost to create&register  the tasks.
 for these case, a task is enough,  the 8 threads run the same task(  with a atomic sub-task id ) without mutex.

**Comment by boxerab** [comment]
> for example, if there are 1000000 similar tasks for 8 threads to run. every task need about 0.1us , its a huge cost to create&register the tasks.
> for these case, a task is enough, the 8 threads run the same task( with a atomic sub-task id ) without mutex.

Thanks, is this a theoretical estimate, or is it based on experience with task-flow ?

**Comment by boxerab** [comment]
@tsung-wei-huang is it possible for a user to control how threads are assigned to tasks, based on knowledge of the algorithm? For my problem, I would like to use processor affinity so that a core and it's hyperthreaded sibling will work on a window of data, to optimize L1 cache usage.

**Comment by tsung-wei-huang** [comment]
Hi @boxerab and @hxxfff , thanks for your discussion. To @boxerab, it's hard to give you a firm answer about performance and suitability in your case. You need to measure. Without measure, all data is less meaningful because different applications have different computational patterns. Creating a task does have certain overheads. We have a task pool to optimize performance and memory reuse. In our platform with 4-core Intel 3.0 GH CPU, creating a task is about a few nanoseconds (amortized). 

We do not provide users explicit control to assign thread affinity. Affining threads to a certain processor is good for performance, but it can be very tedious for interoperability when you have multiple parallel task programs running on the same machine. Also, our scheduler considers GPU workers. It makes very little sense to bind a GPU worker to a particular CPU core. Instead, we have an adaptive scheduling algorithm to handle this for you. It may not be the best performance compared to explicit binding but in general cases, it performs very well. You may find more details in our [paper](https://arxiv.org/abs/2004.10908v2).

**Comment by boxerab** [comment]
@tsung-wei-huang thanks! looking forward to trying it out. I'm sorry but I have a few more questions :)
1. Would the scheduler design allow for taking processor affinity into account when scheduline, let's say for pthreads ?
1. Would the scheduler allow taking NUMA architecture into account ? 

Also, the VLSI background of the project sounds really interesting. Since you support CPU and GPU, you could efficiently add a reinforcement learning network to help optimize place and route, as in
https://ai.googleblog.com/2020/04/chip-design-with-deep-reinforcement.html

**Comment by tsung-wei-huang** [comment]
@boxerab Thanks!

1. Yes, it is compatible with pthreads. Adding the affinity to `tf::Executor` is pretty easy but we think it only works on linux-like systems.
2. Current, no. But like I said, it depends on your applications. Based on our experience, data-intensive applications are more sensitive to NUMA effect. Our scheduler lets OS automatically decide when to migrate and where to place computation. On top of it, we propose an adaptive strategy to balance the worker numbers with available task parallelism.

Yes, I am aware of that paper :)

**Comment by hxxfff** [comment]
@tsung-wei-huang,  to reduce the overhead, would you consider scheduler such  task:
1, all threads run the same task
2, the task is dynamically dived with atomic variable in run time, by all the thread，  atomic variable is changed by all threads, to record the remain&finished sub-task.
3, sub-task need not to be Explicit 
-

**Comment by hxxfff** [comment]
> > for example, if there are 1000000 similar tasks for 8 threads to run. every task need about 0.1us , its a huge cost to create&register the tasks.
> > for these case, a task is enough, the 8 threads run the same task( with a atomic sub-task id ) without mutex.
> 
> Thanks, is this a theoretical estimate, or is it based on experience with task-flow ?

similar as OPENCL pipe operation, 
reserve_id_t reserve_read_pipe(read_only pipe
gentype p, uint num_packets)

the threads first reserve some packets, then run.  the  reserve op on atomic 

> ## @tsung-wei-huang, to reduce the overhead, would you consider scheduler such task:
> 1, all threads run the same task
> 2, the task is dynamically divded with atomic variable in run time, by all the thread， atomic variable is changed by all threads, to record the remain&finished sub-task.
> 3, sub-task need not to be Explicit

**Comment by hxxfff** [comment]
@tsung-wei-huang  ， Is this usage  valid? 

#include <taskflow/taskflow.hpp>  
int main(){

  tf::Executor executor;
  tf::Taskflow taskflow("reenterable");
  
  std::atomic<int> iCount(0);
  const int total=100000;
  
  auto func = [&iCount, &total]() { while(iCount<total){iCount++}
                                   std::cout << "TaskA\n"; };

  auto A = taskflow.emplace(func);
  auto B = taskflow.emplace(func);
  auto C = taskflow.emplace(func);
  auto D = taskflow.emplace(func);
  executor.run(taskflow).wait();
  std::cout <<iCount.load(std::memory_order_relaxed);
  return 0;
}

**Comment by tsung-wei-huang** [comment]
Yes, it is valid, as long as you don't have multiple write to the non-atomic variable `total`. I have been using a similar pattern to develop an asynchronous data fetcher.

**Comment by boxerab** [comment]
>     1. Yes, it is compatible with pthreads. Adding the affinity to `tf::Executor` is pretty easy but we think it only works on linux-like systems.

Thanks, it might be a nice feature, but you're right, the API would have to handle windows and OSX as well.

> 
>     2. Current, no. But like I said, it depends on your applications. Based on our experience, data-intensive applications are more sensitive to NUMA effect. Our scheduler lets OS automatically decide when to migrate and where to place computation. On top of it, we propose an adaptive strategy to balance the worker numbers with available task parallelism.

Thanks, yes, my application is very memory-bound, so sensitive to NUMA. 
I should really avoid premature optimization, and get some experience with the library
first :)

> 
> 
> Yes, I am aware of that paper :)

What would also be interesting is have the library learn the best scheduling strategy for a particular work flow. 

Thank you very much for answering my questions !  Going to close this issue.
