### ISSUE TITLE
busy wait or wait a OS  notification 

### ISSUE THREAD

**Issue by hxxfff** [taskflow/taskflow#187]
busy wait or wait a OS  notification , in this case:
"
A.precede(B, C, E); 
C.precede(D);
B.precede(D, E);
"
when task  D wait B and C,  may be  B and C finished almost a same time (for example time gap =1 us),  will D busy wait or wait a OS  notification(condition)? sometimes, the OS notification delay > 2ms, it mean's D is delayed 2ms before invoked.

**Comment by tsung-wei-huang** [comment]
Hi @hxxfff we don't do busy wait but an adaptive work-stealing strategy. Details can be found in [here](https://arxiv.org/abs/2004.10908v2). Soon after a task meets its dependencies, we immediately insert the task into a local task queue of a worker. It then immediately pops out (or be stolen by another worker) to execute the task. There is no OS-level notification and hence efficiency.

**Comment by hxxfff** [comment]
thanks, that' great.
