### ISSUE TITLE
Allow user control of thread creation

### ISSUE THREAD

**Issue by xbreak** [taskflow/taskflow#191]
**Please describe your feature request.**

I'd like to create my own _host_ threads used by `tf::Executor`, that can be created using the full capability of my platform, to set different policies (NUMA affinity et.c.). In one of my use-cases I would then have differently "flavored" `Executors` instances, each with different properties. In contrast to #190 I'm not asking for any scheduling support (if I understood that request correctly). I would be responsible for submitting tasks to the appropriate executor which I think makes this feature low-impact.

To make it more concrete one use-case I have is to isolate a `tf::Taskflow` computation to a given NUMA node to avoid interference with other activities on other nodes. To do that I'd create a set of threads that match the NUMA topology, set memory policy, affinities and so on.

Given the `std::thread` API a feasible option would be if `tf::Executor` accepts a callable that creates the threads, maybe something like (pseudo-code-ish):

```c++
template<class ThreadCreator>
explicit Executor(ThreadCreator tc, size_t N = std::thread::hardware_concurrency());
...
_spawn() {
  ...
  _threads.emplace_back(
      std::invoke(tc,
                  [this] (Worker& w) -> void {...}
      )
  );
}
```
where `ThreadCreator` implements the concept matching `std::thread` constructor, so something like:

```c++
template< class Function, class... Args >
std::thread (Function&& f, Args&&... args);
```

As far as I can tell the threads are only spawned once so there would be no need to store `ThreadCreator` so no need to make `tf::Executor` class-templated or resort to type erasure. As far as I can tell only `_spawn` would be affected.

Cheers, and thanks for a very nice library!

**Comment by tsung-wei-huang** [comment]
@xbreak thanks for your questions. If I understand correctly, you are asking to have executor-level thread binding. Your idea of passing thread creator is indeed flexible but I am not sure how it is used in the context of template in executor? Probably it's better to let users define upon constructor which thread binds to which cpu?

**Comment by xbreak** [comment]
@tsung-wei-huang: Thanks for the quick reply! 

> If I understand correctly, you are asking to have executor-level thread binding.
Yes, and more.

> ... but I am not sure how it is used in the context of template in executor?

Would you mind elaborating on this? I'm not quite following.

>  Probably it's better to let users define upon constructor which thread binds to which cpu?

Do you mean passing in a data structure that describes e.g. affinities? 
That is indeed an option for core-pinning specifically, and maybe some use-cases are solved by that. But I think if a user resorts to binding threads to cores it seems likely that they would make use of the full capability of e.g. libnuma and/or cpusets as well. Because then they have control over placement, scheduler, memory policy and priority. If the same can be achieved by passing a descriptor to `tf::Executor` I would not mind it, but it seemed difficult and a "big ask" to me.

**Comment by xbreak** [comment]
I played with an implementation to give you an idea what I mean here: https://github.com/taskflow/taskflow/compare/master...xbreak:threadcreator

**Comment by tsung-wei-huang** [comment]
@xbreak thanks! let me digest it a bit and I will get back to you... :)

**Comment by tsung-wei-huang** [comment]
I believe this has just been addressed in the present master branch and will be part of the future 3.5.0 release. Please also refer to [Change the Worker Property](https://taskflow.github.io/taskflow/ExecuteTaskflow.html#ChangeWorkerProperty). 

Feel free to reopen the issue if necessary.
