### ISSUE TITLE
Exception Forwarding to std::future

### ISSUE THREAD

**Issue by dahubley** [taskflow/taskflow#193]
I expected the taskflow library to forward any exceptions thrown in a taskflow to be forwarded to the thread calling std::future<T>::get(). However, anytime an uncaught exception occurs in a taskflow it crashes my program by calling std::abort(). This could be expected behaviour but I felt like the library should behave like std::async where any exceptions get rethrown when std::future::get is called.

**Comment by tsung-wei-huang** [comment]
Currently, we do not plan to forward the exception to `future` but ask users to explicitly wrap their tasks under `try catch` block. Exception handling is application-dependent.

**Comment by dahubley** [comment]
If you miss an exception it results in std::terminate being called from inside a worker thread. Implementing this would make the behavior similar to intel tbb.
