### ISSUE TITLE
Clarify project dependencies and `/3rd-party` directory in README

### ISSUE THREAD

**Issue by xbreak** [taskflow/taskflow#194]
It's not clear to me what the actual taskflow dependencies are (if any). Particularly in respect to the bundled dependencies in /3rd-part. I hope you can clarify both the "build" dependencies and separately dependencies needed for test and examples in the readme and whether they are installed with taskflow.

Cheers

Edit: Also relates to #176.

**Comment by tsung-wei-huang** [comment]
Hi @xbreak , taskflow is header-only. You just need to copy the folder `taskflow/` to your project and include it. The folder 3rd-party is only used for internal benchmarking purpose.

**Comment by xbreak** [comment]
Thanks for the clarification. Although Doctest seem to be used for building unit tests?

**Comment by tsung-wei-huang** [comment]
@xbreak yes, doctest is used for building unit tests.

**Comment by xbreak** [comment]
Thanks!
