### ISSUE TITLE
How much C++17 is actually used?

### ISSUE THREAD

**Issue by IngwiePhoenix** [taskflow/taskflow#200]
(Since this is not a bug report, but could be interpreted as a Feature Request, I decided to post it as such. Sorry in advance! :) )

Hello there!
I am working on a concept for a build tool. I have been struggling to deal with the visualisation of graphs due to my visual impairment and thus need to utilize an external library to handle this portion for me; mainly, a library I can dump a list of my tasks into, and have them executed properly.

Since this is a built tool, the three most important parts are input, output and dependency. Imagine the following (simplified) class:

```c++
class Task {
  public:
  Task(string _input, string _output, list<string> _deps)
    : input(_input), output(_output), deps(deps) {}

  int runCommand();

  private:
  string input, output;
  list<string> deps;
};
```

Each `Task` would be instantiated like so:

```c++
new Task("foo.c", "bar.o", {});
new Task("bar.c", "bar.o", {});
new Task("lib.c", "lib.o", {});
new Task("lib.o", "lib.a", {"lib.o"});
// Not shown in the mock-up above, but the input might also be a list,
// especially when being the end of a chain of tasks.
new Task({"foo.o", "bar.o", "lib.a"}, "app.exe", {"foo.o", "bar.o", "lib.a"});
```

I know that I would have to normally create a directed graph, topologicaly sort that and then distribute the resulting list across my worker threads. However, is there a way to implement a dependency-based task flow using this project?

The reason I specifically ask for C++17 is because I am writing mine in C++98 since it is much more portable across compilers and other toolchains. Especially later versions in and after C++11 are not equally suported across GCC, Clang and MSVC. GCC and Clang support it basically entirely but MSVC is a whole different story...

So how much would I have to modify this library to do exactly what I need it to do - and to comply to C++98 instead of C++17?

Kind regards,
Ingwie

PS. I have been looking for help and answers since a multitude of hours... I am sleepy. Also, I am not a native speaker. Hopefuly I was able to convey my message :)

**Comment by tsung-wei-huang** [comment]
Hi @IngwiePhoenix thanks for your message. Taskflow is written in C++14 and we do heavily use many modern C++ features and idioms. We do not do any topological sort but have a very special schedule due to our condition tasking interface. I am not sure how this can be done using a normal scheduling algorithm. 

I hope I have answered your questions ..?

**Comment by broadsun** [comment]
Hello，why not use c++11

**Comment by IngwiePhoenix** [comment]
Hello @tsung-wei-huang !
I am sorry for replying so late - the notification for your reply got lost surprisingly deep in my mailbox. Oops.

Thank you for your answer! Since you said you use several features, this project may not be what I was looking for myself. I wish you good luck with this :)

@broadsun Up untill a while ago, MSVC and anything newer than >= C++0x was terrible in terms of compatibility. That is why I settled in to use an older, battle-tested standard for my project, so that it can be compiled in *basically* any environment. But from the looks of it, I may have to give this up and go to C++11 instead...

**Comment by totalgee** [comment]
> Especially later versions in and after C++11 are not equally suported across GCC, Clang and MSVC. GCC and Clang support it basically entirely but MSVC is a whole different story...

> Up untill a while ago, MSVC and anything newer than >= C++0x was terrible in terms of compatibility. 

This has not been my experience. GCC, Clang and MSVC have all supported C++11 since 2013 releases of their compilers (and standard libraries), and C++14 has been supported fully by all three since 2017 (or earlier, e.g. for Clang). Xcode's variant of the Clang toolset tends to lag a bit behind, but they're also pretty solidly on C++17 these days, with full C++14 support.

That being said, there are obviously plenty of projects (like yours) which, for various reasons (e.g. are you working on embedded computers?), can't move to a newer toolset.

**Comment by tsung-wei-huang** [comment]
@totalgee agree - I think MSVC is one of the early compiler vendors that support the newest C++ feature. They have been involved in the C++ committee board for years.

**Comment by patlecat** [comment]
> 
> 
> @totalgee agree - I think MSVC is one of the early compiler vendors that support the newest C++ feature. They have been involved in the C++ committee board for years.

Yes they are always among the first ones to adopt new standard features but only ever a few and never all. It has been worse before though.

**Comment by tsung-wei-huang** [comment]
BTW, starting from v3  we will migrate the codebase to cpp17.
