### ISSUE TITLE
Cancel a running taskflow

### ISSUE THREAD

**Issue by mpowelson** [taskflow/taskflow#201]
Is there currently a way to cancel a currently running taskflow? I have tried something like `executor.run_until(taskflow, [this]() { return this->done;});` , but that only seems to check the predicate when restarting the taskflow. Rather, I'd like the ability to have it check it before entering each task in the taskflow or even abort the tasks while they are running.

**Comment by tsung-wei-huang** [comment]
Hi @mpowelson currently we do not have support for canceling a taskflow on the running. This is definitely something we will include in the future release.

**Comment by kam3k** [comment]
I would really appreciate having this feature as well.

**Comment by tsung-wei-huang** [comment]
Hi @kam3k and @mpowelson , the mater branch now supports canceling a running/submitted taskflow through `tf::Future::cancel`. You may check the [doc](https://taskflow.github.io/taskflow/CancelARunningTaskflow.html). This is be included in the next major release v3.

**Comment by tsung-wei-huang** [comment]
This can be closed.
