### ISSUE TITLE
Basics unit tests fail to build in VS Debug configuration

### ISSUE THREAD

**Issue by egorodet** [taskflow/taskflow#202]
**Description**
I've added Taskflow as external submodule to my project and use latest version 2.5.0. I integrate Taskflow in the project build by adding it as subdirectory in CMakeList.txt. When I try to build Debug configuration in VS 2019, I get compilation error in Taskflow basics unit-test: `number of sections exceeded object file format limit`.

**Steps To Reproduce**
1. Generate Visual Studio 2019 solution using cmake `cmake -G "Visual Studio 16 2019" -A x64`
2. Build Debug configuration from VS or cmd `cmake --build . --config Debug`
3. Build fails with error `fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj`:
```
1>------ Build started: Project: basics, Configuration: Debug x64 ------
1>Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x64
1>Copyright (C) Microsoft Corporation.  All rights reserved.
1>cl /c /IC:\Git\MethaneKit\Externals\TaskFlow /I"C:\Git\MethaneKit\Externals\TaskFlow\3rd-party\doctest" /I"C:\Git\vcpkg\installed\x64-windows\include" /Zi /W3 /WX- /diagnostics:column /MP /Od /Ob0 /D WIN32 /D _WINDOWS /D _ENABLE_EXTENDED_ALIGNED_STORAGE /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"basics.dir\Debug\\" /Fd"basics.dir\Debug\vc142.pdb" /Gd /TP /errorReport:prompt C:\Git\MethaneKit\Externals\TaskFlow\unittests\basics.cpp
1>basics.cpp
1>C:\Git\MethaneKit\Externals\TaskFlow\unittests\basics.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
1>Done building project "basics.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Desktop:**
 - OS: Windows 10 Pro 1909
 - Visual Studio 2019 16.6.4
 - Taskflow version 2.5.0

**Additional context**
In general, I don't want to build 3rd-party library unit tests as a part of my project. So it would be nice to have a CMake option to disable Taskflow unit tests build (aded as a separate feature request #203)

**Comment by tsung-wei-huang** [comment]
I believe this issue has been resolved in the newest release (if not - please reopen and show the error)
