### ISSUE TITLE
Add CMake option to disable unit tests and examples build

### ISSUE THREAD

**Issue by egorodet** [taskflow/taskflow#203]
When Taskflow is added as submodule to the target Git project and is integrated in CMake build by adding as subdirectory, it would be nice to have CMake option to disable Taskflow unit tests and examples building, which are not needed when target project is built.

**Comment by tsung-wei-huang** [comment]
Hi @egorodet  I have added a macro `TF_BUILD_TESTS` and `TF_BUILD_EXAMPLES` to the make, default `ON`. You may disable it by `make ../ -DTF_BUILD_TESTS=OFF`. Updates are at the master branch now.

**Comment by egorodet** [comment]
Hi @tsung-wei-huang, thank you for fast resolution!
