### ISSUE TITLE
Please consider re-enabling the case of tf::Executor with 0 workers (Running on main thread)

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [taskflow/taskflow#204]
Previously:
https://github.com/taskflow/taskflow/issues/94
Related:
https://github.com/taskflow/taskflow/issues/128
https://github.com/taskflow/taskflow/issues/164

Hello,

Please consider re-enabling the case of tf::Executor with 0 workers. (Running on main thread)
As it allows the same written-in-node-graph-style, taskflow-integrated library to be ported directly to a system with no threading capability at minimal refactoring costs.

If this comes with a significant performance impact, perhaps consider introducing a preprocessor switch.

**Comment by tsung-wei-huang** [comment]
@UNDEFINED-BEHAVIOR This indeed is a bit difficult - because right now we have GPU workers and it makes the scheduler design very tricky to have zero workers. I guess a workaround is to always use 1 worker in the executor?

**Comment by UNDEFINED-BEHAVIOR** [comment]
I see.

It's unfortunate threading cannot be disabled entirely anymore but I can deal with it on my end.
