### ISSUE TITLE
Simple thread pool use-case

### ISSUE THREAD

**Issue by KingDuckZ** [taskflow/taskflow#205]
**Please describe your feature request.**

Hi, in my code I have a simple thread pool scenario with no dependencies and no need for any other advanced functionality. The way I'm approaching this now:

1. emplace a task that calls a blocking function (it's handy that I have a blocking function to call, but ideally this shouldn't be necessary), store the Subflow* in a std::future and block
2. run the taskflow object with the executor
3. return the Subflow* value so it can be used elsewhere (not sure this is supported)
4. when I want to add new tasks to my pool I emplace on the Subflow object retrieved this way

This seems overly complicated to me and it's also not working. Program segfaults if I run it, and it does nothing if I run it with gdb attached (tasks added to the subflow never get executed).

Can you please provide an example for a simple thread pool scenario with independent tasks that could at any point be 0 without killing the execution? Thanks

**Comment by tsung-wei-huang** [comment]
I think you are referring to something like `std::async` but with a support to run on a thread pool. This is something I am working on to add into the `tf::executor` because it requires some specialized data structure to comply with the dependency graph. Am I understanding your idea correctly?

**Comment by KingDuckZ** [comment]
Maybe yes. In practice I'd like to have an always active thread pool - even when there is no work to do. Then as I receive network requests that chuck of work will be pushed into the pool and some thread will execute it. All jobs are independent from each other and can be run in any order.
Thread pool should only stop running when my program quits.
[This](https://roar11.com/2016/01/a-platform-independent-thread-pool-using-c14/) is probably what I need and I'm considering switching to it, but Taskflow is obviously better maintained, has a better reputation etc, so I'm reluctant.

**Comment by tsung-wei-huang** [comment]
@KingDuckZ I have added a STL-styled async task call, [tf::Executor::async](https://taskflow.github.io/taskflow/master-branch.html), in the master branch. I think this allows you to use `tf::Executor` as a simple thread pool use case. Keep in mind, the underlying scheduling is based on very efficient work stealing which allows you to perform more efficient asynchronous task launch especially under nested cases.

**Comment by KingDuckZ** [comment]
Thank you for looking into this! I have already switched to that roar11 library, but I will play with taskflow again as soon as I get a chance and evaluate what's the impact on changing my code.

**Comment by tsung-wei-huang** [comment]
@KingDuckZ not a problem. Thanks for your interest in Taskflow 👍
