### ISSUE TITLE
v2.5.0 still recognized as 2.4.0

### ISSUE THREAD

**Issue by jgbradley1** [taskflow/taskflow#207]
**Describe the bug**
The `v2.5.0` release is recognized as version `v2.4.0` in cmake.

```
# Project name
project(Taskflow VERSION 2.4.0 LANGUAGES CXX)
```

**To Reproduce**
1. Download the `v2.5.0` release
2. Inspect the top-level `CMakeLists.txt`

**Comment by tsung-wei-huang** [comment]
@jgbradley1 thanks for bringing this up. I am not sure how to get this fixed. Do you have any idea?

**Comment by jgbradley1** [comment]
Easiest solution would be to make a v2.5.1 release from master now (ensure the version is correct in the cmake file this time).

The more complicated suggestion would be to go back to the commit pointed to by the v2.5.0 release, make the necessary change to the cmake file and commit, and edit the release to point to this new commit with the change....then rebase all future commits so the change propagates through.

I only have mediocre experience with rebase like this (not a fan of using it). It would preserve the commit history though. For the sake of your sanity, I would just do a v2.5.1 release.

**Comment by tsung-wei-huang** [comment]
@jgbradley1 I will fix it in the next release - it's very soon.
