### ISSUE TITLE
Windows Style Thread creation

### ISSUE THREAD

**Issue by mgood7123** [taskflow/taskflow#215]
**Please describe your feature request.**

is it possible to implement windows style thread management into taskflow?

specifically the ability to create a thread in a suspended state, and thread_suspend/thread_resume

on UNIX this is achievable by using the clone(2) syscall in order to invoke pkill(..., SIG_STOP) without it also affecting the main program that manages the threads

for example

```C++
tf::Taskflow taskflow;

// Add tasks into the taskflow

// create A in a suspended state
tf::Task A = taskflow.emplace(
    [] () { std::cout << "Task A\n"; }
).suspend();
// can also suspend manually,
// suspending multiple times has no effect
// if task is already suspended
A.suspend();

// create B in a resumed state
tf::Task B = taskflow.emplace(
    [] () { std::cout << "Task B\n"; }
);

// Declare an executor
tf::Executor executor;

std::future<void> future = executor.run(taskflow);  // non-blocking return

// suspend task B if it has not finished executing yet
B.suspend();
// and resume task A
A.resume();

// do some stuff

// resume B
B.resume();

// wait for both A and B to end
future.wait();
```

**Comment by tsung-wei-huang** [comment]
@mgood7123 this is definitely an interesting feature to do and I am very interested in getting this coroutine concept (or boost fiber) into Taskflow. It requires further discussion. For example, when you create a task, it doesn't really do anything but create a node that wraps the callable. I am not very clear what `A.suspend` means here? If you are interested in scheduling a call, please send us an email here: https://taskflow.github.io/

**Comment by mgood7123** [comment]
> @mgood7123 this is definitely an interesting feature to do and I am very interested in getting this coroutine concept (or boost fiber) into Taskflow. It requires further discussion. For example, when you create a task, it doesn't really do anything but create a node that wraps the callable. I am not very clear what `A.suspend` means here? If you are interested in scheduling a call, please send us an email here: https://taskflow.github.io/

A.suspend() would simply suspend the task if it is running, or queue it for immediate suspension if it has not been executed or if it has finished via future.wait()

**Comment by mgood7123** [comment]
or rather, it could set a flag telling the scheduler to not scedule the thread untill the flag is unset

**Comment by tsung-wei-huang** [comment]
@mgood7123 , interesting - I believe this requires coroutine capability and another dedicated task type to handle (e.g., coroutine task).

**Comment by mgood7123** [comment]
hmm ok

**Comment by 5fuheyan** [comment]
I am very interested about this feature, maybe You can refer to the implementation of  Parallel Patterns Library (PPL) concurrency::task。If you include <pplawait.h>, then you can use concurrency::task as a coroutine type.

**Comment by mgood7123** [comment]
> I am very interested about this feature, maybe You can refer to the implementation of Parallel Patterns Library (PPL) concurrency::task。If you include <pplawait.h>, then you can use concurrency::task as a coroutine type.

hmm yes, however would it lead to data races between the thread being suspended, and the task completing?

**Comment by 5fuheyan** [comment]
> > I am very interested about this feature, maybe You can refer to the implementation of Parallel Patterns Library (PPL) concurrency::task。If you include <pplawait.h>, then you can use concurrency::task as a coroutine type.
> 
> hmm yes, however would it lead to data races between the thread being suspended, and the task completing?

If you are talking about two tasks, then yes,it would lead to data races. But this has nothing to do with the suspension ，just because of multi-threaded data race。Two coroutines on the same task will not cause data race，this is the benefit of multiple coroutines 。You can create multiple tasks ,and create multiple coroutines on each task 。maybe you can learn about c++20 coroutine。

**Comment by mgood7123** [comment]
> > > I am very interested about this feature, maybe You can refer to the implementation of Parallel Patterns Library (PPL) concurrency::task。If you include <pplawait.h>, then you can use concurrency::task as a coroutine type.
> > 
> > 
> > hmm yes, however would it lead to data races between the thread being suspended, and the task completing?
> 
> If you are talking about two tasks, then yes,it would lead to data races. But this has nothing to do with the suspension ，just because of multi-threaded data race。Two coroutines on the same task will not cause data race，this is the benefit of multiple coroutines 。You can create multiple tasks ,and create multiple coroutines on each task 。maybe you can learn about c++20 coroutine。

I meant like, for example

a data race between sending SIG_STOP, and the thread ending before SIG_STOP arrives and halts the thread

**Comment by tsung-wei-huang** [comment]
Closed due to no more activities.
