### ISSUE TITLE
alias

### ISSUE THREAD

**Issue by mgood7123** [taskflow/taskflow#217]
**Please describe your feature request.**

could you provide a `tf::Task::depend` alias for `tf::Task::precede`?
and a could you provide a `tf::Taskflow::add` alias for `tf::Taskflow::emplace`?

**Comment by tsung-wei-huang** [comment]
I am not sure if this is really needed.

**Comment by mgood7123** [comment]
> I am not sure if this is really needed.

probs not, but would be useful tho :)
