### ISSUE TITLE
doc grammar

### ISSUE THREAD

**Issue by mgood7123** [taskflow/taskflow#218]
**Describe the bug**
`} // at this point, taskflow might get destructed while it is running, resulting in defined behavior`

**To Reproduce**
1. Go to https://taskflow.github.io/taskflow/chapter2.html#C2_ThreadSafety
3. Scroll up to 'Issuing multiple runs on the same taskflow will automatically synchronize to a sequential chain of executions in the order of run calls.'

**Comment by tsung-wei-huang** [comment]
Thanks. Fixed.
