### ISSUE TITLE
Is it possible to automatically manage the lifecycle of tf::Taskflow?

### ISSUE THREAD

**Issue by nqf** [taskflow/taskflow#223]
```
#include <unistd.h>

#include <taskflow/taskflow.hpp>

//std::shared_ptr<tf::Taskflow> tt;

tf::Executor executor;
int test() {
	auto taskflow = std::make_shared<tf::Taskflow>("simple");
	//tt = taskflow;
	auto A = taskflow->emplace([=]() {
		//sleep(1);
		std::cout << "TaskA\n";
	});
	auto B = taskflow->emplace([=]() {
		//sleep(1);
		std::cout << "TaskB\n"; /*  */
	});
	auto C = taskflow->emplace([=]() {
		//sleep(1);
		std::cout << "TaskC\n";
	});
	auto D = taskflow->emplace([=]() {
		//sleep(1);
		std::cout << "TaskD\n";
	});

	A.precede(B);
	A.precede(C);
	B.precede(D);
	C.precede(D);

	executor.run(*taskflow);

	std::cout << "test end count: " << tt.use_count() << std::endl;
	return 0;
}

int main() {
	std::cout << "call test" << std::endl;

	test();

	std::cout << "call end" << std::endl;
	while (1) {
		std::cout << "count: " << tt.use_count() << std::endl;
		sleep(2);
	};
}
```
After the end of the test function， Taskflow will be released，Is It ( executor.run)  possible to receive a std::shared_ptr<tf::Taskflow> ?

**Comment by tsung-wei-huang** [comment]
I think I will add a support to this but using `std::move` to manage the resource.

**Comment by robinchrist** [comment]
This is probably related:
https://github.com/taskflow/taskflow/issues/165

**Comment by tsung-wei-huang** [comment]
Hello @nqf and @robinchrist  the newest master branch has implemented a movable taskflow and submission to let the executor automatically manage the lifetime of a moved taskflow. Please read the [doc here](https://taskflow.github.io/taskflow/ExecuteTaskflow.html#ExecuteATaskflowWithTransferredOwnership). 

Please reopen the issue if there is still anything to improve.
