### ISSUE TITLE
Is Emscripten supported?

### ISSUE THREAD

**Issue by jnmaloney** [taskflow/taskflow#224]
I see some commenters that have had success building with Emscripten. When I try to build the simple example with emcc I get the error Unknown OS.

**Comment by tsung-wei-huang** [comment]
Are you trying to compile a threaded program to JS? I don't think emscripten is supported on this front.

**Comment by jnmaloney** [comment]
I am trying to compile to web assembly (wasm).

**Comment by tsung-wei-huang** [comment]
As far as I know, wasm doesn't support pthread yet. (not web workers)

**Comment by jnmaloney** [comment]
Thanks for your reply. I've been looking at https://emscripten.org/docs/porting/pthreads.html but I'm still exploring how pthreads are supported in browser applications.

**Comment by tsung-wei-huang** [comment]
@jnmaloney yes, I know that but most browsers disable the support of shared buffer for web workers - which makes threading pretty useless in that sense.
