### ISSUE TITLE
Allow out-of-tree builds

### ISSUE THREAD

**Issue by musteresel** [taskflow/taskflow#226]
**Allow (what is normally standard with CMake) out-of-tree builds**

I was *very* surprised when I first compiled taskflow with my usual approach to a CMake based project:

~~~
# in taskflow repo
cmake -S . -B builddir
cmake --build builddir
cd builddir
ls
~~~

You deliberately break the usual CMake flow by modifying the output directory to put the example/test executables in the source tree. **Why?**

Supporting out-of-source/out-of-tree builds has many positive side effects:

 - Source tree can be read only (some packaging systems require this; or dedicated build servers accessing a network share which is read only for security reasons)
 - Multiple builds (different options / compilers) can happen in parallel; can be tested in parallel
 - Source tree remains clean of build files
 - Removing build files means just removing the build directory

Would you accept a PR which fixes this?

**Comment by tsung-wei-huang** [comment]
@musteresel MANY THANKS if you can submit a PR to fix it! This is one of my TODO items but somehow it was left blank.
