### ISSUE TITLE
Allow static/dynamic library build

### ISSUE THREAD

**Issue by musteresel** [taskflow/taskflow#227]
**Allow to build taskflow as a static or dynamic library and link against it.**

Most of the code is not template code; so it could be compiled into a static or dynamic library and then later linked to applications.  This would most likely reduce compile times a lot.

This can be implemented while at the same time keeping it possible to use taskflow as header only library in the following way:

~~~
// theclass.hpp
class TheClass {
  void dummy(void);
};

#ifdef HEADERONLY
#include "implementation/theclass.cpp"
#endif 
~~~

~~~
// theclass.cpp
#ifndef HEADERONLY
#include "theclass.hpp"
#endif
#include <iostream>
inline void TheClass::dummy(void) {
  std::cout << 42 << std::endl;
}
~~~

We can add a CMake library target with these implementation files to get a static and/or dynamic library.  An application can then either just include the header and later link against that library or define HEADERONLY (probably better something like TASKFLOW_HEADERONLY) and just include the header.

Benefits would be less build time, and no unnecessary standard includes in application code.

**Comment by tsung-wei-huang** [comment]
@musteresel this is definitely an excellent idea - the reason of mostly headers is we didn't have a general-purpose and performant scheduler with no templates until recent days. This is definitely a good thing to add. Would you be interested in cutting in? Cpp sources can be placed under `taskflow/src`

**Comment by wrenoud** [comment]
@tsung-wei-huang are you still interested in this addition?

**Comment by tsung-wei-huang** [comment]
Yes, but I do not have the bandwidth to do this now. Will be happy to see external contributions.

**Comment by wrenoud** [comment]
I just wanted to make sure you were interested if I invested some time in trying this out.
