### ISSUE TITLE
Catch custom exceptions in task Windows

### ISSUE THREAD

**Issue by ljpverbeek** [taskflow/taskflow#236]
**Issue description**
I am trying to catch a custom exception in a taskflow task. I have created a custom exception which inherits from std::exception. I throw this error in the try of a try catch in the task and try to catch it. This works fine on mac, but in windows I got the following error: "'_That': undeclared identifier". Catching std exceptions works just fine.

**To Reproduce**
1. Create custom exception in new class.
2. Create new taskflow.
3. Add try catch in taskflow task.
4. Throw custom exception in try.
5. Catch custom exception in catch.
6. Build error in windows

**Screenshots**
![image](https://user-images.githubusercontent.com/72545027/95431342-51890c80-094d-11eb-9cce-5a798b60e1b9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Microsoft Visual Studio Professional 2019
 - Version 16.7.5
 - Taskflow version 2.7.0

**Additional context**
As I said before, works fine on mac.

**Comment by tsung-wei-huang** [comment]
@ljpverbeek it looks strange to me - I suspect something goes wrong in your defined CustomError? I tried the following on Mac, Linux (CentOS7), and Windows and they all work fine:

```
  auto A = taskflow.emplace(
    []() { 
      try {
        std::cout << "hi\n";
      }   
      catch (std::runtime_error& re){  // or catch(...) {}
      }    
    }   
  );  
```

**Comment by ljpverbeek** [comment]
Thank you @tsung-wei-huang for your reply. Catching std errors (such as std::runtime_error, std::exception) works just fine in a task. It is specifically catching custom errors, catching custom errors outside taskflow work just fine as well. That's why I think the issue is with taskflow and custom errors, in windows (as it is working fine on mac). My CustomError definition looks like this:
![image](https://user-images.githubusercontent.com/72545027/95556563-c6bf1500-0a13-11eb-8b52-0d69047de83f.png)
Am I missing something for catching inside a task?

**Comment by tsung-wei-huang** [comment]
@ljpverbeek  the exception support is up in the current master/dev branch. Examples can be found [here](https://taskflow.github.io/taskflow/ExceptionHandling.html). Please share any feedback. This support will be part of release v3.7. 

Thank you for your contributions!
