### ISSUE TITLE
Not-relocatable CMake package after installation 

### ISSUE THREAD

**Issue by smartnet-club** [taskflow/taskflow#237]
**Describe the bug**
The generated by installer TaskflowTargets.cmake contains a variable with an absolute path.

```
# The installation prefix configured by this project.
set(_IMPORT_PREFIX "T:/sdk/taskflow/v2.6.0")
```
As a result, Taskflow cannot be moved to other location.

**To Reproduce**
1. Install Taskflow

**Additional context**
The problem in [this line](https://github.com/taskflow/taskflow/blob/80127cd2ecd2958bda1345e26be43bb977557a9f/CMakeLists.txt#L337)
You set absolute path in DESTINATION instead of relative to INSTALL_PREFIX

**Comment by tsung-wei-huang** [comment]
@smartnet-club would you please submit a PR to fix this?

**Comment by smartnet-club** [comment]
Unfortunately no. Better to remake and use [GNUInstallDirs](https://cmake.org/cmake/help/v3.19/module/GNUInstallDirs.html)

**Comment by tsung-wei-huang** [comment]
@smartnet-club I believe this has been solved in the master branch as a result of the pull request #280
