### ISSUE TITLE
MPI / IP distributed executor support

### ISSUE THREAD

**Issue by powderluv** [taskflow/taskflow#238]
How do you see distributed execution support in taskflow ? Would it ride on something like hpx ? Or will you natively support such an executor in the future. Any examples would be great.

**Comment by tsung-wei-huang** [comment]
Right now we only do single node heterogeneous computing - but this distributed execution is definitely something we are interested in :)

**Comment by powderluv** [comment]
Great to hear. Do you have any notes / RFCs on how you envision the distributions ? Would you support TCP, MPI, Libfabric etc ? Happy to help if the framework is setup for contributions.
