### ISSUE TITLE
Conditional execution of several threads at once.

### ISSUE THREAD

**Issue by Croolman** [taskflow/taskflow#239]
I am using the conditions to execute the capture from several devices at once. Due to the functionality of condition I have a condition for each capture device. I have not yet found a way to do it other way. Is there a way to implement a barrier-like approach or is it a feature not yet supported? Including a graph to visualize the intended use.
![graphviz](https://user-images.githubusercontent.com/8963977/96479966-e4715300-1239-11eb-8fc7-3a98e61f74c3.png)

**Comment by tsung-wei-huang** [comment]
@Croolman Not sure if I understand your question correctly - but Your graph doesn't seem right. Barrier  returns 0, 1, or 2 and I don't know why you have two edges labled as '1'? When it returns zero, it informs the scheduler to execute itself again, or moves on to either capture1 or capture2.

**Comment by Croolman** [comment]
@tsung-wei-huang I might have expressed myself wrong. The graph was altered to depict the intention. The question is if this might be supported, so if condition is 0 the barrier executes again, if the condition is 1 it executes all its successors at once. Or is this achievable through other means of the library?

**Comment by tsung-wei-huang** [comment]
Hi @Croolman in this sense, your graph correctly implements what you want. Keep in mind don't run into infinite loop :)

**Comment by Croolman** [comment]
@tsung-wei-huang thank you for the warning. The question still remains. Since the graph does not reflect the real implementation in taskflow, because if I understand it correctly, the `condition pattern` in taskflow does run only one successor at the time, is it possible or will it ever be possible to run conditionally multiple successors at once?

**Comment by tsung-wei-huang** [comment]
Yes - it only runs one successor at a time. It's not valid to run multiple successors at once. Condition task is similar to the logic of if-else, you can have only one branch at a time.

**Comment by Croolman** [comment]
Thank you for the answers and help.
