### ISSUE TITLE
Dump does not include subgraphs

### ISSUE THREAD

**Issue by Faaux** [taskflow/taskflow#240]
**Describe the bug**
Subgraphs not dumped to DOT representation.

**To Reproduce**
```c++
tf::Taskflow tf;
tf::Task A = tf.emplace( []() {} ).name( "A" );
tf::Task C = tf.emplace( []() {} ).name( "C" );
tf::Task D = tf.emplace( []() {} ).name( "D" );

// create a subflow graph (dynamic tasking)
tf::Task B = tf.emplace( []( tf::Subflow& subflow ) {
	   tf::Task B1 = subflow.emplace( []() {} ).name( "B1" );
	   tf::Task B2 = subflow.emplace( []() {} ).name( "B2" );
	   tf::Task B3 = subflow.emplace( []() {} ).name( "B3" );
	   B1.precede( B3 );
	   B2.precede( B3 );
	   } )
 	.name( "B" );

A.precede( B );	 // B runs after A
A.precede( C );	 // C runs after A
B.precede( D );	 // D runs after B
C.precede( D );	 // D runs after C 

tf.dump( std::cout );
```

**Screenshots**
Output (missing tasks B1, B2 and B3)
![image](https://user-images.githubusercontent.com/7034806/96773910-88e3c880-13e5-11eb-8474-7983c69975fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Installed via vcpkg (2.6.0)

Expected Output:
Same or similiar to the readme: https://github.com/taskflow/taskflow#dynamic-tasking

**Comment by tsung-wei-huang** [comment]
@Faaux subgraph is created at the execution of `B`. You need to run the taskflow first before dump.

```
executor.run(tf);
tf.dump(std::cout);
```

**Comment by Faaux** [comment]
Wow that was a quick response which makes totally sense! 

Thanks a lot
