### ISSUE TITLE
How to use cublas and cusparse

### ISSUE THREAD

**Issue by mfbalin** [taskflow/taskflow#241]
I have been looking at the API of cudaflow and cudatask but couldn't figure out how to make calls to linear algebra primitives in cublas and cusparse. Any pointers would be appreciated.

**Comment by tsung-wei-huang** [comment]
@mfbalin this is an excellent question - We are building a cublasFlow interface that allows user to perform blas function. This will be included in the next major release 3.0.

**Comment by mfbalin** [comment]
What about cusparse?

**Comment by tsung-wei-huang** [comment]
@mfbalin [tf::cudaFlowCapturer](https://taskflow.github.io/taskflow/GPUTaskingcudaFlowCapturer.html) offers a stream-based interface to capture CUDA graphs for cuSparse and cuBlas. Also, please read the [CUDA Graph support](https://docs.nvidia.com/cuda/cublas/index.html#CUDA-graphs) for using those CUDA libraries under stream capturing modes.
