### ISSUE TITLE
Support for intel compilers

### ISSUE THREAD

**Issue by trevor-vincent** [taskflow/taskflow#248]
Hi, thank you for the really cool library! The CmakeLists.txt blocks intel compilers (icpc), e.g.

```
else()
  message(FATAL_ERROR "\n\
Taskflow currently supports the following compilers:\n\
  - g++ v7.0 or above\n\
  - clang++ v6.0 or above\n\
  - MSVC++ v19.14 or above\n\
  - AppleClang v8 or above\n\
")
```

It would be nice to have icpc support if possible.
Thanks!

**Comment by tsung-wei-huang** [comment]
@trevor-vincent thanks for bringing this up! I think it's supportable by just adding an extra cmake else. Taskflow is standalone relying on only standard libraries. Would you be interested in submitting a pull request?

**Comment by trevor-vincent** [comment]
> @trevor-vincent thanks for bringing this up! I think it's supportable by just adding an extra cmake else. Taskflow is standalone relying on only standard libraries. Would you be interested in submitting a pull request?

Excellent, I'm definitely interested, I'll get a pull request done in the next day or so. Thanks!

**Comment by trevor-vincent** [comment]
Sorry for the delay on this, the official 2.7.0 release (https://github.com/taskflow/taskflow/archive/v2.7.0.tar.gz) compiles with the intel icpc compiler after a minor adjustment of the CMakeLists.txt as you suggested, however when compiling the master branch with icpc the build fails on the error:

```
[  3%] Building CXX object examples/CMakeFiles/condition.dir/condition.cpp.o
cd /scratch/p/pfeiffer/tvincent/taskflow/build/examples && /scinet/intel/2019u4/compilers_and_libraries_2019.4.243/linux/bin/intel64/icpc   -I/scratch/p/pfeiffer/tvincent/taskflow  -O3 -DNDEBUG   -std=gnu++17 -o CMakeFiles/condition.dir/condition.cpp.o -c /scratch/p/pfeiffer/tvincent/taskflow/examples/condition.cpp
In file included from /scratch/p/pfeiffer/tvincent/taskflow/taskflow/core/observer.hpp(3),
                 from /scratch/p/pfeiffer/tvincent/taskflow/taskflow/core/executor.hpp(3),
                 from /scratch/p/pfeiffer/tvincent/taskflow/taskflow/taskflow.hpp(3),
                 from /scratch/p/pfeiffer/tvincent/taskflow/examples/condition.cpp(20):
/scratch/p/pfeiffer/tvincent/taskflow/taskflow/core/task.hpp(343): error: function "std::variant<_Types...>::operator=(const std::variant<_Types...> &) [with _Types=<std::monostate, tf::Node::StaticTask, tf::Node::DynamicTask, tf::Node::ConditionTask, tf::Node::ModuleTask, tf::Node::AsyncTask, tf::Node::cudaFlowTask>]" (declared at line 998 of "/gpfs/fs1/scinet/niagara/software/2019b/core/bin/../include/c++/7.4.0/variant") cannot be referenced -- it is a deleted function
    _node->_handle = std::monostate{};
                   ^

compilation aborted for /scratch/p/pfeiffer/tvincent/taskflow/examples/condition.cpp (code 2)
```
Any suggestions to get around this?

**Comment by tsung-wei-huang** [comment]
I encountered this issue before and in most cases it's the compiler bug in implementing `std::variant`. What is the version of your intel compiler?

**Comment by trevor-vincent** [comment]
So changing line 343 fixes the issue! 

The compiler bug occurs at least in all versions of icpc from "19.0.3.199 20190206" to
"19.1.3.304 20200925" since these are the ones I have access to on the cluster. Would you like me to make a pull request with that line changed and the modified CMakeLists.txt?

**Comment by tsung-wei-huang** [comment]
Let's change line 343 on our side. Would you please do this in the pull as well? :)

**Comment by trevor-vincent** [comment]
Sure, sounds good, I'll do it tonight.
