### ISSUE TITLE
Can taskflows be conditional?

### ISSUE THREAD

**Issue by Levi-Armstrong** [taskflow/taskflow#253]
Currently we leverage the taskflow composability to build larger taskflows but we have a situation where we would like to leverage a taskflow which has a task internal to the taskflow which is called on success and one on failure where we would like to attach different taskflows to each of these tasks. Is this possible leveraging the taskflow composability?

**Comment by tsung-wei-huang** [comment]
Hi @Levi-Armstrong thanks for using Taskflow. Have you looked into [condition task](https://taskflow.github.io/taskflow/chapter4.html)? It looks like condition task is what you want here.

**Comment by Levi-Armstrong** [comment]
Thank you for the quick response. I am using the conditional task in other places when dealing with tasks directly but was not sure how to apply this to a taskflow leveraging task composition. When using the `composed_of` it returns a task, but do I just need to make sure this taskflow returns an integer from the exiting task, then I can use this task as conditional? I am still learning how task composition works.

**Comment by tsung-wei-huang** [comment]
Hi @Levi-Armstrong , would you please draw a graph that represents your intended behavior? You can have condition inside the composition but you can not have condition that goes across different compositions.

**Comment by Levi-Armstrong** [comment]
> can not have condition that goes across different compositions.

Ah, this is what I would like to do. I can work around this. Thank you.

**Comment by tsung-wei-huang** [comment]
@Levi-Armstrong I see. Yes, think about composition as a normal function block in a program and we do not allow condition that goes across different blocks (composition) - :)

**Comment by Levi-Armstrong** [comment]
> we do not allow condition to go across different blocks (composition) - :)

Would this be something that could be supported or is there fundamental reason why this is currently not supported?
