### ISSUE TITLE
gcc8.2.0 build break

### ISSUE THREAD

**Issue by shuzhifeng** [taskflow/taskflow#254]
**Describe the bug**

$g++ examples/simple.cpp -I./ -fno-permissive -std=c++17 -O2 -lpthread -o simple
In file included from /opt/gcc/8.2.0/include/c++/8.2.0/bits/localefwd.h:40,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/ios:41,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/ostream:38,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/iostream:39,
                 from ./taskflow/core/error.hpp:3,
                 from ./taskflow/core/graph.hpp:3,
                 from ./taskflow/core/task.hpp:3,
                 from ./taskflow/core/observer.hpp:3,
                 from ./taskflow/core/executor.hpp:3,
                 from ./taskflow/taskflow.hpp:3,
                 from examples/simple.cpp:13:
/opt/gcc/8.2.0/include/c++/8.2.0/x86_64-kewb-linux-gnu/bits/c++locale.h:52:23: error: 'uselocale' was not declared in this scope
   extern "C" __typeof(uselocale) __uselocale;
                       ^~~~~~~~~
/opt/gcc/8.2.0/include/c++/8.2.0/x86_64-kewb-linux-gnu/bits/c++locale.h:52:23: note: suggested alternative: 'setlocale'
   extern "C" __typeof(uselocale) __uselocale;
                       ^~~~~~~~~
                       setlocale
/opt/gcc/8.2.0/include/c++/8.2.0/x86_64-kewb-linux-gnu/bits/c++locale.h: In function 'int std::__convert_from_v(__locale_struct* const&, char*, int, const char*, ...)':
/opt/gcc/8.2.0/include/c++/8.2.0/x86_64-kewb-linux-gnu/bits/c++locale.h:75:53: error: '__gnu_cxx::__uselocale' cannot be used as a function
     __c_locale __old = __gnu_cxx::__uselocale(__cloc);
                                                     ^
/opt/gcc/8.2.0/include/c++/8.2.0/x86_64-kewb-linux-gnu/bits/c++locale.h:100:33: error: '__gnu_cxx::__uselocale' cannot be used as a function
     __gnu_cxx::__uselocale(__old);
                                 ^
In file included from /usr/include/stdio.h:934,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/cstdio:42,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/ext/string_conversions.h:43,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/bits/basic_string.h:6391,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/string:52,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/bits/locale_classes.h:40,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/bits/ios_base.h:41,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/ios:42,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/ostream:38,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/iostream:39,
                 from ./taskflow/core/error.hpp:3,
                 from ./taskflow/core/graph.hpp:3,
                 from ./taskflow/core/task.hpp:3,
                 from ./taskflow/core/observer.hpp:3,
                 from ./taskflow/core/executor.hpp:3,
                 from ./taskflow/taskflow.hpp:3,
                 from examples/simple.cpp:13:
/usr/include/bits/stdio.h: In function '__ssize_t getline(char**, size_t*, FILE*)':
/usr/include/bits/stdio.h:117:10: error: '__getdelim' was not declared in this scope
   return __getdelim (__lineptr, __n, '\n', __stream);
          ^~~~~~~~~~
/usr/include/bits/stdio.h:117:10: note: suggested alternative: '__stream'
   return __getdelim (__lineptr, __n, '\n', __stream);
          ^~~~~~~~~~
          __stream
In file included from /opt/gcc/8.2.0/include/c++/8.2.0/x86_64-kewb-linux-gnu/bits/gthr-default.h:35,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/x86_64-kewb-linux-gnu/bits/gthr.h:148,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/ext/atomicity.h:35,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/bits/ios_base.h:39,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/ios:42,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/ostream:38,
                 from /opt/gcc/8.2.0/include/c++/8.2.0/iostream:39,
                 from ./taskflow/core/error.hpp:3,
                 from ./taskflow/core/graph.hpp:3,
                 from ./taskflow/core/task.hpp:3,
                 from ./taskflow/core/observer.hpp:3,
                 from ./taskflow/core/executor.hpp:3,
                 from ./taskflow/taskflow.hpp:3,
                 from examples/simple.cpp:13:
/opt/gcc/8.2.0/include/c++/8.2.0/bits/std_mutex.h: At global scope:
/opt/gcc/8.2.0/include/c++/8.2.0/bits/std_mutex.h:66:31: error: braces around scalar initializer for type 'short int'
     __native_type  _M_mutex = __GTHREAD_MUTEX_INIT;
                               ^~~~~~~~~~~~~~~~~~~~
/opt/gcc/8.2.0/include/c++/8.2.0/mutex:75:31: error: braces around scalar initializer for type 'short int'
     __native_type  _M_mutex = __GTHREAD_RECURSIVE_MUTEX_INIT;
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./taskflow/core/graph.hpp:5,
                 from ./taskflow/core/task.hpp:3,
                 from ./taskflow/core/observer.hpp:3,
                 from ./taskflow/core/executor.hpp:3,
                 from ./taskflow/taskflow.hpp:3,
                 from examples/simple.cpp:13:
./taskflow/core/semaphore.hpp: In constructor 'tf::Semaphore::Semaphore(int)':
./taskflow/core/semaphore.hpp:98:23: error: use of deleted function 'constexpr std::mutex::mutex()'
   _counter(max_workers) {
                       ^
In file included from /opt/gcc/8.2.0/include/c++/8.2.0/mutex:43,
                 from ./taskflow/core/semaphore.hpp:4,
                 from ./taskflow/core/graph.hpp:5,
                 from ./taskflow/core/task.hpp:3,
                 from ./taskflow/core/observer.hpp:3,
                 from ./taskflow/core/executor.hpp:3,
                 from ./taskflow/taskflow.hpp:3,
                 from examples/simple.cpp:13:
/opt/gcc/8.2.0/include/c++/8.2.0/bits/std_mutex.h:94:5: note: 'constexpr std::mutex::mutex()' is implicitly deleted because the default definition would be ill-formed:
     mutex() noexcept = default;
     ^~~~~
/opt/gcc/8.2.0/include/c++/8.2.0/bits/std_mutex.h:94:5: error: use of deleted function 'constexpr std::__mutex_base::__mutex_base()'
/opt/gcc/8.2.0/include/c++/8.2.0/bits/std_mutex.h:68:15: note: 'constexpr std::__mutex_base::__mutex_base() noexcept' is implicitly deleted because its exception-specification does not match the implicit exception-specification 'noexcept (false)'
     constexpr __mutex_base() noexcept = default;
               ^~~~~~~~~~~~

**gccinfo**
 $gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/gcc/8.2.0/libexec/gcc/x86_64-kewb-linux-gnu/8.2.0/lto-wrapper
Target: x86_64-kewb-linux-gnu
Configured with: /disk2/compiler/gcc-builder/gcc-builder/gcc-8.2.0/configure -v --with-pkgversion='KEWB Computing Build' --prefix=/opt/gcc/8.2.0 --program-suffix= --enable-tls --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-languages=c,c++ --enable-lto --enable-bootstrap --disable-nls --disable-multilib --disable-install-libiberty --disable-werror --with-system-zlib
Thread model: posix
gcc version 8.2.0 (KEWB Computing Build)
**Additional context**

**Comment by tsung-wei-huang** [comment]
I suspect it's something caused by the gcc wrapper in your build environment: https://stackoverflow.com/questions/26900783/unable-to-compile-any-c-code

Have you tried other higher gcc version?
