### ISSUE TITLE
High CPU usage when executor is mostly idle

### ISSUE THREAD

**Issue by mfornace** [taskflow/taskflow#255]
I'm using taskflow in part to schedule on-demand jobs within a server. That is, I have a `tf::Executor` sitting around much of the time, and I launch task flows on it when a matching HTTP request comes in. 

As such there is a significant amount of time where 1) no taskflows are running or 2) only a few taskflows are running which occupy very little CPU per task. (Low CPU loads are probably not a common use-case for taskflow, but I've done this because I can manage the low and high CPU parts of my program with the same framework.)

I've noticed that in idle periods, my CPU% is still sitting at 100% (this is on both Mac and Arch Linux by the way)--that is, 1 CPU is fully occupied. I profiled this and got the following hot spot.

```
24.02 s   99.8%	0 s	 	     decltype(std::__1::forward<tf::Executor::_spawn(unsigned long, tf::Domain)::'lambda'(tf::Executor::Worker&)>(fp)(std::__1::forward<std::__1::reference_wrapper<tf::Executor::Worker> >(fp0))) std::__1::__invoke<tf::Executor::_spawn(unsigned long, tf::Domain)::'lambda'(tf::Executor::Worker&), std::__1::reference_wrapper<tf::Executor::Worker> >(tf::Executor::_spawn(unsigned long, tf::Domain)::'lambda'(tf::Executor::Worker&)&&, std::__1::reference_wrapper<tf::Executor::Worker>&&)
24.02 s   99.8%	0 s	 	      tf::Executor::_spawn(unsigned long, tf::Domain)::'lambda'(tf::Executor::Worker&)::operator()(tf::Executor::Worker&) const
23.71 s   98.5%	26.00 ms	 	       tf::Executor::_wait_for_task(tf::Executor::Worker&, tf::Node*&)
23.51 s   97.7%	815.00 ms	 	        tf::Executor::_explore_task(tf::Executor::Worker&, tf::Node*&)
13.60 s   56.5%	354.00 ms	 	         std::__1::this_thread::yield()
6.76 s   28.0%	120.00 ms	 	         unsigned long std::__1::uniform_int_distribution<unsigned long>::operator()<std::__1::mersenne_twister_engine<unsigned int, 32ul, 624ul, 397ul, 31ul, 2567483615u, 11ul, 4294967295u, 7ul, 2636928640u, 15ul, 4022730752u, 18ul, 1812433253u> >(std::__1::mersenne_twister_engine<unsigned int, 32ul, 624ul, 397ul, 31ul, 2567483615u, 11ul, 4294967295u, 7ul, 2636928640u, 15ul, 4022730752u, 18ul, 1812433253u>&)
1.87 s    7.7%	270.00 ms	 	         tf::TaskQueue<tf::Node*>::steal()
358.00 ms    1.4%	58.00 ms	 	         std::__1::__atomic_base<bool, false>::operator bool() const
```

Looking at the taskflow code (which I don't know well obviously), it seems like the hot spot is due to `Executor::_explore_task` within the work stealing implementation. It looks like in a normal context, this will not occupy much CPU because `this_thread::yield()` is invoked--however, in my idle context there is no running thread to switch to, so the processor spins. I made the following change to `_explore_task`:

```c++
    if(num_steals++ > _MAX_STEALS) {
      std::this_thread::yield();
      if(num_yields++ > _MAX_YIELDS) {
        std::this_thread::sleep_for(std::chrono::seconds(1)); // <-- ADDED THIS LINE
        break;
      }
    }
```

And now my idle CPU usage is basically gone for me. Is this a fix that is performant, or reasonable? Is there some other solution you can think of, if you understand the problem better? Obviously I can try decreasing the timeout if it's too high for expected performance, but I'd hope there is another non-timeout based solution I can use.

Thanks for your help!

**Comment by tsung-wei-huang** [comment]
@mfornace Our scheduler only keeps a CPU thread busy as long as there is a thread running tasks. Are you using a worker thread from the executor to run tasks in your loop? If there are no tasks executed by the executor, no workers remain busy. For example,

```
tf::Executor executor;  // no tasks at this moment, CPU usage should be very low.

auto future = executor.async([](){});  // one task => invokes one worker thread, which in turn invoke another worker thread to steal tasks 

future.get();  // task finish

// here "all" worker threads in the executor go sleep
```

Keep in mind, the master thread is not involving in the worker threads. Each executor keeps a separate set of threads as workers to run tasks. The executor does not always keep a thread spinning, but only when there is at least one thread running tasks. This is the key idea of our work stealing.

Does this make sense?

**Comment by mfornace** [comment]
Thanks. Mm, yes, I think that makes sense to me. I've checked that the main thread is not involved, correct.

I think my issue is that I have a task running which is very low CPU (contains networking). This means there is a worker thread present but (practically) sleeping. With this the case, the stealer keeps spinning I guess. Do you have any solution to this (besides moving my networking tasks out of the executor)? The networking code is not mine, so from the outside I only see it as a blocking function which uses low CPU.

**Comment by tsung-wei-huang** [comment]
@mfornace yes, as long as you have a worker present, there is always another worker with it to steal tasks. I think this makes sense to you now in terms of our work-stealing algorithm. For compute-intensive workloads, it ends up executing tasks very efficiently. 

In your case, I suggest the following two solutions:

1. You should not let workers present in your work/event loop. This organization causes one worker to always spin. Worker threads are private to the executor. I suggest having another application thread to do this and let the application thread submit tasks to the executor. You can fully trust the executor in scheduling tasks, including invoking workers to run tasks and putting them to sleep. The executor doesn't waste resources (or very less) if not needed.

2. If you really want a worker from the executor to run your loop, then you can add a sleep as you did in the beginning. And, I suggest using [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) strategies to tune the sleep values, i.e., adapt the seconds to different situations rather than constant 1 second. This is a very common strategy implemented by many event-driven libraries and HTTP servers.

**Comment by mfornace** [comment]
OK, thanks. It sounds like I need to just move the non-cpu bound tasks out of the executor I have, which is a reasonable solution. Thanks for your quick help.

**Comment by tsung-wei-huang** [comment]
Yes, I suggest using executor as an independent *execution engine*. The executor manages resources very smartly so you can totally use it in an object-oriented fashion. Also, submitting taskflows to an executor is thread-safe (i.e., `tf::Executor::run`).

**Comment by tsung-wei-huang** [comment]
@mfornace I think we can close this issue?

**Comment by mfornace** [comment]
Yep, thanks @tsung-wei-huang !
