### ISSUE TITLE
CUDA compilation error in the latest committed version.

### ISSUE THREAD

**Issue by xichuang** [taskflow/taskflow#258]
**Describe the bug**
In the most recently committed code, the CUDA sample codes suffered compilation errors. For example, examples/cuda/saxpy.cu, compilation failed by using the flowing command:

nvcc -std=c++17 saxpy.cu -Ipath/to/include/taskflow -O2 -o saxpy

The error message is too long, I only present part of it in the following:

> /home/suwei/local/taskflow-latest/taskflow/core/observer.hpp:644:51: error: ‘TF_ENABLE_PROFILER’ is not a type
     const std::string _fpath {get_env(TF_ENABLE_PROFILER)};
                                                   ^~~~~~~~~         
/share/home/suwei/local/taskflow-latest/taskflow/core/observer.hpp: In destructor ‘tf::TFProfManager::~TFProfManager()’:
/share/home/suwei/local/taskflow-latest/taskflow/core/observer.hpp:670:19: error: ‘_fpath’ was not declared in this scope
   std::ofstream ofs(_fpath);
                   ^~~~~~
/share/home/suwei/local/taskflow-latest/taskflow/core/observer.hpp:670:19: note: suggested alternative: ‘__tanh’
   std::ofstream ofs(_fpath);

This error did not appear until at least in the version of 20c838b (submitted on 2020.12.02).

**Environment:**
 - gcc version: gcc 8.4.0
 - nvcc version: V11.1.74

**Comment by tsung-wei-huang** [comment]
@xichuang it turns out to be a bug in nvcc v11.1 implementation for default initializer in class. I have moved the definition to an explicit constructor definition. Please check again in the master branch. It should fix now.

**Comment by xichuang** [comment]
Yes, it works now. Thank you.
