### ISSUE TITLE
Make Install got Error during Taskflow 2.7.0 Installation from Source

### ISSUE THREAD

**Issue by ecetiner87** [taskflow/taskflow#259]
**Describe the bug**
I just downloaded Taskflow 2.7.0 on my Centos 7 WSL environment and tried to build it as I did before (in cpp-taskflow-2.4.0)

**To Reproduce**
1. tar xvf taskflow-2.7.0.tar.gz
2. cd taskflow-2.7.0
3. mkdir build
4. cd build
5. cmake ../
6. make install
7. Got following error:
Scanning dependencies of target basics
[ 71%] Building CXX object unittests/CMakeFiles/basics.dir/basics.cpp.o
In file included from /home/basics/taskflow-2.7.0/3rd-party/doctest/doctest.h:2717:0,
                 from /home/basics/taskflow-2.7.0/unittests/basics.cpp:3:
./algorithm:1:1: error: stray ‘\177’ in program
 ELF         >    N@     @                @ 8
 ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [unittests/CMakeFiles/basics.dir/build.make:63: unittests/CMakeFiles/basics.dir/basics.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1440: unittests/CMakeFiles/basics.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Screenshots**
Added as attachment.

**Desktop (please complete the following information):**
 - OS: Centos 7.6.1810 - WSL on Windows 10
![taskflowbuilderror](https://user-images.githubusercontent.com/43776056/102501295-545f5680-408e-11eb-906e-5941413232ff.PNG)

**Additional context**
This is cmake output as well:

[root@TUR-GSD-ErkanC build]# cmake ../
-- CMAKE_ROOT: /usr/local/share/cmake-3.12
-- The CXX compiler identification is GNU 7.3.1
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- Setting build type to 'Release'
-- CMAKE_HOST_SYSTEM: Linux-4.4.0-19041-Microsoft
-- CMAKE_BUILD_TYPE: Release
-- CMAKE_CXX_COMPILER: /opt/rh/devtoolset-7/root/usr/bin/c++
-- CMAKE_CXX_COMPILER_ID: GNU
-- CMAKE_CXX_COMPILER_VERSION: 7.3.1
-- CMAKE_CXX_FLAGS:
-- CMAKE_CUDA_COMPILER: NOTFOUND
-- CMAKE_CUDA_COMPILER_ID:
-- CMAKE_CUDA_COMPILER_VERSION:
-- CMAKE_CUDA_FLAGS:
-- CMAKE_MODULE_PATH:
-- CMAKE_CURRENT_SOURCE_DIR: /home/basics/taskflow-2.7.0
-- CMAKE_CURRENT_BINARY_DIR: /home/basics/taskflow-2.7.0/build
-- CMAKE_EXE_LINKER_FLAGS:
-- CMAKE_INSTALL_PREFIX: /usr/local
-- CMAKE_MODULE_PATH:
-- CMAKE_PREFIX_PATH:
-- PROJECT_NAME: Taskflow
-- TF_BUILD_BENCHMARKS: OFF
-- TF_BUILD_CUDA: ON
-- TF_BUILD_TESTS: ON
-- TF_BUILD_EXAMPLES: ON
-- TF_INC_INSTALL_DIR: /usr/local/include
-- TF_LIB_INSTALL_DIR: /usr/local/lib
-- TF_UTEST_DIR: /home/basics/taskflow-2.7.0/unittests
-- TF_EXAMPLE_DIR: /home/basics/taskflow-2.7.0/examples
-- TF_BENCHMARK_DIR: /home/basics/taskflow-2.7.0/benchmarks
-- TF_3RD_PARTY_DIR: /home/basics/taskflow-2.7.0/3rd-party
CMake Warning at CMakeLists.txt:200 (message):
  TF_BUILD_CUDA set but no CUDA compiler found!

  NOT building CUDA examples/benchmarks/...

-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/basics/taskflow-2.7.0/build

**Comment by tsung-wei-huang** [comment]
I suspect this is caused by some weird encoding error between windows and linux. Would you please try the master branch and see if the problem exists.

**Comment by ecetiner87** [comment]
I had same issue when compiling from master branch:

![image](https://user-images.githubusercontent.com/43776056/103022830-ca1b6480-455d-11eb-85f9-f470bab80846.png)

**Comment by tsung-wei-huang** [comment]
Can you disable the build of test and see if the problem exists? If no, it's a problem of doctest.

```cpp
~$ cmake ../ -DTF_BUILD_TESTS=OFF
```

**Comment by ecetiner87** [comment]
Hi Wei;
With the above workaround; it works and make install completed successfully.

Thank you for advise.

**Comment by ecetiner87** [comment]
Solved by following:

cmake ../ -DTF_BUILD_TESTS=OFF
make install
