### ISSUE TITLE
cmake problem Intel machine

### ISSUE THREAD

**Issue by jtorresr1** [taskflow/taskflow#261]
When i tried to run cmake ../ -DTF_BUILD_BENCHMARKS=ON in the Intel machine, y receive these errors

CMake Error at benchmarks/CMakeLists.txt:26 (cmake_policy):
  Policy "CMP0074" is not known to this version of CMake.

-- Building Intel TBB: /usr/bin/make -j10 tbb_build_prefix=tbb_cmake_build_subdir tbb_build_dir=/home/u56094/Paralelos/taskflow/build/benchmarks/tbb_cmake_build compiler=gcc
CMake Error at benchmarks/CMakeLists.txt:211 (add_executable):
  add_executable cannot create target "parallel_sort" because another target
  with the same name already exists.  The existing target is an executable
  created in source directory "/home/u56094/Paralelos/taskflow/examples".
  See documentation for policy CMP0002 for more details.

CMake Error at benchmarks/CMakeLists.txt:219 (target_link_libraries):
  Attempt to add link library "Taskflow" to target "parallel_sort" which is
  not built in this directory.

CMake Error at benchmarks/CMakeLists.txt:219 (target_link_libraries):
  Attempt to add link library "TBB::tbb" to target "parallel_sort" which is
  not built in this directory.

CMake Error at benchmarks/CMakeLists.txt:219 (target_link_libraries):
  Attempt to add link library "TBB::tbbmalloc" to target "parallel_sort"
  which is not built in this directory.

CMake Error at benchmarks/CMakeLists.txt:219 (target_link_libraries):
  Attempt to add link library "TBB::tbbmalloc_proxy" to target
  "parallel_sort" which is not built in this directory.

CMake Error at benchmarks/CMakeLists.txt:219 (target_link_libraries):
  Attempt to add link library "/usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so" to
  target "parallel_sort" which is not built in this directory.

CMake Error at benchmarks/CMakeLists.txt:219 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/libpthread.so" to
  target "parallel_sort" which is not built in this directory.

CMake Error at benchmarks/CMakeLists.txt:219 (target_link_libraries):
  Attempt to add link library "tf::default_settings" to target
  "parallel_sort" which is not built in this directory.

-- Configuring incomplete, errors occurred!

**Comment by davidwojnar** [comment]
Have you ensured, that your cmake version is 3.12 or  above?

**Comment by tsung-wei-huang** [comment]
@davidwojnar yes, this error requires CMake 3.12 or above. I will include this restriction in the next major release.

**Comment by tsung-wei-huang** [comment]
This has been updated with the v3 release and the master branch.
