### ISSUE TITLE
Memory is not being released.

### ISSUE THREAD

**Issue by Levi-Armstrong** [taskflow/taskflow#264]
I have been noticing that memory is not being release even though the taskflow goes out of scope. Do anyone know why for the case below why the memory is not being released?

``` c++
struct TestStruct
{
  using Ptr = std::shared_ptr<TestStruct>;
  using ConstPtr = std::shared_ptr<const TestStruct>;

  std::unordered_map<std::string, double> joints;
};

void runTest()
{
  std::vector<TestStruct::Ptr> t;
  t.reserve(10000000);
  for (std::size_t j = 0; j < 10000000; j++)
  {
    auto p = std::make_shared<TestStruct>();
    p->joints["joint_1"] = 0;
    p->joints["joint_2"] = 0;
    p->joints["joint_3"] = 0;
    p->joints["joint_4"] = 0;
    p->joints["joint_5"] = 0;
    p->joints["joint_6"] = 0;
    t.push_back(p);
  }
}

int main(int /*argc*/, char** /*argv*/)
{
  tf::Executor executor;

  {
    tf::Taskflow taskflow;

    taskflow.emplace([=]() { runTest(); });

    std::future<void> f = executor.run(taskflow);
    f.wait();
  }

  std::cout << "Hit enter key to continue!" << std::endl;
  std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
}
```

Now if I replace the `runTest` with the function below it does what I expect the memory ramps up then drops back to where it started.

``` c++
inline std::mt19937 mersenne{ static_cast<std::mt19937::result_type>(std::time(nullptr)) };
void runTest()
{
  std::vector<double> t;
  t.reserve(1000000000);
  for (std::size_t j = 0; j < 1000000000; j++)
  {
    std::uniform_real_distribution<double> sample{ 0, 10 };
    t.push_back(sample(mersenne));
  }
}
```

**Comment by tsung-wei-huang** [comment]
I don't see any memory leak report in both of you cases by running valgrind. Case 1 is definitely going to take much more memory than Case 2 because of the shared pointer, but those memory areas are correctly freed when taskflow leaves the scope. Have you used valgrind to see any memory leak?

**Comment by Levi-Armstrong** [comment]
I have not. I ran `htop` and did not see the memory for the thread going down as I did for the second example, but maybe this is not a good way to measure. I just assumed that if the second case dropped back down that the other should also.

**Comment by tsung-wei-huang** [comment]
The second case is definitely going to drop down very quickly than the first case. Please keep in mind libc may implement memory pool to keep dynamic memory in place for the next use, and the memory may not drop down even though after a releasing scope. We typically use valgrind to see if memory leak exists. I have checked both cases, and they don't have any memory leak.

BTW, taskflow internally also manages tasks/nodes in a shared object pool, in order to reduce the task creation time. So, when you have created many tasks, the memory may not drop, but no memory leak is possible to my best knowledge.

**Comment by Levi-Armstrong** [comment]
Ah, so does this prevent other processes from using the memory? Currently we are using this library for motion planning and some cases we have motion planning request that consume 30-60 GB.

**Comment by tsung-wei-huang** [comment]
The maximum memory depends on the maximum number of tasks you request. However, I believe modern OS already had something efficient to share memory between processes even though some of them take long ownership.

**Comment by Levi-Armstrong** [comment]
If it turns out that this starving other processes do you have any recommendation on how release the memory faster? I did test that if the executor goes out of scope the then memory is freed immediately, but not sure if it is wise to create multiple executors. Also I assume that the work stealing only occurs within an executor and not between executors?

**Comment by tsung-wei-huang** [comment]
Yes, work stealing occurs only within an executor. I don't think this is a problem of taskflow but a system runtime. When the taskflow goes out of the scope, everything will be freed, and in your case there is only a single task - not a big deal. Executor does take some memory but I believe it's only a few MBs. How much starving memory you have observed?

**Comment by tsung-wei-huang** [comment]
Any update? Or we can close it :)

**Comment by Levi-Armstrong** [comment]
Sorry, It can be closed. I have not had a chance to create the test case yet, but I will reopen if I find anything.

**Comment by tsung-wei-huang** [comment]
Thanks!

**Comment by Levi-Armstrong** [comment]
@tsung-wei-huang I have confirmed that things will eventual crash because the memory is not being release. I have done further research and I believe [this](https://stackoverflow.com/questions/63454529/windows-vs-linux-c-thread-pool-memory-usage) explains what is happening. Do you have any experience with the linux settings? I will try looking into the possible settings to see if this can be solved.

**Comment by Levi-Armstrong** [comment]
The [item](https://www.gnu.org/software/libc/manual/html_node/Memory-Allocation-Tunables.html) below was the issue. After setting the value below provides all of the memory back to the system. I will need to due further testing to find out what the right settings.

``` bash
export GLIBC_TUNABLES=glibc.malloc.mmap_threshold=1000000
```

Documentation:

```

Tunable: glibc.malloc.mmap_threshold

    This tunable supersedes the MALLOC_MMAP_THRESHOLD_ environment variable and is identical in features.

    When this tunable is set, all chunks larger than this value in bytes are allocated outside the normal heap, using the mmap system call. This way it is guaranteed that the memory for these chunks can be returned to the system on free. Note that requests smaller than this threshold might still be allocated via mmap.

    If this tunable is not set, the default value is set to ‘131072’ bytes and the threshold is adjusted dynamically to suit the allocation patterns of the program. If the tunable is set, the dynamic adjustment is disabled and the value is set as static. 
```

**Comment by tsung-wei-huang** [comment]
Hi @Levi-Armstrong , this is an excellent finding - especially for long-running jobs and stream applications. I think changing the glib c memory pool/map is one of the right solutions. Please keep me posted, and I probably could create a post about this in the FAQ page of the documentation.

**Comment by Levi-Armstrong** [comment]
So after further test also just setting arena_max to 1 seemed to have the same affect using tunables. 

Though after further reading several forums recommend leveraging either tcmalloc or jemalloc. This I believe to be the best option because all I had to do is link against either of these libraries and the issue went away. Also the memory usage was much more stable.
