### ISSUE TITLE
Provide access to cancellation flag in callable

### ISSUE THREAD

**Issue by robinchrist** [taskflow/taskflow#265]
I haven't followed taskflow for quite a while (shame on me), but to my great joy I've just read that taskflow got support for cancelling tasks. Nice!

What could now make it even better is if there was a way to access a flag that indicates whether the Taskflow / Subflow was cancelled.

Why? Imagine you have long running functions that you don't want to break up into smaller pieces for some reason. You could now poll the cancellation flag e.g. every outer loop iteration in order to cancel as soon as possible. Basically manual coroutines.
Something like an `std::atomic<bool>` should be very efficient to poll.

The only issue I see is how that flag would be passed, as it would require a larger amount of different function signatures if you want to keep them short.

Possibility 1: Three function signatures
```
<return type> fun(tf::Subflow&)
<return type> fun(const std::atomic<bool>&)
<return type> fun(tf::Subflow&, const std::atomic<bool>&)
```

Possibility 2: Only two function signatures
```
<return type> fun(tf::Subflow&)
<return type> fun(tf::Subflow&, const std::atomic<bool>&)
```

Possibility 3: Introduction of a new packaged type that contains all "options". That would allow adding more options to be passed to the function in the future without having to add new signatures or break any code.
```
struct TaskflowExecutionParams {
    std::reference_wrapper<tf::Subflow> subflow;
    std::reference_wrapper<const std::atomic<bool>> cancellationFlag;
};

<return type> fun(const TaskflowExecutionParams&);
```

What do you think? I could perhaps find some spare time over the holidays and prepare a PR if you like the idea.

**Comment by tsung-wei-huang** [comment]
@robinchrist thanks for the idea. Would you provide a more detailed code about how to use this callback? Right now, when you submit a taskflow, you can specify a callback which will be called when (1) the taskflow finishes or (2) the taskflow got cancelled.

You may check: https://github.com/taskflow/taskflow/blob/master/taskflow/core/executor.hpp#L1044

Is this similar to what you mean?

**Comment by robinchrist** [comment]
Hm, not at all actually.

I'm speaking about something like

```
tf::Executor executor;
tf::Taskflow taskflow;

for(int i=0; i<1000; i++) {
  taskflow.emplace([](const TaskflowExecutionParams& params){ 
    for(size_t index = 0; index < 1234567; ++index) {
        //Don't check every iteration
        if(index % 32 == 0 && params.cancellationFlag.get().load()) {
            return;
         }
         ...do Stuff
    }
  });
}

// submit the taskflow
tf::Future fu = executor.run(taskflow);

// request to cancel the above submitted execution
fu.cancel();

// wait until the cancellation completes
fu.get();
```

**Comment by tsung-wei-huang** [comment]
Currently we do not consider this interface. Thanks.
