### ISSUE TITLE
Question about conditional tasking

### ISSUE THREAD

**Issue by leonsal** [taskflow/taskflow#267]
Hi,

```
SOURCE --->  T1 --->  SINK
             T2 
             T3   
```

I would like to switch in real time, when the graph is running,
the task between SOURCE and SINK, from T1 to T3.
I tried to use conditional tasking to do this, but didn't succeed.
```
source.precede(cond)
cond.precede(t1, t2, t3)
t1.precede(sink)
t2.precede(sink)
t3.precede(sink)
```
When selecting T1 (cond returns 0), for example,
 Instead of executing periodically:
   SOURCE T1 SINK
It executed:
   SOURCE T1 SOURCE T1 SOURCE T1 SINK

What I am doing wrong ?

Regards.

**Comment by tsung-wei-huang** [comment]
In you case, `sink` is dependent on three static tasks. However, the condition task will run only one of them and thus the sink task will never be executed correctly. Think of this as a normal sequential control flow, and you will realize it makes sense. To get the desired behavior, you need to make `t1`, `t2`, and `t3` all condition tasks (indeed, they are like case condition in a normal switch statement):

```cpp
  tf::Executor executor;
  tf::Taskflow taskflow;

  auto [source, cond, t1, t2, t3, sink] = taskflow.emplace(
    [](){ std::cout << "source\n"; },
    [](){ return 0; },
    [](){ std::cout << "t1\n"; return 0; },
    [](){ std::cout << "t2\n"; return 0; },
    [](){ std::cout << "t3\n"; return 0; },
    [](){ std::cout << "sink\n"; }
  );  

  source.precede(cond);
  cond.precede(t1, t2, t3);
  t1.precede(sink);
  t2.precede(sink);
  t3.precede(sink);
```

**Comment by leonsal** [comment]
Hi,

It worked OK now. Thanks !
