### ISSUE TITLE
Question : can TaskFlow be used in the cloud ?

### ISSUE THREAD

**Issue by nmoreaud** [taskflow/taskflow#269]
I wonder if a library like TaskFlow can be used in the cloud with multiple machines?
For example, is it compatible with Kubernetes autoscaling?
Thanks for your good work.

**Comment by tsung-wei-huang** [comment]
Hi @nmoreaud , taskflow is designed for single heterogeneous node. The programming model it self focuses on a single vertical scalability. It depends on how you want to use it with Kubernetes or other LXC container. Yes, you can use it with container and you can create another layer on top of taskflow to make it go distributed (I believe this is an interesting research project).
