### ISSUE TITLE
Expose the node in TaskView Class?

### ISSUE THREAD

**Issue by Levi-Armstrong** [taskflow/taskflow#274]
We are working on creating an observer to trace the path taken through the graph. We plan to leverage the task hash value to accomplish this. Would the authors be willing to expose the node associated with the TaskView allowing you to call hash_value method of the task? Another option would be to add a method that returns this information from the task in the TaskView class.

**Comment by tsung-wei-huang** [comment]
I think it's ok. I believe you mean the following:

```cpp
// Function: hash_value
inline size_t TaskView::hash_value() const {
  return std::hash<Node*>{}(&_node);
}
```

Right? the hash_value is simply calling std::hash on the underlying node pointer. You may consider adding it and submit a pull request. I am very interested in your new observer.

**Comment by Levi-Armstrong** [comment]
Yep. I just created the [PR](https://github.com/taskflow/taskflow/pull/276)

**Comment by tsung-wei-huang** [comment]
Merged. I think this can be closed?

**Comment by Levi-Armstrong** [comment]
@tsung-wei-huang Yep, thank you for the support.
