### ISSUE TITLE
taskflow Visualize 

### ISSUE THREAD

**Issue by Mr-jiayunfei** [taskflow/taskflow#277]
```
# run the program with the environment variable TF_ENABLE_PROFILER enabled
~$ TF_ENABLE_PROFILER=simple.json ./simple
```
Do I need to set this environment variable TF_ENABLE_PROFILER？How I can use tfprof?
I did not know about the tfprof, is there a wiki on how to use it?
Is there any detailed documentation on task flow visualization？
Ifind this file in ~\taskflow\tfprof\server\tfprof.py ,How can I use tfprof.py?
Please help me,Thank you!

**Comment by tsung-wei-huang** [comment]
@Mr-jiayunfei profiling taskflow program is extremely easy. Did you read this [tutorial page](https://taskflow.github.io/taskflow/Profiler.html)? There are two ways, one using .json and another one using .tfp (preferred)

**Comment by Mr-jiayunfei** [comment]
OK，thank you very much!
