### ISSUE TITLE
Can taskflow 3.0 please be made available on the conan registry

### ISSUE THREAD

**Issue by RiverShah** [taskflow/taskflow#282]
conan registry still on 2.4. Really appreciate if 3.0 can be made available on the conan public registry as it simplifies CI/ CD pipelines. Thanks!

**Comment by tsung-wei-huang** [comment]
@RiverShah I will appreciate if you can tell me how to do so.

**Comment by planetmarshall** [comment]
Conan Center Index currently has version 3.0.0 so this issue can probably be closed.
```
conan search taskflow -r conan-center
Existing package recipes:

taskflow/2.2.0
taskflow/2.4.0
taskflow/2.5.0
taskflow/2.6.0
taskflow/2.7.0
taskflow/3.0.0
```

**Comment by tsung-wei-huang** [comment]
Yes, thanks!
