### ISSUE TITLE
What is the definition of bin in object pool?

### ISSUE THREAD

**Issue by xiangpdu** [taskflow/taskflow#286]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tsung-wei-huang** [comment]
A bin is a localized list for recycling objects.

**Comment by xiangpdu** [comment]
Can treat a bin as a blocklist?

**Comment by tsung-wei-huang** [comment]
Yes, it is a blocklist. The relationship between block and bin is each bin is a blocklist of objects to recycle/allocate.

**Comment by xiangpdu** [comment]
If w is the number of a bin, Why w=(m+f+1)/f

**Comment by tsung-wei-huang** [comment]
That is a heuristic - nothing special :)

**Comment by tsung-wei-huang** [comment]
@xiangpdu any questions? Or we can close this issue.

**Comment by xiangpdu** [comment]
One more question, what is the advantage of  bin, why we need to use it?

**Comment by xiangpdu** [comment]
Close it ‘cause it's not an issue.
