### ISSUE TITLE
Unreachable code warning with MSVC

### ISSUE THREAD

**Issue by egorodet** [taskflow/taskflow#287]
**Describe the bug**
MSVC compiler generates warning about unreachable code in Taskflow v3.0.0 or latest master branch.

**To Reproduce**
Build taskflow v3.0.0 or latest master branch with Visual Studio 2019 16.8.4 at maximum warning level => Get compiler warning `taskflow\utility\serializer.hpp(454) : warning C4702: unreachable code`.

**Comment by tsung-wei-huang** [comment]
@egorodet do you still see this error in the master branch?

**Comment by egorodet** [comment]
> @egorodet do you still see this error in the master branch?

I silenced the warning via cmake compiler options for Taskflow target, so I don't see it anymore even if it is still there.

**Comment by tsung-wei-huang** [comment]
I think it got fixed - nothing was wrong and I suspected the problem was due to the MSVC compiler in misinterpreting constexpr in C++17.

**Comment by egorodet** [comment]
I checked it with the latest master branch of Taskflow and the warning is still there. Here's a proof screenshot of the build log with full compiler command-line:
![Taskflow-UnreachableCodeWarning](https://user-images.githubusercontent.com/21955635/109705105-6e4a0900-7ba8-11eb-9741-68b908df9892.jpg)

**Comment by tsung-wei-huang** [comment]
I believe that is an OK warning in MSVC. If the serializer doesn't have the save method provded, that code will not be compiled.

**Comment by egorodet** [comment]
I guess that the problem reported by this warning is about the code generated for the last `return 0` which becomes unreachable when copiler generates code for any of `if constexpr (...) { ... return X; }` because it does not fall under any constexpr branch. The warning can be easily fixed by moving `return 0;` under the last `else`  branch of `if constexpr` right under `static_assert(...)` like this (checked, warning is fixed):

```cpp
   ...
   else if constexpr(std::is_same_v<void, std::void_t<decltype(std::declval<T>().save(*this))>>){
    return t.save(*this);
  }
  else {
    static_assert(dependent_false_v<U>, "custom 'save' method not found");
    return 0;
  }
```

And since there's a static assert which will result in compiler error, there is no much sense in this `return 0;`, so it can be removed completely, but this needs to be checked with other compilers, besides MSVC.

**Comment by tsung-wei-huang** [comment]
Yes, I am aware of this and it will cause NVCC to report a warning again. But I think this caused by insufficient support for `constexpr if` at this stage.

**Comment by tsung-wei-huang** [comment]
Hi @egorodet , I have replaced `constexpr` with `enable_if`. The master branch should not have the issue anymore. Please let me know if you still encounter the warning. Thanks.

**Comment by egorodet** [comment]
Hi @tsung-wei-huang, I confirm - the warning is now fixed. Thank you!
