### ISSUE TITLE
Question: can I configure the number of threads ?

### ISSUE THREAD

**Issue by boxerab** [taskflow/taskflow#290]
My current mult-threading solution is a thread pool where I can set the size of the pool. This is very useful
for measuring how my algorithms scale with number of threads. Is it possible to do the same with taskflow ?

Thanks!

**Comment by tsung-wei-huang** [comment]
Yes, you can configure the number of threads on executor. You may find details [here](https://taskflow.github.io/taskflow/ExecuteTaskflow.html).

```cpp
tf::Executor executor(5);  // use 5 worker threads in the executor
```

**Comment by boxerab** [comment]
Great, thanks!
