### ISSUE TITLE
Non-copyable lambda cannot be handled in tf::Executor::async

### ISSUE THREAD

**Issue by m-dot-jung** [taskflow/taskflow#294]
**Describe the bug**
I want to hand over ownership of a unique_ptr to a taskflow, which is executed asynchronously. This does not compile due to some copy-constructor calls. I am not exactly sure, which line of the async leads to the error...

**To Reproduce**
The following piece of code does not compile with MSVC
`auto uniqueInt = std::make_unique<int>(3);`
`tf::Executor exec;`
`exec.async([ptr = std::move(uniqueInt)]{});`
  
**Additional context**
TF_VERSION 3.1.0

**Comment by tsung-wei-huang** [comment]
By default, Taskflow uses `std::function` to represent a task. The target you pass to create a task must be copyable due to the type erasure. In your case, you can try two things:

```
auto sharedInt = std::make_shared<int>(3)
```

Or, you create a move-on-copy wrapper:

```
// Struct: MoveOnCopyWrapper
template <typename T>
struct MoC {

  MoC(T&& rhs) : object(std::move(rhs)) {}
  MoC(const MoC& other) : object(std::move(other.object)) {}

  T& get() { return object; }
  
  mutable T object; 
};

template <typename T>
auto make_moc(T&& m) {
  return MoC<T>(std::forward<T>(m));
}

taskflow.emplace(
  [MoCData = make_moc(std::make_unique<int>(3))] () {
     std::cout << *(MoCData.object);  // 3
  }
);
```

**Comment by m-dot-jung** [comment]
Yes, I didn't want to go for the shared_ptr solution (Unwrapping the unique_ptr and then rewrapping does not feel very elegant). However, the MoC was a new concept for me and works well in this case.

Thanks for the help!

**Comment by tsung-wei-huang** [comment]
@m-dot-jung Yes, the MoC is very frequently used when using `std::function` as a callable task to implement a threadpool or multithreaded programs that require another interface to communicate user's tasks and library's threading. I would suggest using MoC in you case and it does not have any overhead.
