### ISSUE TITLE
Relative cmake install prefix is more portable

### ISSUE THREAD

**Issue by pancpp** [taskflow/taskflow#296]
This is not a bug fix, but rather a feature request.

Current install prefix is in absolute path, shown as follow:
```cmake
set(TF_INC_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/include")
set(TF_LIB_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/lib")
```
which will generate an absolute path in `TaskflowTargets.cmake` as follow:
```cmake
# The installation prefix configured by this project.
set(_IMPORT_PREFIX "/some/install/path")
```
If `/some/install/path` is not the conventional `/user` or `/usr/local`, this installation will not be portable.

To obtain the portability, the installation prefix is preferred to be relative as follow:
```cmake
set(TF_INC_INSTALL_DIR "include")
set(TF_LIB_INSTALL_DIR "lib")
```
which will generate a portable relative path in `TaskflowTargets.cmake` as follow:
```cmake
# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()
```

In some cases, when I generate a sysroot for portability, this feature will be much useful.

**Comment by tsung-wei-huang** [comment]
@pancpp thanks for your great question. Would you be interested in submitting a pull?

**Comment by pancpp** [comment]
@tsung-wei-huang Yes, the PR #297 has been submitted.

**Comment by pancpp** [comment]
Corresponding PR #297 has been merged. Close the issue.
