### ISSUE TITLE
Calling precede or succeed sometimes causes the task to not run

### ISSUE THREAD

**Issue by Ravbug** [taskflow/taskflow#299]
**Describe the bug**
I think this is probably not a bug in Taskflow but rather me misusing the API. I have some code which allows user code to specify dependencies:
```cpp
struct SystemEntry{
	std::function<void(float,Ref<Entity>)> Tick;
	std::function<const System::list_type&()> QueryTypes;
	std::function<const System::list_type&()> MustRunBefore;
	std::function<const System::list_type&()> MustRunAfter;

	template<typename T>
	SystemEntry(Ref<T> system) :
		Tick([=](float f, Ref<Entity> e){
			system->Tick(f,e);
		}),
		QueryTypes([=]() -> const System::list_type& {
			return system->QueryTypes();
		}),
		MustRunBefore([=]() -> const System::list_type&{
			return MustRunBefore_impl<T>(system);
		}),
		MustRunAfter([=]() -> const System::list_type&{
			return MustRunAfter_impl(system);
		})
		{}
};


struct systaskpair{
	tf::Task task;
	SystemEntry* system;
};
std::unordered_map<ctti_t, systaskpair> graphs;

//...

//added like this:
graphs[ID] = {masterTasks.for_each(l1.begin(), l1.end(), func),&system };

//...

//figure out dependencies
for(auto& graph : graphs){
	tf::Task& task = graph.second.task;
	
	//call precede
	{
		auto& runbefore = graph.second.system->MustRunBefore();
		for(const auto id : runbefore){
			if (graphs.find(id) != graphs.end()){
				task.precede(graphs[id].task); //if this line runs, the task stored at graphs[id] does not run at all
			}
		}
	}
	//call succeed
	{
		auto& runafter = graph.second.system->MustRunAfter();
		for(const auto id : runafter){
			if (graphs.find(id) != graphs.end()){
				task.succeed(graphs[id].task);  //if this line runs, the task stored at graphs[id] does not run at all
			}
		}
	}
}
```
However, when calling `precede` or `succeed`, the task that is being preceded or succeed doesn't run at all. In other cases where I call precede using tasks that are not stored in a data structure, it works correctly.
```cpp
//this works correctly
 auto swap = masterTasks.emplace([this]{
        SwapFrameData();
    });
    auto setup = masterTasks.emplace([this]{
		current->Clear();
    });
    setup.precede(camproc,copydirs,copyambs,copyspots,copypoints);
    sort.precede(swap);
```
If I comment out `task.precede(graphs[id].task);` and `task.succeed(graphs[id].task);`, the tasks run, but not in the correct order, so this can't be my fix. 

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Version: 2.7

**Comment by tsung-wei-huang** [comment]
Have you tried dumping the graph and visualize the dependencies whether they are expected?

```
taskflow.dump(std::cout);
```

The only possibility for a preceded task not to run is there are other dependencies not resolved.

**Comment by Ravbug** [comment]
`System: 35` is the problematic task

With the line commented out:
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/22283943/110280780-41bf3400-7f90-11eb-9d68-35c94d0a9dec.png">
With the line enabled:
<img width="801" alt="image" src="https://user-images.githubusercontent.com/22283943/110280810-4edc2300-7f90-11eb-9478-ee901e27f671.png">
I noticed that with the line enabled, `System: 35` has a dependency on itself, would this cause it to be skipped?
<img width="140" alt="image" src="https://user-images.githubusercontent.com/22283943/110280890-77641d00-7f90-11eb-8033-199fd164adb7.png">

**Comment by tsung-wei-huang** [comment]
You *cannot* have a loop or cycle in static tasks. You need to remove the loop in this case. Unless you need control flow, you can use [condition task](https://taskflow.github.io/taskflow/ConditionalTasking.html) to create loops or cycles.

**Comment by Ravbug** [comment]
Fixed the bug in my code, thanks so much for your help

**Comment by tsung-wei-huang** [comment]
Thank you for using Taskflow, please let me know if you encounter any further problem @Ravbug
