### ISSUE TITLE
LLVM + IPO/LTO + Windows Doesn't link binaries that use taskflow binaries

### ISSUE THREAD

**Issue by Milerius** [taskflow/taskflow#300]
**Describe the bug**

LLVM ERROR: Associative COMDAT symbol '?_per_thread@Executor@tf@@0UPerThread@12@A' does not exist.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.

**To Reproduce**
1. Install LLVM 11
2. Enable interprocedural optimization / lto
3. Create a project that use taskflow + IPO on windows + LLVM

**Comment by doterax** [comment]
Have a working solution with all optimisation enabled.

I moved `PerThread per_thread` from class `Executor` to outer scope.

https://github.com/doterax/Leanify/commit/e0a51cc1da8a98472ee7a71c165ed7cfbd176e79

**Comment by Milerius** [comment]
> Have a working solution with all optimisation enabled.
> 
> I moved `PerThread per_thread` from class `Executor` to outer scope.
> 
> [doterax/Leanify@e0a51cc](https://github.com/doterax/Leanify/commit/e0a51cc1da8a98472ee7a71c165ed7cfbd176e79)

Any chance to propose this pr to the official repo somehow ?

**Comment by doterax** [comment]
I will try organising PR tomorrow.

**Comment by tsung-wei-huang** [comment]
@doterax moving the per_thread to an inline variable will cause all application threads to initialize the PerThread data structure. Can the following lazy initialization fix you problem?

// outside executor scope
inline PerThread& per_thread() {
  thread_local PerThread per_thread;
  return per_thread;
}

I am skeptical this is a bug introduced by the compiler.

**Comment by tsung-wei-huang** [comment]
I believe this is a similar issue to #312 which has been solved.
