### ISSUE TITLE
Question: can user data be passed to individual threads in executor ?

### ISSUE THREAD

**Issue by boxerab** [taskflow/taskflow#301]
I am getting ready to enable task flow in my codec project. 

Currently, I use a thread pool for concurrency. Let's say I have 1000 blocks to decode and 8 threads in the pool.
Each block uses an intermediate buffer that can be re-used for the next block , so I pass a buffer
object to each of the 8 threads before executing the pool on the 1000 blocks. This avoids having 1000 intermediate
buffers allocated, or having a shared buffer pool with locking.

Is it possible to do this with task flow, without using a shared buffer pool with locking ? As each block is decoded
independently, I don't want to add a lock dependency between the block decodes.

Thanks!

**Comment by tsung-wei-huang** [comment]
I believe it is doable - I have been doing something very similar before. Each worker thread in an executor has a unique id in the range, `[0, N)`, and you can use the id to map a worker to your data structure. 

```
int buffer[8][1000000]

tf::Executor executor(8);   // 8 worker threads
tf::Taskflow taskflow;
taskflow.emplace(
  [&] () {  
    int id = executor.this_worker();
    // access my buffer
    buffer[id][0] = 1;
    ...
  }
);
```

**Comment by boxerab** [comment]
Thanks, that is perfect, in fact, I realised that's what I've actually been doing, just relying on the unique id.
