### ISSUE TITLE
Update iterator ranges 

### ISSUE THREAD

**Issue by Ravbug** [taskflow/taskflow#302]
If I have the following code:
```cpp
auto& geometry = GetAllComponentsOfType<StaticMesh>();
			
auto sort = masterTasks.for_each(geometry.begin(), geometry.end(), [this](Ref<Component> e){ ... }
```
How can I update the begin and end iterators for a subsequent run of the Taskflow without re-generating the Task? For example, if the number of elements changes in `geometry` between runs, I want that to be reflected when the graph is executed again. 
Also is this the correct place to ask questions?

**Comment by tsung-wei-huang** [comment]
@Ravbug I believe you are referring to [stateful capture](https://taskflow.github.io/taskflow/ParallelIterations.html#A1IteratorBasedParallelFor) which can be done using `std::ref`

```cpp
std::vector<int> vec;
std::vector<int>::iterator first, last;;

tf::Task init = taskflow.emplace([&](){
  vec.resize(1000);
  first = vec.begin();
  last  = vec.end();
});

tf::Task pf = taskflow.for_each(std::ref(first), std::ref(last), [&](int i) {
  std::cout << "parallel iteration on item " << i << '\n';
});

// wrong! must use std::ref, or first and last are captured by copy
// tf::Task pf = taskflow.for_each(first, last, [&](int i) {
//   std::cout << "parallel iteration on item " << i << '\n';
// });

init.precede(pf);
```

**Comment by Ravbug** [comment]
This works, thank you!
