### ISSUE TITLE
can task be run on a particular thread?

### ISSUE THREAD

**Issue by wppr** [taskflow/taskflow#306]
I'm working on a real-time gaming program and  In my case ,I want to dynamic create  tasks in every frame. 
But I have some tasks ,which must work on **main thread**,and I have some other tasks thah can work on any thread and they may have some dependency.

Can I do this with taskflow?

**Comment by tsung-wei-huang** [comment]
Unfortunately, right now we don't make this assumption to affine tasks to a particular thread.
