### ISSUE TITLE
Semaphore performance optimization by A Lightweight Semaphore with Partial Spinning

### ISSUE THREAD

**Issue by chi2liu** [taskflow/taskflow#307]
**The realization of semaphore is currently implemented with mutex, maybe can consider A Lightweight Semaphore with Partial Spinning which performance is better**
https://preshing.com/20150316/semaphores-are-surprisingly-versatile/

![image](https://user-images.githubusercontent.com/19861628/113263931-fc7af180-9304-11eb-8f72-bec9ddabeee5.png)

https://github.com/preshing/cpp11-on-multicore/blob/master/common/sema.h

I am willing to try to import a  A Lightweight Semaphore with Partial Spinning to see if there is any improvement in performance

**Comment by tsung-wei-huang** [comment]
Hi @chi2liu I will be happy if you can help contribute to it. There are two places where mutex happens, at `tf::Taskflow`, `tf::FlowBuilder::reduce_*` and at `tf::Semaphore`.  The former two are most dominant. Please let me know your thoughts.

**Comment by chi2liu** [comment]
> Hi @chi2liu I will be happy if you can help contribute to it. There are two places where mutex happens, at `tf::Taskflow`, `tf::FlowBuilder::reduce_*` and at `tf::Semaphore`. The former two are most dominant. Please let me know your thoughts.

Yeah, I will try to reimplement `tf::Semaphore` first，replacing it with a Partial Spinning Semaphore without mutex.
Try to find whether can improve performance.

**Comment by tsung-wei-huang** [comment]
close first - feel free to reopen or submit a pull request if you are still interested in the help.
