### ISSUE TITLE
Does it possible to use taskflow in c++11 standard? 

### ISSUE THREAD

**Issue by xinlnix** [taskflow/taskflow#308]
Now a lot of old server are using c++11 standard to compile c++ program. I am really desire the features in it.

**Comment by tsung-wei-huang** [comment]
@xinlnix unfortunately you will need C++17 now.

**Comment by xinlnix** [comment]
> @xinlnix unfortunately you will need C++17 now.

It's unfortunately, but also thanks to your excellent work.

**Comment by xinlnix** [comment]
> @xinlnix unfortunately you will need C++17 now.

Does the taskflow has implement "parallel pipeline" like function?  So multi task can run parallel and one's output is another's input. Just like pipeline in hardware.

**Comment by xinlnix** [comment]
@tsung-wei-huang Just like parallel_pipeline in TBB.

**Comment by tsung-wei-huang** [comment]
We don't have pipeline now but it's definitely under the TO-DO item.
