### ISSUE TITLE
Add dependencies between tasks during execution

### ISSUE THREAD

**Issue by dmangira** [taskflow/taskflow#311]
I am really interested in using Taskflow and I was wondering how Ι can add dependencies between tasks during execution.

I have written the following code as an example of what I want. It creates a taskflow of 7 tasks that runs for 2 iterations. In the first iteration task E runs after B. When first iteration ends, Task F adds an extra dependency from task D to E, so that in the remaining iterations task E runs after both B and D. 

```
#include <iostream>
#include <taskflow/taskflow.hpp>

int main() {
  int iter = 1;
  
  tf::Executor executor(2);
  tf::Taskflow taskflow("simple-example");
  
  auto A = taskflow.emplace([] () { std::cout << "TaskA\n"; }).name("A");
  auto B = taskflow.emplace([&iter] () { 
    std::cout << "--" << iter << "--\n";
    std::cout << "TaskB\n"; 
  }).name("B");
  auto C = taskflow.emplace([] () { std::cout << "TaskC\n"; }).name("C");
  auto D = taskflow.emplace([] () { std::cout << "TaskD\n"; }).name("D");
  auto E = taskflow.emplace([] () { std::cout << "TaskE\n"; }).name("E");
  auto F = taskflow.emplace([&iter, &D, &E] () { 
    std::cout << "TaskF\n"; 
    if (iter == 1) {
      D.precede(E);
    }
    if (iter == 2) {
      return 1;
    }
    iter++;
    return 0;
  }).name("F");
  auto G = taskflow.emplace([] () { std::cout << "TaskG\n"; }).name("G");
  
  A.precede(B);
  B.precede(C, E);
  C.precede(D);
  D.precede(F);
  E.precede(F);
  F.precede(B, G);
  
  std::cout << "Dump before run\n";
  taskflow.dump(std::cout);
  
  executor.run(taskflow).wait();
  
  std::cout << "Dump after run\n";
  taskflow.dump(std::cout);
  
  return 0;
}

```

This is the output I get:
```
TaskA
--1--
TaskB
TaskE
TaskC
TaskD
TaskF
--2--
TaskB
TaskE // Here task E should wait for task D
TaskC
TaskD
TaskF
TaskG
```
And this is the visualization of the graph **before** and **after** the run.
![taskflow-dumps](https://user-images.githubusercontent.com/35765493/115068086-7365dc00-9efa-11eb-880c-47ea295ab3d6.png)

From the dumps I understand that the extra dependency is created but from the execution sequence of the tasks it looks like there isn't any change (task E does **not** wait for task D). 
Is there any way to apply similar changes in the dependencies during execution so that the tasks respect them?

Thanks,
Dimitris

**Comment by tsung-wei-huang** [comment]
@dmangira sorry for the late response. You cannot create a dependency on-the-fly. In your example:

```cpp
if (iter == 1) {
      D.precede(E);
}
```

This is invalid. I assume you want to create an interative control-flow. Please have a look at the cook [here](https://taskflow.github.io/taskflow/ConditionalTasking.html)

**Comment by dmangira** [comment]
@tsung-wei-huang Thank you for your reply!
