### ISSUE TITLE
[question about task execute ordering]

### ISSUE THREAD

**Issue by xinlnix** [taskflow/taskflow#313]
I want to know after we build the task DAG, the task execute order is *topological* or *postorder" ?
> A topological ordering of a rooted tree is an ordering that numbers children vertices before their parent.
> A postorder is a topological ordering which numbers the vertices in any subtree consecutively.

**Comment by tsung-wei-huang** [comment]
Hi @xinlnix the execution is always a topological order that is consistent with their dependencies. For example, if you have A->B->C, then the executor order will be A, B, C.

**Comment by xinlnix** [comment]
Maybe I didn't make it clearly.
As this picture described, there are two ways to select topological ordering. 
![describe picture](https://github.com/xinlnix/images/blob/main/img/20210421125304.png)
The bottom left picture's order is random, the bottom right picture's order is more locally,I think the locally may cache friendly in small task, which can speed up the task switch time.

**Comment by xinlnix** [comment]
Another little question:
picture![](https://raw.githubusercontent.com/xinlnix/images/main/img/20210421234603.png)
Why the task start from 40k us, What does it do in the span: 0-40k us ? Thanks in advance.

**Comment by xinlnix** [comment]
@tsung-wei-huang

**Comment by tsung-wei-huang** [comment]
@xinlnix in terms of task start, it depends on the scheduler. The scheduler is dynamic and there is always overhead to star up the executor.

I think the topological order here is nothing to do with the tree order. It is a topological order of a DAG.

**Comment by xinlnix** [comment]
@tsung-wei-huang Can I speed up the time of task start up?. Does that time consume depend on the task number or other things?

**Comment by xinlnix** [comment]
The whole task execute time is 52k us, 0-40 is the start up time. Is that mean my task is too small?

**Comment by xinlnix** [comment]
![](https://raw.githubusercontent.com/xinlnix/images/main/img/20210422133937.png)

**Comment by tsung-wei-huang** [comment]
Creating a task has a certain overhead - around 50 ns amortized time. 0-40 is not bad actually. How many tasks do you have?

**Comment by xinlnix** [comment]
@tsung-wei-huang In my test, I have 19631 tasks. But the task is too small. So the task execute time is less than task schedule time in every thread. Maybe I should use other method to schedule my task? Please give me some suggestion.

**Comment by tsung-wei-huang** [comment]
19631 is not a big number. However, if each of your task runs only a few microseconds, you should consider merging some of them into bigger ones.

**Comment by xinlnix** [comment]
Got that, thank you very much
