### ISSUE TITLE
Returning values of task

### ISSUE THREAD

**Issue by RedFree** [taskflow/taskflow#314]
Hi, I have two qustions,
1. I want to know the current task can return the value.
2. Can the value current task returned  pass to the next tasks.

**Comment by tsung-wei-huang** [comment]
@RedFree Taskflow doesn't do any data abstraction but gives this to users.

**Comment by RedFree** [comment]
How is data passed between tasks。I want the previous result to pass to next tasks, what should I do?

**Comment by tsung-wei-huang** [comment]
@RedFree currently, you need to manage the data yourself and capture those data in lambda

**Comment by RedFree** [comment]
@tsung-wei-huang I know, thank you very much!
