### ISSUE TITLE
Simple.cpp Segmentation Fault when Statically Linked

### ISSUE THREAD

**Issue by gmclay** [taskflow/taskflow#317]
**Describe the bug**
Segmentation fault occurs when example is statically linked. 

When trying to use taskflow in my project, I kept hitting segmentation faults whenever invoking a member of tf::Taskflow (ie `taskflow.placeholder()`). To reduce the number of variables, I went back and tried to statically link the simple.cpp example and hit the same issue.

**To Reproduce**
1. Build the simple.cpp example but with the added `-static` flag.
g++ -std=c++17 simple.cpp -I taskflow/taskflow -O2 -pthread -static -o simple
2. Run simple
./simple
3. See segmentation fault

```
$ g++ -std=c++17 simple.cpp -I ../taskflow -O2 -pthread -o simple
$ ./simple 
TaskA
TaskC
TaskB
TaskD
$ g++ -std=c++17 simple.cpp -I ../taskflow -O2 -pthread -static -o simple
$ ./simple 
Segmentation fault (core dumped)
```

The issue seems to relate to pthread and statically linking but both have been in my project before integrating taskflow so I don't understand why it might be an issue now. Is this a known limitation of taskflow? I haven't seen it documented anywhere. Any guidance is welcomed. Thanks.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS

**Additional context**
Compiler: x86_64-linux-gnu-g++-9

**Comment by tsung-wei-huang** [comment]
I don't recommend using `-static` because it is almost impossible to compile a ball that statically link all the C++ threading libraries. Much cpp thread facility is built as shared library. I tried compiling the example using `-static` and I didn't see any issue. However, in other environments, it shows segmentation fault due to inappropriate linking to `stdc++` in the machine.

**Comment by gmclay** [comment]
Dr. Huang, thank you for your quick response! I realize compiling a static binary has its challenges but the advantages outweigh the challenges for my project. 

In case this helps others with similar issues, for my specific project needs I found the following linker flags fixed my issue. 

`-pthread -static -static-libstdc++ -Wl,--whole-archive -lrt -lpthread -Wl,--no-whole-archive`

Original idea came from: 
https://stackoverflow.com/questions/58848694/gcc-whole-archive-recipe-for-static-linking-to-pthread-stopped-working-in-rec

**Comment by tsung-wei-huang** [comment]
@gmclay thank you for finding out the correct linkage!
