### ISSUE TITLE
[Question]: removed partition algorithms

### ISSUE THREAD

**Issue by matt77hias** [taskflow/taskflow#318]
Commit 56accf750753481601002d3ea7178c9f5ad753dc removed explicit partitions in algorithms.

The current documentation of [`tf::FlowBuilder::for_each`](https://taskflow.github.io/taskflow/classtf_1_1FlowBuilder.html#a564252001be679600b20ca9ed9920f6a) states:
> By default, we employ the guided partition algorithm with chunk size equal to one.

Is there any way to select a different (from the default) partition algorithm?
(The static partition algorithm can be emulated by wrapping the original callable in a for loop inside a new outer callable, though.)

**Comment by tsung-wei-huang** [comment]
We use the guided partition algorithm as the default strategy because it outperforms many cases in our work-stealing scheduler.  Static partition is not working well with dynamic work-stealing based on our user feedback.

**Comment by matt77hias** [comment]
And is that also the rationale for the removal of the chunk size parameter (i.e. now the implicit chunk size is always one)?

**Comment by tsung-wei-huang** [comment]
@matt77hias yes, I will update the doc later. The new design is also to comply with the C++ standard.
