### ISSUE TITLE
Adding dependencies to already scheduled tasks

### ISSUE THREAD

**Issue by wrenoud** [taskflow/taskflow#319]
In the example below C never executes, despite the graph appearing correct.

Is this a bug or is this by design? Is it inappropriate to be passing around references to tasks for the sake of adding dependencies?

```cpp
tf::Taskflow taskflow;
tf::Executor executor;

auto A = taskflow.emplace([]() {}).name("A");
auto B = taskflow.emplace([&A](tf::Subflow& subflow) {
     auto C = subflow.emplace([]() {
                         std::puts("Got here");
                     }).name("C");
     A.precede(C);
     subflow.detach();
 }).name("B");

executor.run(taskflow).wait();
```

![graphviz](https://user-images.githubusercontent.com/2761756/117851133-4e108780-b286-11eb-839b-7d00372fb779.png)

**Comment by tsung-wei-huang** [comment]
Hi @wrenoud this is not allowed. You cannot have dependencies across different subgraphs.

**Comment by wrenoud** [comment]
@tsung-wei-huang I just wanted to add a thank you for the quick response, but also for a great library. I really appreciate what you've produced here. I'm new with taskflow but I think it can be put to good use in my company's codebase and I'm excited to use it. I've been looking at various toolsets and haven't really been excited about using them because they all felt like a heavy lift to get started, until taskflow.

**Comment by tsung-wei-huang** [comment]
@wrenoud no problem. Thank you for using taskflow. Please let me know if any thing I can help.
