### ISSUE TITLE
will `callback` run after task is cancelled?

### ISSUE THREAD

**Issue by GOGOYAO** [taskflow/taskflow#320]
**Please describe your feature request.**

will `callback` run after task is cancelled? I need the callback run no matter what happened.

**Comment by tsung-wei-huang** [comment]
@GOGOYAO yes, the callback will be run. Cancelling a taskflow is a normal operation. The callback will be invoked when the cancellation finishes. You can see the code [here](https://github.com/taskflow/taskflow/blob/c3ca091f511df4fbfd3bbddc8f4d21fbae8672fa/taskflow/core/executor.hpp#L1058)

**Comment by GOGOYAO** [comment]
> @GOGOYAO yes, the callback will be run. Cancelling a taskflow is a normal operation. The callback will be invoked when the cancellation finishes. You can see the code [here](https://github.com/taskflow/taskflow/blob/c3ca091f511df4fbfd3bbddc8f4d21fbae8672fa/taskflow/core/executor.hpp#L1058)

thank you
