### ISSUE TITLE
Please reference the original Taskflow project

### ISSUE THREAD

**Issue by johnsom** [taskflow/taskflow#321]
**Describe the bug**

Since this project has changed it's name to be the same as the existing python TaskFlow project (Eight years old now) it would be nice reference it in your readme so folks searching for the original Taskflow project can find it easier.

https://wiki.openstack.org/wiki/TaskFlow
https://github.com/openstack/taskflow

**Comment by tsung-wei-huang** [comment]
@johnsom thanks for pointing this out. Essentially, the two "taskflows" are totally different. I will add your suggestion to the README in the next release.
