### ISSUE TITLE
Can we create a DAG in parallel?

### ISSUE THREAD

**Issue by EzioZz** [taskflow/taskflow#322]
I have added `#pragma omp parallel for num_threads(4)` in line 72 trying to build a DAG in paralle.
Once I run the code, there will be some runtime error.
```
main(97739,0x70000a7ec000) malloc: *** error for object 0x7f8258c05ec0: pointer being freed was not allocated
main(97739,0x107002dc0) malloc: *** error for object 0x7f8258c05eb0: pointer being freed was not allocated
[1]    97739 segmentation fault  /Users.../build/main
```

![image](https://user-images.githubusercontent.com/22981348/118500300-42c3cd00-b75a-11eb-825e-843efe8ffae9.png)

**Comment by tsung-wei-huang** [comment]
@EzioZz the `tf::Taskflow` object is not thread-safe. You should use only one thread to create/touch a taskflow.
