### ISSUE TITLE
Best practice with OpenMP

### ISSUE THREAD

**Issue by JAF130195** [taskflow/taskflow#326]
Hello there, 

I have a need in my code to mix both OpenMP and Taskflow. 
Openmp is needed for some depencies I'm using and for simple loop parallelisation in parts of my own code while Taskflow is obviously the much better choice for parts of my code that require task-based programming. 

So, my questions are:

 1) **Can taskflow and OpenMP play well together in the same code?**
2) **If so, do you have any "best practice" tips for getting good performance** (not calling taskflow in an omp parallel region I would expect to be one of them, for example) 

Thanks in advance and great work with Taskflow! It's a really awesome library. 

John Ferguson.

**Comment by tsung-wei-huang** [comment]
@JAF130195 thanks for your interest in using taskflow. Please see my response below:

1. Yes, you can use taskflow together with OpenMP. Taskflow has a dynamic scheduler that automatically balances the number of workers with available task parallelism at any time during the execution. However, OpenMP does not. So you may need to see if over-subscribed threading can be a problem to your application. 
2. Actually, this depends on your application. Here are some general guidelines:
    + reuse taskflow object as much as possible
    + reuse the same executor object as much as possible

I wonder what kind of features you need in OpenMP that Taskflow does not handle well?

**Comment by JAF130195** [comment]
Taskflow has all of the features I require, I only need OpenMP in order to call multithreaded OpenBLAS and Superlu.
So would I be correct in saying that sol long as I avoid calling OpenMP code within a task executed in paralllel by taskflow that I am unlikely to oversubribe threading?

**Comment by tsung-wei-huang** [comment]
It depends on your applications. Each task is executed by one thread. It's totally fine to spawn OpenMP calls within a Taskflow task. That being said, if you spawn multiple OpenMP calls within multiple Taskflow tasks, you may have oversubscribed threading issues. As far as I know, the impact is not too much given the dynamic scheduling behavior of Taskflow.

**Comment by JAF130195** [comment]
I see, good to know. I will do some testing myself and see what works for my application. 

Thanks for your time!

**Comment by tsung-wei-huang** [comment]
Thanks.
