### ISSUE TITLE
Taskflow is failing to run when compiled with cuda on windows

### ISSUE THREAD

**Issue by GPomare** [taskflow/taskflow#330]
tried compiling and running the following code. It fails at the taskflow code segment when compiling for cuda, but runs when running with g++. Running this on windows 10 with a GeForce RTX 2060 with Cuda 11.2

```
#include <taskflow/taskflow.hpp>
#include <iostream>

int main(int argc, const char** argv) {

	std::cout << "start\n";
	tf::Taskflow taskflow;
	tf::Executor executor;

	taskflow.emplace([](){
		std::cout << "running thread\n";
	});

	executor.run(taskflow).wait();

std::cout << "finish\n";

  return 0;
}
```

g++ output
```
PS C:\Users\Grant\Documents> .\test.exe
start
finish
```

cuda output
```
PS C:\Users\Grant\Documents> .\test.exe
start
```

**Comment by tsung-wei-huang** [comment]
where did you put your executor to run the taskflow in your code?

**Comment by GPomare** [comment]
I'll add the executor in and run it again, but looks like it's failing when setting up the taskflow task

**Comment by GPomare** [comment]
Updated the sample. It runs fine when compiled with nvcc using the .cpp extension, but fails to run with .cu

**Comment by tsung-wei-huang** [comment]
please give the entire code so I can take a closer look.

**Comment by tsung-wei-huang** [comment]
what is your compilation command?

**Comment by GPomare** [comment]
nvcc test.cu -I taskflow -o test -std=c++17

**Comment by bravestpeng** [comment]
on windowns "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64" -x cu   -I"D:\project\taskflow-master" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include"     --keep-dir x64\Debug  -maxrregcount=0  --machine 64 --compile -cudart static --extended-lambda -std=c++17 /bigobj -Xcompiler="/EHsc -Zi -Ob0 -Wall,-Wextra,-Wfatal-errors" -g  -D_WINDOWS -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W3 /nologo /Od /Fdcuda_reduce.dir\Debug\vc142.pdb /FS /Zi /RTC1 /MDd /GR" -o cuda_reduce.dir\Debug\cuda_reduce.obj "D:\project\taskflow-master\examples\cuda\cuda_reduce.cu"”已退出，返回代码为 1。	cuda_reduce	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.4.targets	785

**Comment by tsung-wei-huang** [comment]
Are you still seeing the issue? (I am guessing you may need to include `-pthread`?)

**Comment by GPomare** [comment]
Still getting the same issue
