### ISSUE TITLE
What exactly are the requirements for this library?

### ISSUE THREAD

**Issue by agauniyal** [taskflow/taskflow#332]
I see it supports Win/Linux/macOS mentioned on your project details, but are there any requirements that doesn't let taskflow run on Android or iOS or some other platforms? Most of these platforms already support C++17 as well as std::thread library.

**Comment by tsung-wei-huang** [comment]
Not really, as far as I know. As long as you have C++17 support, you should be able to use the most part of taskflow (i.e., cpu-parallelism).
