### ISSUE TITLE
How to handle web requests with taskflow?

### ISSUE THREAD

**Issue by patlecat** [taskflow/taskflow#333]
Is there some documentation or examples discussing how one should handle incoming web requests for a web-server application when not using Apache or nginx? I feel that each request should get it's own asynchronous task and go through a few preset paths to process them, but that may be too naive? What are your suggestions? Does anyone have experience with that?

**Comment by tsung-wei-huang** [comment]
We do not aim for this purpose. However, you may create a taskflow to handle the job/task corresponding to each HTTP request or so.

**Comment by patlecat** [comment]
Yes that's what I like to know from devs that are using taskflow this way. Maybe someone can write their experience here...
