### ISSUE TITLE
math.hpp  unique_id() 

### ISSUE THREAD

**Issue by wiltchamberian** [taskflow/taskflow#334]
template <typename T, std::enable_if_t<std::is_integral_v<T>, void>* = nullptr>
T unique_id() {
  static std::atomic<T> counter{0};
  return counter.fetch_add(1, std::memory_order_relaxed);
}
no one use this function, but it can not generate a unique id of the type

**Comment by wiltchamberian** [comment]
here is my implement :

class UniqueTypeCounter {
	public:
		template<class _T>  //deprecated
		size_t unique_type_id_old() {
			size_t res = 0;
			static _T b = [this ](size_t& siz) {
				siz = counter_++;
				return _T();
			}(res);
			return res;
		}
		template<class _T>
		size_t unique_type_id() {
			static std::once_flag flag;
			size_t res = 0;
			std::call_once(flag, [&res,this]() {
				res = counter_++;
				});
			return res;
		}
	private:
		std::atomic<size_t> counter_;
	};

**Comment by tsung-wei-huang** [comment]
Will consider this in the next release. Thanks.
