### ISSUE TITLE
Attaching user data to tasks

### ISSUE THREAD

**Issue by Endilll** [taskflow/taskflow#335]
Is it possible or considered for future development to attach user data to a task? My primary interest is a seemingly simple case when a taskflow consists of tasks each with consistent set of boolean flags attached to it. They are used by conditional tasks to skip over some calculations if certain flags are set in dependencies.

It seems that `Node::name` is similar kind of data. Maybe it could be generalized for such use cases.

I can also help implementing this.

**Comment by tsung-wei-huang** [comment]
@Endilll you can simply create stateful or non-stateful lambda that capture the data you need in a task.

```cpp
taskflow.emplace([a = int{5}](){
  std::cout << "my data is " << data << std::endl;
});
```

**Comment by Endilll** [comment]
But it's not possible to inspect this data from other tasks. Consider the following example:
```
tf::Taskflow taskflow;
auto task{taskflow.placeholder()};
task.succeed(taskA, taskB, taskC);
task.precede(do_work, skip_work);
task = taskflow.emplace([] {
    bool deps_are_good{true};
    task.for_each_dependent([&deps_are_good] (tf::Task dependency) {
        if (!dependency.user_data<User_data>().good) { // not possible today 
            deps_are_good = false;
        }
    });    
    if (!deps_are_good) {
        return 1; // skip over work
    }
    return 0; // do work
});
```
Currently I'm able to achieve this by maintaining `std::unordered_map<size_t, User_data>` global read-only mapping, but I wonder if taskflow can (plan to) save me from this.

The bigger picture is that I have a graph of tens of thousands nodes each consisting of a piece of calculation and a small amount of data representing state of the node. Edges of this graph represent data dependencies between those pieces of calculations. Graph is static and need to be run multiple times with different user input to nodes that doesn't have dependencies. So I'm trying to leverage taskflow not just for pure computation, but also for keeping a graph. Let me know if I'm abusing the library.

**Comment by tsung-wei-huang** [comment]
I see. I am thinking about the following:

```cpp
int my_data = 5;
tf::Task task = taskflow.placeholder();
task.data(&my_data);  // let's say, each node has a C-style void* pointer to user-defined data
task.work([task](){       // assign the work after data binding and capture the task
   void* ptr = task.data();
   // ...
})  
```

Would this be something useful for you? This is actually the interface I have been thinking about for a while for associating data to a task.

**Comment by Endilll** [comment]
Very much useful. Two questions, thought:
1) Is it possible to make it more type-safe?
2) Should it be generalized for all kinds of data that is not required to perform a computation? Like name of the task, which users currently pay for even if they don't use it.

**Comment by tsung-wei-huang** [comment]
1. yes; however, I will need to use `std::any` that comes with copy-only data restrictions. Since data management is typically application-dependent, I prepare the simple `void*` that gives users the most freedom. 
2. I would say name is the only exception - because the TFProf will need it to perform visualization. We should separate it from the user data.

Feel free to comment and give suggestions. I can add this quickly. Thanks.

**Comment by Endilll** [comment]
Is template stuff out of question? I can see it going viral through codebase, thought, which adds more complexity than usefulness

**Comment by tsung-wei-huang** [comment]
@Endilll yes, template will complicate the codebase especially from the scheduling point of view. I think the simple `void*` is the optimal solution, considering the software tradeoff, although it comes at the cost of non-safe type. As long as users are knowledgeable about their use of data, error should be avoided. What do you think?

**Comment by Endilll** [comment]
What do you think about providing not just `void* data()` and a corresponding `const` overload, but also `template<typename T> T& data()` with its corresponding `const` overload, which encapsulates `*static_cast<T*>(data_ptr)`, making user code cleaner?

**Comment by tsung-wei-huang** [comment]
I think returning data is the best solution from a library-design perspective because it is the bottommost call. Users can always create a wrapper on their own. Also, this method `task.data() -> void*` implicitly tells users this method is not type-safe.

Would you be interested in creating a pull request? I can do it but may be a bit late this week.

**Comment by Endilll** [comment]
Yes. I've already taken a took into relevant sources and they are so much easier compared to standard library implementations or Boost, so I can have some confidence in my PR.

**Comment by tsung-wei-huang** [comment]
@Endilll merged to the master with documentation [here](https://taskflow.github.io/taskflow/StaticTasking.html#AttachUserDataToATask)
