### ISSUE TITLE
[doc] typo in the cookbook

### ISSUE THREAD

**Issue by xq114** [taskflow/taskflow#336]
**Describe the bug**
https://taskflow.github.io/taskflow/ExecuteTaskflow.html#ObserveThreadActivities

Here the function on_entry and on_exit don't override any functions since the first parameter in `tf::ObserverInterface` is of type `tf::WorkView` instead of `size_t`.

![image](https://user-images.githubusercontent.com/42310255/131476943-96265d46-6108-4042-b694-57a90399f5a1.png)
![image](https://user-images.githubusercontent.com/42310255/131477244-94b18075-ff79-4794-9fac-954a1e485b62.png)

**Comment by tsung-wei-huang** [comment]
@xq114 thank you for the catch. Yes, it should be `tf::WorkerView` which is more general than the legacy `std::size_t`. I have updated it in the doc.
