### ISSUE TITLE
high sys cpu usage

### ISSUE THREAD

**Issue by MambaWong** [taskflow/taskflow#339]
when change the `executor.run(taskflow).wait();` to `executor.run_until(taskflow, [](){ return false; }).wait();`
use `top` command:
![top](https://user-images.githubusercontent.com/16932438/131791437-d1e77743-d138-4fcc-84ba-76949818e133.png)
use `strace`:
![strace](https://user-images.githubusercontent.com/16932438/131794325-2b3aa00d-8a12-4fbd-ac68-b4c6c0fd7302.png)

https://github.com/taskflow/taskflow/blob/348e5c5c38057ad53605279feec476daf2f1ea49/taskflow/core/executor.hpp#L517-L522

**Comment by tsung-wei-huang** [comment]
It depends on the program you are running. Taskflow's scheduling algorithm has a special thread coordination strategy to dynamic balance the available threads with task parallelism.
