### ISSUE TITLE
Removing a task from a taskflow

### ISSUE THREAD

**Issue by Endilll** [taskflow/taskflow#341]
As far as I can understand, currently there's no way to remove a task from a taskflow or severe dependency between tasks (combined with `reset_work()` this effectively eliminates a task from execution, I assume), and no workarounds except for ugly hacks like accessing private members of taskflow objects.

It seems rather straightforward to provide both, at least for `tf::Taskflow` (I haven't looked into other back-ends like SYCL yet). If I'm not missing something important, can you give your thoughts on the interface for this?

From my side I'd like to ask for an API to remove multiple tasks at once.

**Comment by tsung-wei-huang** [comment]
@Endilll This should be doable - the [graph object](https://github.com/taskflow/taskflow/blob/master/taskflow/core/taskflow.hpp#L173) in `tf::Taskflow` is indeed just a vector of node pointers. Each node has two vectors to store [output](https://github.com/taskflow/taskflow/blob/master/taskflow/core/graph.hpp#L220) and [input](https://github.com/taskflow/taskflow/blob/master/taskflow/core/graph.hpp#L221) nodes. We may add graph deletion methods in Taskflow, like `tf::Taskflow::remove(tf::Task)`.

Feel free to comment and submit pull request.

**Comment by Endilll** [comment]
Since `clear` and `emplace` are already present, shouldn't it be named `erase` after standard containers member functions?

**Comment by tsung-wei-huang** [comment]
Agree. `tf::Taskflow::erase(tf::Task task_to_remove)` is better. The method will remove a task and all its input and output dependencies.

**Comment by tsung-wei-huang** [comment]
This has been merged. #342
