### ISSUE TITLE
Question: How does taskflow work with TBB?

### ISSUE THREAD

**Issue by rgirish28** [taskflow/taskflow#343]
Hi, 

We are looking to use taskflow within the graph modules in our project, but many parts of the codebase already use TBB. 

So, we were wondering how both these packages play together? I understand each of the packages have their own task scheduler to manage tasks with their own worker threads, but is there any way to restrict the overall project to N worker threads between taskflow and tbb? 

Sadly, we are not in a position to rewrite all our modules that use TBB, but would like to use Taskflow to see if we can achieve speedup. Thanks for all the good work!

Cheers,
Girish Ramesh

**Comment by tsung-wei-huang** [comment]
@rgirish28 thanks for your interest. Indeed, there is no conflict between the use of Taskflow and TBB. Both systems have adaptive work-stealing schedulers trying to balance threads with available task parallelism. It's totally fine to mix the use and we have several users doing the same thing.

That being said, our schedulers do outperform TBB in several cases, especially for complex graph workloads. You may read our [research paper](https://tsung-wei-huang.github.io/papers/tpds21-taskflow.pdf).

**Comment by tsung-wei-huang** [comment]
Feel free to reopen if you have further questions.

**Comment by rgirish28** [comment]
Thanks for the quick response. It's good to know that the systems behave well together. However, one of the main requirements in our system is the ability to restrict the number of overall worker threads, which I think will be difficult given that both TBB and Taskflow will spawn their own set of threads. Do you have any suggestions on whether this situation can be handled?

**Comment by rgirish28** [comment]
Sadly, this might mean that we have to wait until the interoperability issue is solved before we integrate Taskflow into our project. Thanks for the info and your feedback!
