### ISSUE TITLE
Question about handbook "Implement While-Loop Control Flow"

### ISSUE THREAD

**Issue by jonesmz** [taskflow/taskflow#344]
The handbook has this example code.

```
// wrong implementation of while-loop using only one condition task
tf::Taskflow taskflow;

int i;

auto [init, cond, body, done] = taskflow.emplace(
  [&](){ std::cout << "i=0\n"; i=0; },
  [&](){ std::cout << "while i<5\n"; return i < 5 ? 0 : 1; },
  [&](){ std::cout << "i++=" << i++ << '\n'; },
  [&](){ std::cout << "done\n"; }
);

init.precede(cond);
cond.precede(body, done);
body.precede(cond);
```

The description says 
>In the taskflow diagram above, the scheduler starts with init and then decrements the strong dependency of the loop condition task, while i<5. After this, there remains one strong dependency, i.e., introduced by the loop body task, i++. However, task i++ will not be executed until loop condition task returns 0, causing a deadlock.

Why can't the task `body` be changed to be

`  [&](){ std::cout << "i++=" << i++ << '\n'; return 0; },`

to change the strong dependency to a weak dependency?

This is nearly identical to how "Implement Do-While-Loop Control Flow" is shown.

Is the reason that this cannot be done because when the conditional path is taken to from `cond` to `body`, if that does not cause a strong-dependency on `cond`, something bad happens?

**Comment by tsung-wei-huang** [comment]
@jonesmz , You can change `body` to a condition task as you wrote. This is just a demonstration in the handbook for how to use condition tasks.

**Comment by jonesmz** [comment]
I think the handbook is misleading and should be rewritten to clearly explain what is, and isn't allowed.
