### ISSUE TITLE
Moving away from conditional execution implicitly relying on indicies

### ISSUE THREAD

**Issue by jonesmz** [taskflow/taskflow#345]
See the "switch-case" example from https://taskflow.github.io/taskflow/ConditionalTasking.html#ImplementSwitchControlFlow

```cpp
tf::Taskflow taskflow;

auto [source, swcond, case1, case2, case3, target] = taskflow.emplace(
  [](){ std::cout << "source\n"; },
  [](){ std::cout << "switch\n"; return rand()%3; },
  [](){ std::cout << "case 1\n"; return 0; },
  [](){ std::cout << "case 2\n"; return 0; },
  [](){ std::cout << "case 3\n"; return 0; },
  [](){ std::cout << "target\n"; }
);

source.precede(swcond);
swcond.precede(case1, case2, case3);
target.succeed(case1, case2, case3);
```
In the above example, the return value from `swcond` are implicitly used as `indices` into the list of possible next tasks to execute.

I think that index based dependencies are a recipe for disaster.

Imagine a large system with multiple maintainers. One maintainer manages a collection of functions and data structures that those functions operate on, and other maintainers create applications that use those functions.

In this example, imagine that `FunctionA` returns some enum

```cpp
enum FunctionAReturnCode
{
    ThingOne, // just so happens to be 0
    ThingTwo  // just so happens to be 1
};
```
One of the application maintainers decides to use `taskflow` to tie all of the functions that the library maintainer build, and this application maintainer relies on `FunctionA` returning something that be passed to `std::to_underlying()`.

Then they set up their conditional task flow like:

```cpp
tf::Taskflow taskflow;
auto [source, functionA, thingOne, thingTwo, target] = taskflow.emplace(
  [](){ std::cout << "source\n"; },
  [](){ std::cout << "functionA\n"; return std::to_underlying(FunctionA()); },
  [](){ std::cout << "ThingOne\n"; return 0; },
  [](){ std::cout << "ThingTwo\n"; return 0; },
  [](){ std::cout << "target\n"; }
);

source.precede(functionA);
functionA.precede(thingOne, thingTwo);
target.succeed(thingOne, thingTwo);
```

This works, everyone's happy, they sell a million copies and sell the company and retire to a beach on a tropical island paradise.

Now, the new maintainer of the system, who has no idea that `FunctionA` happens to be used in the application, or that taskflow is involved, looks at their `FunctionA` function, and decides that for one of their internal use-cases (e.g. `FunctionB` happens to call `FunctionA`), they need to have a new enum value

```cpp
enum FunctionAReturnCode
{
    Neither,     // Just so happens to be 0
    ThingOne, // OOPS! This is now 1
    ThingTwo  // OOPS! This is now 2
};
```

And now the taskflow breaks, because sometimes it gets `2`.

Or, they flip the order of the enum values

```cpp
enum FunctionAReturnCode
{
    ThingTwo,  // OOPS! This is now 0
    ThingOne // OOPS! This is now 1
};
```
Or they just add values for "self documentation".

```cpp
enum FunctionAReturnCode
{
    ThingOne =1,
    ThingTwo = 2
};
```

Of course, taskflow can say "index based conditional dependencies is how taskflow works and that's final", but I think that even if we were going to ignore that the maintainer of the application should have explicitly written their task like:

```cpp
[]()
{
    std::cout << "functionA\n";
    auto outcome = FunctionA();
    switch(outcome)
    {
        case ThingOne: return 0;
        case ThingTwo: return 1;
        default: assert(false); std::abort();
    }
}
```
The decision to use implicit indices is not very ergonomic, is prone to mistakes, and doesn't provide facilities that normally would be expected in a C++ language based program when it comes to things like enum, or complex objects.

For example, imagine:
```cpp
enum class FunctionAReturnCode
{
    Neither,     // Just so happens to be 0
    ThingOne, // OOPS! This is now 1
    ThingTwo  // OOPS! This is now 2
};

tf::Taskflow taskflow;
auto [source, functionA, thingOne, thingTwo, defaultTask, target] = taskflow.emplace(
  [](){ std::cout << "source\n"; },
  [](){ std::cout << "functionA\n"; return FunctionA(); },
  [](){ std::cout << "ThingOne\n"; return 0; },
  [](){ std::cout << "ThingTwo\n"; return 0; },
  [](){ std::cout << "Default Outcome\n"; return 0; },
  [](){ std::cout << "target\n"; }
);

source.precede(functionA);
functionA.conditionally_precede(FunctionAReturnCode::ThingOne, thingOne);
functionA.conditionally_precede(FunctionAReturnCode::ThingTwo, thingTwo);
functionA.conditionally_precede(tf::default_case{}, defaultTask);
target.succeed(thingOne, thingTwo, defaultTask);

```

Which provides the ability to explicitly say what return value from the function maps to which task. This can be generically extended to support any type that implements operator==, really, but for simplicity it could be initially introduced as integer comparisons only.

This could go even further, and a macro could be setup that can be used to generate a warning if one of the possible enum values aren't used.

```cpp
enum class FunctionAReturnCode
{
    Neither,     // Just so happens to be 0
    ThingOne, // OOPS! This is now 1
    ThingTwo  // OOPS! This is now 2
};

tf::Taskflow taskflow;
auto [source, functionA, thingOne, thingTwo, defaultTask, target] = taskflow.emplace(
  [](){ std::cout << "source\n"; },
  [](){ std::cout << "functionA\n"; return functionA(); },
  [](){ std::cout << "ThingOne\n"; return 0; },
  [](){ std::cout << "ThingTwo\n"; return 0; },
  [](){ std::cout << "Default Outcome\n"; return 0; },
  [](){ std::cout << "target\n"; }
);

source.precede(functionA);

// Warning, one of the values of FunctionAReturnCode is not used!!!
TASKFLOW_BUILD_SWITCH_CASE(functionA, // first argument is the task which branches out.
                                                      FunctionAReturnCode::ThingOne, thingOne,
                                                      FunctionAReturnCode::ThingTwo, thingTwo);

// No warning, since there's a default task.
TASKFLOW_BUILD_SWITCH_CASE_WITH_DEFAULT(functionA, // first argument is the task which branches out.
                                                                                defaultTask, // second argument is the task to use as default.
                                                                                FunctionAReturnCode::ThingOne, thingOne,
                                                                                FunctionAReturnCode::ThingTwo, thingTwo);

target.succeed(thingOne, thingTwo, defaultTask);

```

**Comment by tsung-wei-huang** [comment]
@jonesmz thanks for the points. Would you be interested in submitting a pull request to overcome the problem you mention?

**Comment by tsung-wei-huang** [comment]
Feel free to reopen the issue if you are willing to submit a pull request.

**Comment by jonesmz** [comment]
That's... Not really a good approach to collaborating with open source contributors.

Either the idea is worth implementing, or its not.

The issue shouldn't be closed unless the person who opened the issue is willing to submit a PR. It should only be closed if the idea itself is not worth while.
