### ISSUE TITLE
Doesn't respect the cmake find_package's QUIET keyword

### ISSUE THREAD

**Issue by yurivict** [taskflow/taskflow#346]
**Describe the bug**

```find_package(Taskflow REQUIRED QUIET)``` still prints:
> \- Taskflow found. Headers: /usr/local/include

Version: 3.2.0
cmake-3.20.5
FreeBSD 13

**Comment by tsung-wei-huang** [comment]
@yurivict I am not sure how this can be fixed? Do you have any ideas?

**Comment by yurivict** [comment]
I am not a cmake expert, but your cmake procedure should check if ```QUIET``` is given before printing anything.

**Comment by milianw** [comment]
You can check the `Taskflow_FIND_QUIETLY` before doing the `message()`

**Comment by tsung-wei-huang** [comment]
Close first - feel free to reopen it if the problem is still there.
