### ISSUE TITLE
Is it safe to call `taskflow.clear()` after cancelling, without calling `.wait_for_all()` on the executor?

### ISSUE THREAD

**Issue by sunbubble** [taskflow/taskflow#348]
Is it safe to call `taskflow.clear()` after cancelling, without calling `.wait_for_all()` on the executor?
Essentially, I want to understand whether the snippet bellow is a valid and safe use of taskflow.
All lines besides the last one come from the [example documenting](https://taskflow.github.io/taskflow/classtf_1_1Future.html#a3bf5f104864ab2590b6409712d3a469b) the `tf::Future::cancel` member function.

```C++
tf::Executor executor;
tf::Taskflow taskflow;

for(int i=0; i<1000; i++) {
  taskflow.emplace([](){ 
    std::this_thread::sleep_for(std::chrono::seconds(1));
  });
}

tf::Future fu = executor.run(taskflow);
fu.cancel();
fu.get();

// Is this operation guaranteed safe without calling executor.wait_for_all()?
taskflow.clear()
```

**Comment by tsung-wei-huang** [comment]
Hi @sunbubble thanks for the question. When you call `tf::Future::cancel`, the executor will stop threads from running the tasks afterwards, and this request is not guaranteed to finish until your explicit wait on the future `tf::Future::get`. That is, when you return from `tf::Future::get`, the cancellation is guaranteed to complete and you are free to clear/modify the taskflow.

`tf::Executor::wait_for_all` is similar but it waits on all submitted taskflows to complete, including cancellation. Does this make sense to you?

**Comment by sunbubble** [comment]
Makes perfect sense. I had assumed this was the case, but I could not find clearly stated in the documentation. So I wanted to ask to be sure :)

**Comment by tsung-wei-huang** [comment]
@sunbubble I will update the doc to clarify the points :) Thanks.
