### ISSUE TITLE
Question: Is it possible to name an async/silent_async task?

### ISSUE THREAD

**Issue by theakman2** [taskflow/taskflow#351]
Is it possible to name a task created via `Executor::async` or `Executor::silent_async`? I can't seem to find a way to do this via the public API.

It's currently very difficult to differentiate between async tasks in the profiler. Names would be very helpful here.

Thanks in advance!

**Comment by tsung-wei-huang** [comment]
@theakman2 thank you for the question. Yes, it is possible to do this. What about an API like this?

```
tf::Executor::async([](){}, "name of the task");
```

**Comment by theakman2** [comment]
@tsung-wei-huang Thanks for looking into this. Yes, that API looks good to me. Would silent_async tasks also have a similar API?

**Comment by tsung-wei-huang** [comment]
@theakman2 I have added two methods `tf::Executor::named_async` and `tf::Executor::named_silent_async` in the master branch. You can see the documentation [here](https://taskflow.github.io/taskflow/classtf_1_1Executor.html#a51acee1670e9f246c7ccd7f6a63f1524).

**Comment by theakman2** [comment]
Great, thank you for this! I'm happy to star the project.
