### ISSUE TITLE
Can a async task use semaphore?

### ISSUE THREAD

**Issue by AbrasiveBoar902** [taskflow/taskflow#355]
In my program, I have to add tasks when running. But some tasks can't run together with other tasks, like modifying a same object. It's impossible to use mutex because the relationship between objects is not simple, and I don't want them to block other tasks. How can I use a semaphore or something else?

**Comment by AbrasiveBoar902** [comment]
emm it seems that using a executor to run async tasks is like a threadpool?

**Comment by tsung-wei-huang** [comment]
@AbrasiveBoar902 thanks for the question. Asyn task cannot acquire semaphore at this moment. You will need to create tasks from taskflow to acquire semaphore. I will see what I can do to modify the async task interface.

**Comment by AbrasiveBoar902** [comment]
> @AbrasiveBoar902 thanks for the question. Asyn task cannot acquire semaphore at this moment. You will need to create tasks from taskflow to acquire semaphore. I will see what I can do to modify the async task interface.

Thank you very much! emm I think you don't need to devote much time working on this, sinceI have wrote one to do things like this these days. But it's highly depends on my project. Also, its apis and running logics are a great difference form taskflow's so it's hard to merge these things. I use multi "tags" to divide tasks since this is what I need in the project...

**Comment by AbrasiveBoar902** [comment]
[executor.txt](https://github.com/taskflow/taskflow/files/7520553/executor.txt)
this is the main body (since I think my codes are awful and it loses some depends)

**Comment by AbrasiveBoar902** [comment]
> [executor.txt](https://github.com/taskflow/taskflow/files/7520553/executor.txt) this is the main body (since I think my codes are awful and it loses some depends)

exactly, it's still can't use semaphore but it's what I need

**Comment by tsung-wei-huang** [comment]
Thanks for the question!
