### ISSUE TITLE
CUDA kernel grid/block parameters computed by previous task ?

### ISSUE THREAD

**Issue by touisteur** [taskflow/taskflow#357]
Using cudaflows, I'd like to be able to make the block/grid arguments of tf::cudaFlow::kernel() (e.g. at https://taskflow.github.io/taskflow/GPUTaskingcudaFlow.html) dependent on the result of preceding tasks.
Is there a way to do this?

**Comment by tsung-wei-huang** [comment]
Unfortunately, there is no way to do this because of the limitation of CUDA Graph. You must specify all parameters up front. Or you can simply use Taskflow as the tasking framework and wrap your own GPU operations into CPU tasks.
