### ISSUE TITLE
Taskflow and cuDNN

### ISSUE THREAD

**Issue by touisteur** [taskflow/taskflow#358]
Hi,

Is there anything to know before embarking on wrapping cudnn calls in taskflow? What's the recommended way to do this with cuda libraries? Is there any experience, example, tutorial that I'd have missed on this topic?

Thanks in advance and sorry if it's the wrong place to ask this kind of questions... Please let me know so I post the next questions in the correct place!

BR
Lionel

**Comment by tsung-wei-huang** [comment]
@touisteur no sorry at all :) The easiest way is to wrap your GPU tasks in one or more CPU tasks in a taskflow. This is a very common method to use taskflow for heterogeneous computing.
