### ISSUE TITLE
How to implement std::transform algorithm with tf::for_each ?

### ISSUE THREAD

**Issue by antonysigma** [taskflow/taskflow#360]
I recently encountered the following pattern needing parallelization in a multi-threaded environment. I wonder if `cpp-taskflow` provides a `tf::transform` feature?

```c++
struct KdTree {
  // Skipping implementations....
public:
  // Expensive operation.
  float findNNeighborDistance(const Point &);
} tree;
using Rank = std::uint8_t;
const std::multimap<Rank, Point> candidates;

auto task_a = tf::for_each(0, max_score, 1, [&](const auto rank) {
  // Important! Not a random access iterator.
  const auto [first, last] = candidates.equal_range(rank);
  std::vector<float> distances(std::distance(first, last));

  std::transform(first, last, distances.begin(),
                 [](const auto &x) { return tree.findNNeightborDistance(x); });
});
```

I am aware that `cpp-taskflow` can be mixed with OpenMP and `std::par` in C++17, but I am curious how I can emplace the above algorithm in the Taskflow provided scheduler? My goal is to avoid a mutex to block all other tasks whenever I run `task_a`.

There are what I tried but failed:

```c++
// Result failed the validation tests; `idx` appears randomized.
subflow.for_each(std::ref(first), std::ref(last),
                 [&, idx = size_t(0)](const auto &p) mutable {
                   distances[idx++] = tree.findNNeightborDistance(p);
                 });

// Result passed validation tests, but slower than std::transform because of 
// the non-random access of iterators.
subflow.for_each_index(0, std::distance(first, last), 1, [&](const size_t idx) {
  const auto &p = *(std::advance(first, idx));
  distance[idx] = tree.findNNeightborDistance(p);
});

// Result passed validation tests; benchmark shows ~5% improvement in compute time.
// But I was hoping to avoid explicit memory copy.
vector<Point> matched;
std::copy(first, last, matched.begin());

subflow.for_each_index(0, matched.size(), 1, [&](const size_t idx) {
  distance[idx] = tree.findNNeightborDistance(matched[idx]);
});
```

**Comment by antonysigma** [comment]
I also read somewhere in the Github issue about the "re-entering anonymous function" coding pattern, which seek to defeat the Taskflow scheduler to create a fixed number of "workers".

I am not sure if it will resolve my issue though... I will post the direct link here later today.

**Comment by tsung-wei-huang** [comment]
If I understand your idea correctly, you want to do nested loops. Currently, taskflow only does one-level parallel-for. In you case, you may consider partitioning your first level range, `[0, max_score, 1]`, manually by creating an even partition across the number of threads, followed by another parallel-for. It is like this:

```
auto chunk = max_score / num_threads;
for(int i=0; i<num_threads; i++) {
  taskflow.emplace([=](tf::Subflow& sf){
    auto beg = i*chunk;
    auto end = min((i+1)*chunk, max_score);
    sf.parallel_for(beg, end, ...) ;
  })
}
```

Does this solve your problem?

**Comment by antonysigma** [comment]
Sorry about the confusion with the nested parallel for. Here's the revised example code. I was wondering if I adjust the constant `concrrency_limit` in the code to `1`, how can I refactor the `std::transfrom` to some `subflow` code to run in parallel?

> manually by creating an even partition across the number of threads.

Acknowledged. I am thinking about the case then `concurrency_limit < n_threads`, or even worse, the two values are co-prime. How does one utilize Taskflow dynamic scheduling in such case?

```c++
for (auto rank = 0; rank < max_rank; rank++) {
  read_task[rank] = tf::emplace([&, rank]() {
    // Do something...
  });

  query_task[rank] = tf::emplace([&, rank]() {
    // Important! Not a random access iterator.
    const auto [first, last] = candidates.equal_range(score);

    std::transform(
        first, last, distances[rank].begin(),
        [](const auto &x) { return tree.findNNeightborDistance(x); });
  });

  write_task[rank] = tf::emplace([&, rank]() {
                       // Do something...
                     })

                         read_task[rank]
                             .precede(query_task[rank]);
  query_task[rank].precede(write_task[rank]);

  constexpr auto consurrency_limit = 3;
  if (rank > concurrency_limit) {
    query_task[rank].precede(query_task[rank - concurrency_limit]);
  }
}
```

**Comment by tsung-wei-huang** [comment]
Is your iterator random accessible?

**Comment by antonysigma** [comment]
No it isn't randomly accessible. In my case, the iterators came from a B-tree or Rd-tree list structure, e.g. `std::multimap`. The distance between `beg` and `end` is only known at runtime, so I can only describe the parallelism with dynamic scheduling in taskflow subflow. 

Update: I figured that I had my typo in the example code above. It is supposed to be `std::multimap` instead of `std::map`.

**Comment by tsung-wei-huang** [comment]
So, ideally, you need a parallel-transform that allows you to do the following:

```cpp
  query_task[rank] = tf::emplace([&, rank](tf::Subflow& sf) {
    // Important! Not a random access iterator.
    const auto [first, last] = candidates.equal_range(score);

    sf.transform(first, last, distances[rank].begin(), [](const auto &x) {
      return tree.findNNeightborDistance(x);
    });
  });
```

Right? I think I can try to add one function for this.

**Comment by antonysigma** [comment]
> Right? I think I can try to add one function for this.

Yes, it will be perfect. Will it make your job easier if I submit a mock test case for validation? It will be the same as the above pseudo-code, except that `return tree.findNNeighborDistance(x.second)` will be replaced with a generic one, e.g. `return x.second;`.

**Comment by tsung-wei-huang** [comment]
@antonysigma it's on the master branch. The syntax is the same as the `std::transform`. 

```cpp
sf.transform(first, last, distances[rank].begin(), [](const auto &x) {
    return tree.findNNeightborDistance(x);
});
```

There is also a version that takes two input range and a binary transformation operator. You are welcome to add any tests to the end of `unittests/algorithm.cpp`

**Comment by antonysigma** [comment]
Thank you. Please see my draft pull request at: https://github.com/taskflow/taskflow/pull/362

I am yet to include one more test case, that is to verify the `subflow.transform` behavior. But this should do for now.

**Comment by tsung-wei-huang** [comment]
@antonysigma thanks! Let me know if you need any help with your project.
