### ISSUE TITLE
Stopping a subflow

### ISSUE THREAD

**Issue by aawalimb** [taskflow/taskflow#361]
We have multiple subflows created in our implementation and they run in the order the user has defined. If any exception occurs in any of the tasks in a subflow, we want to stop only that subflow and continue with the others. Is there any way of stopping just the running subflow and abort the next tasks belonging to it? Since subflows might be running in sequence or in parallel as per the defined order, we do not want to start them with the async api. Is there any other way of aborting just the running subflow?

**Comment by tsung-wei-huang** [comment]
Currently, we only allow canceling taskflow as a unit. Are you creating nested subflows? If not, is it possible to create a taskflow for each subflow so it can be cancelled on a per-subflow basis?

**Comment by aawalimb** [comment]
Thank you. Appreciate your quick response.
Our subflows are also arranged in a graphical manner and we can achieve the ordering of the subflows with precede and succeed apis as they return the tf::Task handle. (Each subflow has another internal graph of tasks. So we have two levels of graphs being executed) If we convert the subflows in taskflows, I am not sure how we can arrange the taskflows in a graphical manner for execution. I couldn't find any example in the cookbook. Do you have any example that you can share?

**Comment by tsung-wei-huang** [comment]
I see. If you have a nested subgraph then my idea didn't work. Now, another question emerges. Since you have a nested structure of subflows, does your canceling apply hierarchically as well? For example, subflow `A` spawns another child subflow `B`, canceling `A` will cancel `B` as well. On the other hand, canceling `B` doesn't imply canceling `A`. Is this your objective?

**Comment by gmclay** [comment]
Hierarchical cancelling makes sense to me. Similar to how a child process can be killed if the parent process is killed. This would be a nice enhancement to have.

**Comment by flemingpatel** [comment]
I have recently begun experimenting with the code. I have observed that in a context where an exception arises within the task, both Taskflow and Subflow display similar behavior; they appear to wait indefinitely.

Not sure if I understood the ask correctly - It is also worth noting that the conditional task appears to be functional under these circumstances (by returning true under catch block if an exception occurs).

**Comment by tsung-wei-huang** [comment]
@tsung-wei-huang currently, Taskflow does not handle exception but leave it to the application. You will need to catch the exception in your task.

**Comment by tsung-wei-huang** [comment]
This has been supported in the current master branch and will be part of 3.7.0. Basically, when an exception is thrown from a task, unless caught by the application, it will get propagated to its parent and cancel the current topology.
