### ISSUE TITLE
Heap Corruption when unloading a DLL using Taskflow (dtor of ObjectPool) 

### ISSUE THREAD

**Issue by dasmig** [taskflow/taskflow#363]
**Description**
We are using the latest release of the library. Our use case of task flow is pretty simple. 

We have an executor which runs a few *taskflows*, one at a time. Each taskflow contains between hundreds and thousands of tasks.  The tasks don't outlive the taskflow, we are not sure if this is required. But the taskflow outlives the executor while being executed. No issues occur during the execution. The exception doesn't always trigger, although it triggers more often when there are more tasks created during the execution.

When the program finishes and the dll is unloaded, the destructor of ObjectPool triggers an exception:
```
0xC0000005
The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
```
[It is triggered during the iteration on the object pool nodes:](https://github.com/taskflow/taskflow/blob/9e1f08d4e42d2397215e8a0cf0655b6ab7c0d69d/taskflow/utility/object_pool.hpp#L550)
``` cpp
// Procedure: _for_each_block_safe
// Iterate each item of a list - safe to free
template <typename T, size_t S>
template <typename C>
void ObjectPool<T, S>::_for_each_block_safe(Blocklist* head, C&& c) {
  Blocklist* p;
  Blocklist* t;
  for(p=head->next, t=p->next; p!=head; p=t, t=p->next) {
    c(_block_of(p));
  }
}
```

I can't provide you the minidump file nor our application, although if necessary we can schedule a debug session. We could also try to reproduce our usage using a prototype but it would take considerably longer.

**System**
 - Windows 10
 - Built using vs17
 - Latest release of taskflow (v3.2.0)

**Comment by tsung-wei-huang** [comment]
What do you mean by "outlive"?

**Comment by dasmig** [comment]
> What do you mean by "outlive"?

The *task* object returned when using the *emplace* into the *taskflow* goes out of scope before the *taskflow* object does.

**Comment by tsung-wei-huang** [comment]
`tf::Task` is just a wrapper over a pointer to a graph node. It doesn't own the lifetime of a task. Only taskflow owns the lifetimes of tasks. Do you have a code snippet that can show me your usecase? Will be even better if the code can reproduce your problem.

**Comment by dasmig** [comment]
> `tf::Task` is just a wrapper over a pointer to a graph node. It doesn't own the lifetime of a task. Only taskflow owns the lifetimes of tasks. Do you have a code snippet that can show me your usecase? Will be even better if the code can reproduce your problem.

Well, then we are using `tf::task` correctly :). I will try to write a code snippet with our use case and post later today. I'll also try testing it on my end and let you know if I can reproduce the issue.

**Comment by tsung-wei-huang** [comment]
Yes, will be helpful to see a code snippet.

**Comment by tsung-wei-huang** [comment]
BTW, you may try calling `executor.wait_for_all` before you leave the program to ensure all outstanding tasks/taskflows finish.

**Comment by dasmig** [comment]
We do call wait_for_all before leaving. I had a problem with my workstation, it will take a little longer to provide the code snippet.

**Comment by tsung-wei-huang** [comment]
will close this issue first - feel free to reopen it if the problem still exists.
