### ISSUE TITLE
Is it time to release 3.3?

### ISSUE THREAD

**Issue by pancpp** [taskflow/taskflow#364]
It has been almost 5 months since last release. Is it the time to launch a new release? I really need the `FlowBuilder::erase` method in my project. Or, is it safe to use the master branch in production? Thank you!

**Comment by tsung-wei-huang** [comment]
@pancpp thanks for your comment. Yes, we are about to release v3.3 which will have significant improvements and several new features (e.g., pipeline scheduling). Currently, we are at the stage of wrapping up documents and are aiming for Chrismas to release v3.3.

At this stage, it is safe to use the master branch in production. The master branch contains pretty much everything v3.3 will have except documentation.

**Comment by pancpp** [comment]
@tsung-wei-huang thank you so much for your information and really appreciate your contributions!

**Comment by tsung-wei-huang** [comment]
@pancpp v3.3 has been released.
