### ISSUE TITLE
Could I get a call back from all work threads after work thread created?

### ISSUE THREAD

**Issue by vkensou** [taskflow/taskflow#366]
Could I get a call back from all work threads after work thread created?
I need set taskExecutor->this_worker_id() to every thread_local variable. So i could get thread_id from everywhere.

**Comment by tsung-wei-huang** [comment]
This may require a modification to the executor's constructor by passing custom thread creation lambda/methods. Any idea how to define such an interface that could be useful for your application?

**Comment by vkensou** [comment]
> This may require a modification to the executor's constructor by passing custom thread creation lambda/methods. Any idea how to define such an interface that could be useful for your application?

I make a lambda to wrap executor->this_worker_id() call, code like: [this](){executor->this_worker_id}. Then I can call it anywhere.
