### ISSUE TITLE
can I use a stable version base on c++14

### ISSUE THREAD

**Issue by TonyBarber** [taskflow/taskflow#367]
hello，

for some reasons,our product cant support c++17,so i want to use v2.x version to match c++14

any supports to which specific version? any known bugs or problems in v2.x version？

**Comment by TonyBarber** [comment]
thanks

**Comment by tsung-wei-huang** [comment]
Hi @TonyBarber the latest version that supports c++14 is [v2.7](https://github.com/taskflow/taskflow/releases/tag/v2.7.0). However, I would highly recommend using the newest version if possible, as C++17 has introduced a significant improvement over the core language features and standard support.
