### ISSUE TITLE
Pass parameters to the task

### ISSUE THREAD

**Issue by Black-YJ** [taskflow/taskflow#368]
Hi, thanks for sharing this great topic, but I still have some questions wondering how can I use it. Sorry for this help request, hope it's ok to post here.

I want to use the taskflow in the following scenario:

![image](https://user-images.githubusercontent.com/73266959/148166549-bfae33b0-7e77-4d29-b2ad-443b79a9eb0f.png)

- Each thread execute the "same" flow to complete the work
- So in each thread, I need to pass the independent data (maybe a buffer) to complete multiple works and get the results.  

I think there are some similar issues like [#148](https://github.com/taskflow/taskflow/issues/148), and [#135](https://github.com/taskflow/taskflow/issues/335) but I still have a question:  
- So far I know there is a method to attach user data to the function, but I think the data may be modified by another thread. This may cause the final result to be wrong. So I want to pass a global parameter (void*) to every function, then every function can process the buffer independently, is it possible?

Any advice would be appreciated! Thanks.

**Comment by tsung-wei-huang** [comment]
I assume you are talking about data-parallel tasking. We have a new [tf::Pipeline](https://taskflow.github.io/taskflow/ParallelPipeline.html) that allows you to create a pipeline scheduling framework to overlap tasks in time. 

Would this be a fit for your application?

**Comment by Black-YJ** [comment]
As far as I know about the tf::Pipeline, it needs to specify a specific number of pipelines at the beginning. Then when the build taskflow is executed, all pipelines will start. Is that correct?  If so, it may not fit my scenario.

My scenario is that at every time interval I will create a new thread and give taskflow an execution request. So what I think is that the build taskflow of each thread is the same (only one taskflow), the difference is just the passed data in it is different.

Maybe I can do it in a similar way to [#301](https://github.com/taskflow/taskflow/issues/301). But what I think is whether there is a similar way to the following code that can pass data during execution, and every taskflow can get a common local variable(pLocalData) every time it is executed.

``` c++
tf::Executor executor;
auto task = executor.run(*TestFlow, (void*)pLocalData);
```

**Comment by tsung-wei-huang** [comment]
@Black-YJ Yes, you need to specify all pipes in the pipeline at the beginning. 

If you just want to pass the data at the beginning of running a taskflow, you may consider the following:

```cpp
#include <taskflow/taskflow.hpp>

int main(){

  tf::Executor executor;
  tf::Taskflow taskflow("attach data");
  
  int data;
  
  // create a task and attach it the data
  auto A = taskflow.placeholder();
  A.data(&data).work([A](){
    auto d = *static_cast<int*>(A.data());
    std::cout << "data is " << d << std::endl;
  }); 
  
  // run the taskflow iteratively with changing data
  for(data = 0; data<10; data++){
    executor.run(taskflow).wait();
  }

  return 0;
}
```

**Comment by tsung-wei-huang** [comment]
@Black-YJ close first - feel free to reopen if the above answers haven't solved your problem.
