### ISSUE TITLE
how to use taskflow for data streaming?

### ISSUE THREAD

**Issue by Thanh-Binh** [taskflow/taskflow#370]
Dear all,
at a time instance, we have to get sensor data and want to process them parallely like your "simple.cpp":
taskA --> taskB -> taskD
          --> taskC -> 

here taskA is executed by sensor and generates continuous data
Normally, I do it (without parallelizing) like
while(1)
{
   wait_for_sensor_data and if receive, input them into taskA
   run taskA
   run taskB
   run taskC
   run taskD
}

I think I should do it like belows but not sure if it is correct?
// solution 1:
tf::Executor executor;
while(1)
{
   wait_for_sensor_data and if receive, input them into taskA
   tf::Taskflow taskflow;
   tf::Task A = taskflow.emplace([](){}).name("A");  
   tf::Task C = taskflow.emplace([](){}).name("C");  
   tf::Task D = taskflow.emplace([](){}).name("D"); 
  A.precede(B, C);  // A runs before B and C
  D.succeed(B, C);  // D runs after  B and C
                                      
  executor.run(taskflow).wait();
}

// solution 2: Does it work??????????????
tf::Executor executor;
tf::Taskflow taskflow;
tf::Task A = taskflow.emplace([](){}).name("A");  
tf::Task C = taskflow.emplace([](){}).name("C");  
tf::Task D = taskflow.emplace([](){}).name("D"); 
A.precede(B, C);  // A runs before B and C
D.succeed(B, C);  // D runs after  B and C
while(1)
{
   wait_for_sensor_data and if receive
   input them into taskA           // I really do not know how can I input data into taskA. Using pointer to data????                           
  executor.run(taskflow).wait();
}

Could you please help me?
Thanks

**Comment by tsung-wei-huang** [comment]
@Thanh-Binh Your solution 2 is better as it can reuse the same taskflow graph structure.

Also, if you want to enable task overlap in time with data stream, you can consider using our new [pipeline feature](https://taskflow.github.io/taskflow/ParallelPipeline.html). There is another [example](https://taskflow.github.io/taskflow/TextProcessingPipeline.html) on how to use `tf::Pipeline` for text filter.

**Comment by Thanh-Binh** [comment]
@tsung-wei-huang 
Thanks for your info, but how can I input data into taskA?

if I use Pipeline, how can I run it endless?
It is better for me if you help me to write a short code for solution 2?
Best thanks

**Comment by tsung-wei-huang** [comment]
@Thanh-Binh In your solution 2, you can use `tf::Task::data(void*)` to attach data to your task. See an example [here](https://taskflow.github.io/taskflow/StaticTasking.html#AttachUserDataToATask). I believe in your case, solution 2 is the best since your task graph is not linear.

If you want to use the pipeline, you need to find a topological order of your graph first, i.e., `A->B->C->D`, and then create a `tf::Pipeline` of 4 serial pipes:

```cpp
tf::Pipeline pl( num_lines, /* tunable parameter, you can use std::thread::hardware_concurrency() */
  tf::Pipe{tf::PipeType::SERIAL, [](tf::Pipeflow& pf){
    ...
  }},
  tf::Pipe{tf::PipeType::SERIAL, [](tf::Pipeflow& pf){
    ...
  }},
  tf::Pipe{tf::PipeType::SERIAL, [](tf::Pipeflow& pf){
    ...
  }},
  tf::Pipe{tf::PipeType::SERIAL, [](tf::Pipeflow& pf){
    ...
  }}
);

taskflow.compose_of(pl);
executor.run(taskflow).wait();
``` 

Keep in mind, we don't do data abstraction, so it's totally your responsibility to manage data. (this is an advantage for many task-parallel pipeline applications where user wants to manage the data on their own wish).

If you want to create a pipeline that runs endless, you can add a condition task after the pipeline task to detect whether you need to go back to run the pipeline again. See the [example](https://taskflow.github.io/taskflow/ParallelPipeline.html#IterateAPipeline).

**Comment by tsung-wei-huang** [comment]
@Thanh-Binh another small example to demonstrate how to attach data to a task and run it iteratively with changing data:

```cpp
#include <taskflow/taskflow.hpp>

int main(){

  tf::Executor executor;
  tf::Taskflow taskflow("attach data");
  
  int data;
  
  // create a task and attach it the data
  auto A = taskflow.placeholder();
  A.data(&data).work([A](){
    auto d = *static_cast<int*>(A.data());
    std::cout << "data is " << d << std::endl;
  }); 
  
  // run the taskflow iteratively with changing data
  for(data = 0; data<10; data++){
    executor.run(taskflow).wait();
  }

  return 0;
}
```

Output:

```bash
data is 0
data is 1
data is 2
data is 3
data is 4
data is 5
data is 6
data is 7
data is 8
data is 9
```

**Comment by Thanh-Binh** [comment]
@tsung-wei-huang 
Thanks for your example.

If I understood you well, there are 2 ways for inputing external data into taskflow:
1. using pipeline
2. or A.data(...)

Can pipeline access data from Task A?

**Comment by tsung-wei-huang** [comment]
Yes, your understanding is correct. In pipeline, you will need to define your own data buffer to manage data. The task inside pipeline is invisible.

**Comment by Thanh-Binh** [comment]
@tsung-wei-huang best thanks
