### ISSUE TITLE
Failure to build unit-tests with gcc 11.2.1 (use of non-constexpr system call in doctest dependency)

### ISSUE THREAD

**Issue by RalphSteinhagen** [taskflow/taskflow#372]
**Describe the bug**
```
[ 63%] Building CXX object unittests/CMakeFiles/utility.dir/utility.cpp.o
cd /home/steinhagen/git/taskflow/build/unittests && /usr/bin/c++  -I/home/steinhagen/git/taskflow -I/home/steinhagen/git/taskflow/3rd-party/doctest -O3 -DNDEBUG -Wall -Wextra -Wfatal-errors -MD -MT unittests/CMakeFiles/utility.dir/utility.cpp.o -MF CMakeFiles/utility.dir/utility.cpp.o.d -o CMakeFiles/utility.dir/utility.cpp.o -c /home/steinhagen/git/taskflow/unittests/utility.cpp
In file included from /home/steinhagen/git/taskflow/unittests/utility.cpp:3:
/home/steinhagen/git/taskflow/3rd-party/doctest/doctest.h:4032:47: error: size of array ‘altStackMem’ is not an integral constant-expression
 4032 |         static char             altStackMem[4 * SIGSTKSZ];
      |                                               ^
compilation terminated due to -Wfatal-errors.
```
Not a bug in the taskFlow library itself but in one of its unit-test dependencies: doctest. 

The compiler assessment seems to be correct though since `SIGSTKSZ` resolves into a non-`constexp` system call defined through a macro `# define SIGSTKSZ sysconf (_SC_SIGSTKSZ)` and evaluated during run-time. See also fixed [doctest issue](https://github.com/doctest/doctest/issues/473) and (here)[https://github.com/doctest/doctest/blob/a384864346f48c7ff5608051c176e7bd505712ae/CHANGELOG.md#L93].

As a possible workaround: bump the doctest dependency to the latest?

**To Reproduce**
tested on the main git branch [ac1a3f8f] with plain `cmake .. & make` in `build` directory

**Desktop:**
 - OS: Linux (OpenSUSE Tumbleweed)
 - gcc: 11.2.1 20211124
 - nvcc: release 11.5, V11.5.119
 - cmake version 3.22.1

Any help would be much appreciated and keep up the good work! :+1:

**Comment by tsung-wei-huang** [comment]
@RalphSteinhagen Thanks. I have just updated the master with the newest doctest version.

**Comment by dotlambda** [comment]
Is it possible not to use the vendored doctest?
