### ISSUE TITLE
cudaflow error : cuda_meta.hpp conflicts with c++ 17 on windows 10

### ISSUE THREAD

**Issue by hjxy2012** [taskflow/taskflow#373]
My programming environment is as follows:
Windows 10 home 
Visual Studio 2019
CUDA 11.5
Taskflow v3.3.0

The errors when compiles cuda_transform.cu as follows since **std::binary_function** has been removed by c++17.

![image](https://user-images.githubusercontent.com/6129913/148626533-c286b37c-b712-405e-af13-bd970f8ec98f.png)

So I just modified cuda_meta.hpp as follows and it compiles.

![image](https://user-images.githubusercontent.com/6129913/148626600-7494f2a0-bc15-45f8-be40-68a3a0ae6a6a.png)

And my nvcc command is like this.

`nvcc --compiler-bindir  "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/" -std=c++17 "D:/OpenSourceCodes/C++/TaskFlow/Src/taskflow/examples/cuda/cuda_transform.cu" -I "D:/OpenSourceCodes/C++/TaskFlow/Src/taskflow/" --extended-lambda  -o "D:/OpenSourceCodes/C++/TaskFlow/Src/taskflow/examples/cuda/cuda_transform.exe"`

Hopes it will help someone using cudaflow.

**Comment by tsung-wei-huang** [comment]
@hjxy2012 Thanks for the notice! Would you be interested in creating a PR to fix this issue?

**Comment by tsung-wei-huang** [comment]
Fixed in #374
