### ISSUE TITLE
Non-global ObjectPool for control over memory footprint

### ISSUE THREAD

**Issue by sunbubble** [taskflow/taskflow#378]
My understanding of the internals of taskflow is quite limited. So pardon if this is a dumb question.

I'm using taskflow as an asynchronous simulation engine. I'm only using static tasks, although quite a lot of them.

I have a struct more or less like this:
```C++
struct TaskflowContext {
    tf::Executor executor;
    tf::Taskflow taskflow;
    tf::Future future;
};
```
(Maybe this is irrelevant for this question but I use the future to be able to cancel the running simulation.)

What happens is that once the taskflow finishes executing for a large task graph. I notice that there is still a substantial amount of memory that isn't released.
I implemented a shrink function that reassigns the `tf::Taskflow` after completion, and that frees some memory, but only around 10% of the total usage.

I also tried destroying and restarting the executor (by wrapping it in a `std::optional<tf::Executor>`) but that didn't work either.

Which led me find the `tf::ObjectPool<Node> node_pool;`. Is this the thing I'm looking for? Is this a global object and if so can it be cleared safely at some point in time?

Or alternatively, make it possible to pass in your own `node_pool` reference to the `tf::Executor` and `tf::Taskflow` constructors? This way the user could have control over the entire memory footprint of the taskflow context.

**Comment by tsung-wei-huang** [comment]
Hi @sunbubble , I would say it's not memory leak but the retention/reuse of the memory due to our object pool. Taskflow has a global object allocator to create, release, and recycle tasks. Creating a task from scratch has certain overhead and the purpose of the allocator is to minimize it.

**Comment by sunbubble** [comment]
Thanks for your input.
I looked more through the code and I now understand. It's not a leak because the pool will recycle its memory.

For my use case it can still be a problem. I have a non-trivial program that only in some Workflows just perform expensive operations expedited by taskflow. But the fact that this object pool is global, other parts of the program cannot reuse this memory once the taskflow context terminates and is destroyed.

So my question, maybe in the form of a feature request. Would it be possible to optionally pass in a reference to my own managed object pool, that I could destroy once I'm sure the executor has finished all its work?

Alternatively, or maybe additionally would be giving the ObjectPool class a shrink_to_fit() member function and possibly a reserve(...) as well. Like [std::vector](https://en.cppreference.com/w/cpp/container/vector/shrink_to_fit)

**Comment by sunbubble** [comment]
I changed the issue title since I now better understand the situation

**Comment by tsung-wei-huang** [comment]
@tsung-wei-huang I will see how this can be done. Just curious, what is the memory usage of your program?

**Comment by bradphelan** [comment]
> The problem though is that since the program can stay running for an arbitrary amount of time doing other jobs that are not simulation (i.e. taskflow), it can be painful for the user to have to deal with the fact that the taskflow object pool is holding 80% of the system RAM while not doing anything active. So I would like to have the option to free the memory when the simulation engine is idle and that is not currently possible.

Just a suggestion. Perhaps break the simulation engine out into a separate process independent of the interactivity side. Then when you don't need it simply kill the process.

**Comment by sunbubble** [comment]
> Just a suggestion. Perhaps break the simulation engine out into a separate process independent of the interactivity side. Then when you don't need it simply kill the process.

This unfortunately quite awkward, because the simulation itself is interactive and reactive to user input.

**Comment by tsung-wei-huang** [comment]
The global object pool has been removed (though user can explicitly turn it on through compile-time macro `TF_ENABLE_TASK_POOL`).
