### ISSUE TITLE
i want to know the diff between [static tasking] and [dynamic tasking] in readme 

### ISSUE THREAD

**Issue by ChunelFeng** [taskflow/taskflow#380]
![image](https://user-images.githubusercontent.com/37905059/152120488-ad16307f-8a2f-4b71-9b61-17605106bfc8.png)

please let me know, or give me a tutorial, thanks.

**Comment by tsung-wei-huang** [comment]
The cookbook [here](https://taskflow.github.io/taskflow/pages.html) has a tutorial.
