### ISSUE TITLE
How to get to know the name of the task that is being scheduled.

### ISSUE THREAD

**Issue by Bhavin-MatreComm** [taskflow/taskflow#381]
I am creating an array of tasks, as shown in the following sample code:

#include <taskflow/taskflow.hpp>
int main()
{

for(i=0;i<2;i++)
{
A[i] = taskflow.emplace([](){cout<<"Hello "<<endl;}).name(graphOne["nodes"][i]["id"]);    // graphOne is a JSON object
}

A[1].precede(A[0]);
A[0].succeed(A[1]);
executor.run(taskflow).wait();

}

I want to print the name of the task whenever the task gets scheduled, How do I do this?

I am not able to access any of the variables in the program as well. 

Or suggest any way by which I can print a unique message for every task, when it gets scheduled.

Any advice is appreciated, Thank You!

**Comment by tsung-wei-huang** [comment]
How about this:

```cpp
tf::Task t = taskflow.placeholder();  // create a task of no work
t.work([t](){  // assign the work and capture the task
  std::court << t.name() << std::endl;
});
t.name("hi");
executor.run(taskflow).wait();  // see "hi" printed
```

**Comment by Bhavin-MatreComm** [comment]
@tsung-wei-huang  Nope, that doesn't work. Adapting your code to my situation looks like this:

//code snippet starts

tf::Task t[sample_json.size()];

for(i=0; i<sample_json.size();i++)
{
t[i] = taskflow.placeholder();
t[i].work([t](){
    std::cout<<t[i].name()<<std::endl;    // PROBLEM: ' i ' cannot be accessed inside this curly braces
});
t[i].name(sample_json[i]);
}

executor.run(taskflow).wait();

//code snippet ends



I will not be able to print the name of the task that will get scheduled, because of the problem shown above.

**Comment by tsung-wei-huang** [comment]
You mean this?

```cpp
t[i].work([task=t[i]](){
  std::cout << task.name() << '\n';
});
```

**Comment by Bhavin-MatreComm** [comment]
Yes! Thanks for the help!!
