### ISSUE TITLE
Is there any strategy to send messages from Asynchronous Tasks to master thread? 

### ISSUE THREAD

**Issue by jeffreykuang** [taskflow/taskflow#384]
**Please describe your feature request.**
I have  a  asynchronous task which can output some information such as progress,  performance metrics or warning information during running. Is there any method to send messages form the task to the the master thread?

**Comment by tsung-wei-huang** [comment]
Taskflow does not do data abstraction or message passing between threads, but task scheduling. In your case, you will need to manage the message passing and data yourself.
