### ISSUE TITLE
tf::Executor shutdown method

### ISSUE THREAD

**Issue by boxerab** [taskflow/taskflow#385]
I am using `taskflow` in my codec project through a "Meyers" singleton " :

```
static tf::Executor* instance(uint32_t numthreads)
{
    static tf::Executor singleton(numthreads ? numthreads : std::thread::hardware_concurrency());

    return &singleton;
}
```

This works fine on Linux, but I get crashes on exit in windows - I am assuming that  runtime destruction of static objects
is broken. 

It would help me if I could call shutdown on the executor, which would do exactly what the destructor is currently doing.

```
void Executor::shutdown() {
 if (_done)
   return;  

  // wait for all topologies to complete
  wait_for_all();
  
  // shut down the scheduler
  _done = true;

  _notifier.notify(true);
  
  for(auto& t : _threads){
    t.join();
  } 
}
```

Of course this could only be used as the final call on the executor.

**Comment by tsung-wei-huang** [comment]
@boxerab sorry for the late response! I am actually very curious why that error exists. I suspect it's due to the static object destruction order. Do you have any object that may access the taskflow at the program's exist time? Ideally, you should ensure no taskflows are running when the executor is being destructed.

**Comment by boxerab** [comment]
@tsung-wei-huang thanks,  I just re-tested on windows with the static singleton, and it does work. 
Not quite sure what changed - I did upgrade the compiler to VS 2022. Anyways, I'm happy to use the static singleton design
cross-platform, and now there's no need for any changes. Closing.

**Comment by boxerab** [comment]
@tsung-wei-huang I'm afraid this bug is still here.  I get intermittent failures due to timeout on my test suite when
running the tests in my Github Actions.

https://github.com/GrokImageCompression/grok/actions/runs/2025895068
https://github.com/GrokImageCompression/grok/runs/5653895303?check_suite_focus=true

This may be hard to debug :) 
In the mean time, I am rolling back my changes on my master branch, but I will put the failing code on a separate branch, in case you would like to investigate.

**Comment by tsung-wei-huang** [comment]
Is it possible to create a small example of your workload that can reproduce this error?

**Comment by boxerab** [comment]
@tsung-wei-huang thanks - my CI has around 2200 unit tests, and one of those tests will intermittently time out.
I remember now that I had the same problem on windows with my simple thread pool, so I don't think this is a `taskflow` bug, but rather just crappy windows runtime. 

I've made a small [local patch](https://github.com/GrokImageCompression/grok/commit/7a8c9a72a1fa530b21aeeee5538bae68fee0b312) to add shutdown and it works great.

**Comment by tsung-wei-huang** [comment]
@boxerab very likely to be the bug of windows runtime when you use a static object / method for executor. I wonder why separating a shutdown method makes the problem go away...

**Comment by boxerab** [comment]
Well, when I use a shutdown method, I call it just before my main method exits, before the runtime takes over and starts managing object destruction. Otherwise, the object is destroyed by the runtime itself. My feeling is that the thread joining
causes some race condition, and the program hangs. I'm happy to just keep a local patch, as the change is so simple, but I think other users are also going to encounter this issue.

**Comment by boxerab** [comment]
@tsung-wei-huang it looks like the timeout issue isn't related to static object destruction, or at least isn't fixed by calling "shutdown" before exit of main. I've had to simply disable my windows CI tests until I can understand what's going on. Closing this for the moment.
