### ISSUE TITLE
Shared future equivalent to tf::Future

### ISSUE THREAD

**Issue by Levi-Armstrong** [taskflow/taskflow#387]
The following seems to work but you loose the ability to cancel the task. Do you see any issue with doing this and is there an std::shared_future equivalent for tf::Future where you can cancel? 

``` c++
std::shared_future<std::optional<int>> future = executor.async([](){ 
  std::cout << "async task returns 1\n";
  return 1;
});

**Comment by tsung-wei-huang** [comment]
In order to support cancel, we have derive a `tf::Future` from `std::future`. So in your case, you should instead write:

```
tf::Future < std::optional<int> > fu = executor.async([](){ 
  std::cout << "async task returns 1\n";
  return 1; 
});

auto sfu = fu.share();

// cancel the task if you want
fu.cancel();
```

**Comment by Levi-Armstrong** [comment]
Thanks for the info. One more question after `auto sfu = fu.share();` are there issues if `fu` goes out of scope?

**Comment by tsung-wei-huang** [comment]
No - it actually is just a derived interface from [std::future](https://en.cppreference.com/w/cpp/thread/future/share). As long as the reference count is not zero, the state remains valid.

**Comment by Levi-Armstrong** [comment]
Thank you for the quick response.
