### ISSUE TITLE
[Question]-Task timeout

### ISSUE THREAD

**Issue by mohsenomidi** [taskflow/taskflow#389]
Thanks for your great library 

I want to know is there any way to detect a timeout from the running task? 

For example you have taskflow with some routine (sub flow) when the application receiving the message, it sends it to taskflow for execution, and each tasks has some timeout for execute the request, if the execution takes time we need to mark it as a timeout and send timeout reply to requester and terminate the running task

How can we detect the timeout for each task from main process?

**Comment by tsung-wei-huang** [comment]
Currently, we don't do timeout. But you may implement your own detection mechanism, like creating a monitor task with a condition task.

**Comment by mohsenomidi** [comment]
The conditional loop is not the good way to detect the timeout, it will be cpu consuming task and also effects on performance and it is blocking operation.
For high performance operations for example processing 10K transactions per second, I can't use the loop, the recommended way is something like this:

`
#include <thread>
#include <future>
...
// Launch the thread.
std::thread thread(ThreadFnc, ...);
...
// Terminate the thread.
auto future = std::async(std::launch::async, &std::thread::join, &thread);
if (future.wait_for(std::chrono::seconds(5)) 
    == std::future_status::timeout) {

  /* --- Do something, if thread has not terminated within 5 s. --- */

}
`

Or using the conditional variable, this way is also has bad effect on performance

If there is the good way in library that implements the timeout it will be very useful for such scenarios, I think many apps will use this feature if exist

**Comment by mohsenomidi** [comment]
Kindly want to know is there any chance to have this feature

**Comment by jparsert** [comment]
I would also be interested in this feature. Any progress?

**Comment by yshahedi** [comment]
Dear @tsung-wei-huang 

Thanks for your library, I am wondering to know about this feature, is there any plan to implement the timeout ?

**Comment by mohsenomidi** [comment]
Dear @tsung-wei-huang 

Is there any plans to have this feature?

**Comment by willstudy** [comment]
@tsung-wei-huang Is there any plans to have this feature?

**Comment by tsung-wei-huang** [comment]
@willstudy currently, we do not plan to have this feature as it is different from the design of task-parallel system. We believe it's more suitable for event-driven system.
