### ISSUE TITLE
Unit test 'Test #341: ParallelTraversal.5' failed

### ISSUE THREAD

**Issue by 2010YOUY01** [taskflow/taskflow#392]
Hi, I tried to run the unit tests on my machine and 1 of them failed.

**Describe the bug**
For the current master branch code, If I run the unit test several times, roughly half of the runs will fail on one of 'ParallelTraversal.*'

**To Reproduce**
Run the unit tests according to the doc.

**Screenshots**
<img width="820" alt="image" src="https://user-images.githubusercontent.com/23360377/160954881-c3e69560-5c50-445c-af1c-d63e7576c86a.png">

<img width="603" alt="Screen Shot 2022-03-30 at 5 26 49 PM" src="https://user-images.githubusercontent.com/23360377/160954838-58ea84ee-8ae9-48df-81af-253d2ff7c7f0.png">

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
The error happened in 1 worker thread [inside this function](https://github.com/taskflow/taskflow/blob/891fe4d251147766de4e0b3a93c09e8e8981f0a1/unittests/traversals.cpp#L272)
If I modified the size of DAG [here](https://github.com/taskflow/taskflow/blob/891fe4d251147766de4e0b3a93c09e8e8981f0a1/unittests/traversals.cpp#L259) to 500 nodes, then that unit test will always pass on my machine; If the size of DAG changed to 1500 nodes, it will always fail.
So I guess this is caused by the calling stack of a thread exceeding maximum size? The thread stack size limit on MacOS seems to be 512 KB, which is smaller than the 8MB size on Linux.
The full stack trace from the debugger of the failing thread is attached.
[stacktrace.zip](https://github.com/taskflow/taskflow/files/8385173/stacktrace.zip)

**Comment by tsung-wei-huang** [comment]
@2010YOUY01 Yes, this is indeed related to your system. The `ParallelTraversal ` calls recursive parallelism which may be too deep in your machine. I would say, it's not an error, but you can totally ignore it.
