### ISSUE TITLE
Question: how to create N subflows using placeholders

### ISSUE THREAD

**Issue by boxerab** [taskflow/taskflow#393]
I have a list of tasks that I want to break up into `Subflows`. The number of `Subflows` is only known at runtime.
Below is the code I currently use to schedule all of the tasks (simplified for demonstration purposes). 
I would like to segregate the tasks into N subflows, and manage dependencies between the subflows. 
Each `resTaskArray` would go into a `Subflow`.

Currently, I don't see any sample code on how to do this. Any guidance would be very much appreciated !

```
const size_t N;
size_t blocksPerResolution[N];
tf::Taskflow taskflow;
auto resTasks = new tf::Task*[N];
for(size_t i = 0; i < N; ++i){
  auto resTaskArray = new tf::Task[blocksPerResolution[i]];
  for (size_t blockno = 0; blockno < blocksPerResolution[i]; ++blockno)
	  resTaskArray[blockno] =  taskflow.placeholder();
  resTasks[i] = resTaskArray;
}
```

**Comment by tsung-wei-huang** [comment]
If this is the case, then I typically do composition - instead of creating `N` subflows, we can do `N` taskflows and compose sub execution from them:

```
for(size_t i = 0; i < N; ++i){
  auto resTaskArray = new tf::Task[blocksPerResolution[i]];
  for (size_t blockno = 0; blockno < blocksPerResolution[i]; ++blockno)
	  resTaskArray[blockno] =  taskflow.placeholder();
  resTasks[I].composed_of(resTaskArray);
}
```

Keep in mind, `composed_of(target_taskflow)` only maintains a soft mapping (e.g., pointer) to `target_taskflow`. And you should ensure `target_taskflow` remains alive during its execution.

Details about composition can be found [here](https://taskflow.github.io/taskflow/ComposableTasking.html).

Please let me know if this works for your workload.

**Comment by boxerab** [comment]
@tsung-wei-huang fantastic ! I got it working, and one of my performance tests is now 5-10% faster.
thank you !

**Comment by tsung-wei-huang** [comment]
No problem! @boxerab

**Comment by boxerab** [comment]
By the way, I use this simple class to manage the components of a composition. It's been very handy for my workflow,
where I have N collections of undirected tasks, but each collection must follow a certain order relative to the other collections.
If you have a place for utility classes outside of the taskflow core, this might be good to have in it.

```
struct FlowComponent
{
	FlowComponent(void) = default;
	~FlowComponent(void) = default;
	FlowComponent* addTo(tf::Taskflow& composition)
	{
		composedFlowTask_ = composition.composed_of(flow_);
		return this;
	}
	FlowComponent* precede(FlowComponent* successor)
	{
		composedFlowTask_.precede(successor->composedFlowTask_);
		return this;
	}
	FlowComponent* name(const std::string& name)
	{
		composedFlowTask_.name(name);
		return this;
	}
	tf::Task* nextTask()
	{
		tasks_.push(flow_.placeholder());
		return &tasks_.back();
	}

	std::queue<tf::Task> tasks_;
	tf::Taskflow flow_;
	tf::Task composedFlowTask_;
};
```
