### ISSUE TITLE
While compiling taskflow with CUDA code by nvcc, report "undefined reference"

### ISSUE THREAD

**Issue by Search-the-unknown** [taskflow/taskflow#394]
Hi,when i compile the simple.cu    using :
nvcc -std=c++17  -I ../myproject/include/  --extended-lambda  simple.cu -o simple
the error is:
/tmp/tmpxft_00002052_00000000-11_simple.o：in the function‘main::{lambda(tf::cudaFlow&)#2}::operator()(tf::cudaFlow&) const’：
tmpxft_00002052_00000000-6_simple.cudafe1.cpp:(.text+0x234)：‘tf::cudaTask tf::cudaFlow::single_task<__nv_dl_wrapper_t<__nv_dl_tag<int (*)(int, char const**), &main, 1u>> >(__nv_dl_wrapper_t<__nv_dl_tag<int (*)(int, char const**), &main, 1u>>)’undefined reference
collect2: error: ld returned 1 exit status

cudaflow.hpp  has been included,how to deal with it?
Could someone help me? thanks!

**Comment by tsung-wei-huang** [comment]
@Search-the-unknown can you paste your entire code to me so I can reproduce it?

**Comment by Search-the-unknown** [comment]
The entire code:
#include <taskflow/taskflow.hpp>  // core taskflow routines
#include <taskflow/cuda/cudaflow.hpp>  // core cudaflow routines

int main(int argc, const char** argv) {

  tf::Executor executor;
  tf::Taskflow taskflow;

  tf::Task task1 = taskflow.emplace([](){}).name("cpu task");
  tf::Task task2 = taskflow.emplace([](tf::cudaFlow& cf){
    tf::cudaTask cudaTask = cf.single_task(
      [] __device__ () { printf("hello cudaFlow!\n"); }
    );
  }).name("gpu task");

  task1.precede(task2);

  executor.run(taskflow).wait();
  return 0;
}

Here ,the only change is line 2 : #include <taskflow/cuda/cudaflow.hpp>
if not in this way ,it will reports error: fatal error: xxx.hpp : no such file or directory.
I wonder if there was a cmake error?  Thanks for your help.

**Comment by litterbus** [comment]
compile the _simple.cu_ I would report this same error too

**Comment by tsung-wei-huang** [comment]
I see you forgot to include `<taskflow/cuda/algorithm/for_each.hpp>` as [documented here](https://taskflow.github.io/taskflow/SingleTaskCUDA.html). 

I see `single_task` used in other page but no include info was mentioned. I will updated it. So the entire code looks like the follows:

```cpp
#include <taskflow/taskflow.hpp> // core taskflow routines
#include <taskflow/cuda/cudaflow.hpp> // core cudaflow routines
#include <taskflow/cuda/algorithm/for_each.hpp>

int main(int argc, const char** argv) {

tf::Executor executor;
tf::Taskflow taskflow;

tf::Task task1 = taskflow.emplace([](){}).name("cpu task");
tf::Task task2 = taskflow.emplace([](tf::cudaFlow& cf){
  tf::cudaTask cudaTask = cf.single_task(
    [] __device__ () { printf("hello cudaFlow!\n"); }
  );
}).name("gpu task");

task1.precede(task2);

executor.run(taskflow).wait();

return 0;
}
```

Compilation command:

```
~$ nvcc simple.cu -I path/to/taskflow -std=c++17 --extended-lambda
```

**Comment by Search-the-unknown** [comment]
Ok, I  follow the QUICKSTART step by step, and missed it. The problem has been solved, thanks very much.
