### ISSUE TITLE
question: what's the best way to make use of thread local storage with taskflow ?

### ISSUE THREAD

**Issue by boxerab** [taskflow/taskflow#396]
I would like to be able to create an object for every thread in the pool, and then have a way of destroying each of these objects when I am finished using them. Is this possible ? Thanks!

**Comment by boxerab** [comment]
@tsung-wei-huang thanks - I was thinking of use TLS for one work flow, but I realized I could more easily just create an array of objects, one per core, and have each thread use its designated object. Much simpler. Closing.

**Comment by tsung-wei-huang** [comment]
Hi @boxerab , would you mind sending me an email? (twh760812@gmail.com). I couldn't find your email info online - just want to touch base with more details about your experience with Taskflow :)
