### ISSUE TITLE
Pipeline builder

### ISSUE THREAD

**Issue by wizardsd** [taskflow/taskflow#398]
Taskflow v3.3 has very useful pipeline feature, but pipes can be created at compile-time only, i.e.  I have to pass all `tf::Pipe` objects to `tf::Pipeline` constructor.
Can you add another interface to create pipelines like this:

```c++
const size_t num_lines = 2;
tf::PipelineBuilder builder(num_lines);
for(int i = 0; i < n; ++i)
  builder.push_back(tf::Pipe{ tf::PipeType::SERIAL, []{} });
tf::Pipeline pl = builder.build();
```

It will be extremally useful when pipeline structure depends on user input.

**Comment by tsung-wei-huang** [comment]
Hi @wizardsd , I believe you are referring to [tf::ScalablePipeline](https://taskflow.github.io/taskflow/ParallelScalablePipeline.html) which allows you to create a pipeline with structures (lines, pipes) depending on runtime variables.
