### ISSUE TITLE
Hetero_traversal error 

### ISSUE THREAD

**Issue by ashah1222** [taskflow/taskflow#399]
**Describe the bug**
I am trying to run the hetero traversal benchmark and am getting 
"invalid argument (cudaErrorInvalidValue) - failed to create an executable graph"
I think this could be a problem with cudaGraphInstantiate at taskflow/cuda/cudaflow.hpp line 1628.

**To Reproduce**
$ ./hetero_traversal

:~/taskflow/build/benchmarks$ ./hetero_traversal -t 4 -g 1 -r 10 -m tf
model=tf num_threads=4 num_gpus=1 num_rounds=10
     |V|+|E|     Runtime
terminate called after throwing an instance of 'std::runtime_error'
  what():  [/home/*/taskflow/taskflow/cuda/cudaflow.hpp:1628] invalid argument (cudaErrorInvalidValue) - failed to create an executable graph
Aborted

**Comment by tsung-wei-huang** [comment]
what is your version of CUDA and GPU? CUDA Graph requires certain version of support.

**Comment by tsung-wei-huang** [comment]
close first since there hasn't been much activity - feel free to reopen if it is still there.
