### ISSUE TITLE
Question: is it possible to trigger the execution of individual tasks in a graph as data becomes available serially for each task ?

### ISSUE THREAD

**Issue by boxerab** [taskflow/taskflow#405]
### Current work-flow for my decompressor

1. single thread reads through compressed file and prepares N data blocks for N tasks
2. N tasks are scheduled and run in parallel by `taskflow`

step 1 is relatively slow as it is single-threaded.

### Possible Optimization

If it were possible to start executing a  task in step 2 as its data block becomes available,
then time for step 1 can be overlayed with time for step 2. Is it possible to schedule N tasks,
but allow the program to trigger each task as data becomes available for this task ?

I guess this could be implemented as a pipeline with two pipes, one serial and one parallel.

Thanks!

**Comment by tsung-wei-huang** [comment]
Do you mean something like [this example](https://taskflow.github.io/taskflow/RuntimeTasking.html#CreateARuntimeTask)?

**Comment by boxerab** [comment]
perfect! exactly what I needed.
