### ISSUE TITLE
Submitting tasks in runtime

### ISSUE THREAD

**Issue by maxsharabayko** [taskflow/taskflow#408]
I was thinking to utilise the `taskflow` for a UDP load balancer.
One thread receives UDP packets in a loop. For each packet received it can create a routing task. I.e. find the destination server from the routing table and send the packet to it.
I also want each route to a server to be an independent flow. Otherwise, packets from the same route may be reordered by parallel threads.

However, I am struggling to understand if and how it can be accomplished with the `taskflow` library. A taskflow cannot be modified during execution, thus I can't dynamically push tasks to it. Should I use the Pipeline? Maybe the library does not allow such use cases.
Please advise!

**Comment by maxsharabayko** [comment]
I was thinking about something like this to start with:

```c++
void th_recv(tf::Taskflow& taskflow) {
    while (auto pkt = udp.recv()) {
        taskflow.emplace([pkt] () { std::cout << "Packet routing task\n"; });
    }
}

int main() {
    tf::Taskflow taskflow;
    auto t = std::async(std::launch::async, th_recv, std::ref(taskflow));
    executor.run(taskflow);
    t.wait();
}
```

I was thinking about several taskflows each for a separate route, so that packets within the same route are sent sequentially, but several routes in parallel.
Later I found out you can't add a task to a taskflow while it is (probably) being executed.

**Comment by tsung-wei-huang** [comment]
That seems quite weird because you are modifying the taskflow while it is running. This is typically not allowed for most task-parallel libraries. Is it possible to fix the structure of the graph (or if needed, using dynamic tasking) during the execution?

**Comment by maxsharabayko** [comment]
> Is it possible to fix the structure of the graph (or if needed, using dynamic tasking) during the execution?

If a task is defined as "queue a packet for routing to a different destination", then tasks are arriving in run-time, dynamically.
There could be one queue of tasks per route (pipe?), but the task itself has to be added dynamically.

Or a task could be the routing loop, reading a packet from some queue and sending it to the target. Then the whole taskflow consists of a single task, and it is just executed while application is running or while the route exists.

```c++
tf::Executor executor;
tf::Taskflow taskflow;
std::queue<udp_packet*> q;
std::atomic_bool force_break;

tf::Task A = taskflow.emplace([q] () {
    if (q.empty())
        q.wait_non_empty();

    auto pkt = q.front();
    q.pop();
    udp.send(target_addr), *pkt);
});

executor.run_until(taskflow, force_break);
```

The goal is in serializing sending of packets of the same route (to avoid reordering), while allowing parallel sending of packets over several routes (hope it is not confusing).
That's why I am not adding a task of determining the route to the taskflow above. It has to be in a different taskflow, I guess. 🤔 

Does it make sense to have taskflows on one task? :)

**Comment by tsung-wei-huang** [comment]
@maxsharabayko  We have the first version of dynamic task graph parallelism using [dependent asynchronous tasking](https://taskflow.github.io/taskflow/DependentAsyncTasking.html). It is being experimented in both master and dev branches and will be included in the next release 3.6.0. 

Please give it a try :)

**Comment by tsung-wei-huang** [comment]
Close first as this has been merged to v3.6.0 - Feel free to reopen it if there is additional issue.

**Comment by maxsharabayko** [comment]
Hi @tsung-wei-huang 
Thanks, will take a look!

P.S. There seem to be a typo on this page https://taskflow.github.io/taskflow/DependentAsyncTasking.html
In the very first example should be `fuD.get()` instead of `D.get()`.
```c++
auto [D, fuD] = executor.dependent_async([](){ printf("D\n"); }, B, C);
D.get();  // wait for D to finish, which in turns means A, B, C finish
```

**Comment by tsung-wei-huang** [comment]
Oops! Thanks for the catch! Will fix it and push it to the main branch soon.
