### ISSUE TITLE
Synchronization of variables between Taskflow and main thread

### ISSUE THREAD

**Issue by gamagan** [taskflow/taskflow#412]
Hi,

I looked in the manual, but didn't come across the info I'm looking for. 

What are the synchronization requirements for data that gets read/written within a Taskflow callback, and the same data used by non-Taskflow functions.
Specifically, I have a setup like the following:

```cpp
struct Foo {...};

void InvokedByTaskFlow(Foo& foo) {
    foo.Update();
}

int main() {
    Foo foo;
    // Main loop
    while (Quit() == false) {
        if (NeedsRebuildGraph()) {
            RebuildTaskflowGraph(foo); 
        }
        UseFooBefore(foo);
        executor.run(taskflow);
        executor.wait_for_all();       
        UseFooAfter(foo);
    }
   return 0;
}
```

The function `UseFooBefore()` updates an int field of Foo, `Foo.myInt`. Then the taskflow is executed -- `Foo.myInt` does _not_ get updated in the Taskflow callback, but other variables might be. Sometimes, in `UseFooAfter()`, the change made in `UseFooBefore()` does not propagate (in time, I suppose) when read. That is, reading `Foo.myInt` in UseFooAfter() might have a different value as set in `UseFooBefore()`.

I assume this is a race condition, but it's a little surprising because the field `Foo.myInt` is only ever read/written to from the main thread. How do variables like 'Foo' need to be synchronized between Taskflow and the main thread, when the main thread and Taskflow do not run at the same time.

**Comment by gamagan** [comment]
> I am not sure when your InvokedByTaskflow will be called? Is it by a task in Taskflow or somewher in the master thread?

It is the callback invoked by taskflow.

**Comment by tsung-wei-huang** [comment]
In the logic of your code, you will execute UseFooBefore, then update it when you submit a Taskflow, and then run UseFooAfter, in a sequential order. I don't see any possibility that you can't see the update being prograted after "wait_for_all". Maybe you can provide a complete code so I can reproduce it?

**Comment by gamagan** [comment]
To clarify, it's like this:
> In the logic of your code, you will execute `UseFooBefore` [and update it within `UseFooBefore`], then you submit a Taskflow [wherein field `Foo.myInt` is not modified], and then run `UseFooAfter`, in a sequential order.

Yes, this is the case.

> I don't see any possibility that you can't see the update being prograted after "wait_for_all".

Yep, this has been stumping me; can't figure out. But, it's good to confirm that the value *should* be visible in `UseFooAfter`

> Maybe you can provide a complete code so I can reproduce it?

I was trying to do this, but it's part of a large codebase from which I can't rip just this chunk out. I discovered this as part of the unit-tests in this codebase. Sorry, I know it would have helped.

**Comment by tsung-wei-huang** [comment]
No problem. I will close this issue first - feel free to reopen it when you find more insight. For now, I don't see any issue of your use case of Taskflow.
