### ISSUE TITLE
Checking executor done without blocking

### ISSUE THREAD

**Issue by gamagan** [taskflow/taskflow#413]
Is there a way to check if an executor is done executing without waiting on it?

```cpp
    // On main thread
    executor.run(taskflow);
    while (IsDone(executor) == false) {
        DoIdleWork();
    }
```
Another question. When waiting for an executor on the main thread:
```
    executor.wait_for_all();
```
Does the main thread join the thread-pool of the executor, or does it wait idle?

**Comment by gamagan** [comment]
> ... so you can use that returned future to wait on that particular taskflow

Yes. But, my question is if it's possible to determine whether the executor is done with its work *without waiting*, without blocking, so the main thread can perform other work while the executor is running, as shown in the example. Or, conversely, if there is no way to determine when the executor is done running, without waiting/blocking.

```cpp
auto future = executor.run(taskflow);
while (tf:is_future_ready(future) == false) {
    DoMainThreadWorkWhileWaiting();
}
```

**Comment by tsung-wei-huang** [comment]
I see. That's an interesting question. Currently, we don't have anything that determines when the executor is done running, without waiting/blocking. The rationale is that all submission methods are thread-safe. In other words, it's not possible to precisely define what "an executor completes" really means as multiple threads can submit their own taskflows at an arbitrary time. However, if you know only one thread (e.g., main) is submitting taskflows, you may do the following polling:

```cpp
while(executor.num_topologies() != 0) {
}
```

Each time you submit a taskflow or create an async task from an executor, it creates a `tf::Topology` that keeps a certain runtime record to that execution.

Another solution might be adding a method `tf::Executor::try_wait_for_all` that returns immediately if at the moment you call nothing is completed.

Any thought?

**Comment by gamagan** [comment]
In my case, only the main thread is submitting tasksflows, so the polling should work for my usecase.

> Another solution might be adding a method tf::Executor::try_wait_for_all that returns immediately if at the moment you call nothing is completed.

I don't think that particular method would work for my particular usecase. From the sound of it, if something hasn't completed, it would return immediately, which is good. But, if something has completed, then it would block until the rest also complete. What I'm after is more like the `.num_topologies()` snippet, which tells if any taskflow is currently running -- this answers the question whether the executor is currently performing some work or not. The general flow would go something like this:

```cpp
void MyClass::RunTaskflow() {
    if (NeedsTaskflowGraphRebuild()) {
        RebuildTaskflowGraph();
    }

    // Run the multi-threaded work.
    this->executor->run(this->taskflow);

    // Possibly, perform some other work that's independent of the taskflow work.
    // This is work we can do before needing the result of executor->run().
    DoIndependentWork();

    // At this point, we must sync with Taskflow before returning, but the tasks may not be done executing.
    // In that latter case, use this wait time to do some other, unrelated, work in the main thread.
    // This is similar to DoIndependentWork(), but only runs if we have time to spare while waiting.
    // Maybe we defrag some memory in a memory-pool, or something.
    while(executor.num_topologies() != 0) {
        DoMainThreadWorkWhileWaiting();
    }

    // At this point, the tasks have completed and sync'ed with the main thread.
    // The result of executor->run() can be used.
    return;
}
```

Thank you

**Comment by tsung-wei-huang** [comment]
If only the master (one thread) is submitting taskflows to your executor, you can use `tf::Executor::num_topologies()` to query if the executor has completed all taskflows. Indeed, `tf::Executor::wait_for_all` uses a condition variable to wait on the number of topologies for completion.

Will close the issue now - feel free to reopen it if you have any more questions. Thank you for using Taskflow!
