### ISSUE TITLE
Why does taskflow depend on Eigen?

### ISSUE THREAD

**Issue by sampotter** [taskflow/taskflow#415]
Not really a bug... But why does Taskflow bundle Eigen in its set of 3rd party libraries? Is there some special reason for this?

**Comment by tsung-wei-huang** [comment]
Hi @sampotter Taskflow doesn't depend on Eigen. The 3rd-party is just used for benchmarking purposes (i.e., `benchmarks/mnist/`). In your project, you should just use the Taskflow headers.

**Comment by sampotter** [comment]
My mistake... thanks for the quick reply. Because of some idiosyncrasy with my development setup I thought the bundled Eigen was getting pulled in to my build, but it is not. Closing this.
