### ISSUE TITLE
null value after launching task

### ISSUE THREAD

**Issue by jmricher70** [taskflow/taskflow#416]
*I have created a class and one of the method -- int operator()() -- is used as a task. I have done that to compute PI using a monte-carlo algorithm and I can start several tasks and everything is fine. 

I am working under Linux Ubuntu 20.04.

The class I have written is the following :

```
class NQueensTask {
public:
    Context *_ctx;
    int _C, _R;

    NQueensTask( Context *ctx, int C, int R);
    void next( Context *ctx, int C );
    int operator()();
};
```
I create the tasks like this :

```
vector<NQueensTask *> tasks;

// create the NQueens tasks            
for (int R = 0; R < NQ; ++R) {
        Context *new_ctx = new Context( *ctx );
	NQueensTask	 *task = new NQueensTask( new_ctx, C, R );
        tasks.push_back( task );
}
          
for (auto task : tasks) {
     tf::Task A = taskflow.emplace( [&]() { (*task)(); } );
}    
     
executor.run( taskflow ).wait();

```
Everything works fine until I enter the operator()() method : 

int NQueensTask::operator()() {

    Value<QueenStoreValue> *vac1 = _ctx->qs().add( QueenStoreValue( _C, _R ) );

    if (queen_constraints_satisfied( _ctx, vac1 )) {
            next( _ctx, _C+1 );
    }

    _ctx->qs().del( vac1 );
	
    return 1;
}

When accessing one of the data members (_ctx, _R or _C) I get a segmentation fault because _ctx or _R or _C is considered as a nullptr.

I can't explain and it's kind of weird considering that I have another example based on the same principles working.

**Comment by tsung-wei-huang** [comment]
I believe this is a misuse of C++ lambda capture - nothing to do with Taskflow:

```
for (auto task : tasks) {
     tf::Task A = taskflow.emplace( [&]() { (*task)(); } );
}    
```

Here, you capture your `task` in reference and that `task` will disappear when you go out of the for-loop. So you should do it by copy instead:

```
for (auto task : tasks) {
     tf::Task A = taskflow.emplace( [task]() { (*task)(); } );
}    
```

**Comment by jmricher70** [comment]
Effectively, it works now ;-)
Thank you very much for your help.
