### ISSUE TITLE
Run benchmarks on mac m1

### ISSUE THREAD

**Issue by csphile** [taskflow/taskflow#418]
I'm not able to run benchmarks on mac m1. 
The error message is: 
`-- Building is unsuccessful (2): ~/taskflow/3rd-party/tbb/./build/Makefile.tbb:28: CONFIG: cfg=release arch=ia32 compiler=clang target=macos runtime=cc_os12.4
ld: unknown/unsupported architecture name for: -arch armv4t
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libtbb.dylib] Error 1
make: *** [tbb] Error 2`
Is there any way to fix it?

**Comment by tsung-wei-huang** [comment]
This is actually Intel's TBB problem when building the benchmarks. I am not sure how to resolve it but perhaps you may post this at Intel TBB's repository.
