### ISSUE TITLE
Question: How to create an object pool with capacity equal to maximum parallelization of a subtask set.

### ISSUE THREAD

**Issue by bradphelan** [taskflow/taskflow#419]
In our current system we have large buffers that are allocated. A task should be able to request a buffer, perform some work with it and at the end of the task return the buffer. It should be guaranteed that this buffer is not used by any other task in parallel. So the workflow is

Allocate N buffers where N is the maximum parallelization for the subtasks
Spin up M sub tasks
When a task is started it checks out a buffer from the pool.
When a task exits it checks the buffer back into the pool.
When all subtasks have finished all buffers are deallocated.

The important thing is to allocate exactly the number of buffer required to satisfy the maximum parallelization. Too many allocated and we waste memory. Too few allocated and we can't achieve maximum parallelization.

Suggestions on how to achieve this?

**Comment by tsung-wei-huang** [comment]
Hi @bradphelan , the buffers do not seem to conflict with Taskflow but I am a bit confused by the question itself. Taskflow doesn't handle data but only parallelizes task graphs based on your definition. In this case, shouldn't you just create a pool of `N` buffer where `N` equals the maximum parallelism? When each task starts, it goes to the pool to grab a buffer. The design of the buffer pool is completely up to you.

**Comment by bradphelan** [comment]
Yes. Maybe I've made other question too complex. The question should really
be: how to get this number N which is the maximum parrelization? Sorry for
the confusion.

**Comment by boxerab** [comment]
@bradphelan tasks are executed by a `tf::Executor`, which is created with a specified number of threads. The default constructor uses `std::thread::hardware_concurrency()`. So, once you have created an executor, you can call `num_workers()` to get its number of threads.

```
tf::Executor exec;
size_t numWorkers = exec.num_workers();
```

**Comment by tsung-wei-huang** [comment]
close for now - feel free to reopen if the issue is still there.
