### ISSUE TITLE
Question: has taskflow been compiled/tested/used with WebAssembly ?

### ISSUE THREAD

**Issue by boxerab** [taskflow/taskflow#421]
https://web.dev/webassembly-threads/

https://webassembly.org/roadmap/

**Comment by tsung-wei-huang** [comment]
I believe I ever tried using Emscripten and it worked out ok - but at that time pthread was not fully supported yet. This might be an interesting direction to investigate.

**Comment by boxerab** [comment]
Thanks, I will take a look. As with many web standards, it wasn't clear in 2017 whether WebAssembly would get enough traction to survive, but it looks like it is succeeding - there's been a lot of activity these past few years, including improved support for threading and SIMD. So, having a taskflow sample built for WASM would definitely help the project reach a wider audience.

**Comment by boxerab** [comment]
unfortunately, the examples fail with error below

```
/home/src/taskflow/taskflow/core/../utility/os.hpp:83:2: fatal error: Unknown OS
#error Unknown OS
```

**Comment by tsung-wei-huang** [comment]
It's totally fine to remove the corresponding [macro block](https://github.com/taskflow/taskflow/blob/96620cce7cf3bb67e039dad4ecd556ba61347787/taskflow/utility/os.hpp#L79) such that the macro does not trigger the error.

**Comment by boxerab** [comment]
compile is now enabled in #422
