### ISSUE TITLE
Minor performance issue with static tasking

### ISSUE THREAD

**Issue by derandomiz** [taskflow/taskflow#423]
**Describe the bug**

I tried to use Taskflow on simple tree traversal example, but encountered some overhead. In the example I generate a random tree with weight `node_weight(i)` associated to node `i` and want to compute the sum of all node weights. As this is an experiment I deliberately chose to implement this with dynamic programming where `subtree_weight(parent) = node_weight(parent) + sum(subtree_weight(children))`. Then the sum of all node weights equals `subtree_weight(root)`.

As a baseline, I implemented a simple DFS function (see `GetSum` function below) to collect all the weights and timed its running time. Next I used Taskflow to create a task graph in which a parent node `succeed` its children. To make the comparison fair I used a `Executor` with one thread. In the end I found that Taskflow's running time is almost 3x of the baseline. 
![image](https://user-images.githubusercontent.com/36243020/180389818-890d0c5b-d617-4857-8594-a6a8beefc4c7.png)
I understand the overhead probably comes from concurrency primitives, but is 3x expected here? If so, is there any optimization I can make on my end to accelerate the code.

**To Reproduce**
This is my code
```
using Graph = std::vector<std::vector<uint32_t>>;
using Clock = std::chrono::high_resolution_clock;

template <typename T>
inline double DurationInSec(const T& s, const T& e) {
  std::chrono::duration<double> elapsed = e - s;
  return elapsed.count();
}

void AddEdge(const uint32_t parent, uint32_t child, Graph* graph) {
  (*graph)[parent].push_back(child);
}

Graph GenerateRandomTree(const uint32_t n, std::mt19937_64* rng) {
  Graph tree(n);
  for (int i = 1; i < n; ++i) {
    // Find random parent
    const uint32_t parent =
        std::uniform_int_distribution<uint32_t>(0, i - 1)(*rng);
    AddEdge(parent, i, &tree);
  }
  return tree;
}

void GetSum(const Graph& tree, const std::vector<int>& node_weights,
            const int i, std::vector<uint64_t>* subtree_weights) {
  for (const auto s : tree[i]) {
    GetSum(tree, node_weights, s, subtree_weights);
    (*subtree_weights)[i] += (*subtree_weights)[s];
  }
  (*subtree_weights)[i] += node_weights[i];
}

int main(int argc, char* argv[]) {
  // Prepare data
  std::mt19937_64 rng;
  const int n = 1000000;
  const auto tree = GenerateRandomTree(n, &rng);
  std::vector<int> node_weights(n);
  std::iota(node_weights.begin(), node_weights.end(), 0);

  // Time simple DFS implementation
  auto start_time_dfs = Clock::now();
  std::vector<uint64_t> dfs_subtree_weights(n);
  GetSum(tree, node_weights, 0, &dfs_subtree_weights);
  std::cout << "DFS Weight sum: " << dfs_subtree_weights[0] << std::endl;
  auto end_time_dfs = Clock::now();
  std::cout << "DFS running time: " << DurationInSec(start_time_dfs, end_time_dfs) * 1000
            << std::endl;

  // Task flow implementation
  std::vector<uint64_t> subtree_weights(n);
  // Use only one thread
  tf::Executor executor(1);
  tf::Taskflow taskflow;
  std::vector<tf::Task> tasks;

  for (int i = 0; i < n; ++i) {
    tasks.push_back(taskflow
                        .emplace([&subtree_weights, &node_weights, &tree, i]() {
                          for (int s = 0; s < tree[i].size(); ++s) {
                            subtree_weights[i] += subtree_weights[tree[i][s]];
                          }
                          subtree_weights[i] += node_weights[i];
                        })
                        .name(std::to_string(i)));
  }

  for (int p = 0; p < n; ++p) {
    for (int s = 0; s < tree[p].size(); ++s) {
      tasks[p].succeed(tasks[tree[p][s]]);
    }
  }

  auto start_time = Clock::now();
  executor.run(taskflow).wait();
  auto end_time = Clock::now();

  std::cout << "Taskflow weight sum: " <<  subtree_weights[0] << std::endl;
  std::cout << "Taskflow running time: " << DurationInSec(start_time, end_time) * 1000 << std::endl;

  return 0;
}
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Compiler: gcc 7.5.0

**Comment by tsung-wei-huang** [comment]
The DFS is a very fast linear-time algorithm and your computation per node (see below) is very lightweight. In this case, running any parallel version (not just using Taskflow but also other libraries) will not give you any benefit.  

```
for (int s = 0; s < tree[i].size(); ++s) {
    subtree_weights[i] += subtree_weights[tree[i][s]];
}
subtree_weights[i] += node_weights[i];
```

You can try to increase the computation and you will be able to see the benefit when per-node computation becomes heavy.

**Comment by derandomiz** [comment]
Thank you for your explanation. I tried to increase the per-node computation and the overhead becomes negligible.
