### ISSUE TITLE
Cleanup async taskflow

### ISSUE THREAD

**Issue by yonik** [taskflow/taskflow#424]
Need a mechanism to delete a previously dynamically allocated Taskflow after it has finished.

Motivation:
The thread submitting a new Taskflow to an executor won't be around to call wait() on the future, hence the submitted Taskflow needs to be dynamically allocated and deleted when the Taskflow is completed.  But how do we know when the Taskflow has completed?

I tried cleaning up the Taskflow in the executor callback specified via
   tf::Future<void> run(Taskflow& taskflow, C&& callable);
Deleting the taskflow from callable causes things to hang later.  Likewise, even waiting on the future from the callable causes things to hang.  The docs only specify 
"This member function executes the given taskflow once and invokes the given callable when the execution completes."

It would be most useful if the associated taskflow were actually done when the callback is invoked, hence one could delete it or call future.wait(), but the intended behavior should be documented regardless.

If I can't use the callback mechanism, then I suppose I would need an external cleaning thread, which is much less straightforward.

**Comment by tsung-wei-huang** [comment]
Do you mean [submit a taskflow with moved ownership](https://taskflow.github.io/taskflow/ExecuteTaskflow.html#ExecuteATaskflowWithTransferredOwnership)? When you run a taskflow with "move" semantic, its lifetime will be managed by the executor (i.e., automatically released upon completion).

**Comment by yonik** [comment]
> Do you mean submit a taskflow with moved 
Ah, that works perfectly! Thanks!
