### ISSUE TITLE
[Question] Is taskflow for_each_index a drop-in replacement for Intel TBB parallel_for ?

### ISSUE THREAD

**Issue by boxerab** [taskflow/taskflow#425]
I am taking a look at a project that uses TBB `parallel_for` for a few loops. When I tried replacing one of these calls
with `taskflow` `for_each_index` call, the average duration for the loop increased by around 5X.

**Comment by tsung-wei-huang** [comment]
Yes, tf::Taskflow::for_each is a drop-in replacement - by default, it uses the guided scheduling algorithm similar to OpenMP. What does each iteration look like in your case? The source code is available [here](https://github.com/taskflow/taskflow/blob/master/taskflow/algorithm/for_each.hpp).

**Comment by tsung-wei-huang** [comment]
Tried compiling the code but got the following error:

```
CMake Error at ext/libigl/external/glfw/CMake/modules/FindWaylandProtocols.cmake:9 (message):
  Missing wayland-protocols pkgdatadir
Call Stack (most recent call first):
  ext/libigl/external/glfw/CMakeLists.txt:280 (find_package)
```

Any idea?

**Comment by tsung-wei-huang** [comment]
PS: I don't mind you create a secure log-in account to whatever machine you benchmark the workload :) which might be easier for me to configure all requires files in order to run the program

**Comment by tsung-wei-huang** [comment]
```
-- Using X11 for window creation
CMake Error at ext/libigl/external/glfw/CMakeLists.txt:252 (message):
  The Xinerama headers were not found
```

Any idea?

**Comment by tsung-wei-huang** [comment]
Thanks! Now it compiles. Anyway I can skip the following core-dump due to x11 code?

```
~$ ./OptCuts_bin 10 ../input/bimba_i_f10000.obj 

igl::opengl::glfw::Viewer usage:
  [drag]  Rotate scene
  A,a     Toggle animation (tight draw loop)
  F,f     Toggle face based
  I,i     Toggle invert normals
  L,l     Toggle wireframe
  O,o     Toggle orthographic/perspective projection
  T,t     Toggle filled faces
  Z       Snap to canonical view
  [,]     Toggle between rotation control types (trackball, two-axis
          valuator with fixed up, 2D mode with no rotation))
  <,>     Toggle between models
  ;       Toggle vertex labels
  :       Toggle face labels
Offline optimization mode
Use default lambda = 0.999
Use default testID = 1
Use default method: OptCuts.
random 2-edge initial cut for closed surface
E_initial = 3.73973
X11: The DISPLAY environment variable is missingThe GLFW library is not initializedThe GLFW library is not initializedThe GLFW library is not initializedFloating point exception (core dumped)
```

**Comment by tsung-wei-huang** [comment]
OK - let me wait for a complete run to finish and dig into it a bit more. Could you please let me know what each step of the parallel-for-loop is doing? (in a very high-level description). Additionally, I am interested in the following questions:

1. Is the parallel-for-loop balanced or unbalanced at each step? i.e., each step does pretty much the same or different workload
2. How many steps in general? i.e., data.F.rows()
3.

**Comment by tsung-wei-huang** [comment]
On my machine, I saw about 2x slower, i.e., 0.015 (Taskflow) vs 0.008 (TBB). I also tried changing that loop to OpenMP and it ran about 0.006.

```
#omp parallel for schedule(guided, 1)
```

Taskflow's parallel-for algorithm is essentially the same as OpenMP's guided scheduling implementation. But it's quite interesting and confusing to me that the loop doesn't work out as efficient as OpenMP in this particular workload :)

I will need a bit more time to look into the problem. Meanwhile, if you have any thoughts or new findings, please let me know.

**Comment by tsung-wei-huang** [comment]
Are you doing any recursive tasking based on the number of workers configured in the executor?

**Comment by tsung-wei-huang** [comment]
It does look like to be the inherent tasking overhead of taskflow. Unlike TBB or OpenMP where you can start the parallel-for immediately, taskflow wraps the for-each workload in a taskflow and you will need to submit it to an executor. These tasking work count for overhead. 

Yes, I did a slight optimization for all parallel algorithms in taskflow, and they have been pushed to the master branch. The improvement is not significant but I will see what else overhead I can reduce.

**Comment by tsung-wei-huang** [comment]
Also, you may try experimenting different numbers of worker threads for the executor. Although Taskflow will dynamically balance the worker threads with available task parallelism, more workers do give more overhead during the balancing process. For instance, on my machine of 16  Intel(R) Core(TM) i7-11700 @ 2.50GHz, using 4 worker threads gives the best performance.
