### ISSUE TITLE
Query: FPU context save and reset within tasks

### ISSUE THREAD

**Issue by bradphelan** [taskflow/taskflow#430]
** Does Taskflow manage FPU state?*

In our wrappers for OpenMP we use have a utility to reset the FPU state for each task or chunk of tasks. Does the Taskflow scheduler perform any FPU register management at all?

**Comment by tsung-wei-huang** [comment]
Taskflow does not perform any FPU register management. It's completely up to your choice.

**Comment by bradphelan** [comment]
Could this be managed via the tf::ObserverInterface? That is adding in custom hooks into the TF lifecycle?

**Comment by tsung-wei-huang** [comment]
That sounds like a viable solution - although not recommended because observer is supposed to just observe when a task is executed by which thread.

**Comment by tsung-wei-huang** [comment]
Yes, that's a new interface to allow some customization for worker threads spawned by an executor. Feel free to give any comment or PR if you find any extension to it.
