### ISSUE TITLE
How  does taskflow schedule  multiple tasks on an Executor with multiple workers?

### ISSUE THREAD

**Issue by Search-the-unknown** [taskflow/taskflow#431]
I plan to schedule tasks with taskflow in a real-time system, so I need to know how long it takes to finish a task and make sure every task meets its deadline.

Supposing that :  we have five tasks called A, B, C, D, E . The time required to complete each of them with 10 workers is 1 second, 2 seconds, 4 seconds, 6 second and 10 seconds . we know this in advance.

Now , we create a  taskflow with  the above five  tasks with default priority , every task is independent ,and an Executor with 10 workers. How does taskflow schedule these tasks?   In other words, when  will they be finished ? or  unpredictable and randomly scheduled?

**Comment by tsung-wei-huang** [comment]
Hi @Search-the-unknown , taskflow is not designed for real-time system or real-time scheduling. In your case, you can assign a priority to tasks that need to finish earlier, but you are right, the task execution order is completely random and decided by the taskflow's work-stealing scheduler at runtime.
