### ISSUE TITLE
run_and_wait causes deadlock

### ISSUE THREAD

**Issue by dinesh-10** [taskflow/taskflow#435]
**Describe the bug**
run_and_wait API causes deadlock for the below example. I slightly modified examples/run_and_wait.cpp file and got a deadlock. 
Can you please tell the reason of the deadlock ? It looks like a bug in implementation, Can you please confirm ? 

**To Reproduce**
Run below example with taskflow-3.4.0 version : 

```
// This example demonstrates how to use the run_and_wait
// method in the executor.
#include <taskflow/taskflow.hpp>
#include <iostream>

int main(){

  // create an executor and a taskflow
  tf::Executor executor(2);
  tf::Taskflow taskflow("Demo");

  int counter{0};
  
  // taskflow to run by the main taskflow
  tf::Taskflow others;
  tf::Task A = others.emplace([&](){ std::cout << "others::A " << counter << "\n"; counter++; }); 
  tf::Task B = others.emplace([&](){ std::cout << "others::B " << counter << "\n";  counter++; }); 
  A.precede(B);

  // main taskflow
  tf::Task C = taskflow.emplace([&](){
     std::cout << "taskflow::C " << counter << "\n";
     executor.run_and_wait(others);
  }); 
  tf::Task D = taskflow.emplace([&](){
     std::cout << "taskflow::D " << counter << "\n";
     executor.run_and_wait(others);
  }); 
  //C.precede(D);

  executor.run(taskflow).wait();
  std::cout << "counter is: " << counter << std::endl;

  return 0;
}
```

**Desktop (please complete the following information):**
using taskflow3.4 version

**Comment by tsung-wei-huang** [comment]
I saw you running the taskflow `others` by two tasks in parallel, `C` and `D`. This is not allowed - a taskflow cannot be run concurrently by two or more threads. But when you uncomment `//C.precede(D);`, the program should finish correctly.

**Comment by dinesh-10** [comment]
Thank you tsung for clarification. It would be great if you add this info in taskflow document saying "A taskflow cannot be run concurrently by two or more threads.".

**Comment by tsung-wei-huang** [comment]
I will add this statement to the handbook in the next release. Thanks for the comment!
