### ISSUE TITLE
run_and_wait() API backport to older version

### ISSUE THREAD

**Issue by dinesh-10** [taskflow/taskflow#436]
Hi, 

Currently I am using taskflow-3.0.0 version. I found "run_and_wait" API which is added recently and very useful for my use-case. 

I am trying to backport it to taskflow-3.0.0 version, below is what I added : 

```
template <typename T>
void Executor::run_and_wait(T& target) {
  
  //auto w = _this_worker();
  // worker thread
  auto w = _per_thread.worker;

  if(w == nullptr) {
    TF_THROW("run_and_wait must be called by a worker of the executor");
  }

  Node parent;  // dummy parent
  _invoke_dynamic_task_internal(*w, &parent, target._graph, false);
  // _join_graph(*w, &parent, target.graph());
}
```

On running the below example "run_and_wait.cpp" while the API works fine but when I re-submit "other" taskflow to the executor it causes deadlock :

```
// This example demonstrates how to use the run_and_wait
// method in the executor.
#include <taskflow/taskflow.hpp>
#include <iostream>

int main(){

  // create an executor and a taskflow
  tf::Executor executor(2);
  tf::Taskflow taskflow("Demo");

  int counter{0};
  
  // taskflow to run by the main taskflow
  tf::Taskflow others;
  tf::Task A = others.emplace([&](){ std::cout << "others::A " << counter << "\n"; counter++; }); 
  tf::Task B = others.emplace([&](){ std::cout << "others::B " << counter << "\n"; counter++; }); 
  A.precede(B);

  // main taskflow
  tf::Task C = taskflow.emplace([&](){
     std::cout << "taskflow::C " << counter << "\n";
     executor.run_and_wait(others);
  }); 
  tf::Task D = taskflow.emplace([&](){
     std::cout << "taskflow::D " << counter << "\n";
     executor.run_and_wait(others);
  }); 
  C.precede(D);

  executor.run(taskflow).wait();
  std::cout << "taskflow finished\n";

  // run others again
  executor.run(others).wait();     // <- Causes deadlock

  std::cout << "counter is: " << counter << std::endl;

  return 0;
}
```

Question :
1. Is my "run_and_wait" API correct or am I missing anything ? 
2. Why re-submission of the "others" taskflow causes deadlock in my case but works fine with taskflow-3.4.0 version ?

**Comment by dinesh-10** [comment]
Hi tsung,
Yes problem exist when C.precede(D) is specified. 
Can you confirm that the API "run_and_wait", which I shared, is correct for w.r.t taskflow-3.0.0 version. Is there anything missed here ?

**Comment by tsung-wei-huang** [comment]
v3.4 and v3.5 (main branch) have a different scheduling organization to support `run_and_wait` - and your implementation idea is correct but the call to `per_thread` and `_invoke_dynamic_task_internal` has been modified in the later release to fix some bugs. HAve you tried using v3.4 and see if the problem is still there?

**Comment by tsung-wei-huang** [comment]
Starting at v3.6.0 (currently the master branch), this method has been renamed to `corun` for expressiveness. Please see the [release note](https://taskflow.github.io/taskflow/release-3-6-0.html).
