### ISSUE TITLE
difference between tf::PipeType::SERIAL or tf::PipeType::PARALLEL

### ISSUE THREAD

**Issue by YangYike007** [taskflow/taskflow#438]
Hi, I'm getting started with taskflow. I'm not quite clear about the impact of these two pipe types based on the sample on the website. Could you please give an example to illustrate their function or explain their impact on the running of worker threads?
For example, (tf::PipeType::PARALLEL) refers to parallelism between pipes in a line or lines?
Thanks

**Comment by tsung-wei-huang** [comment]
Pipe type referes to the parallelism of a pipe between lines. For example, if you have a parallel pipe under 4 lines, the maximum parallelism is 4. Does this make sense?

**Comment by YangYike007** [comment]
Yes that makes sense. [https://taskflow.github.io/taskflow/TextProcessingPipeline.html](url) In this pipeline processing example, the code is const size_t num_lines = 2, and the comment says the pipeline consists of three pipes (serial-parallel-serial) and up to four concurrent scheduling tokens. According to what you said,  I guess it's a typo and the actual concurrency should be 2?
Thanks a lot.

**Comment by tsung-wei-huang** [comment]
@YangYike007 sorry it is a typo. When I first created the example, I used `num_lines = 4`. In this case, you are right. The parallelism is of 2. I will fix this typo in the next release. Thanks!
