### ISSUE TITLE
Looks DeadLock For MultiTasks

### ISSUE THREAD

**Issue by liujp** [taskflow/taskflow#447]
It look a lot of task in a Taskflow, an deadlock may occurred

 tf::Executor executor;
    tf::Taskflow tasks("Test");
    for (int i = 0; i < 32; i++) {
      tasks.emplace([i, this]() {
        const auto &path = MakeTempFiles(tmp_file_path_, label_ + "_f_", i);
        this->DoSomeThing(path);
      });
    }
    executor.run(tasks).wait();

**Comment by tsung-wei-huang** [comment]
I am quite skeptical about this. Could you please paste the complete code? Did you capture `i` in copy?

**Comment by liujp** [comment]
yes, the local value ’i‘ is captured by copy, then I want to run agin and paste the detail

**Comment by tsung-wei-huang** [comment]
I don't see any possibility of a deadlock. Have you actually run into a deadlock? Maybe a complete example is better for me to reproduce the issue.

**Comment by liujp** [comment]
The background is that:  I use task flow to set kv Paris to the kv-store which use the CSA method, when I use this, the program hang here, and then I use the CPP thread to send kv pairs it works fine, so I think this may be a lock in taskflow , for the time on-line, I did not debug the program carefully.
  
void BatchPut() {
    tf::Executor executor;
    tf::Taskflow tasks("ClientBatchPut");
    for (int i = 0; i < partitions_; i++) {
      tasks.emplace([i, this]() {
        const auto& path = MakeTempFiles(this->tmp_dir_, this->file_name_, i);
        Logger::get("Importer").information("Importer File: " + path);
        KvReader reader(path.data());
        std::string values;
        int cnt = 0;
        std::vector<KvPair> kvs;
        kvs.reserve(BATCH_SIZE + 5);
        struct timeval start, end;
        gettimeofday(&start, NULL);
        while (reader.NextValue(&values)) {
          KvPair kv_p;
          kv_p.ParseFromString(values);
          kvs.push_back(std::move(kv_p));
          if (kvs.size() % BATCH_SIZE == 0) {
            int re_try = 0;
            for (; re_try < CAS_CNT; ++re_try) {
              try {
                clients_[i]->BatchPut(kvs);
                break;
              } catch (const std::exception& e) {
                Logger::get("Importer").error("Try again batch exception: " + e.message() + kvs[0].key());
              }
              break;
            }
            if (re_try > CAS_CNT) {
              Logger::get("Importer").error("skiped keys" + kvs[0].key());
            }
            kvs.clear();
          }
        }  // push the spares
        int re_try = 0;
        for (; re_try < CAS_CNT; ++re_try) {
          try {
            clients_[i]->BatchPut(kvs);
            break;
          } catch (const std::exception& e) {
            Logger::get("Importer").error("Try again batch exception: " + e.message() + kvs[0].key());
          }
          break;
        }
        if (re_try > CAS_CNT) {
          Logger::get("Importer").error("skiped keys" + kvs[0].key());
        }
        gettimeofday(&end, NULL);
        Logger::get("Importer")
            .information("Put batch keys in QPS: " + std::to_string((kvs.size() * 1000 /
                                                                     (double)((end.tv_sec - start.tv_sec) * 1000 +
                                                                              (end.tv_usec - start.tv_usec) / 1000))));
        kvs.clear();
        Logger::get("Importer").information("Importer Done: " + reader.GetFileName());
      });
    };
    executor.run(tasks).wait();
  }

**Comment by liujp** [comment]
The background is that: I use task flow to set kv Paris to the kv-store which use the CSA method, when I use this, the program hang here, and then I use the CPP thread to send kv pairs it works fine, so I think this may be a lock in taskflow , for the time on-line, I did not debug the program carefully.

void CASPut() {
    tf::Executor executor;
    tf::Taskflow tasks("ClientCASPut");
    for (int i = 0; i < partitions_; i++) {
      tasks.emplace([i, this]() {
        const auto& path = MakeTempFiles(this->tmp_dir_, this->file_name_, i);
        KvReader reader(path.data());
        std::string values;
        int cnt = 0;
        std::vector<KvPair> kvs;
        kvs.reserve(BATCH_SIZE + 5);
        struct timeval start, end;
        gettimeofday(&start, NULL);
        while (reader.NextValue(&values)) {
          KvPair kv_p;
          kv_p.ParseFromString(values);
          kvs.push_back(std::move(kv_p));
          if (kvs.size() % BATCH_SIZE == 0) {
            int re_try = 0;
            for (; re_try < CAS_CNT; ++re_try) {
              try {
                clients_[i]->CASBatchPut(kvs);
                break;
              } catch (const std::exception& e) {
                Logger::get("Importer").error("Try again batch exception: " + e.message() + kvs[0].key());
              }
              break;
            }
            if (re_try > CAS_CNT) {
              Logger::get("Importer").error("skiped keys" + kvs[0].key());
            }
            kvs.clear();
          }
        }  // push the spares
        int re_try = 0;
        for (; re_try < CAS_CNT; ++re_try) {
          try {
            clients_[i]->CASBatchPut(kvs);
            break;
          } catch (const std::exception& e) {
           Logger::get("Importer").error("Try again batch exception: " + e.message() + kvs[0].key());
          }
          break;
        }
        if (re_try > CAS_CNT) {
          Logger::get("Importer").error("skiped keys" + kvs[0].key());
        }
        gettimeofday(&end, NULL);
        Logger::get("Importer")
            .information("Put batch keys in QPS: " + std::to_string((kvs.size() * 1000 /
                                                                     (double)((end.tv_sec - start.tv_sec) * 1000 +
                                                                              (end.tv_usec - start.tv_usec) / 1000))));
        kvs.clear();
      });
    };
    executor.run(tasks).wait();
  }

**Comment by liujp** [comment]
The background is that: I use task flow to set kv Paris to the kv-store which use the CSA method, when I use this, the program hang here, and then I use the CPP thread to send kv pairs it works fine, so I think this may be a lock in taskflow , for the time on-line, I did not debug the program carefully.

void CASPut() {
tf::Executor executor;
tf::Taskflow tasks("ClientCASPut");
for (int i = 0; i < partitions_; i++) {
tasks.emplace([i, this](https://github.com/taskflow/taskflow/issues/447) {
const auto& path = MakeTempFiles(this->tmp_dir_, this->file_name_, i);
KvReader reader(path.data());
std::string values;
int cnt = 0;
std::vector kvs;
kvs.reserve(BATCH_SIZE + 5);
struct timeval start, end;
gettimeofday(&start, NULL);
while (reader.NextValue(&values)) {
KvPair kv_p;
kv_p.ParseFromString(values);
kvs.push_back(std::move(kv_p));
if (kvs.size() % BATCH_SIZE == 0) {
int re_try = 0;
for (; re_try < CAS_CNT; ++re_try) {
try {
clients_[i]->CASBatchPut(kvs);
break;
} catch (const std::exception& e) {
Logger::get("Importer").error("Try again batch exception: " + e.message() + kvs[0].key());
}
break;
}
if (re_try > CAS_CNT) {
Logger::get("Importer").error("skiped keys" + kvs[0].key());
}
kvs.clear();
}
} // push the spares
int re_try = 0;
for (; re_try < CAS_CNT; ++re_try) {
try {
clients_[i]->CASBatchPut(kvs);
break;
} catch (const std::exception& e) {
Logger::get("Importer").error("Try again batch exception: " + e.message() + kvs[0].key());
}
break;
}
if (re_try > CAS_CNT) {
Logger::get("Importer").error("skiped keys" + kvs[0].key());
}
gettimeofday(&end, NULL);
Logger::get("Importer")
.information("Put batch keys in QPS: " + std::to_string((kvs.size() * 1000 /
(double)((end.tv_sec - start.tv_sec) * 1000 +
(end.tv_usec - start.tv_usec) / 1000))));
kvs.clear();
});
};
executor.run(tasks).wait();
}

**Comment by liujp** [comment]
tasks.emplace([I, this](){})

**Comment by liujp** [comment]
tasks.emplace('[i, this]'{})

**Comment by tsung-wei-huang** [comment]
@liujp would you please try the current/newest master branch again?

**Comment by tsung-wei-huang** [comment]
close first - feel free to reopen if new activity is there.
