### ISSUE TITLE
Missing licensing details for reference PDFs

### ISSUE THREAD

**Issue by troycurtisjr** [taskflow/taskflow#451]
**Describe the bug**
I was trying to determine the exact license terms for the various reference PDFs included in the source tarball and docs, but it isn't clear what the terms are. Several of the PDFs have copyright notices, especially IEEE related ones, which seems to indicate potential distribution restrictions. However, they seem to indicate that other terms can be used "with permission". Are there details available?

**Comment by tsung-wei-huang** [comment]
Hi @troycurtisjr, 

By default, it is your responsibility to comply with the IEEE copyright. Since all the reference articles are associated with the project's creator, we provide a copy as is (which is allowed by IEEE copyright as far as I know). However, if you want to redistribute those articles, you will need to abide the distribution rules of IEEE (or ACM).

**Comment by troycurtisjr** [comment]
[BLUF](https://en.wikipedia.org/wiki/BLUF_(communication)): Unfortunately that doesn't clarify the practical terms, and potentially indicates that no outside contributions can be made to the project since the act of forking the repository may well be in violation of one or more of the document's copyright.

Ultimately you are correct, each person is responsible for compliance with licensing terms. However, in this instance it isn't clear what terms to comply with, which actually means it isn't possible to comply with terms which are unknown. Taking each PDF in turn to illustrate my confusion/uncertainity:

# PDF Copyright details
## 2004.10908v2.pdf
No copyright listed
Following the link to the arxiv reference, there is reference that submitters should choose a license, and it provided some recommendations, but I can't find what license it is under.

## mm19.pdf, lin_19_01.pdf, iccad20.pdf
Copyright to ACM:

> Permission to make digital or hard copies of all or part of this work for personal or
> classroom use is granted without fee provided that copies are not made or distributed
> for profit or commercial advantage and that copies bear this notice and the full cita-
> tion on the first page. Copyrights for components of this work owned by others than
> ACM must be honored. Abstracting with credit is permitted. To copy otherwise, or re-
> publish, to post on servers or to redistribute to lists, requires prior special permission
> and/or a fee. Request permissions from permissions@acm.org.

The "post on server or redistribute to lists, requires prior special permission" seems potentially problematic.

## tcad21-taskflow.pdf
> Personal use is permitted, but republication/redistribution requires IEEE permission.
> 0278-0070
> See https://www.ieee.org/publications/rights/index.html for more information.

This also bears the somewhat concerning notice:
> Authorized licensed use limited to: The University of Utah. Downloaded on September 03,2021 at 18:13:54 UTC from IEEE Xplore. Restrictions apply.

Following the link, there is indeed the statement about the author being allowed to post pre-print versions of the article, though I wonder about this particular statement:

> The policy also states that authors are allowed to post pre-print versions of their articles on approved third-party servers that are operated by not-for-profit organizations.

Hopefully GitHub applies, at least in spirit if not in letter, as a not-for-profit organization since it is the defacto place for FLOSS software development.

## ipdps19.pdf, hpec19.pdf, icpads20.pdf, huang_15_01.pdf
This just has copyright, IEEE. Perhaps we can presume the standard IEEE copyright similar to tcad21-taskflow.pdf?

# Remaining confusion

1 document doesn't have any copyright defined, 4 of the documents do not have clear terms provided, and while IANAL, some of the terms of the ACM and even the IEEE which are present, seem potentially problematic posting to GitHub, even by the authors. That said, since the posting is clearly not for profit or commercial gain, I can't imagine it ever being pursued as a violation.

# Forking issue

Even if posting to the GitHub repo of one of the author's doesn't run afoul of the licensing terms, it seems pretty clear that no one, other than the authors, would be authorized to use the prominent "fork" GitHub feature. Since forking is the only practical way to make contributions to the code (even unrelated to the docs themselves) on GitHub, it seems like the presence of the files, at least in the absence of additional clarifying terms, makes it potentially infringing to provide any pull requests to the project.

# Misleading project licensing

At the project level there is a LICENSE file listing only the MIT license. And while the source files do not themselves have a license listed in their headers, it is reasonable (and typical) to assume all files, unless otherwise marked, fall under the project's MIT license. However, there is no mention at the project level, neither in the LICENSE or README.md file, which indicates that the project itself is not wholly under the MIT license. The top-level files imply the project as a whole can be distributed under the MIT license, but in fact the project contains copyright terms with more strict requirements (when they are even defined).

IANAL, but I can't imagine ACM or IEEE actually pursuing an infringment case for any contributor, or any good-faith OSS distribution, of this project. However, copyright compliance is not only about avoiding procesution or consequences, but rather it is also about honoring the terms of the copyright holder. After all, all open source relies on copyright to protect the rights of consumers and producers of FLOSS code. So in this case, I don't honestly think there is any real danger of any sort of legal action being taken, but without clear terms, no indivdual or company utilizing this project can easily compily with all applicable licensing desired by the copyright holder.
