### ISSUE TITLE
Whether there are multiple executors share task to execute?

### ISSUE THREAD

**Issue by zhangdexin** [taskflow/taskflow#453]
I read executor.hpp code and find this:
```
inline void Executor::_schedule(Worker& worker, Node* node) {
  // ...
  if(worker._executor == this) {
   // ...
    return;
  }

  {
    std::lock_guard<std::mutex> lock(_wsq_mutex);
    _wsq.push(node, p);
  }

  // ...
}
```
It has this ``` if(worker._executor == this) ``` condition，so I think how use taskflow can be ```worker._executor != this```  situation？

**Comment by tsung-wei-huang** [comment]
It is possible when you have a worker submitting a taskflow from another executor. You can take a look at the [nested run tests](https://github.com/taskflow/taskflow/blob/97aa6eaca3605e16c254eb766e9425d013b05423/unittests/basics.cpp#L941).

**Comment by tsung-wei-huang** [comment]
Close the issue - feel free to reopen it if needed.
