### ISSUE TITLE
TaskFlow vs OpenMP for simple arallel for loop

### ISSUE THREAD

**Issue by jspoxon** [taskflow/taskflow#455]
I’ve just started to investigate this library because it seems to be what I’m looking for regarding complex multithreading control. 
I started to test a simple parallel for loop (compared to my previous OpenMP implementation) and I am observing much slower execution times in Taskflow vs OpenMP. Over a factor of 10 slower in Taskflow. I It could be that I’m making mistakes, so I just wanted to share some simplified code.

void TaskFlow_Vs_OpenMP_for_Test(int CPUNumber)
{
	std::vector<float> X(100000, 1.f);
	std::vector<float> SumOfX(X.size(), 0.f);

	auto taskflow_start = std::chrono::steady_clock::now();

	tf::Taskflow taskflow;
	tf::Executor executor(CPUNumber);

	taskflow.for_each_index(0, static_cast<int>(X.size()), 1,
		[&](int i)
		{
			SumOfX[i] = static_cast<double>(i) * X[i];
		}
	);

	executor.run(taskflow).get();
	auto taskflow_end = std::chrono::steady_clock::now();
	auto Time_tasflow_for = std::chrono::duration_cast<std::chrono::milliseconds>(taskflow_end - taskflow_start).count();

	X.assign(100000, 1.f);
	SumOfX.assign(X.size(), 0.f);

	auto omp_start = std::chrono::steady_clock::now();

	omp_set_num_threads(CPUNumber);
	#pragma omp parallel for
	for (int i = 0; i < X.size(); i++)
	{
		SumOfX[i] = static_cast<double>(i) * X[i];
	}
	
	auto omp_end = std::chrono::steady_clock::now();
	auto Time_omp_for = std::chrono::duration_cast<std::chrono::milliseconds>(omp_end - omp_start).count();

	std::cout << "Taskflow And Omp:"
		<< std::chrono::duration_cast<std::chrono::microseconds>(taskflow_end - taskflow_start).count()
		<< ","
		<< std::chrono::duration_cast<std::chrono::microseconds>(omp_end - omp_start).count()
		<< "\n";
}

**Comment by tsung-wei-huang** [comment]
Hi @jspoxon 

With N only about 100000, the overhead of tasking (scheduling, graph initialization) of Taskflow becomes dominant. That literally gives you no advantage of parallelism. So, with the following modified version:

```cpp
void TaskFlow_Vs_OpenMP_for_Test(int N, int CPUNumber) {
  std::vector X(N, 1.f);
  std::vector SumOfX(X.size(), 0.f);

  auto taskflow_start = std::chrono::steady_clock::now();

  tf::Taskflow taskflow;
  tf::Executor executor(CPUNumber);

  taskflow.for_each_index(0, static_cast<int>(X.size()), 1,
    [&](int i)
    {
      SumOfX[i] = static_cast<double>(i) * X[i];
    }
  );

  executor.run(taskflow).get();
  auto taskflow_end = std::chrono::steady_clock::now();
  auto Time_tasflow_for = std::chrono::duration_cast<std::chrono::milliseconds>(taskflow_end - taskflow_start).count();


  X.assign(N, 1.f);
  SumOfX.assign(X.size(), 0.f);

  auto omp_start = std::chrono::steady_clock::now();

  omp_set_num_threads(CPUNumber);
  #pragma omp parallel for
  for (int i = 0; i < X.size(); i++)
  {
    SumOfX[i] = static_cast<double>(i) * X[i];
  }

  auto omp_end = std::chrono::steady_clock::now();
  auto Time_omp_for = std::chrono::duration_cast<std::chrono::milliseconds>(omp_end - omp_start).count();

  std::cout << "Taskflow And Omp:"
    << std::chrono::duration_cast<std::chrono::microseconds>(taskflow_end - taskflow_start).count()
    << ","
    << std::chrono::duration_cast<std::chrono::microseconds>(omp_end - omp_start).count() 
    <<'\n';
```

I have the following data:

```
$ ./a.out 100000000 8
Taskflow And Omp:30451,33460
$ ./a.out 100000000 8
Taskflow And Omp:30374,33508
$ ./a.out 100000000 8
Taskflow And Omp:30520,33530
$ ./a.out 100000000 8
Taskflow And Omp:30112,29675
$ ./a.out 100000000 8
Taskflow And Omp:30123,29790

$ ./a.out 10000000 8
Taskflow And Omp:3401,3428
$ ./a.out 10000000 8
Taskflow And Omp:3653,3423
$ ./a.out 10000000 8
Taskflow And Omp:3737,3303
$ ./a.out 10000000 8
Taskflow And Omp:3604,3284
$ ./a.out 10000000 8
Taskflow And Omp:3828,3260
```

Also, OpenMP has the best performance for your particular example (data-parallel loop with static partition). Ideally, Taskflow will outperform OpenMP for irregular workloads.

I hope this helps!

**Comment by tsung-wei-huang** [comment]
I assume the OpenMP implementation in your windows has some SIMD optimization enabled by default. How many CPU cores does your machine have? 

Additionally, would you try using `#pragma omp parallel for schedule(guided)` and report the runtime again? Taskflow by default implements the guided scheduling algorithm.

**Comment by jspoxon** [comment]
The machine has 14 cores. I have redone the example with the "schedule(guided)" option and now it seems to be doing similar times.

I have used the `#pragma omp parallel for` option in my project (mostly brute force method) and it has optimized my code quite well. If I try to use now the `taskflow.for_each_index` optimization execution times are around 2 times slower. 

It is hard for me to set up an example to share since there are many things going on and huge dependencies in my loop. I'll try to come up with something though. 

A question: could I create a simple static taskflow graph containing a function that uses OpenMP loop inside? (My first test is not producing the same results as calling the function outside of the taskflow graph).

Thank you.

**Comment by tsung-wei-huang** [comment]
@jspoxon yes, the default implementation of `for_each_index` is indeed a guided scheduling algorithm. If you need static partitioning algorithm of openmp, you can always use openmp from a `tf::Task`:

```cpp
taskflow.emplace([](){
  #omp parallel for
  for(...)
});
```

**Comment by pavel-perina** [comment]
Thanks. I just wanted to ask because I wanted something that can deal with cases where i need hundreds of iterations and each of them last 5ms plus minus order of magnitude depending on input data and specific algorithm (basically image processing pipeline) and I came to the same conclusion. OneTBB seems fastest, OpenMP close second (I just don't like it and don't use it for myself) and now I found that TaskFlow copied from MandelBrot example is 100 times slower. But it became 50 to 300% more slow with each other 2000 iterations when I measured time.

But! This may solve problem for @jspoxon as well

I constructed both tf::Executor and tf::Taskflow once to reuse it. Then I tried to construct them in each iteration cause I was suspicious that tasks are added and not erased from it's internals. It helped with next batches. Then I constructed executor once and taskflow for each iteration. I ended with times roughly 1.3 times worse than OneTBB. Much better than 100 times slower!

Then, obviously iterating throw each row means many calls to lambda function:

```cpp
taskflow.for_each_index(0, nRows, 1, [&](int i) { // not optimal
```

and this is a bit better
```cpp
//--- in constructor ---
        constexpr int rowsPerTask = 20;
        int iStart = 0, iEnd;
        do {
            iEnd = std::min(iStart + rowsPerTask, nRows);
            if (iEnd == iStart)
                break;
            ranges.push_back({ iStart, iEnd });
            iStart = iEnd;
        } while (true);
// --- time critical for loop ---
        tf::Taskflow taskflow;
        // tbb::parallel_for(tbb::blocked_range<int>(0, H, grainSize), [&](tbb::blocked_range<int>& range) {
        taskflow.for_each(ranges.begin(), ranges.end(), [&](const std::pair<int,int>& range) {
            // init constants
            const __m256 f_ = _mm256_set1_ps(f);
            // process image
            // (TBB code) for (int i = range.begin(); i < range.end(); ++i) {
            for (int i = range.first; i < range.second; ++i) {
                for (int j = jMin; j < jMax; j += 8) {
                    __m256 uCurrent = _mm256_load_ps(&u.at<float>(i, j));
            
// ---
private:
  std::vector<std::pair<int, int>> ranges;

```

Not only it's a bit better, it's better enough to outperform OneTBB. Not by much,

**Comment by tsung-wei-huang** [comment]
@pavel-perina thank you for the detailed information! Yes, creating an executor is quite expensive and you should reuse it as much as possible - similarly for `tf::Taskflow`. You can reuse `tf::Taskflow` by doing `tf::Taskflow::clear` to clean out the graph storage. 

The current implementation of Taskflow parallel algorithms is primarily based on the guided scheduling algorithm which typically performs best in irregular patterns. For regular workload (i.e., each iteration spends roughly the same time), the static partitioning from OpenMP is typically the best. However, this is something we can add to enhance the scheduling of Taskflow parallel algorithms.

**Comment by jspoxon** [comment]
Thank you for the insight. I think I'm starting to get a handle on things now.I'm not very familiar on how to use the lambda functions exactly inside my classes. If I have any more questions I'll let you know.
Jaime
    En martes, 7 de febrero de 2023, 18:19:14 CET, Tsung-Wei Huang ***@***.***> escribió:  
 
 


@pavel-perina thank you for the detailed information! Yes, creating an executor is quite expensive and you should reuse it as much as possible - similarly for tf::Taskflow. You can reuse tf::Taskflow by doing tf::Taskflow::clear to clean out the graph storage.

The current implementation of Taskflow parallel algorithms is primarily based on the guided scheduling algorithm which typically performs best in irregular patterns. For regular workload (i.e., each iteration spends roughly the same time), the static partitioning from OpenMP is typically the best. However, this is something we can add to enhance the scheduling of Taskflow parallel algorithms.
