### ISSUE TITLE
Does this project support save or load tasks? 

### ISSUE THREAD

**Issue by libaineu2004** [taskflow/taskflow#460]
Does this project support saving and loading tasks? 
Can Text Files (json, xml/etc) be used to define DAGs, which are then parsed by the Scheduler to form specific Task objects for execution?
My requirement is to save N tasks as a txt text file, then load the text file when the application is enabled, and then dynamically generate the individual tasks and run them.

**Comment by tsung-wei-huang** [comment]
@libaineu2004 We do not have this feature at this time - as it requires serializing a task and deserializing it back to the runtime.

**Comment by libaineu2004** [comment]
> @libaineu2004 We do not have this feature at this time - as it requires serializing a task and deserializing it back to the runtime.

Is there a plan to realize this function in the future?
