### ISSUE TITLE
Task Return value

### ISSUE THREAD

**Issue by 12real** [taskflow/taskflow#461]
**Please describe your feature request.**
How can i get a tf::task return value?

**Comment by tsung-wei-huang** [comment]
what do you mean by `tf::Task` return value?

**Comment by 12real** [comment]
Thank you for your reply! Like Thread in C++ ,when you create a task ,you will get a future variable . you can get task return value from future when task been finished!

**Comment by tsung-wei-huang** [comment]
I believe `tf::Executor::async` gives the thing you want :)

**Comment by 12real** [comment]
OK，thank you very much!
