### ISSUE TITLE
Compile error on VS 2022 in tsq.hpp

### ISSUE THREAD

**Issue by Ravbug** [taskflow/taskflow#463]
**Describe the bug**
After updating from to  3.4.0 to 3.5.0, `tsq.hpp` fails to compile in VS 2022 for x64 targets.
```
taskflow\core\tsq.hpp(109,32): error C2059: syntax error: 'constant' 
taskflow\core\tsq.hpp(110,17): error C2143: syntax error: missing ';' before '{'
taskflow\core\tsq.hpp(110,17): error C2447: '{': missing function header (old-style formal list?)
taskflow\core\tsq.hpp(260,32): error C2059: syntax error: 'constant'
taskflow\core\tsq.hpp(261,27): error C2653: 'TaskQueue': is not a class or namespace name 
```

**System Information:**
 - OS: Windows 10 22H2
 - VS: 2022 17.5.0 with MSVC 19.35.32215
- C++ version: 20

**Additional context**
Interestingly, the compile succeeds when targeting Windows ARM64.

**Comment by tsung-wei-huang** [comment]
There was a pull request about this issue caused by `MAX_PRIORITY` in the template argument. Could you please try the master branch and see if the problem is still there? Basically, the current master branch replaces all `MAX_PRIORITY` with `TF_MAX_PRIORITY`.

**Comment by Ravbug** [comment]
Updating to master resolved the issue, thank you!
