### ISSUE TITLE
Control the flow for large number of tasks?

### ISSUE THREAD

**Issue by KrishnaPG** [taskflow/taskflow#465]
Thank you for sharing this work. It looks great. 

Looking for a way to achieve the below (work-stealing producer-consumer) but could not find much info on how to achieve it with this library. Any help or relavant examples would be greatly appreciated.

Scenario is: 

  - One **producer** of tasks 
  - N **consumers** of tasks (say N == cores)
  - tasks are of different varieties and each may take **different time** to complete.

The producer produces a very large number of tasks continuously, but to avoid overflowing the consumers, it has to: 

  - first generate N tasks, so that the N consumers each can grab one task and start executing.
  - whenever a consumer is done with its task, producer produces the Next task

The question is: how to achieve this kind of **controlled flow** between the producer and consumers?

Specifically:

  - how to make the producer generate N tasks first and then **wait** for **any one task** to complete, 
  - and whenever a task is completed, generate the next task and **wait** again for any one task to complete? 

Most of the examples in the guide seem to be using "wait for all tasks" kind of mechanism, which is not what is needed here. Waiting for any one task to complete so that next can be produced forever in a loop (till some condition is met).

Help is greatly appreciated. Thank you.

**Comment by tsung-wei-huang** [comment]
Have you looked into our [conditional tasking](https://taskflow.github.io/taskflow/ConditionalTasking.html)? We may have `N` condition tasks forming `N` loops each iteratively grabbing one task from a centralized queue?

**Comment by KrishnaPG** [comment]
Thank you @tsung-wei-huang . Will look into it.
