### ISSUE TITLE
Scheduling a module task causes the executor to hang

### ISSUE THREAD

**Issue by derek-path** [taskflow/taskflow#468]
**Describe the bug**
Using a runtime task to schedule a module task causes the executor to hang after the module task has been executed.

**To Reproduce**
The following code will reproduce the bug.
Expected: The application prints:
```
m1
m2
B
C
```
and then exits normally.
Actual: The application prints 
```
m1
m2
```
and then hangs indefinitely.

```c++
#include <taskflow/taskflow.hpp>
#include <iostream>
#include <fstream>

int main()
{
  tf::Taskflow tf;

  auto a = tf.emplace([]() { std::cout << "A\n"; }).name("A");
  auto module_task = tf.placeholder().name("module");
  auto b = tf.emplace([]() { std::cout << "B\n"; }).name("B");
  auto c = tf.emplace([]() { std::cout << "C\n"; }).name("C");

  a.precede(module_task);
  module_task.precede(b);
  b.precede(c);

  tf::Taskflow module_flow;
  auto m1 = module_flow.emplace([]() { std::cout << "m1\n"; }).name("m1");
  auto m2 = module_flow.emplace([]() { std::cout << "m2\n"; }).name("m2");
  m1.precede(m2);

  module_task.composed_of(module_flow);

  // Attach an "entrypoint" to our taskflow which allows us to either execute it normally or schedule a subset of tasks
  auto entrypoint = tf.emplace([]() { return 0; }).name("entrypoint");
  auto schedule = tf.emplace([&](tf::Runtime& runtime) {
    runtime.schedule(module_task);  // When this schedules "a" or "b" the issue is not encountered
  }).name("schedule");
  entrypoint.precede(schedule, a);

  tf::Executor executor;
  executor.run(tf);

  std::ofstream out{ "/tmp/taskflow.dot" };
  tf.dump(out);

  return 0;
}
```

**Desktop:**
 - OS: Ubuntu 18.04 and Ubuntu 20.04
 - Browser: n/a
 - Version: master (a0b98e4ed), v3.5.0
 - g++: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
 - `g++ -std=c++17 main.cpp -lpthread`

**Additional context**
Modifying the runtime task to schedule either task "a" or task "b" results in the expected behavior. The application prints `A\nm1\nm2\nB\nC\n` and `B\nC\n` respectively and then exits normally.

**Comment by tsung-wei-huang** [comment]
@derek-path thanks for the issue! In fact, it is a bug when scheduling a nested flow explicitly.

At `taskflow/core/executor.hpp`, could you please modify the `Runtime::schedule` function as follows (with a 
new line of setting join counter to zero):

```cpp
inline void Runtime::schedule(Task task) {
  
  auto node = task._node;
  // add the following new line to solve the problem
  node->_join_counter.store(0, std::memory_order_relaxed);

  auto& j = node->_parent ? node->_parent->_join_counter :
                            node->_topology->_join_counter;
  j.fetch_add(1);
  _executor._schedule(_worker, node);
}
```

Let me know if this fixes your problem. I will do another thorough test and fix it in the main branch.

**Comment by tsung-wei-huang** [comment]
at main branch now - will be included to the next release.
