### ISSUE TITLE
documentation (corun / run_and_wait)

### ISSUE THREAD

**Issue by gegoggigog** [taskflow/taskflow#469]
**Please describe your feature request.**

It seems that the documentation at https://taskflow.github.io/taskflow/classtf_1_1Executor.html is mirroring the master branch, not the latest commit. E.g., `run_and_wait` is now `corun`.  I propose that the docs reflect the latest release. Even better would be if the docs had a scroll-down for each version, like the online docs for CMake (attached image).
![image](https://user-images.githubusercontent.com/1716001/225942576-4a57e0c1-8933-4ec7-8a58-e27cb0ec8c04.png)

**Comment by tsung-wei-huang** [comment]
@gegoggigog Thank you for the suggestion - and apologize for this breaking change which has been highlighted in our prospective release note [3.6.0](https://taskflow.github.io/taskflow/release-3-6-0.html). This is in fact a limitation of the m.css documentation generation tool we used. I will submit an issue to their github and see how that can be done.
