### ISSUE TITLE
cudaFlow has no member run

### ISSUE THREAD

**Issue by JosueGauthier** [taskflow/taskflow#470]
Hello,

I try to test cudaFlow (version of taskflow is 3.5.0) for a project and when the line ```cf.run(stream);``` is reach i get the error ```error: class "tf::cudaFlow" has no member "run"```. It seems that it is a version problem, the function run has been removed, but i build all my project with taskflow 3.5 so I would like to test it in 3.5.

I follow this chapter on the handbook (https://taskflow.github.io/taskflow/CompileTaskflowWithCUDA.html) and i found nothing on internet how to proceed in 3.5. 

I check on cuda/cudaflow.hpp and indeed the run function of streams disappear but i found nothing on internet how to use it now. 

Thank you, 

Example : 
```

#include <taskflow/taskflow.hpp>
#include <taskflow/cudaflow.hpp>  
#include <taskflow/cuda/for_each.hpp>

int main(int argc, const char** argv) {

  tf::Executor executor;
  tf::Taskflow taskflow;

  tf::Task task1 = taskflow.emplace([](){}).name("cpu task");
  tf::Task task2 = taskflow.emplace([](){
    // create a cudaFlow of a single-threaded task
    tf::cudaFlow cf;
    cf.single_task([] __device__ () { printf("hello cudaFlow!\n"); });
    
    // launch the cudaflow through a stream
    tf::cudaStream stream;
    cf.run(stream);
    stream.synchronize();
  }).name("gpu task");

  task1.precede(task2);

  executor.run(taskflow).wait();
  return 0;
}


```

**Comment by tsung-wei-huang** [comment]
@JosueGauthier this is a new change that will be available in the next release 3.6.0 - currently at the master branch.
