### ISSUE TITLE
Discussion: Task parallizing library vs Asycrhonous programming

### ISSUE THREAD

**Issue by Weaverzhu** [taskflow/taskflow#474]
I'm seeing a lot of people wanting for

1. dynamically submiting tasks
2. submit task to a taskflow during its execution

In my opinion taskflow is a static computation graph like tensorflow 1.x. It can be 'dynamic' by creating a static computation graph(Subflow) during the runtime ([Dynamic Tasking](https://github.com/taskflow/taskflow#dynamic-tasking)).

Meanwhile, a taskflow can be a real dynamic computation graph. By using `await` keyword one can specify dependency between different nodes, and the whole graph will be evaluated in reverse topology order, but run in the right topology order. This makes dynamically composing the graph possible. In cpp I believe we can achieve it by c++20 coroutines.

Taskflow execute the graph in normal topology order, so changing the graph during the runtime can be painful (or maybe we can carefully handle the multithreading on the graph).

I would like to know if my options are right or not? And how do you think about the `real dynamic computation graph`? Is it possible to make Taskflow a dynamic computation graph?

**Comment by tsung-wei-huang** [comment]
Yes, this is a feature we are planning to have in the near future of Taskflow. Basically there will be an interface similar to `tf::Executor::async` but user can express dynamic dependencies among async tasks. 

I do not think the current dynamic graph or dynamic tasking can meet this purpose because of `tf::Subflow` basically still requires an up-front description of the graph. 

Hopefully, this new async interface will come out soon...

**Comment by tsung-wei-huang** [comment]
@Weaverzhu We have the first version of dynamic task graph parallelism using [dependent asynchronous tasking](https://taskflow.github.io/taskflow/DependentAsyncTasking.html). It is being experimented in both master and dev branches and will be included in the next release 3.6.0. 

Please give it a try :)

**Comment by Weaverzhu** [comment]
> @Weaverzhu We have the first version of dynamic task graph parallelism using [dependent asynchronous tasking](https://taskflow.github.io/taskflow/DependentAsyncTasking.html). It is being experimented in both master and dev branches and will be included in the next release 3.6.0.
> 
> Please give it a try :)

Sounds very cool, I'm going to play with it right now!

Besides, what do you think of making dag computation graphs using asychronous programming models like `async/await` or `future/promise`? What will the differences between them and taskflow in your opinions? (performance, easy to use or so on)

[Folly FutureDAG example in unittest](https://github.com/facebook/folly/blob/main/folly/experimental/test/FutureDAGTest.cpp#L196)

Its [implementation](https://github.com/facebook/folly/blob/main/folly/experimental/FutureDAG.h) is very simple compared to taskflow. I believe the [coroutine](https://github.com/facebook/folly/tree/main/folly/experimental/coro) version of DAG will be even cleaner.

One of the major challenge I met with taskflow is that: my workload is consists of both on-cpu tasks and off-cpu tasks(many rpc call for 10ms-500ms+).

If I put all of the workload into taskflow, the number of thread cannot be set to `std::thread::hardware_concurrency` because of the blocking calls of rpc are really time-cosuming, but setting too many threads will also cause performance problems, resulting in measurable cost of (workstealing or yield), saw in flamegraph.

Lastly, the **dynamic schedule** during the runtime is somehow restricted, basically it's very hard to modify the current running taskflow.

Let's say `A.precede(B)`. It's not safe to make `A.precede(C)` while running A because C may have run already, but it does make sense to make `A.succeed(C)` while running A, and the syntax can always be satisfied, no matter whether C has run or not.

However, I saw you also replied for https://github.com/taskflow/taskflow/issues/408#issuecomment-1161913191. Hopefully the new api solves all the problems.

**Comment by tsung-wei-huang** [comment]
It depends on your application. If it is IO-driven, coroutine-based asynchronous programming is definitely the one that you should be looking for. However, our users have also been using [tf::Executor::corun](https://taskflow.github.io/taskflow/classtf_1_1Executor.html#a8fcd9e0557922bb8194999f0cd433ea8) to avoid blocking wait on many asynchronous calls, and Taskflow's work-stealing is actually very good in many cases that coroutines can do.

In my experience, modifying the structure of existing task graph is very difficult and not quite practical in many applications. It makes tracking and debugging extremely difficult. The new dynamic task graph programming model in v3.6.0 only allows creating a task graph dynamically, and you can only relate a dependency from a creating task to a previously created task.

I hope this makes sense to u :)

**Comment by Weaverzhu** [comment]
Thanks for the quick reply!

So, to conclude, `tf::Executor::corun` can avoid block-waiting for another `Taskflow`, but cannot avoid block-waiting on some IO workload? Otherwise, rpc client likes `grpc` should provide an api call that returns a `tf::Task` or `tf::Taskflow` for users.

Now I'm looking into the new async api, and also interested in how far can work-stealing go. I may even try to equip coroutine executor with work-stealing. I think I don't other questions until I figure out things above more, closing this issue.
