### ISSUE TITLE
How to observe/profile the `tf::Pipe` steps in a `tf::PipeFlow`?

### ISSUE THREAD

**Issue by antonysigma** [taskflow/taskflow#476]
Thank you for introducing the `tf::Pipeflow` syntax to construct a processing pipeline decoupled from the data buffer. Quick question, is there a way to label the `tf::Pipe` with `std::string` or `std::string_view` ?

For example, how do I modify the Taskflow source code to implement this:
```c++
CritialSection write_lock{1};

Pipeflow my_pipeflow{
    Pipe{SERIAL, [&]() { /* Read task */ }, "Read pipe"},
    Pipe{PARALLEL, [&]() { /* Process task */ }, "Process pipe"},
    Pipe{PARALLEL, [&, &write_lock]() { /* Process task */ }, "Write pipe"},
};
```

In order to export the Chromium tracing file having the timing information? Like this mock up visualization:
![image](https://user-images.githubusercontent.com/12185630/230954821-418a48c0-d098-45e1-8d9f-2f83424e0241.png)

**Comment by antonysigma** [comment]
Follow up question: does `tf::Pipeflow` guarantee thread affinity of the pipeline? In other words, if I coded the `ReadPipe` to store data to (L2/L3) cache in thead #1, does the `ProcessPipe` read the same data from thread #1 as well? 

I am aware that the logical thread affinity is different from physical CPU core affinity, like what we do with the NUMA architecture. Agreed that CPU affinity requirement of out of the Taskflow project scope.

**Comment by tsung-wei-huang** [comment]
@antonysigma Taskflow does not process pipes in any specific order but use one task per line to process pipes. So, it's difficult to visualize the execution on a per-pipe basis because a worker can fuse adjacent pipes in one execution to reduce scheduling overhead.

Does this make sense?

**Comment by antonysigma** [comment]
Thanks that's clear. Actually, I am in favor of the single worker per pipe design choice to reduce scheduling overhead. I can also confirm the single worker design from the Pipeflow source code.

Closing this thread...
