### ISSUE TITLE
Pin specific pipe to specific CPU core (set affinity of pipe).

### ISSUE THREAD

**Issue by joshuaahklein** [taskflow/taskflow#480]
Based on some prior issues (#190, #477) it's unclear if this is already implemented or not.  So I would like to ask if this is possible.

If it is already possible, it would be great to have some example code to look at and/or possibly a recipe in the documentation.

But assuming it isn't, I would like for there to be some way of setting the hardware thread affinity of specific pipes.  I imagine this could be implemented as a condition to the task assignment algorithm itself (e.g., only assign task if w.id() == X) in conjunction with the extended worker interface (scheduler_prologue --> setAffinity(w.id())).

**Comment by tsung-wei-huang** [comment]
@joshuaahklein thanks for bringing this up. Currently, we do not have this feature to affine a pipe to a specific thread. This is a result of our work-stealing scheduler algorithm that does not allow us to wake up a specific thread ID.
