### ISSUE TITLE
Asynchronous tasking with module tasks 

### ISSUE THREAD

**Issue by marcin-ochman** [taskflow/taskflow#485]
**Describe the bug**

Dear Taskflow Team,

First of all, I would like to thank you for providing such an excellent library.

However, I have encountered a problem with asynchronous tasking. Attached below is a program that reproduces this issue. It comprises three module tasks: `inputTask`, `processTask`, and `outputTask`. One of the tasks in `processTask`, namely `processB`, runs an asynchronous task periodically. Regrettably, profiling has shown that async task occasionally "becomes" part of the `processTask` module. As a result, the `processTask` takes more time than it normally should (it should typically take ~ (15 + 20) ms). I reproduced issue on both Windows and Linux systems.

Is this a bug, or is it functioning as expected? If this isn't a bug, could you suggest how such a situation could be avoided?

**To Reproduce**
Our task graph is much more complicated, however the code below is sufficient to reproduce the issue:

```cpp
#include <chrono>
#include <iostream>
#include <taskflow/taskflow.hpp>
#include <thread>

void sleep_for(int ms) {
  using namespace std::chrono_literals;

  std::this_thread::sleep_for(std::chrono::milliseconds(ms));
}

int main() {
  tf::Executor executor(2);
  tf::Taskflow mainTaskflow, input, process, output;

  auto [inputA, inputB] = input.emplace(
      []() {
        sleep_for(10);
        std::cout << "InputA\n";
      },
      []() {
        sleep_for(10);
        std::cout << "InputB\n";
      });

  inputA.precede(inputB);

  auto [processA, processB, processC] = process.emplace(
      []() {
        sleep_for(15);
        std::cout << "ProcessA\n";
      },
      [&executor]() {
        sleep_for(20);
        static int i = 0;

        // schedule long async periodically
        //
        if (i % 40 == 0) {
          executor.silent_async([i = i]() {
            std::cout << "Async Task started " << i << "\n";
            sleep_for(400);
            std::cout << "Async Task finished " << i << "\n";
          });
        }

        ++i;

        std::cout << "ProcessB\n";
        return i != 10;
      },

      []() {
        sleep_for(1);
        std::cout << "ProcessC\n";
      });

  auto processEnd = process.placeholder().name("End Process");
  processA.precede(processB);
  processB.precede(processC, processEnd);

  auto outputA = output.emplace([]() {
    sleep_for(5);
    std::cout << "OutputA\n";
  });

  auto inputTask = mainTaskflow.composed_of(input);
  auto processTask = mainTaskflow.composed_of(process);
  auto outputTask = mainTaskflow.composed_of(output);

  inputTask.precede(processTask);
  processTask.precede(outputTask);

  inputA.name("InputA");
  inputB.name("InputB");
  processA.name("ProcessA");
  processB.name("ProcessB");
  processC.name("ProcessC");
  outputA.name("OutputA");
  inputTask.name("InputTask");
  processTask.name("ProcessTask");
  outputTask.name("OutputTask");

  std::ofstream f{"graph.txt"};
  mainTaskflow.dump(f);

  for (auto i = 0; i < 500; ++i)
    executor.run(mainTaskflow).wait();
}


```

1. Compile
2. Run
3.  The issue reveals when sudden "pause" of processing happens.
4. Analyze profiling, look for long `processTask` running > 400ms.

**Screenshots and files**

![image](https://github.com/taskflow/taskflow/assets/55946922/fa6d87ef-ba60-4fe4-9058-de03db094558)
![image](https://github.com/taskflow/taskflow/assets/55946922/ca46d54c-f3d0-4acc-ba5b-e381046177f5)

For more information have a look at profiling data and analyze it in your profiling tool:
[profiling_async_issue.zip](https://github.com/taskflow/taskflow/files/11582951/profiling_async_issue.zip)

**Desktop**
 - OS:Windows, Linux
 - Version 3.4.0

**Comment by tsung-wei-huang** [comment]
Hi @marcin-ochman , thanks for your message! This is not a bug but an expected behavior of the current scheduling method. When a module is invoked, the executor will run it through [_invoke_module_task](https://github.com/taskflow/taskflow/blob/9e4a095602a0af2d4de473214d3da9f17e17ed26/taskflow/core/executor.hpp#L1853) which in turn goes to [_consume_graph](https://github.com/taskflow/taskflow/blob/9e4a095602a0af2d4de473214d3da9f17e17ed26/taskflow/core/executor.hpp#L1790) and [_corun_until](https://github.com/taskflow/taskflow/blob/9e4a095602a0af2d4de473214d3da9f17e17ed26/taskflow/core/executor.hpp#L1249). Inside the corun method, the worker that runs your module task `m2` will [loop the work-stealing](https://github.com/taskflow/taskflow/blob/9e4a095602a0af2d4de473214d3da9f17e17ed26/taskflow/core/executor.hpp#L1255) until the predicate becomes zero. If that worker steals an async task, it will sleep for 400 ms which causes the async task to participate in the module task - as you have observed from the long runtime of module task.

I will see what I can do to avoid this problem, but in the meanwhile, a simple fix is to flat out `m2` to avoid spawning async tasks from a module task.

**Comment by marcin-ochman** [comment]
Thank you for your response. It would be great to avoid such a problem, because it doesn't seem obvious at first. What about version 3.6.0, is it the same?

**Comment by tsung-wei-huang** [comment]
Yes - this is actually unexpected, and thanks for pointing it out. I will see what I can do to enhance it in the next release.

**Comment by marcin-ochman** [comment]
Yes, I'll try it and let you know whether problem still exists or not. Thank you

**Comment by marcin-ochman** [comment]
@tsung-wei-huang - I've just tested dev branch. The problem doesn't reproduce anymore. Thank you very much for your quick responses and fix.

**Comment by tsung-wei-huang** [comment]
Thanks for pointing out this problem!

**Comment by makeuptransfer** [comment]
what if call excutor.async in a subflow？will still hava a chance to accmulate the time cost by aysnc task into subflow？just a guess

**Comment by makeuptransfer** [comment]
what if there is a subflow in a module and call excutor.async in the subflow，this will still suffer from this problem，i think the question is how to define a module‘s correct behavior
