### ISSUE TITLE
reusable TaskQueue 

### ISSUE THREAD

**Issue by 13015517713** [taskflow/taskflow#488]
The top and bottom pointers of _wsq(TaskQueue in Executor) are increasing when the executor object is used to execute taskflow multiple times. There is a risk of overflow and resource waste. 

Is it possible to consider:
- add func to clear storage in TaskQueue
- resetting the pointer and storage of TaskQueue after execution in Executor

**Comment by tsung-wei-huang** [comment]
@13015517713 in fact you are right, but in practice, this is very very less likely to happen, given that both `top` and `bottom` are 64-bit integers, which are enough to represent very big and fast work-stealing workload. The details can be referred to [this paper](https://www.dre.vanderbilt.edu/~schmidt/PDF/work-stealing-dequeue.pdf).

**Comment by 13015517713** [comment]
Indeed, there is probably no such scenarios, as the executor object is not required to have state. If necessary, it is enough to create a new executor object directly.
