### ISSUE TITLE
The standard algorithms are not available by includes taskflow/taskflow.hpp

### ISSUE THREAD

**Issue by bradphelan** [taskflow/taskflow#490]
**Describe the bug**
Many of the algorithms are forward declared by including ``taskflow/taskflow.hpp`` but are only available if ``taskflow/algorithm/*.hpp`` is explicity included.

This causes confusion as there end up being linker errors rather than compiler errors. I don't see anywhere in the documentation to indicate that extra includes are required to use the algorithms.

I see a few possible solutions.

1. Include all the algorithm header files from taskflow/taskflow.hpp
2. Do not forward declare the algorithm on the builder class. ( this is difficult because c++ does not support mixins ). Perhaps use ADL instead of members.
3. Document clearly that the current behaviour requires including the algorithm header files and that if you don't you will see linker errors.

**Comment by tsung-wei-huang** [comment]
Hi @bradphelan thanks for pointing this out. I believe each page of the algorithm documentation has mentioned the necessary file to include, like [parallel iteration header](https://taskflow.github.io/taskflow/ParallelIterations.html#ParallelIterationsIncludeTheHeader).

**Comment by bradphelan** [comment]
Ok. I guess I just ended up directly at the class documentation directly

https://taskflow.github.io/taskflow/classtf_1_1FlowBuilder.html

which doesn't detail the include requirements.

**Comment by tsung-wei-huang** [comment]
That's a good point - I will modify them in the next release.
