### ISSUE TITLE
ForLoop creating tasks cannot work

### ISSUE THREAD

**Issue by BCSN000001** [taskflow/taskflow#491]
Dear team,

      For below c++ codes, it cannot work.
      If I replace 

                   for (size_t i = 0; i < subgroup_names.size(); ++i)
		{
			task_map[subgroup_names[i]] = &taskflow.emplace(
				[&]() { ordered_subgroup_names.emplace_back(subgroup_names[i]); });
		} 

         by 

		task_map["A"] = &taskflow.emplace(
			[&]() { std::cout << "TaskA\n"; ordered_subgroup_names.emplace_back("A"); });
		task_map["B"] = &taskflow.emplace(
			[&]() { std::cout << "TaskB\n"; ordered_subgroup_names.emplace_back("B"); });
		task_map["C"] = &taskflow.emplace(
			[&]() { std::cout << "TaskC\n"; ordered_subgroup_names.emplace_back("C"); });
		task_map["D"] = &taskflow.emplace(
			[&]() { std::cout << "TaskD\n"; ordered_subgroup_names.emplace_back("D"); });

          then it works. Could you take a look at? Many tks.

                tf::Executor executor;
		tf::Taskflow taskflow;

		const std::vector<std::string>& subgroup_names = { "B", "A", "D", "C" };
		std::vector<std::string> ordered_subgroup_names;
		std::unordered_map<std::string, tf::Task*> task_map;

		// Create task map for each subgroup name
		for (size_t i = 0; i < subgroup_names.size(); ++i)
		{
			task_map[subgroup_names[i]] = &taskflow.emplace(
				[&]() { ordered_subgroup_names.emplace_back(subgroup_names[i]); });
		}

		//task_map["A"] = &taskflow.emplace(
		//	[&]() { std::cout << "TaskA\n"; ordered_subgroup_names.emplace_back("A"); });
		//task_map["B"] = &taskflow.emplace(
		//	[&]() { std::cout << "TaskB\n"; ordered_subgroup_names.emplace_back("B"); });
		//task_map["C"] = &taskflow.emplace(
		//	[&]() { std::cout << "TaskC\n"; ordered_subgroup_names.emplace_back("C"); });
		//task_map["D"] = &taskflow.emplace(
		//	[&]() { std::cout << "TaskD\n"; ordered_subgroup_names.emplace_back("D"); });

		for (size_t i = 0; i < subgroup_names.size(); ++i)
		{
			std::vector<std::string> precedes;
			if (subgroup_names[i] == "A")
				precedes = { "B", "C" };
			for (auto precede : precedes)
			{
				if (task_map.count(precede) > 0)
					task_map[subgroup_names[i]]->precede(*task_map[precede]);
			}
			std::vector<std::string> succeeds;
			if (subgroup_names[i] == "D")
				succeeds = { "B", "C" };
			for (auto succeed : succeeds)
			{
				if (task_map.count(succeed) > 0)
					task_map[subgroup_names[i]]->succeed(*task_map[succeed]);
			}
		}
		executor.run(taskflow).wait();

**Comment by tsung-wei-huang** [comment]
This is a common mistake by misuse of C++ lambda. Your code capture `i` in reference which will change at every iteration:

```
task_map[subgroup_names[i]] = &taskflow.emplace(
			[&]() { ordered_subgroup_names.emplace_back(subgroup_names[i]); }
);
```

You should capture `i` by copy otherwise its value will change when you move on to the next iteration of creating the task:

```
task_map[subgroup_names[i]] = &taskflow.emplace(
			[i]() { ordered_subgroup_names.emplace_back(subgroup_names[i]); }
);
```

**Comment by BCSN000001** [comment]
Many tks! ^_^
