### ISSUE TITLE
make_for_each_index_task() function missing definition of distance()

### ISSUE THREAD

**Issue by kevincopps** [taskflow/taskflow#495]
The `make_for_each_index_task()` function in `for_each.hpp` is missing the definition of `distance()` from `util/iterator.hpp`.

This can cause a compilation error depending on which taskflow headers you `#include`.

For example, including only: 

```
#include <taskflow/core/flow_builder.hpp>
#include <taskflow/core/task.hpp>
#include <taskflow/algorithm/sort.hpp>
#include <taskflow/algorithm/for_each.hpp>
```

in a compilation unit will cause the error.

**Comment by tsung-wei-huang** [comment]
@kevincopps thanks for pointing this out! did you include `taskflow.hpp` in the top?

**Comment by kevincopps** [comment]
I did not include `taskflow/taskflow.hpp`. Should it always be included?

**Comment by tsung-wei-huang** [comment]
Yes, the correct order should be 

```
#include <taskflow/taskflow.hpp>
#include <taskflow/algorithm/sort.hpp>
#include <taskflow/algorithm/for_each.hpp>
```
