### ISSUE TITLE
在序列化模板类中的一部分实现问题

### ISSUE THREAD

**Issue by xclhs** [taskflow/taskflow#498]
for(size_t i=0;i<num_data;++i){
             sz+= _load(make_kv_pair(k,v));
             hint=t.emplace_hint(hint,std::move(k),std::move(v));
         }
         return sz;
这里为什么move以后还能load，不会导致未定义的行为吗？

**Comment by tsung-wei-huang** [comment]
we load it first before move

**Comment by xclhs** [comment]
已收到~ thanks
