### ISSUE TITLE
std::packaged_task can't be used to collect exception because Executor::async requires copy constructible task

### ISSUE THREAD

**Issue by bradphelan** [taskflow/taskflow#499]
**Describe the bug**
A design issue in taskflow doesn't set the exception on the future. This really should be fixed as it not obvious how to deal with exceptions here.

https://godbolt.org/z/7Md9v3xPe

The workaround attempted is to use std::packaged_task like so

https://godbolt.org/z/zfnzhaMa6

but this does not work because the task used by Excecutor::async is copied rather than moved.

Wrapping the packaged_task in a shared_ptr and then wrapping again with a lambda solves the problem but at the expensive of dynamic memory allocation.

**Comment by tsung-wei-huang** [comment]
@bradphelan  the exception support is up in the current master/dev branch. Examples can be found [here](https://taskflow.github.io/taskflow/ExceptionHandling.html). Please share any feedback. This support will be part of release v3.7. 

Thank you for your contributions!
