### ISSUE TITLE
Is the data structure used in this project DAG?

### ISSUE THREAD

**Issue by libaineu2004** [taskflow/taskflow#503]
DAG:Directed Acyclic Graph

1.Is the data structure of "taskflow" a graph or a tree?
2.If it is a graph, is it acyclic or cyclic?
3.Is there any documentation that explains the principles of each node/task traversal? Is it depth-first or breadth-first?

**Comment by tsung-wei-huang** [comment]
1. It is a tree.
2. It can be cyclic with conditional tasking.
3. We do not do any traversal but schedule tasks whenever their dependencies are met.
