### ISSUE TITLE
Per chunk RAII support

### ISSUE THREAD

**Issue by bradphelan** [taskflow/taskflow#504]
**Issue Summary:**

We are encountering a problem related to managing floating point exceptions (FPU) on the CPU. Currently, we are using a workaround involving a lambda function to maintain FPU settings across subtasks, but this approach is both costly and inefficient. Instead, we need to implement a default chunk wrapper that applies FPU settings at the start of a task and restores the previous FPU state at the task's end. This change will optimize performance and prevent corruption of tasks that yield to the executor.

**Problem Description:**

We need to manage the FPU settings for CPU operations in our code. The challenge is ensuring that all subtasks created after setting the FPU context inherit the parent task's FPU settings. Currently, we achieve this by encapsulating the loop body within a lambda function. This lambda function captures the FPU state before calling `executor.corun` and then applies this FPU state on every iteration of the loop. However, this approach has proven to be inefficient and resource-intensive.

The inefficiency arises from the overhead associated with making these FPU state calls on every iteration of the loop. Moreover, this approach is unnecessary as FPU settings only need to be applied at the beginning of each chunk or task. At the end of each task, we must also restore the previous FPU state to avoid corrupting any tasks that have yielded to the executor at this point.

**Proposed Solution:**

To address this problem efficiently, we propose implementing a default chunk wrapper for all algorithms. This wrapper would take care of applying the necessary FPU settings at the beginning of each chunk or task, and it would ensure the restoration of the previous FPU state at the task's end. By doing so, we can eliminate the overhead and inefficiency associated with applying FPU settings on every loop iteration, resulting in improved performance and avoiding task corruption issues.

**Desired Outcome:**

Implement a default chunk wrapper that handles FPU settings at the start and end of tasks, optimizing performance and preventing task corruption issues. This change will simplify code and improve overall efficiency in managing floating point exceptions on the CPU.

**Psuedo Code**

```
auto defaultChunkWrapper = [](auto && chunkRunner){
    std::forward<decltype(chunkRunner)>(chunkRunner());
};
```

however in our case we want something like

```
FPUSaver saver;
auto fpuChunkWrapper = [&saver](auto && chunkRunner){
    // Appy stored FPU settings to the current tasks and
    // restore the FPU setting as the end of the task
    FPUApplier applier(saver);
    std::forward<decltype(chunkRunner)>(chunkRunner());
};

Taskflow taskflow;
taskflow.for_each_index(0,10000,1,[](double i){  
     // trigger FP exception
     i / 0.0;
}, tf::DynamicPartioner(), chunkRunner);

executor.corun(taskflow);
```

The global https://taskflow.github.io/taskflow/classtf_1_1ObserverInterface.html interface doesn't really solve the problem in an elegant way.

**Comment by bradphelan** [comment]
The patch I'm working on now has the following support.

```
// ChunkContext
TEST_CASE("Chunk.Context" * doctest::timeout(300))
{


  for (int tc = 4; tc < 64; tc++)
  {
    tf::Executor executor(tc);
    std::atomic<int> startCount = 0;
    auto task_wrapper = [&](auto &&task)
    {
      startCount++;
      task();
    };
    std::atomic<int> count = 0;
    tf::Taskflow taskflow;
    taskflow.for_each_index(
        0, 100, 1, [&](int i)
        { count++; },
        tf::StaticPartitioner(1), task_wrapper);
    executor.run(taskflow).wait();

    REQUIRE(count == 100);
    REQUIRE(startCount == tc);
    
  }
}
```

whereby

```
// Function: for_each_index
template <typename B, typename E, typename S, typename C, typename P, typename W>
Task FlowBuilder::for_each_index(B beg, E end, S inc, C c, P&& part, W&&task_wrapper){
  return emplace(
    make_for_each_index_task(beg, end, inc, c, std::forward<P>(part), std::forward<W>(task_wrapper))
  );
}
```

**Comment by tsung-wei-huang** [comment]
How about we combine part with task_wrapper?

```cpp
tf::Executor executor(tc);
std::exception_ptr x;
tf::StaticPartitioner part(1, [&](auto &&task){
  try {
  task();
  }catch(...){
    x = std::current_exception();
  }
});

std::atomic<int> count = 0;
tf::Taskflow taskflow;
taskflow.for_each_index(
    0, 100, 1, [&](int i)
    { count++; },
    tf::StaticPartitioner(1)
);
executor.run(taskflow).wait();
if(x)
   std::rethrow_exception(exceptionPtr);
```
