### ISSUE TITLE
Executing task before all preceding task have been completed

### ISSUE THREAD

**Issue by Levi-Armstrong** [taskflow/taskflow#508]
**Describe the bug**
I am experiencing an issue where tasks are being ran before all predecessor have finished. In the image below I am seeing that TaskF starts immediately after TaskD finished and does not wait for the preceding Tasks B, C and E to have completed. Is this expected behavior?

**Screenshots**
![image](https://github.com/taskflow/taskflow/assets/9803128/5f2fca2b-9862-402b-99e7-fa0a980d4094)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Additional context**
Taskflow version 3.5.0

**Comment by Levi-Armstrong** [comment]
@tsung-wei-huang  I am not sure what is going on but something seem very wrong.

``` c++
  tf::Executor executor;
  tf::Taskflow taskflow;

  auto [A, B, C, D, E, F, G, Sync, Done, Abort] = taskflow.emplace(
    [] () { std::cout << "TaskA\n"; return 1; },
    [] () { std::cout << "TaskB\n"; sleep(5); return 1; },
    [] () { std::cout << "TaskC\n"; sleep(5); return 1; },
    [] () { std::cout << "TaskD\n"; return 1; },
    [] () { std::cout << "TaskE\n"; return 1; },
    [] () { std::cout << "TaskF\n"; return 1; },
    [] () { std::cout << "TaskG\n"; return 1; },
    [] () { std::cout << "TaskSync\n"; },
    [] () { std::cout << "TaskDone\n"; },
    [] () { std::cout << "TaskAbort\n"; }
  );

  A.precede(Abort, Sync);
  Sync.precede(D, B, C);
  B.precede(Abort, E);
  C.precede(Abort, E);
  D.precede(Abort, F);
  E.precede(Abort, F);
  F.precede(Abort, G);
  G.precede(Abort, Done);

  executor.run(taskflow).wait();
```

![image](https://github.com/taskflow/taskflow/assets/9803128/5c8a02a3-f997-4263-a908-ce0ecd55c7fe)

``` bash
TaskA
TaskSync
TaskC
TaskD
TaskF
TaskG
TaskDone
TaskB
TaskE
TaskF
TaskG
TaskDone
TaskE
TaskF
TaskG
TaskDone
```

**Comment by Levi-Armstrong** [comment]
I believe this has something todo with the [scheduling policy](https://taskflow.github.io/taskflow/ConditionalTasking.html#TaskSchedulingPolicy). Has this always been the case?


> When you submit a task to an executor, the scheduler starts with tasks of zero dependents (both zero strong and weak dependencies) and continues to execute successive tasks whenever their strong dependencies are met. However, the scheduler skips this rule when executing a condition task and jumps directly to its successors indexed by the return value.

**Comment by Levi-Armstrong** [comment]
The issue was related to how the scheduling policy works. I assume it has always functioned this way and I am surprised I have never experienced this behavior before.

**Comment by tsung-wei-huang** [comment]
@Levi-Armstrong yes, this is how the conditional tasking works in scheduling. Some people may use [tf::Runtime](https://taskflow.github.io/taskflow/RuntimeTasking.html) to enforce their own scheduling methods.

**Comment by Levi-Armstrong** [comment]
Thank you for the info.
