### ISSUE TITLE
Is tf::taskflow re-entrant with .sort()?

### ISSUE THREAD

**Issue by lhog** [taskflow/taskflow#511]
Hi!

I wonder if I make a logical mistake here. `tf::Taskflow taskflow;` is located outside of repeating loop and this code is certainly broken on MSVC 2022. In debug mode I get `"cannot seek invalidated vector iterator"` exception thrown after the first loop is done, the release mode just crashes after a few loops.

```
    std::vector<int> data = generateRandomVector(numElements);
    std::vector<int> data2;

    tf::Executor executor(std::thread::hardware_concurrency());
    tf::Taskflow taskflow;
    for (int i = 0; i < 100; ++i) {
        data2 = data;

        taskflow.sort(data2.begin(), data2.end(), std::less{});
        executor.run(taskflow).wait();
    }
```
while with `tf::Taskflow taskflow;` put inside the loop the code works perfectly:
```
    std::vector<int> data = generateRandomVector(numElements);
    std::vector<int> data2;

    tf::Executor executor(std::thread::hardware_concurrency());
    for (int i = 0; i < 100; ++i) {
        data2 = data;
        tf::Taskflow taskflow;
        taskflow.sort(data2.begin(), data2.end(), std::less{});
        executor.run(taskflow).wait();
    }
```

If taskflow object us not meant to be re-entrant, perhaps the right way is to throw an exception in case the "consumed" object is getting run() once again, otherwise if it's ok to execute it once again, we may have a bug here.

**Comment by tsung-wei-huang** [comment]
@lhog every time you call `taskflow.sort` it creates a task in that taskflow to sort the given range. So, in your first example, you essentially end up with creating 100 parallel-sort tasks to sort data2 - which also give you data race. 

In the second example, `taskflow` is wrapped in an RAII scope. So you only end up with one parallel-sort task to sort data2 at each iteration.

Does this make sense to you ?

**Comment by lhog** [comment]
Makes perfect sense now @tsung-wei-huang My understanding of what `tf::Taskflow` do and doesn't was completely off.
Thanks a lot for clarification!
