### ISSUE TITLE
Compiler error on VS2022 17.7.3 - easy fix

### ISSUE THREAD

**Issue by damienhocking** [taskflow/taskflow#512]
Using the latest VS2022 and latest code for TaskFlow, there's a compiler error in executor.hpp. 

error C2665: 'std::atomic_flag::atomic_flag': no overloaded function could convert all the argument types
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\atomic(2886): note: could be 'std::atomic_flag::atomic_flag(const std::atomic_flag &)'
E:\pathtotaskflow/executor.hpp(1046): note: 'std::atomic_flag::atomic_flag(const std::atomic_flag &)': cannot convert argument 1 from 'initializer list' to 'const std::atomic_flag &'

At line 1046 you have 

std::atomic_flag _all_spawned {false};

std::atomic_flag isn't convertible to a bool. In the C++ standard, initialization is described this way:

https://en.cppreference.com/w/cpp/atomic/ATOMIC_FLAG_INIT

So line 1046 should be:

std::atomic_flag _all_spawned = ATOMIC_FLAG_INIT;

This fixes the compiler error.

**Comment by tsung-wei-huang** [comment]
@damienhocking thank you for the catch! Would you like to create a pull request to help fix it?  Thanks!

**Comment by damienhocking** [comment]
Yep can do.

**Comment by tsung-wei-huang** [comment]
I have fixed it and will include it in the next release.

**Comment by damienhocking** [comment]
Oh I'm so sorry. This slipped my mind with work.
