### ISSUE TITLE
Failed generating docs

### ISSUE THREAD

**Issue by alanzhai219** [taskflow/taskflow#513]
**Describe the bug**
Follow the guide: https://taskflow.github.io/taskflow/install.html#BAIBuildDocumentation
But can't generate the docs.
Error is:
```bash
./doxygen.py /path/to/taskflow/doxygen/conf.py
Traceback (most recent call last):
  File "/path/to/m.css/documentation/./doxygen.py", line 4013, in <module>
    subprocess.run(["doxygen", doxyfile], cwd=os.path.dirname(doxyfile), check=True)
  File "/path/to/conda/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/path/to/conda/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/path/to/conda/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'doxygen'
```

**To Reproduce**
1. Go to 'https://taskflow.github.io/taskflow/install.html#BAIBuildDocumentation'
2. `pip install jinja2 Pygments`
3. clone taskflow and m.css
4. `./doxygen.py /path/to/taskflow/doxygen/conf.py`

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Py: 3.9.12

**Additional context**
N/A.

**Comment by tsung-wei-huang** [comment]
Have you installed `doxygen` on your machine?

**Comment by alanzhai219** [comment]
@tsung-wei-huang That works for me.
`sudo apt-get install doxygen graphviz`
Thanks a lot.
