### ISSUE TITLE
How to transfer data between nodes?

### ISSUE THREAD

**Issue by libaineu2004** [taskflow/taskflow#514]
1、How to transfer data between nodes?

example: A/B/C/D
How do A/B/C/D transfer data to each other?
For example, the output result of A needs to be used as the input of C.
The output results of B and C serve as the input of D.
If a computing exception occurs on node A, then C will no longer run, and each error message should be displayed.
Can you write an example?

2、code
#include <taskflow/taskflow.hpp>  // Taskflow is header-only

int main(){
  
  tf::Executor executor;
  tf::Taskflow taskflow;

  auto [A, B, C, D] = taskflow.emplace(  // create four tasks
    [] () { std::cout << "TaskA\n"; },
    [] () { std::cout << "TaskB\n"; },
    [] () { std::cout << "TaskC\n"; },
    [] () { std::cout << "TaskD\n"; } 
  );                                  
                                      
  A.precede(B, C);  // A runs before B and C
  D.succeed(B, C);  // D runs after  B and C
                                      
  executor.run(taskflow).wait(); 

  return 0;
}

**Comment by tsung-wei-huang** [comment]
I believe [attach user data to a task](https://taskflow.github.io/taskflow/StaticTasking.html#AttachUserDataToATask) is the thing you need.

**Comment by libaineu2004** [comment]
> I believe [attach user data to a task](https://taskflow.github.io/taskflow/StaticTasking.html#AttachUserDataToATask) is the thing you need.

1. Regarding data, can taskflow extract a C++ abstract class for users to inherit. It is convenient for users to get the input and output data of each node.

2. If node A crashes or becomes abnormal. How to make taskflow end automatically instead of continuing to execute node C/D. Because C/D relies on A's data.

**Comment by tsung-wei-huang** [comment]
1. One of the most important decision we made when designing taskflow is we do not want to touch data - Very often, the way you manage data is application dependent, and the best abstraction we have found is task parallelism. Another layer of data abstraction will force an application to covert their data structure to that abstraction to gain parallelism, which can easily accumulate non-negligible overhead.
2. This will be supported by the exception - which is something we are developing now. When a node throws an exception, it will force the entire taskflow to stop. The next release will include exception support.

**Comment by libaineu2004** [comment]
> 1. One of the most important decision we made when designing taskflow is we do not want to touch data - Very often, the way you manage data is application dependent, and the best abstraction we have found is task parallelism. Another layer of data abstraction will force an application to covert their data structure to that abstraction to gain parallelism, which can easily accumulate non-negligible overhead.
> 2. This will be supported by the exception - which is something we are developing now. When a node throws an exception, it will force the entire taskflow to stop. The next release will include exception support.

ok!thank you!

**Comment by bradphelan** [comment]
> The next release will include exception support.

This is very exciting. However can I suggest you please do your development more in the open. There are at least 5 threads where exceptions are asked for and you reply that you will not do them because it has too much overhead. Is there a public document or design review discussing planning for new features so users can comment.

**Comment by tsung-wei-huang** [comment]
@bradphelan exception support has been made available in the current branch. Examples are available [here](https://taskflow.github.io/taskflow/ExceptionHandling.html). Supporting exception is a big effort that we want to collect as many feedback as possible. Finally, we are able to seek a solution that imposes the minimum overhead.

Regarding the open discussion, I do not intend to create another hierarchy but use the GitHub issue. Of course, if you have any ideas, please do not hesitate to let me know :) I will be looking into your question of nested semaphore problem now.

**Comment by QiuYilin** [comment]
>1、How to transfer data between nodes?

I have a simple implementation, the main idea is to regard the propagation of data as part of the task.The cost is to wrap taskflow again with a graph-like structure that adds connection information.

The following is a draft.

```
struct ConnectionInfo {
  Node* adj;
  unsigned int port_out;
  unsigned int port_in;
};

class Node {
  friend class Graph;

 public:
  Node();
  virtual ~Node() = default;
  virtual void compute();
  void computeAndUpdateData();
  virtual void setInPortData(unsigned int index, NodeData data) = 0;
  virtual NodeData getOutPortData(unsigned int) = 0;
  std::string name() { return name_; }

 private:
  tf::Task task_;
  std::vector<ConnectionInfo> previous_;
  std::vector<ConnectionInfo> next_;

 protected:
  std::string name_;
  // NodeData in_data_;
  // NodeData out_data_;
};

  Node::Node() {
    
  }

  bool Node::initCompute() {
    return true;
  }

  void Node::compute() {
    return;
  }

  void Node::computeAndUpdateData(){
    compute();
    //update data;
    for(auto& connection : this->next_){
      connection.adj->setInPortData(connection.port_in, this->getOutPortData(connection.port_out));
    }
    return;
  }
```

```
class Graph {
 public:
  Graph();
  ~Graph();
  void addNode(Node* node);
  bool connect(Node* from,unsigned int port_out, Node* to,unsigned int port_in);
 private:
  std::vector<Node*> nodes_;
  tf::Taskflow taskflow_;
};

void Graph::addNode(Node* node) {
  nodes_.push_back(node);
  std::function<void()> task =
      std::bind(&Node::computeAndUpdateData, node);
  node->task_ =
      taskflow_.emplace(task); 
  node->task_.name(node->name());
}

bool Graph::connect(Node* from, unsigned int port_out, Node* to,
                    unsigned int port_in) {
  //TODO some check
  from->next_.push_back(ConnectionInfo{to, port_out,port_in});
  to->previous_.push_back(ConnectionInfo{from, port_out,port_in});
  from->task_.precede(to->task_);
  return true;
}
```

Although the principle of taskflow is not to touch data, if the characteristics of dataflow can be attached through methods such as open inheritance, it may bring a larger application space.
