### ISSUE TITLE
How to do non stopping task in a cyclic iterative conditional loop?

### ISSUE THREAD

**Issue by shrit** [taskflow/taskflow#515]
Hello,

I have been playing with the library and it is really well done, nice work from the community.

I have a very specific question that I am not able to figure out. I have been working recently on the condition example where you have a cyclic graph in one iterative loop. 

Currently the condition example do the following:

_Task C is monitoring the task B and once this task is accomplished task C passes the work to task D._

What I am try to achieve is similar to the above but with a minor modification:

_Task C is monitoring task B but instead of task B being stopped when the task D is working, I want to keep the task B running all the time (concurrently with task D), and once the work is ready / condition is achieved, task C start task D again. The only condition task B will stop if task D is not ready yet (e.g., did not finish the work from the previous task)_

Any idea how to achieve this? I went through all the examples and I couldn't find a way to achieve it.

Thanks for your help

**Comment by tsung-wei-huang** [comment]
Can you draw a task diagram to illustrate your idea? For example, what do you mean by Task C monitoring Task B? Do you mean Task C is a condition task that will precede D based on the condition task B will finish?

**Comment by shrit** [comment]
To add more context I can have a link from D to B so when D is finished B will start again. However, I want B to run all the time without stopping even when the execution is still at D.

To elaborate even more suppose I have several tasks after D, like E and F, and suppose executing E and F will take a certain period of time let us called it `t` I want B to stay running, during that time `t`. 

Any idea how to do that? here is the graph:

![IMG_20231004_163731](https://github.com/taskflow/taskflow/assets/15039782/1ce62889-b5c3-4612-a941-feb1ed934efb)

PS: sorry image are upside down, Andriod phone issue

**Comment by BenBE** [comment]
Let me summarize:

You have a producer task B, that fills up a queue with task items that should be processed by task D. In between you have a monitoring task C that should start task D once there's work in the queue, but should stop task B if after a certain threshold of work items in the queue is exceeded, such that task D can catch up with the work. Once the queue is empty again, you want task B to continue?

If I see thi right, you basically need:
* A semaphore ev1 in B to signal to C that tasks are in the queue
* A semaphore ev2 in D to signal to C that a task has been processed

With this setup, you can:
* wait in C for B to signal ev1
* once signalled start D (or have D wait for another semaphore to unblock)
* wait in C for B to signal ev1 again
* if by that time D has not signalled ev2 (or the task queue has too many items) stop B (or block a 4th semaphore to inhibit task B)
* wait for the task queue to empty below a threshold and re-enable task B
* whenever D finishes a work item, signal ev2

Quick outline, not tested. But should do. (The task B inhibiter should be disabled at startup, the task D inhibiter enabled).

**Comment by shrit** [comment]
@BenBE you have perfectly understood what I am trying to do. Also thank you for the proposed solution.

In the past I was managing this by hand, but the number of semaphore start to increase after adding a couple of tasks after the task D. Therefore I thought of using this library to make my life easier.


Do you have some kind of an example using this library on how to implement this ? or just a small sketch up so I can elaborate more on it ?

**Comment by tsung-wei-huang** [comment]
@BenBE can you tell me which edges in the two pictures are conditional edges (weak dependencies)? Taskflow uses dotted edges to represent conditional edges :)

**Comment by tsung-wei-huang** [comment]
@shrit As far as I know, I do not think this can be easily achieved using Taskflow - as your Task `B` and Task `C` both depend on the availability of a custom queue. I would thus suggest you manage the control flow yourself and issue a taskflow separately when you detect something from `B`.

For example:

```
queue B;
while(!B.empty()) {
  grab a task from B;
  executor.run(taskflow);  // here you don't need to call get so the execution can overlap with B
}
```

Does this make sense to you?

**Comment by shrit** [comment]
@tsung-wei-huang the conditional edges from what I draw and from what I understand are the one from C to B and from F to B. However the edge from B to B is just to show that this is an infinite look that is filling the queue as @BenBE described.

@tsung-wei-huang I do not know if this might work, my idea of using taskflow is to avoid using while loop in my code and moving the management of semaphore to another library. If I have tree queues like B then my code is going to be a nightmare. B is only a prototype but I might having several B's (B1, B2, B3 ..... Bn) at the same time that are filling a queue.

if taskflow is not the library that I should use for this purpose, do you know if there is another library that can handle this kind of scenario ?

**Comment by tsung-wei-huang** [comment]
@shrit I think what you need is a more event-driven programming library - when `B` has something (`B1`, `B2`, `B3`, etc.), it creates an event to launch a task graph (e.g., `D`, `E`, `F`). Probably, you can search for `libevent` and see if that works :)

**Comment by shrit** [comment]
@tsung-wei-huang thank you very much, I thought I can use taskflow to do some kind of event. I will look into event driven libraries, there are a couple that I know that are header only.
Thank again
