### ISSUE TITLE
Cancelling a taskflow in 3.6.0?

### ISSUE THREAD

**Issue by bwehlin** [taskflow/taskflow#526]
In the release notes for 3.6.0: "Dropped support for cancelling asynchronous tasks"

I have a taskflow with thousands of items (parallel_for) and I'd like to cancel the whole flow on user request. My workaround for right now is to have an atomic bool that I set to true on user cancellation. The threads check this variable on each loop iteration as follows:

```
    flow.for_each_index<size_t, size_t, size_t>(0ul, sz, 1ul, [](size_t i) {
        if (stop_requested)
        {
          return;
        }
        compute_item(i);
      });

    auto future = executor.run(std::move(flow));
```

However, this seems quite inefficient. I'd rather just let the currently running loop iterations finish (they don't take that much time each) and then just not execute the remaining loop iterations.

Is what I'm asking for possible in the new release or should I keep doing what I'm currently doing?

Thanks!

**Comment by tsung-wei-huang** [comment]
Hi @bwehlin , cancellation of flow is still supported. We only disable the support for cancelling the tasks of `tf::Executor::async`. In your case, you can still issue `future.cancel()` to cancel `flow`. 

Does this make sense?

**Comment by bwehlin** [comment]
Aha, I see! Yes, makes sense, and thanks for the quick turn-around!
