### ISSUE TITLE
undefined reference to `tf::Executor::_tear_down_async(tf::Node*)'

### ISSUE THREAD

**Issue by renzhong** [taskflow/taskflow#527]
**Describe the bug**
I think core/executor.hpp should include core/async.hpp

**To Reproduce**
I do include "taskflow/core/executor.hpp" on my cpp file to use tf::Executor executor; when I compile my project catch compile error "undefined reference to `tf::Executor::_tear_down_async(tf::Node*)'"
when I read taskflow/core/executor.hpp code, I find  taskflow/core/executor.hpp didn't include core/async.hpp.
I want to know why .
maybe It's a design code for some reason.
the final way to fix this compile error, I need include "taskflow/taskflow.hpp" in my cpp file, but I don't think is the best way for this.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tsung-wei-huang** [comment]
You should just include `taskflow/taskflow.hpp` in your project which will automatically include all necessary files.
