### ISSUE TITLE
Determinism in single-threaded mode

### ISSUE THREAD

**Issue by Ravbug** [taskflow/taskflow#531]
If I create an executor with 
```cpp
 tf::Executor executor{1};
 ```
then give it the same task graph repeatedly, is the order that the tasks run in guaranteed to be the same across each call to `.run()`? I'm trying to diagnose a potential race condition in my application, which creates a task graph at startup and invokes `.run()` once per frame.

**Comment by tsung-wei-huang** [comment]
Yes. If the executor has only one worker, the execution order is deterministic.
