### ISSUE TITLE
Benchmark script expects wrong paths

### ISSUE THREAD

**Issue by kiwixz** [taskflow/taskflow#533]
**Describe the bug**
`benchmark.py` is looking for tests with `{target}/{target}` but tests should be called with `../build/benchmarks/bench_{target}` (if started from benchmarks directory).

**To Reproduce**
Follow the instructions of [benchmark.md](https://github.com/taskflow/taskflow/blob/44dd1dd56feff68761f84430ad755ae942f78f9a/benchmarks/benchmarks.md).

**Desktop (please complete the following information):**
 - OS: Debian
 - Version 12

**Comment by tsung-wei-huang** [comment]
Thanks for the catch up. Feel free to help create a pull request to fix this!

**Comment by tsung-wei-huang** [comment]
fixed in the current branch - will include this in the next release v3.9
