### ISSUE TITLE
Async task priority

### ISSUE THREAD

**Issue by qbojj** [taskflow/taskflow#537]
Some tasks are less important than others: (e.g. optimization of shader pipelines while having less optimized version avaiable).
It would be helpful to have a non-`tf::taskflow` version of assigning priority to e.g. async and dependent async tasks.

**Comment by tsung-wei-huang** [comment]
@qbojj this is available in the current main branch with [tf::TaskParams](https://github.com/taskflow/taskflow/blob/10dfa7920d1a786099a92614c4183f6339975728/taskflow/core/graph.hpp#L530)

```
unsigned priority = 2;
executor.async(TaskParam{"my task", priority}, [](){});
```
