### ISSUE TITLE
CUDA 12 on Linux with -std=c++20 compile error

### ISSUE THREAD

**Issue by doocman** [taskflow/taskflow#539]
**Describe the bug**
Using nvcc with -std=c++20 gives a compile error in taskflow's `cuda_memory.hpp` due to usage of `std::allocator<void>::const_pointer` which do no longer exist (`std::allocator<void>`-specialisation is deprecated in c++17 and removed in c++20)

**To Reproduce**
1. Get CUDA Toolkit 12
2. Try to create some CuFlow objects
3. Press compile

**Desktop (please complete the following information):**
 - OS: ALMA Linux

**Comment by tsung-wei-huang** [comment]
Thank you for the fix! I have merged your pull request :)
