### ISSUE TITLE
line label

### ISSUE THREAD

**Issue by welloncn** [taskflow/taskflow#540]
when dump to a graph add line label，how to do this?
![image](https://github.com/taskflow/taskflow/assets/4989505/d8d288f3-b657-4b54-8900-264609bb317d)
this is my code diff to support this feature

[https://github.com/taskflow/taskflow/compare/master...welloncn:taskflow:add_line_label_540](https://github.com/taskflow/taskflow/compare/master...welloncn:taskflow:add_line_label_540)

**Comment by tsung-wei-huang** [comment]
You can change the name of a task to include the line instead of creating another `std::string` inside `tf::Node`.
