### ISSUE TITLE
Crash when running a move-constructed ScalablePipeline

### ISSUE THREAD

**Issue by MaxStegenRD** [taskflow/taskflow#543]
**Describe the bug**
Running a move-constructed ScalablePipeline crashes consistently.

ScalablePipeline::_build creates tasks by using lambdas which capture the 'this' pointer.
The move-constructor takes ownership of the moved-from pipeline's tasks, which have captured the 'this' pointer of the moved-from pipeline.
Running the move-constructed pipeline accesses the captured 'this' pointer, which now points to an invalid object.

The expected behaviour for the move-constructor would likely be to behave like ScalablePipeline::reset(num_lines, first, last).

**To Reproduce**
Minimal example to reproduce the issue:
```
#include <taskflow/taskflow.hpp>
#include <taskflow/algorithm/pipeline.hpp>

#include <iostream>

template<typename P>
void run(const char* name, P& pipeline)
{
    std::cout << "running pipeline " << name << " (" << &pipeline << ")" << std::endl;
    
    tf::Taskflow taskflow;
    taskflow.composed_of(pipeline).name("pipeline");
    
    tf::Executor executor;
    executor.run(taskflow).wait();
}

int main(int argc, char **argv)
{
    auto pipe = tf::Pipe{tf::PipeType::SERIAL, [](tf::Pipeflow& pf){
        if(pf.token() == 5)
            pf.stop();
        else
            std::cout << "pipe " << pf.pipe() << " line " << pf.line() << " token " << pf.token() << std::endl;
    }};
    
    // create a pipeline
    auto oldPipeline = tf::ScalablePipeline{4, &pipe, &pipe + 1};
    //run("oldPipeline", oldPipeline); // uncomment to verify the pipeline runs correctly
    std::cout << "oldPipeline: " << &oldPipeline << std::endl;
    
    // move the pipeline
    auto newPipeline = std::move(oldPipeline);
    run("newPipeline", newPipeline); // < crash!
    
    return 0;
}
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Compiler: GCC 13.2.1
 - Taskflow Version: 3.6.0

**Comment by cheng-hsiang-chiu** [comment]
@MaxStegenRD 

Thank you so much for bringing up this issue. 
The reason to the bug is exactly as what you mentioned. 
We have fixed the bug. 
Right now, the master branch is bug-free.

**Comment by tsung-wei-huang** [comment]
Close first - feel free to reopen it if the issue remains there.
