### ISSUE TITLE
NumFOCUS: GSoC 2024 Update

### ISSUE THREAD

**Issue by henrykironde** [taskflow/taskflow#550]
If you intend to participate, kindly ensure you update the information as there are only a few hours left until the deadline.

ref: 
https://github.com/numfocus/gsoc
https://github.com/numfocus/gsoc/blob/master/2024/ideas-list.md

**Comment by tsung-wei-huang** [comment]
Hi @henrykironde I have submitted a [pull request](https://github.com/numfocus/gsoc/pull/457) to include Taskflow's GSoC'24 idea.
