### ISSUE TITLE
Ability to detect cycles in a graph

### ISSUE THREAD

**Issue by Kuhnovic** [taskflow/taskflow#561]
The taskflow execution will hang if there the graph contains non-conditional cycles. From what I understand taskflow is meant to be used with DAGs only. IMHO taskflow should come with a function to check whether the graph is a DAG or not, e.g. whether tasks contains cyclic dependencies.

I'm still a bit new to taskflow so forgive me if such a feature already exists. I searched the cookbook and github but didn't find anything.

Here's a snippet to reproduce the "problem":

```
tf::Taskflow tf;

tf::Task A = tf.emplace([&](){ std::cout << "Running A\n"; });
tf::Task B = tf.emplace([&](){ std::cout << "Running B\n"; });

A.precede(B);
B.precede(A);

tf::Executor ex;
ex.run(tf).wait(); // Don't hold your breath...
```

**Comment by tsung-wei-huang** [comment]
@Kuhnovic currently, we don't have this but delegate this to applications. Keep in mind, we do support cycles as part of our [conditional tasking](https://taskflow.github.io/taskflow/ConditionalTasking.html).
