### ISSUE TITLE
Does taskflow have a feature like cudaStreamBeginCapture to create graph dependency automatically when using SYCL backend? 

### ISSUE THREAD

**Issue by mazhaojia123** [taskflow/taskflow#562]
Hi, 

Does taskflow have a feature like cudaStreamBeginCapture to create graph dependency automatically when using SYCL backend?  

Is there any code sample like following code using sycl with taskflow?

```cpp
# A simple cuda code sample to create graph.
cudaStreamBeginCapture(default_stream, cudaStreamCaptureModeGlobal);
kernel();
cudaStreamEndCapture(default_stream, &graph);
cudaGraphInstantiate(&instance, graph, NULL, NULL, 0);
```

Thank you.

**Comment by tsung-wei-huang** [comment]
@mazhaojia123 Hi, I think you mean [cudaFlowCapturer](https://taskflow.github.io/taskflow/GPUTaskingcudaFlowCapturer.html).
