### ISSUE TITLE
VS2019 compiler error

### ISSUE THREAD

**Issue by evehal** [taskflow/taskflow#563]
cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -permissive- -Zc:__cplusplus -Zc:externConstexpr -O2 -MD -std:c++17 -utf-8 -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DQWT_DLL -DNDEBUG -DQT_NO_DEBUG -DQT_AXCONTAINER_LIB -DQT_OPENGLWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. 

using qt + vs2019 64bit, c++17 enabled

F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2589: “(”:“::”右边的非法标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(124): error C2589: “(”:“::”右边的非法标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(125): note: 查看对正在编译的 类 模板 实例化“tf::SmallVectorTemplateCommon<T,<unnamed-symbol>>::AlignedUnionType<X>”的引用
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(232): note: 查看对正在编译的 类 模板 实例化“tf::SmallVectorTemplateCommon<T,<unnamed-symbol>>”的引用
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“(”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2092: “buff”数组元素类型不能是函数或抽象类类型
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2098: 数据成员“buff”后的意外标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“>”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“?”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2334: “:”的前面有意外标记；跳过明显的函数体
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C1903: 无法从以前的错误中恢复；正在停止编译
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2589: “(”:“::”右边的非法标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(124): error C2589: “(”:“::”右边的非法标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(125): note: 查看对正在编译的 类 模板 实例化“tf::SmallVectorTemplateCommon<T,<unnamed-symbol>>::AlignedUnionType<X>”的引用
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(232): note: 查看对正在编译的 类 模板 实例化“tf::SmallVectorTemplateCommon<T,<unnamed-symbol>>”的引用
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“(”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2092: “buff”数组元素类型不能是函数或抽象类类型
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2098: 数据成员“buff”后的意外标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“>”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“?”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2334: “:”的前面有意外标记；跳过明显的函数体
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C1903: 无法从以前的错误中恢复；正在停止编译
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2589: “(”:“::”右边的非法标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(124): error C2589: “(”:“::”右边的非法标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(125): note: 查看对正在编译的 类 模板 实例化“tf::SmallVectorTemplateCommon<T,<unnamed-symbol>>::AlignedUnionType<X>”的引用
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(232): note: 查看对正在编译的 类 模板 实例化“tf::SmallVectorTemplateCommon<T,<unnamed-symbol>>”的引用
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“(”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2092: “buff”数组元素类型不能是函数或抽象类类型
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2098: 数据成员“buff”后的意外标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“>”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“?”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2334: “:”的前面有意外标记；跳过明显的函数体
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C1903: 无法从以前的错误中恢复；正在停止编译
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2589: “(”:“::”右边的非法标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(124): error C2589: “(”:“::”右边的非法标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(125): note: 查看对正在编译的 类 模板 实例化“tf::SmallVectorTemplateCommon<T,<unnamed-symbol>>::AlignedUnionType<X>”的引用
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\core\../utility/small_vector.hpp(232): note: 查看对正在编译的 类 模板 实例化“tf::SmallVectorTemplateCommon<T,<unnamed-symbol>>”的引用
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“(”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2092: “buff”数组元素类型不能是函数或抽象类类型
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2098: 数据成员“buff”后的意外标记
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“>”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2059: 语法错误:“?”
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C2334: “:”的前面有意外标记；跳过明显的函数体
F:\qtprojects\SwitchVideoAlpha3\3rdLib\taskflow-master\taskflow\utility\small_vector.hpp:124: error: C1903: 无法从以前的错误中恢复；正在停止编译

**Comment by tsung-wei-huang** [comment]
Did you enable `-std=c++17`

**Comment by dibetgonzalez** [comment]
D:\CODES\New\Nucleo\taskflow\core\nonblocking_notifier.hpp(501): error C2760: syntax error: unexpected token 'public', expected 'declaration'
D:\CODES\New\Nucleo\taskflow\core\nonblocking_notifier.hpp(495): note: This diagnostic occurred in the compiler generated function 'void tf::NonblockingNotifierV2::_notify(void)'

using C++ qt and VS2019
