### ISSUE TITLE
Add support for more complex dependencies inside a pipeline

### ISSUE THREAD

**Issue by fran6co** [taskflow/taskflow#564]
To reduce latency we have the case of creating pipelines that have some parallel tasks inside that would make this graph:

```
a -> b -> d -> h -> i
  -> c -> e ->
  -> f -> g ->
```

where b, d, c,e and f,g run in parallel to each other and each one of them can be parallel or serial (so the next line waits for them accordingly). The pipeline waits for both of them to finish to move on to h.
I tried implementing this with a sub taskflow that has the parallel tasks, but it doesn't capture the dependencies the same way as it would need to make it serial if any of sub tasks are serial.

**Comment by fran6co** [comment]
I checked Graph Processing Pipeline article but I don't see how would it work if there are more than 2 "forks" in the graph

**Comment by tsung-wei-huang** [comment]
Currently, we do not have a plan to accomplish this, also due to the scheduling difficulties for this feature.
