### ISSUE TITLE
Specify g++ version, or disable compile without certain compiler support

### ISSUE THREAD

**Issue by wilderfield** [taskflow/taskflow#566]
**Please describe your feature request.**

This code base uses std::inclusive_scan which does not exist in g++-7.

Is there a way we can document the supported compilers, or maybe better perform some check in CMake that checks for the minimum required compiler support?

**Comment by tsung-wei-huang** [comment]
The Readme does mention the G++ version needs to be [at least v8](https://github.com/taskflow/taskflow?tab=readme-ov-file#supported-compilers)
