### ISSUE TITLE
How to quickly terminate a running flow？ Some flows may contain dead loop tasks

### ISSUE THREAD

**Issue by willstudy** [taskflow/taskflow#583]
Our flow will run user-defined code, including dead loops。

[RequestCancellation](https://taskflow.github.io/taskflow/RequestCancellation.html) can not kill dead loops。

**Comment by willstudy** [comment]
Use POSIX pthread instead of std::thread?  `pthread_cancel` kill dead loops task？

**Comment by tsung-wei-huang** [comment]
Perhaps a code example showing your problem might be better for me to understand what a dead loop means. The termination of Taskflow should have no dependency on this scenario.

**Comment by tsung-wei-huang** [comment]
Close this first as there are no responses - feel free to reopen it again with a code example.
