### ISSUE TITLE
wrong cmake path include

### ISSUE THREAD

**Issue by Anesthesia4** [taskflow/taskflow#586]
cmake throw an error when add_subdirectory, i check the CMakeLists.txt, here is what it shuod be
in CMakeLists.txt 51
it shoud be 
``
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/CheckAtomic.cmake)
``
not
``
include(${CMAKE_SOURCE_DIR}/cmake/CheckAtomic.cmake)
``

**Comment by tsung-wei-huang** [comment]
@Anesthesia4 thanks for the catch! Could you please help submit a pull request? Thanks!
