### ISSUE TITLE
for_each stuck after exception?

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [taskflow/taskflow#590]
Hi,
I am using for_each to execute some tasks and I noticed that if an exception is thrown, the future waits forever. The code is like

```
tf::Taskflow tf;
  tf.for_each(indices.begin(), indices.end(), [&](const auto& index) {
  if(index == 0) throw std::runtime_error("FOO"); // I know 0 is in indices
}

auto f = tf::Executor().run(taskflow);
f.wait(); // never get out of here
```

I am working with version 3.7.0 and compiling on clang 17. I have been looking into 

https://taskflow.github.io/taskflow/ExceptionHandling.html#CatchAnExceptionFromARunningTaskflow

and I can't see what is going on.

**Comment by tsung-wei-huang** [comment]
@andrea-cassioli-maersk I will look into this.

**Comment by andrea-cassioli-maersk** [comment]
@tsung-wei-huang apologies, I must have made a mistake installing 3.7! A new fresh installation, removing 3.6 first, have solved the issue.
