### ISSUE TITLE
[question] Where do CPU worker-threads get their tasks from?

### ISSUE THREAD

**Issue by blonded04** [taskflow/taskflow#593]
Hello!

Can you please tell me which function is responsible for task-dispatching for CPU threads? For example, when do threads decide to check local queue, when do threads decide to steal task from neighbor thread, etc. Also, if you have multiple queues, as in TBB (mailboxes, critical tasks, fifo streams, etc), can you please describe how do tasks get to different queues, like, which task goes to which queue.

**Comment by tsung-wei-huang** [comment]
Hi @blonded04 , please refer to tf::Executor::_explore_task and tf::Executor::_wait_for_task :)

**Comment by blonded04** [comment]
Thank you!
