### ISSUE TITLE
Performance regression in 3.8

### ISSUE THREAD

**Issue by boxerab** [taskflow/taskflow#595]
I have a test suite of size ~1950 for my codec which uses TaskFlow. I just updated TaskFlow code to latest in master, version 3.8, and now see ~15% more time taken to run the suite.

Here is the diff of the updates vs my original version

[changes.zip](https://github.com/user-attachments/files/15746386/changes.zip)

My project uses c++ std 23, btw.

Thanks !

**Comment by tsung-wei-huang** [comment]
@boxerab thank you for bringing this up! would you please try the master branch ([where I brought back the object pool](https://github.com/taskflow/taskflow/commit/57e960c7e2324da2b73dd05abbd69578f0e04ec7)) again and let me know if the difference is still there?

**Comment by tsung-wei-huang** [comment]
I am looking into this - Meanwhile, could you please let me know the architecture of your benchmarks? x86 or arm64, etc.?

**Comment by tsung-wei-huang** [comment]
@boxerab can you try the [dev branch](https://github.com/taskflow/taskflow/tree/dev) and let me know if the problem is still there?

**Comment by tsung-wei-huang** [comment]
Interesting. My side shows a good amount of improvement due to the use of C++20 atomic wait/notification. I assume you compiled the test using C++20 or above. Could you please try compiling and running the tests without C++20 (i.e., C++17)?

```cpp
~$ cd build
~$ cmake ../ -DCMAKE_CXX_STANDARD=17
~$ make
```

**Comment by tsung-wei-huang** [comment]
What do you mean by `old version`? Here is the data I have on my ubuntu machine on the current dev branch:

```cpp
// with c++20 using cmake ../ -DCMAKE_CXX_STANDARD=20
Total Test time (real) =  41.58 sec
Total Test time (real) =  41.30 sec
Total Test time (real) =  41.73 sec
Total Test time (real) =  41.53 sec
Total Test time (real) =  41.43 sec
Total Test time (real) =  41.47 sec
Total Test time (real) =  42.15 sec
Total Test time (real) =  41.56 sec
Total Test time (real) =  41.79 sec
Total Test time (real) =  41.62 sec

// with c++17 using cmake ../ -DCMAKE_CXX_STANDARD=17
Total Test time (real) =  43.11 sec
Total Test time (real) =  42.78 sec
Total Test time (real) =  42.82 sec
Total Test time (real) =  42.84 sec
Total Test time (real) =  42.91 sec
Total Test time (real) =  42.92 sec
Total Test time (real) =  42.72 sec
Total Test time (real) =  43.24 sec
Total Test time (real) =  42.93 sec
Total Test time (real) =  43.00 sec
```

Would you mind posting your regression data?

**Comment by tsung-wei-huang** [comment]
I did see some performance issues with the C++20-based [atomic notifier](https://github.com/taskflow/taskflow/blob/dev/taskflow/core/atomic_notifier.hpp), so I switched back to the ordinary [nonblocking notifier](https://github.com/taskflow/taskflow/blob/dev/taskflow/core/nonblocking_notifier.hpp). Would you try the [dev branch](https://github.com/taskflow/taskflow/tree/dev) again and let me know if the issue is still there? Notice that you may still observe a slight performance difference between c++17 and c++20/23, but the difference should be small this time.

**Comment by tsung-wei-huang** [comment]
Sounds good - will merge it with the master branch!
