### ISSUE TITLE
tf::Executor crash during initialization

### ISSUE THREAD

**Issue by lovezhangtao** [taskflow/taskflow#597]
from crash dump:
C++ EH exception - code e06d7363
_THROW_CPP_ERROR(_RESOURCE_UNAVAILABLE_TRY_AGAIN)

Here is the call stack for crash:
![image](https://github.com/taskflow/taskflow/assets/22004897/c7188f6e-fca1-4825-b4a7-1986efe0ee98)

I specified a thread count of 6 when constructing the Executor
But from the dump, it appears that over 1000 threads were created, resulting in system resource unavailability and then throwing a C++exception causing a crash.
This is a call stack for over 1000 other threads, seem to wait
![image](https://github.com/taskflow/taskflow/assets/22004897/afcd2c63-1e09-49fd-8f18-740f644a958d)

I want to know why the number of threads is specified,
But tf:: executor has created a large number of threads internally
Thank you.

**Comment by tsung-wei-huang** [comment]
I suspect your error comes from your application-level mis-use of executor. If you create an executor like this `tf::Executor executor(6)` you are guaranteed to have only 6 worker threads created in `executor`. Perhaps you can paste your code here?

**Comment by lovezhangtao** [comment]
Thank you for your prompt response.
Here is my code:
`tf::Executor m_tfExecutor;`
`m_tfExecutor(std::max((int)std::thread::hardware_concurrency() - 2, 1))`
The purpose of reducing 2 is not to occupy all CPU cores, so the machine has 8 cpu cores, 
The value passed into the Executor is 6，As indicated by the parameters in dump
`tf::Executor::_spawn(unsigned int64 N = 6)+0x20c
tf::Executor::Executor(unsigned int64 N = 6, class std::shared_ptr<tf::WorkerInterface> * wix = 0x0000005e`7c27c638 empty)+0x2df`
This issue currently appears to appear on certain platforms

**Comment by tsung-wei-huang** [comment]
@lovezhangtao I don't exactly know why this is happening. If you have only one executor and, as you see, the method `spawn` is the place to create threads, you should only observe up to 6 threads in the executor.
