### ISSUE TITLE
Go to C++23 directly

### ISSUE THREAD

**Issue by patlecat** [taskflow/taskflow#608]
I've read in the roadmap that it is planned to update v4 to C++20, but it's already 2024 now and v4 isn't coming soon. I think it would be more economic to the sparse resources in the project to directly go to C++23 instead.

https://taskflow.github.io/taskflow/release-roadmap.html

**Comment by blonded04** [comment]
> I've read in the roadmap that it is planned to update v4 to C++20, but it's already 2024 now and v4 isn't coming soon. I think it would be more economic to the sparse resources in the project to directly go to C++23 instead.
> 
> https://taskflow.github.io/taskflow/release-roadmap.html

C++23 is not close to be widely used between existing codebase, so imho C++20 is a better choice as of 2024 (I'm not a maintainer of taskflow, just a user)

**Comment by patlecat** [comment]
> > I've read in the roadmap that it is planned to update v4 to C++20, but it's already 2024 now and v4 isn't coming soon. I think it would be more economic to the sparse resources in the project to directly go to C++23 instead.
> > https://taskflow.github.io/taskflow/release-roadmap.html
> 
> C++23 is not close to be widely used in existing codebases, so imho C++20 is a better choice as of 2024 (I'm not a maintainer of taskflow, just a user)

There is no need to support every little iteration of the C++ standards, makes no sense at all. Whoever doesn't want to use C++23 can use C++17. There's no downside to this. And since a port of a lib as complex as this takes a lot of time it would be wasted going to C++20 actually.

**Comment by tsung-wei-huang** [comment]
Currently no specific plan for C++23 but the next major release will include C++20.

**Comment by patlecat** [comment]
@tsung-wei-huang That's sad.
