### ISSUE TITLE
`for_each_index` is homogeneous while it claims to be heterogeneous

### ISSUE THREAD

**Issue by blonded04** [taskflow/taskflow#610]
**Describe the bug**
Function for_each_index has following signature: template <typename B, typename E, typename S, typename C, typename P> Task FlowBuilder::for_each_index(B beg, E end, S inc, C c, P part); which implies, that range might be heterogeneous: for example, beg and end can be of type size_t, and inc can be int.

However, it's not the case, because C++ compilers fail to deduce type on functions is_range_invalid and distance, which are used under the hood of for_each_index, because they are homogeneous.

**To Reproduce**
something like following example wouldn't compile, because compiler fails to deduce types of arguments for homogeneous functions distance and is_range_invalid:
```
template<typename F>
void parallel_for(size_t from, size_t to, F&& f) {
    tf.for_each_index(from, to, 1, std::forward<F>(f));
}
```

**Additional**
I created a pull-request that addresses this issue: https://github.com/taskflow/taskflow/pull/609

**Comment by blonded04** [comment]
@tsung-wei-huang hello! 

Can you please review my small pull-request which fixes this issue? https://github.com/taskflow/taskflow/pull/609/files

**Comment by tsung-wei-huang** [comment]
@blonded04 Thank you for your help! This is a great pull fix. I have merged it :) Sorry for the late response as I just came back from vocation.
