### ISSUE TITLE
Is Taskflow NUMA aware and optimised?

### ISSUE THREAD

**Issue by patlecat** [taskflow/taskflow#612]
As mentioned here by Fedor Pikus (https://youtu.be/wGSSUSeaLgA?si=ZbSLQ62fzZ27VAdk) threadpools on modern CPUs could waste a lot of time if they're not coded in a NUMA aware way. And he claims that his own lib is 50x faster than the threadpool in Asio. How is it with Taskflow?

**Comment by samayala22** [comment]
It is not. See https://github.com/taskflow/taskflow/issues/581

**Comment by tsung-wei-huang** [comment]
Current, we do not target NUMA optimization.
