### ISSUE TITLE
How to Connect Multiple Exit Points from a Taskflow to Different Visualization Taskflows?

### ISSUE THREAD

**Issue by FRAOTIAC** [taskflow/taskflow#614]
Hi Taskflow Team,

I'm working on a C++ project using the Taskflow library to handle parallel and sequential tasks. I've created two classes, ComplicatedInferTask and ComplicatedVisualizeTask, which respectively manage data inference and visualization tasks. Each class builds a separate Taskflow object.

In the inference taskflow (ComplicatedInferTask), there are three exit points corresponding to different post-processing results (A, B, and C). My goal is to connect each of these exit points to different visualization tasks in the ComplicatedVisualizeTask class.

Here’s a simplified version of my code:

```
#include <taskflow/taskflow.hpp>

class ComplicatedInferTask {
private:
    float input_{0};
    float output_a_{100};
    float output_b_{1000};
    float output_c_{10000};
public:
    ComplicatedInferTask() = default;

    tf::Taskflow BuildInferTask(const float &input) {
        tf::Taskflow infer_taskflow;

        auto load_data_task = infer_taskflow.emplace([this, input]()mutable {
            std::cout << "Load data task: " << input << std::endl;
            input_ = input;
        }).name("Load Data Task");

        auto infer_task = infer_taskflow.emplace([this]()  mutable {
            input_ += 10;
            std::cout << "Infer task input_ += 10: " << input_ << std::endl;
        }).name("Infer Task");

        auto post_process_task_a = infer_taskflow.emplace([this]() {
            output_a_ += input_ * 10;
            std::cout << "Post process task A output_a_: " << output_a_ << std::endl;

        }).name("Post Process Task A");

        auto post_process_task_b = infer_taskflow.emplace([this]() {
            output_b_ += input_ * 100;
            std::cout << "Post process task B output_b_: " << output_b_ << std::endl;
        }).name("Post Process Task B");
        auto post_process_task_c = infer_taskflow.emplace([this]() {
            output_c_ += input_ * 1000;
            std::cout << "Post process task C output_c_: " << output_c_ << std::endl;
        }).name("Post Process Task C");

        load_data_task.precede(infer_task);
        infer_task.precede(post_process_task_a, post_process_task_b, post_process_task_c);

        return infer_taskflow;
    }
};

class ComplicatedVisualizeTask {
private:
    float input_{0};
    float output_{0};

public:
    ComplicatedVisualizeTask() = default;
    // Build a full visualize taskflow
    tf::Taskflow BuildFullVisualizeTask(const float &input) {
    }

};


int main() {
    tf::Executor executor;
    tf::Taskflow taskflow;

    ComplicatedInferTask complicate_infer_task;
    ComplicatedVisualizeTask complicated_visualize_task;
    float infer_input = 10;
    float infer_output {};

    auto infer_taskflow = complicate_infer_task.BuildInferTask(infer_input);
    // assume get infer_output using infer_taskflow method

    auto visualize_taskflow = complicated_visualize_task.BuildFullVisualizeTask(infer_output);

    tf::Task infer_task = taskflow.composed_of(infer_taskflow).name("Infer Task");

    tf::Task visualize_task = taskflow.composed_of(visualize_taskflow).name("Visualize Task");
    
    // how to connect infer_task and visualize_task?

    executor.run(taskflow).wait();

    taskflow.dump(std::cout);

    return 0;
}
```
My Question:

In the infer_taskflow, I have three different exit points corresponding to A, B, and C post-processing results. How can I connect these exit points to different visualization taskflows (A, B, and C) in ComplicatedVisualizeTask? Specifically, I need to ensure that the visualization tasks are triggered based on the completion of their respective post-processing tasks.

Is there a recommended way in Taskflow to manage this kind of mapping between different taskflow outputs and inputs? 
![image](https://github.com/user-attachments/assets/7c7ad08b-cca7-4453-b163-b131d383951d)

**Comment by tsung-wei-huang** [comment]
Can you draw a task diagram of what you need exactly? I am a bit confused by your notations here: "I have three different exit points corresponding to A, B, and C post-processing results. How can I connect these exit points to different visualization taskflows (A, B, and C)" 

Are you saying that you would like to reconnect A to A, B, or/and C? Or, you would like to do some in-graph control flow (which can be done via [Conditional Tasking](https://taskflow.github.io/taskflow/ConditionalTasking.html)).

**Comment by FRAOTIAC** [comment]
Thank you for your response. I apologize for any confusion in my initial description. Let me clarify my question with a more detailed explanation and a diagram.

Current structure:

```mermaid
graph TD
    A[Load Data Task] --> B[Infer Task]
    B --> C[Post Process Task A]
    B --> D[Post Process Task B]
    B --> E[Post Process Task C]
    
    subgraph ComplicatedInferTask
    A
    B
    C
    D
    E
    end
```

Desired structure:

```mermaid
graph TD
    A[Load Data Task] --> B[Infer Task]
    B --> C[Post Process Task A]
    B --> D[Post Process Task B]
    B --> E[Post Process Task C]
    C --> F[Visualize Task A]
    D --> G[Visualize Task B]
    E --> H[Visualize Task C]
    
    subgraph ComplicatedInferTask
    A
    B
    C
    D
    E
    end
    
    subgraph ComplicatedVisualizeTask
    F
    G
    H
    end
```

My main question is: Is it possible for a Taskflow graph (ComplicatedVisualizeTask in this case) to have multiple entry points? Specifically, can I create a Taskflow in ComplicatedVisualizeTask that has three separate entry points (D, E, F) that can be directly connected to the corresponding output tasks (A, B, C) from ComplicatedInferTask?

If this is not possible, what are the alternative approaches? Some options I've considered:

1. Creating separate Taskflows for each visualization task.
2. Using a conditional task to determine which visualization task to run.
3. Using subflows to dynamically create the appropriate visualization task.

Could you please advise on the best way to structure this in Taskflow? I'm open to any suggestions or best practices for handling this kind of branching workflow.

Thank you for your time and assistance.

**Comment by FRAOTIAC** [comment]
Hi @tsung-wei-huang,

I found a solution to my issue. It turns out that by arranging the tasks as shown in the diagram, the desired connections between the post-processing tasks (A, B, C) and the visualization tasks (A, B, C) work correctly without any extra setup. Each post-processing task can directly trigger its respective visualization task within the same Taskflow graph.

This approach allows for the smooth execution of the tasks as intended, so I'll go ahead and close the issue.

Thanks again for your support!
