### ISSUE TITLE
misuse in unit-test of utility

### ISSUE THREAD

**Issue by NanaGlutamate** [taskflow/taskflow#631]
https://github.com/taskflow/taskflow/blob/3b512a3172281412f8ea6c0eee3086b644277197/unittests/test_utility.cpp#L243

**Comment by NanaGlutamate** [comment]
seems should be `REQUIRE(size == std::unique(uuids.begin(), uuids.end()) - uuids.begin())` or somethings like this

**Comment by tsung-wei-huang** [comment]
Thank you very much!
