### ISSUE TITLE
Potential Risks of Using a Custom Pipeline Wrapper with Taskflow

### ISSUE THREAD

**Issue by FRAOTIAC** [taskflow/taskflow#634]
Hi @tsung-wei-huang and Taskflow Team,

I've been experimenting with a custom wrapper class that integrates with Taskflow, aiming to create a monad-like pipeline for data processing. Here is a simplified version of the code:
```
#include <taskflow/taskflow.hpp>
#include <iostream>
#include <functional>
#include <memory>

template <typename T>
class Pipeline {
public:
    Pipeline(tf::Taskflow& tf, T data)
            : taskflow(tf), data(std::move(data)) {}

    Pipeline& process(std::function<T(T)> func) {
        data = func(data);
        taskflow.emplace([value = data]() {
            std::cout << "Processed: " << value << '\n';
        });
        return *this;
    }

    T result() const {
        return data;
    }

private:
    tf::Taskflow& taskflow;
    T data;
};

int main() {
    tf::Executor executor;
    tf::Taskflow taskflow("Monad-like Pipeline");

    int initial_data = 10;
    auto pipeline = Pipeline(taskflow, initial_data)
            .process([](int x) { return x + 5; })
            .process([](int x) { return x * 2; })
            .process([](int x) { return x - 3; });

    executor.run(taskflow).wait();

    std::cout << "Final result: " << pipeline.result() << '\n'; 

    return 0;
}

```
Question:
Is this approach considered a best practice when using Taskflow, or are there any potential risks I should be aware of?

Thanks for your time!

**Comment by tsung-wei-huang** [comment]
@FRAOTIAC sorry for the late response. I was traveling over the last week. 

We have a [tf::Pipeline](https://taskflow.github.io/taskflow/TaskParallelPipeline.html) interface. Have you looked into it? In your example, I don't see any parallelism in the pipeline (?)

**Comment by FRAOTIAC** [comment]
Hi @tsung-wei-huang and Taskflow Team,

Thanks for getting back to me. I've looked into tf::DataPipeline and it's been working well for single-input-single-output cases. However, I find this limitation a bit restrictive for my current solution, and I noticed others have brought up similar issues.

I was wondering what your thoughts are on extending the pipeline to support multi-input and multi-output. Is this something technically challenging? Would love to hear any insights you might have.

Thanks again!

**Comment by tsung-wei-huang** [comment]
@FRAOTIAC  sorry for the late response as I was working on some paper deadlines. Indeed, you are right. Currently, `tf::Pipeline` variants only supports single-input-single-output pipeline. Although the processing stages of different inputs can go in parallel. I can't think of a good scheduling algorithm to handle multiple-input-multiple-output pipeline. I think it is not even available in existing pipeline programming frameworks, such as tbb, due to scheduling difficulty (I guess). 

Perhaps the best way to do multiple-input-multiple-output pipeline is simply creating `N` pipeline objects each processing an independent stream of data. 

This is my two cent :)

**Comment by FRAOTIAC** [comment]
Thanks for your detailed explanation! This is quite insightful. I'll look into frameworks like TBB to better understand the specific scheduling challenges they face with multiple-input-multiple-output pipelines. This will be really helpful for understanding the problem.
