### ISSUE TITLE
 tf::Runtime::corun fails with lambda for tf::Subflow due to missing graph() member

### ISSUE THREAD

**Issue by FRAOTIAC** [taskflow/taskflow#635]
**Describe the bug**
When using tf::Runtime::corun with a lambda that accepts a tf::Subflow as described in the documentation, a compilation error occurs. The error indicates that the lambda does not have a graph() member, even though it follows the example in the Taskflow documentation.

**To Reproduce**

1. Create a Taskflow and an Executor.
2. Use tf::Runtime::corun with a lambda accepting tf::Subflow.
3. Compile the following code:

```
#include <taskflow/taskflow.hpp>

int main() {
  tf::Executor executor;
  tf::Taskflow taskflow;

  taskflow.emplace([](tf::Runtime& rt) {
    rt.corun([](tf::Subflow& sf) {
      tf::Task A = sf.emplace([]() { std::cout << "Task A\n"; });
      tf::Task B = sf.emplace([]() { std::cout << "Task B\n"; });
      A.precede(B);
    });
  });

  executor.run(taskflow).wait();
  return 0;
}
```

4.  Compilation error appears: lambda(tf::Subflow&) has no member named 'graph'.

**Desktop (please complete the following information):**
OS: Ubuntu 20.04
Compiler: GCC 9.4.0/ clang 10
Taskflow Version: v3.8.0

**Comment by tsung-wei-huang** [comment]
@FRAOTIAC this is an error in documentation which should be removed. The co-run now does not take any subflow argument. Feel free to help submit a pull to fix the mistake 👍

**Comment by FRAOTIAC** [comment]
Hi  @tsung-wei-huang,

I have submitted a PR that addresses the documentation error regarding `tf::Runtime::corun`. The current co-run method does not take a subflow argument, and the documentation has been updated accordingly. Please feel free to review the PR.

Thanks!
