### ISSUE TITLE
How to make the lifecycle of the `thread_local` variable in the task consistent with that of the executor

### ISSUE THREAD

**Issue by Domegu** [taskflow/taskflow#636]
In my code, I need to set some attribute values for the thread itself and require them to be consistently retained. However, during execution, I found that once the `run` and `wait` operations are executed in between, the value of the `thread_local` variable changes when I try to access it again.

```c++
namespace Xxx{
thread_local int thread_id{0};
}

{
 tf::Executor executor{8};
  tf::Taskflow taskflow;
  std::mutex mtx;

{
  sem_t task_barrier;
  sem_init(&task_barrier, 0, 0);

  taskflow.for_each_index(0, 8, 1, [&](int i) {
    Xxx::thread_id = (rand() % 100) + 1;
    {
      std::lock_guard<std::mutex> lck(mtx);
      std::cout << std::this_thread::get_id() << ",workid: " << executor.this_worker_id() << ", thread id: "  << Xxx::thread_id << std::endl;
    }
  },tf::StaticPartitioner(1));

  executor.run(taskflow).wait();
std::cout << "\n\n\n";

  for(int i = 0; i < 500; ++i) {
      taskflow.emplace([&]() {
      {
        std::lock_guard<std::mutex> lck(mtx);
        std::cout << std::this_thread::get_id() << ",workid: " << executor.this_worker_id() << ", thread id: " << Xxx::thread_id << std::endl;
      }
      usleep(Xxx::thread_id);
    });
  }

  executor.run(taskflow).wait();
}

}
``` 

The printed information is:
```
140664153700096,workid: 7, thread id: 14
140664162092800,workid: 6, thread id: 30
140664071255808,workid: 3, thread id: 56
140664195663616,workid: 1, thread id: 41
140664204056320,workid: 0, thread id: 37
140664178878208,workid: 4, thread id: 39
140664170485504,workid: 5, thread id: 71
140664187270912,workid: 2, thread id: 10



140664187270912,workid: 2, thread id: 10
140664153700096,workid: 7, thread id: 72
140664178878208,workid: 4, thread id: 28
140664204056320,workid: 0, thread id: 37
...
``` 

How can I achieve my goal?

**Comment by blonded04** [comment]
Taskflow provides task scheduler on top of OS thread scheduler, which `thread_local` variables depend on, so using `thread_local` in Taskflow or other userspace parallel runtimes won't lead you to what you want to do. 

What you can do in contrast, is have a global array where each thread uses only one entry (ideally, each entry should be cacheline-padded).

Or, in your simple case, you can use [tf::Executor::this_worker_id](https://taskflow.github.io/taskflow/classtf_1_1Executor.html#a6487d589cb1f6b078b69fd3bb1082345)

**Comment by Domegu** [comment]
i forget clear taskflow...... first part will be run twice....sorry
