### ISSUE TITLE
g++ shows false-positive warnings with -Wnull-dereference

### ISSUE THREAD

**Issue by bi0ha2ard** [taskflow/taskflow#646]
**Describe the bug**
g++ 13 and newer raise "potential null-dereference" warnings when compiling Taskflow with `-Werror=null-dereference`. The warnings are triggered from `Executor::_invoke()`, where the `node->_handle` variant is processed in a switch statement and the underlying task is dispatched based on the variant contents. In the implementations (f.e. `_invoke_subflow_task()`) the `node->_handle` is then unwrapped with a `std::get_if` matching the switch `case`. Since `std::get_if` returns `nullptr` if the requested type and the contained types don't match and the returned pointer is immediately dereferenced with `auto& work = std::get_if<Node::Static>(&node->_handle)->work;`, the compiler seems to detect that as a potential null pointer dereference.

The code should be correct and no null dereference should ever happen because the caller (`Executor::invoke()`) checks the type in the switch statement, but it's still flagged as a warning by the compiler.

**To Reproduce**
Here's a godbolt link to the example from the README with a recent version of GCC and the `-Werror=null-dereference` flag: https://godbolt.org/z/oET1EWbej

**Additional context**
One way to make the compiler happy is to use `std::get` instead. It throws on type mismatch, so there's no nullptr to check.
I'm not sure if there's any concerns about performance/interactions with the exception try/catch infrastructure, but it should never actually have to take the error branch, since we're guarded by the switch statement.

Another way that avoids the warning is performing the `std::get_if` in the switch statement and passing the unwrapped handle to the invoke functions. Then the compiler seems to be able to reason about the fact that the `std::get_if` will never return nullptr.

I'm happy to open a PR if any of the above sounds reasonable, or if there's some other workaround that I'm missing.

PS:
`examples/text_pipeline.cpp:102` the compiler also warns about using the result of `std::max_element` without checking that it's valid.

**Comment by tsung-wei-huang** [comment]
@bi0ha2ard this is a false alarm - we use `std::get_if` simply to bypass another if-check on the exception. You can skip the warning, but thank you very much for pointing this out!
