### ISSUE TITLE
corun method can handle master thread instead of throwing exception

### ISSUE THREAD

**Issue by aslanfatih** [taskflow/taskflow#648]
The suggestion is related to handling corun method if it is being called from main thread. Here is the relevant exception
 
![image](https://github.com/user-attachments/assets/45ad3606-ad7d-43ec-9a16-129440366684)

The reasons are:
* When taskflow is used in multiple places within the same thread,  it might not be easy to understand whether it is called from main thread or worker.
* The worker and main thread approach can vary. In prod code, even if corun method can be part of worker thread in the flow, the same code part becomes outer thread in unittest which cause unittest code fail. It can be illustrated with a simple example
```

func_in_worker_thread(tf::Executor& executor) {
    tf::Taskflow taskflow;
    // Impl.
    executor.corun(tf);
}


void func_in_master_thread(tf::Executor& executor) {
    tf::Taskflow taskflow;
    // Impl. 
    func_in_worker_thread(executor); 
    executor.run(taskflow).wait();
}
````
When we want to **ONLY** test  _func_in_worker_thread_ in an isolated manner, _corun_ will give exception and test case will fail.

The proposed approach is instead of throwing exception, handling the scenario in corun impl. as below

```
// Function: corun legacy
template <typename T>
void Executor::corun(T& target) {
  
  if(pt::worker == nullptr || pt::worker->_executor != this) {
      //TF_THROW("corun must be called by a worker of the executor"); // Comment the exception
      // Proposed Lines START
      run(target).wait();
      return;
      // Proposed Lines END
  }

  Node parent;  // auxiliary parent
  _corun_graph(*pt::worker, &parent, target.graph());
  parent._process_exception();
}

```

**Comment by tsung-wei-huang** [comment]
@aslanfatih thank you for the proposal. The concept of `corun` is defined for running the target graph from a `worker` of an executor. We do not want to automatically handle the exception by calling `run`. This will violate the original concept of `corun`. In this case, the decision is up to users for correctly calling `run` or `corun`. You can always use `tf::Executor::this_worker` to check if the calling thread is a worker of the executor.
