### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by ForgeMistress** [taskflow/taskflow#69]
I have encountered std::bad_alloc issues in my codebase and all of the profiling I have done is pointing to the node pool not being properly cleaned up or handled. It seems like the graph is allocating new nodes instead of reusing existing ones. This occurred as well in the prior version that did not include the pooling.

What I am observing is a steady climb in memory usage where I would expect there to be an initial spike and then some settling as the pool begins to fill up. Has there been any investigation on this?

**Comment by twhuang-uiuc** [comment]
@ForgeMistress , could you please show us a piece of code in your application that may causes the memory climb? We havn't seen any memory leak in our tests.

**Comment by ForgeMistress** [comment]
And neither have I. I made an isolated case that mimics my situation and there is no leak. Please disregard.

**Comment by ForgeMistress** [comment]
I am actually reopening this issue, because I did some further digging. Turns out that I simply didn't leave the test case running for long enough, and I also have a user-facing fix for this kind of problem.

Here is the test case code:

`#include "stdafx.h"

#include "taskflow.hpp"

static size_t _s_numTasks{ 50000 };
int main(int ac, char** av)
{
	tf::Taskflow tf(std::thread::hardware_concurrency());
	tf::Taskflow tf2(std::thread::hardware_concurrency());
	while(1)
	{
		for(size_t i=0; i<_s_numTasks; ++i)
		{
			{
				auto t1 = tf.silent_emplace([] {
					std::cout<<"Itty bitty baby, itty bitty boat."<<std::endl;
				}).name("baby"+std::to_string(i));

				auto t2 = tf.silent_emplace([] {
					std::cout<<"I don't believe it!"<<std::endl;
				}).name("believe"+std::to_string(i));

				auto t3 = tf.silent_emplace([] {
					std::cout<<"HABEEB IT!"<<std::endl;
				}).name("habeeb"+std::to_string(i));

				auto t4 = tf.silent_emplace([] {
					std::cout<<"TWINKIE HOUSE!"<<std::endl;
				}).name("twinkie"+std::to_string(i));

				tf.linearize({ t1, t2, t3, t4 });
			}

			{
				auto t1 = tf2.silent_emplace([] {
					std::cout<<"Itty bitty baby, itty bitty boat."<<std::endl;
				}).name("baby"+std::to_string(i));

				auto t2 = tf2.silent_emplace([] {
					std::cout<<"I don't believe it!"<<std::endl;
				}).name("believe"+std::to_string(i));

				auto t3 = tf2.silent_emplace([] {
					std::cout<<"HABEEB IT!"<<std::endl;
				}).name("habeeb"+std::to_string(i));

				auto t4 = tf2.silent_emplace([] {
					std::cout<<"TWINKIE HOUSE!"<<std::endl;
				}).name("twinkie"+std::to_string(i));

				tf2.linearize({ t1, t2, t3, t4 });
			}
		}
		tf.dispatch().get();
		tf2.wait_for_all();
	}
}
`

Looooong dead memes aside, I ran this in debug and after a while, the console would freeze and then either the memory graph would spike in size or it would only slightly increase in size (I'm using visual studio diagnostics tools to debug this).

However, if the dispatch().get() is changed to wait_for_all(), the graph remains steady, save for a small dip when the freeze occurs then returning to its normal size.

Alternative fix is to ensure that wait_for_topologies() is called when appropriate for your application.

**Comment by clin99** [comment]
Hi @ForgeMistress , the reason is that the `dispatch().get()` does not remove the task graph and release the allocated memory and memory will be exhausted in the long run. 

To make sure the memory is release (and the graph is removed) after each execution, you should use the `wait_for_topologies()` or `wait_for_all()` (which calls `wait_for_topologies()` internally).

Thanks.

**Comment by tsung-wei-huang** [comment]
Hi, @ForgeMistress  the reason we retain the topologies is to access the graph of dynamic tasking. In dynamic tasking, some tasks will spawned only during the time. This is why in this case we want users to use `dispatch` without cleaning up topologies so they can examine the structure of the graph. By default, `wait_for_all` will clean up all topologies.

**Comment by tsung-wei-huang** [comment]
@ForgeMistress , please try the newest version where we isolate executor from taskflow. Users no longer need to worry about the topology. It will be automatically cleared when it finishes.
