### ISSUE TITLE
BasicTaskflow should let us specify the Closure type

### ISSUE THREAD

**Issue by Lectem** [taskflow/taskflow#70]
Hi,

I think it would be great if we could define our own `Closure` type for `BasicTaskflow`, and for multiple reasons:

* One could limit the usage to a fixed sized type instead of relying on std::function. For example use a `function_ref` http://wg21.link/p0792
* One could implement Executors that would recognize properties of the Closure, such as priority, long running task, IO task. What I'm thinking about here is having something similar to the windows threadpool https://docs.microsoft.com/fr-fr/windows/desktop/ProcThread/thread-pool-api that can spawn more threads when needed, or change their priority.
* On some systems, some functions are restricted to a given CPU core, we could imagine adding some kind of core affinity to the closure

Some of those features could be implemented by other means, but I think customizing the `BasicTaskflow::Closure` type would be the easiest way to have a system with mixed requirements.

**Comment by clin99** [comment]
Hi @Lectem ,  sorry for my reply. I agree that allowing ```Closure``` customization would be beneficial to 
the users that have their own executors and allows more dedicated scheduling strategies for different kinds of tasks. As currently ```Closure``` is the main data structure used in both ```BasicTaskflow``` and the underlying ```executor```, we need to think carefully about how to do this. We will add this into our TODO list. 

Thanks for your feedback!

**Comment by robinchrist** [comment]
@clin99 
Is there any specific reason for using `std::atomic<int>` instead of `std::atomic<unsigned int>`?

**Comment by tsung-wei-huang** [comment]
The current version does not plan to do this but leave it with `std::function`
