### ISSUE TITLE
tf::Taskflow cannot be declare as extern nor static variable or even as namespace variable

### ISSUE THREAD

**Issue by PaTiToMaSteR** [taskflow/taskflow#76]
**Describe the bug**
tf::Taskflow cannot be declare as extern nor static variable or place it in a namespace

**To Reproduce**
Visual Studio 2017/2019 just declare it as static, extern or in a namespace. Will get stuck here:
// Procedure: _spawn
template <typename Closure>
void WorkStealingExecutor<Closure>::_spawn(unsigned N) {
  
  // Lock to synchronize all workers before creating _worker_mapss
  for(unsigned i=0; i<N; ++i) {
    _threads.emplace_back([this, i, N] () -> void {
...

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: latest in master

If someone can fast-test it? I'll delay the initialization in my source code at the moment. 
Thanks!

**Comment by tsung-wei-huang** [comment]
Hi @PaTiToMaSteR  Can you paste more code that caused your this error? It's hard to reproduce your error from this code fragment.

**Comment by PaTiToMaSteR** [comment]
Is not my source code. It’s yours guys :) Just saying that hangs in the method _spawn passing in my case 8 as parameter.

You reproduce it as simple as declare the variable outside of a class. For instance, take whatever the test and place tf::Taskflow outside of the main. The dynamic initializer will trigger the constructor and hangs there.

**Comment by clin99** [comment]
Hi @PaTiToMaSteR , I have tried making `tf::Taskflow` as a static variable and the code works. 

The code:
```cpp
#include <taskflow/taskflow.hpp>  // the only include you need
// Declare a static Taskflow object
static tf::Taskflow taskflow(8);

int main(){

  auto [A, B, C, D] = taskflow.emplace( 
    [] () { std::cout << "TaskA\n"; },                                      
    [] () { std::cout << "TaskB\n"; },        
    [] () { std::cout << "TaskC\n"; },        
    [] () { std::cout << "TaskD\n"; }        
  );                                      
                                          
  A.precede(B);  // B runs after A           
  A.precede(C);  // C runs after A         
  B.precede(D);  // D runs after B         
  C.precede(D);  // D runs after C      
  taskflow.wait_for_all();  // block until finished

  // Hold the console
  std::cin.get();

  return 0;
}
```

My environment:
OS:  Win 10
Visual Studio 2019
MSVC full version: 192027508
Latest Cpp-Taskflow master branch

Could you please try above example and see any issue?

Thanks!

**Comment by PaTiToMaSteR** [comment]
Is not small project hmm! I’m not sure how can I share that big chunk. So my unique alternative seems to try to reproduce it in a small little project 🤔

**Comment by PaTiToMaSteR** [comment]
Altho. I used VS 2017 and 19 using /std=c++latest. I’ll try to figure out how reproduce it!
