### ISSUE TITLE
Simple Makefile Compilation

### ISSUE THREAD

**Issue by csverma610** [taskflow/taskflow#92]
Hello,

I tried compiling example/simple.cpp with ( on Linux Ubuntu 18.04: Compiler g++-8)
       g++ simple.cpp -I.. 

I get tons of compilation errors; But with CMake it compiles and runs fine. 
In file included from ../taskflow/core/executor.hpp:58,
                 from ../taskflow/taskflow.hpp:3,
                 from simple.cpp:6:
../taskflow/core/spmc_queue.hpp:140:10: error: ‘optional’ in namespace ‘std’ does not name a template type
     std::optional<T> pop();
          ^~~~~~~~
../taskflow/core/spmc_queue.hpp:140:5: note: ‘std::optional’ is only available from C++17 onwards
     std::optional<T> pop();
     ^~~
../taskflow/core/spmc_queue.hpp:150:10: error: ‘optional’ in namespace ‘std’ does not name a template type
     std::optional<T> unsync_pop();
          ^~~~~~~~
../taskflow/core/spmc_queue.hpp:150:5: note: ‘std::optional’ is only available from C++17 onwards
     std::optional<T> unsync_pop();
     ^~~
../taskflow/core/spmc_queue.hpp:158:10: error: ‘optional’ in namespace ‘std’ does not name a template type
     std::optional<T> steal();
          ^~~~~~~~
../taskflow/core/spmc_queue.hpp:158:5: note: ‘std::optional’ is only available from C++17 onwards
     std::optional<T> steal();

**Comment by tsung-wei-huang** [comment]
Hello @csverma610 , did you enable c++17 in build?  `g++ simple.cpp -std=c++1z ...`

**Comment by csverma610** [comment]
Hello,

Thank you for your prompt response. It worked with c++17. I did not know
what z stands for, so I was using C++11.

In our company, people are showing big praise for your software.

csv

**Comment by tsung-wei-huang** [comment]
@csverma610 thanks for the remark :) Please try it out and let us know if you hit performance issues or have any API suggestions we can improve.

**Comment by csverma610** [comment]
Hello Dr. Tsung,

I am looking for an example for iterative tasks.  That is one node(A) reads
the files and other (B) writet to a png file.  Also, I need to stop B
with some signal that A will not request more files. How Can I create a
taskflow for such an application?

Regards.
csv

**Comment by tsung-wei-huang** [comment]
I am thinking about the following:

```cpp
tf::Executor executor;
tf::Taskflow taskflow;
auto [A, B] = taskflow.emplace(
  [] () { read_file() },
  [] () { write_png() }
);
A.precede(B);
executor.run_until(taskflow, [] () { return my_stopping_criteria(); });
```

**Comment by csverma610** [comment]
Hello Dr. Tsung,

I was also thinking along the same line. However, my problem was as follows:

There are 1000 files to read and write. Even if the files are independent,
what could be the best
way to provide different ID to read and write files. In the case of
standard C++ I would have
written:

        for( int i = 0; i < 1000; i++) {
              read_file(i);
              write_png(i);
       }

thanks
csv

**Comment by tsung-wei-huang** [comment]
How about parallel for?

```cpp
taskflow.parallel_fir(0, 1000, 1, [] (int i) {
  read_file(i);
  write_file(i);
})
```
