### ISSUE TITLE
Add ability to name parallel_for tasks

### ISSUE THREAD

**Issue by bsviglo** [taskflow/taskflow#95]
Right now when I execute `parallel_for` on a range it returns startTask and endTask, on which I can assign names, but internal tasks between startTask and endTask is hidden and we can't assign desired custom names on them.
Is any recomended way how to assign custom names on such tasks except explicit override method `paralle_for` inside cpp-taskflow with one additional parameter nameOfInternalTasks?

I do need this feature to mimize overhead of inserting profiling point inside lamda function of `parallel_for` method which in turn may spawn lots of marks for my profiler (imagine we have 1 million elements in array and it spawns 1 million marks to the profiler output which kills application and profiler performance).
Instead I've added `tf::ExecutorObserverInterface` which spawns profiler marks by overriding methods `on_entry` and `on_exit` and using name of the task as a profler mark name.

Thanks in advance.

**Comment by tsung-wei-huang** [comment]
@bsviglo this is a good point. Right now we don't give users privilege to name internal tasks. But we will include this to a to-do list.

Like you did in `tf::ExecutorObserverInterface`, you can alwasy override the method `on_entry` and `on_exit` to get access to `TaskView` which allows you to query the name of the task.

**Comment by tsung-wei-huang** [comment]
I believe this has been solved in the newest release.
