### ISSUE TITLE
Benchmarks that showcase scaling beyond 2-3 cores

### ISSUE THREAD

**Issue by mratsim** [taskflow/taskflow#97]
I ran the MNIST and parallel DNN benchmarks with TF, OMP and TBB implementations, however the parallelism seems to be exposed at a too coarse-grained level and I only get a 2-3x speedup versus serial on my i9-9980XE (18 physical cores, 36 logical).

![DeepinScreenshot_select-area_20190719174420](https://user-images.githubusercontent.com/22738317/61548802-cae9c600-aa4e-11e9-8473-f8d9c735fb68.png)

Benchmarks that show scaling on higher core count systems would be valuable, especially given the rise of many-cores in both ARM CPUs and the latest AMD and Intel offerings

**Comment by tsung-wei-huang** [comment]
Hi @mratsim , the runtime speed-up depends on the task graph structure. For example, in the following graph the maximum concurrency is 2 (B and C). 

```cpp
a.precede(b);
a.precede(c);
b.precede(d);
c.precede(d);
```

In `mnist` and `parallel_dnn`, I believe graph structures limit the concurrency to 4-5.
